### ISSUE TITLE
Norwegian adblocklist

### ISSUE THREAD

**Issue by FTno** [DandelionSprout/adfilt#1]
Earlier it was a norwegian adblocklist as supplement for EasyList, which also was present in ublock.
It was removed because it was not updated for a long time.
Here is a link to it: https://pastebin.com/GpbgZJRw

Maybe you can find some filters there to add to your filterlist.

**Comment by DandelionSprout** [comment]
Ah, thanks! 😃 I had wondered where that old list had gone...

It has many unique filters (compared to my list) from what I can see, including for sites and ad-exclusive servers that I had never thought of checking out. Even if a substantial number of the sites on that list seems to be defunct, the vast majority of the filters seem suitable for me to add. Thank you.
