### ISSUE TITLE
Scrollbar disappearing

### ISSUE THREAD

**Issue by Broken-Glass1** [DandelionSprout/adfilt#1004]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

**_Browse websites without logging in_** filter causes disappearing of scrollbar on ins-ta while scrolling the page

### Add screenshots below if needed

.

### Add a screenshot of the extension's logger

.

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

latest version

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

.

### Which browser(s) did you use when testing this?

Firefox Browser

### Browser version(s)

latest version

### OS version(s)

.

**Comment by iam-py-test** [comment]
What is "ins-ta"?
Would you mind sharing a link where we can reproduce, along with more information.
Thank you

**Comment by DandelionSprout** [comment]
Okay, so, as the example page requires logging in in the first place. I'll see which entries I can remove or change. If you can check uBlock Origin's logger to see which entries show up in yellow when you visit that example page, it'd certainly help me, but isn't mandatory.

**Comment by DandelionSprout** [comment]
Long story short: Instagram doesn't like me very much.
![image](https://github.com/DandelionSprout/adfilt/assets/22780683/a31b002c-c196-4201-8e57-88a973ef80ca)

As such, such a blue button doesn't seem to exist on the image pages that I do have access to.

**Comment by DandelionSprout** [comment]
Judging by my E-mail inbox: You are aware that GitHub comments have an Edit button, right? 😅

**Comment by DandelionSprout** [comment]
• "I do not know why an ins[tagram] account not opening on your web browser"
I genuinely don't know either. I always presume Meta hates me on a personal level.

**Comment by DandelionSprout** [comment]
• *"**If you can check uBlock Origin's logger to see which entries show up in yellow when you visit that example page, it'd certainly help me (…)**"*
Hint hint.

As would a list of any other adblocker lists you're using.

**Comment by DandelionSprout** [comment]
Hmm, that actually **does** explain a fair bit more.

So, from that screenshot alone, the lack of scrolling seems like a direct result of Instagram begging people to sign up, with the prompt directly refusing to let people scroll past.

There may be methods to fix it, something like `instagram.com##body:style(scroll-behavior: unset !important; overflow: unset !important)`. It's a gamble, but it may very well actually work. Could you test out that entry on your end, by pasting it into "My Filters" in uBO?

**Comment by DandelionSprout** [comment]
In that case I give up. I've been emptied of energy testing out different things. You can try your luck with https://reports.adguard.com/new_issue.html, as they're even better at testing than I am.

**Comment by DandelionSprout** [comment]
But they can fix it in their lists, which also work pretty well.

**Comment by DandelionSprout** [comment]
I can't handle this anymore. I'm genuinely so tired of this. I've given it my all, and have just been met with "Fix this now! Fix this now! Fix this now!", when I'm not even sure if my list is even the cause anymore.

Contact https://github.com/uBlockOrigin/uAssets/issues about this instead. I give up completely.
