### ISSUE TITLE
shop.samsung.com (URL Tracker)

### ISSUE THREAD

**Issue by juarez-spa3** [DandelionSprout/adfilt#1005]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

This link will direct you to the Samsung Shop `https://s.humanz.ai/pre-order/145798/1`

```
cid: 
hmz_campaign:
hmz_inf:
hmz_lid: 
```

### Add screenshots below if needed

not needed

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.55

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Default uBO filters + Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Browser version(s)

Chrome 121

### OS version(s)

Windows 10

**Comment by iam-py-test** [comment]
`cid` is already removed, but I have added the rest.
Thank you.
