### ISSUE TITLE
pcloud.com breakage

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [DandelionSprout/adfilt#1006]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Your annoyances filter list breaks pCloud download pages like:

https://transfer.pcloud.com/download.html?code=5ZE4N50Zh0AMgxT7iGJZtun3Zazb0cIQfvCF8uW5hJuvp1X8N4IBk

### Add screenshots below if needed

![Screenshot 2024-02-15 at 13-10-56 Send large files up to 5GB for free](https://github.com/DandelionSprout/adfilt/assets/101707608/864d71cf-0cd0-45b0-bb6c-c9a55487535b)

### Add a screenshot of the extension's logger

https://www.dropbox.com/scl/fi/2yg6x9w2mhowu1odj3xo0/uBO-Logger.zip?rlkey=xl7qis8ywtblhbg5ianyulot7&dl=1

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.55.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

All filters offered by uBO + Greek Adblock filter + your Annoyances filter.

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

115.7.0esr

### Which OS(s) did you use when testing this?

Windows 7

### OS version(s)

32bit SP1

**Comment by DandelionSprout** [comment]
I've come up with a temporary solution real quick, and am certainly hoping the solution will work in the long term.
