### ISSUE TITLE
api.githubcopilot.com is blocked

### ISSUE THREAD

**Issue by patrikelfstrom** [DandelionSprout/adfilt#1009]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

The domain `api.githubcopilot.com` is used by GitHub Copilot but is blocked by the `||githubcopilot.` rule

https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-network-errors-for-github-copilot#diagnosing-network-issues

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

v0.107.44

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

Dandelion Sprout's Anti-Malware List

### Which browser(s) did you use when testing this?

<i>(Other)</i>

### Browser version(s)

curl

### Which OS(s) did you use when testing this?

macOS

**Comment by iam-py-test** [comment]
This has already been addressed: https://github.com/DandelionSprout/adfilt/commit/b13edbb0f5b2006341e3117b8656fbafee992fe9
Please update your filterlists and retest. If you do not use the main (uBo/AG) version, you may have to wait for the fix to be available in that version.
Thank you
