### ISSUE TITLE
[Invalid Block] Desura.com on blocklist

### ISSUE THREAD

**Issue by azerial** [DandelionSprout/adfilt#1010]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

As a user, I use nextdns which allows me to enable OISD. I reported a false positive to them and their bot redirected me to here. desura.com is, from their landing page, "Desura® offers a unique platform where everyone can play their favorite free online games. Our collection is so diverse that every player can find a truly beloved game to enjoy alone, with a friend in two-player games, or in a group of pals. All activities on Desura are free and require no installation on your computer allowing you to play online, and importantly, are available on all devices, from desktops and tablets to smartphones." Games such as, Project Zomboid, which you might have heard of, started there. 

### Add screenshots below if needed

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Anti-Elsagate%20List.txt

### Add a screenshot of the extension's logger

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Anti-Elsagate%20List.txt

### Which adblocker(s) did you use when testing this?

DNS adblocking server(s), incl. AdGuard Public DNS and Quad9, <i>(Other)</i>

### Adblocker version(s)

nextdns

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

OISD

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

Firefox Developer 123.0b7 (64-bit)

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Fedora 39

**Comment by azerial** [comment]
Apparently it was blocked, likely without any regression on the issue, as "extremely violent HTML 5 games". Its not at all. I know as a block list, you are trying to protect users; however, some regression needs to happen on reports. 8 bit zombies are not extreme violence, sorry.

**Comment by DandelionSprout** [comment]
Come on, man. You know ***very*** well what I'm talking about.

• Baby Hazel Leg Injury
• Pixie Accident AR
• Funny Nose Surgery
• Mommy Home Recovery
• Foot Hospital

Some of their thumbnails are so brutal and violent that they're most violent than all Grand Theft Auto games combined. In fact they're so violent that I'm not even sure if it'd be legal for me to post the thumbnail collage on GitHub, so I've had to post an image link instead: https://images2.imgbox.com/2d/e1/3RYGAbq1_o.png

At least Trevor Philips (GTA V) didn't rip nostrils wide open to the point of bleeding, nor did he cause 4 scars and a glass shard under someone's foot.

**Comment by azerial** [comment]
Sending email to publisher. They should know. 

And for your specific information, I _DID NOT_  know.

**Comment by DandelionSprout** [comment]
Ah, okay. I thought you were representing Desura in some official capacity of some sort. 😅

**Comment by azerial** [comment]
Also, the link you provided does not resolve.

**Comment by DandelionSprout** [comment]
It's supposed to be a raw image, but does this work instead? https://imgbox.com/3RYGAbq1

**Comment by azerial** [comment]
I worked at Electronic Arts for 13 years. I also https://en.wikipedia.org/wiki/Wikipedia:Assume_good_faith

**Comment by azerial** [comment]
I HATE THAT. What the hell. As a user, im going to send an email. Ahh!

**Comment by DandelionSprout** [comment]
Elsagate as a concept/scandal pretty much revolves around those kinds of "games" and YouTube "videos". 😅 There's a fair few forums dedicated to finding the worst possible examples out there in an attempt to make people more aware of what Elsagate is and why it's hurtful… for pretty much everyone, not just kids.

**Comment by azerial** [comment]
Heard. Wow thats pretty not great. As for the approach, do again, encourage you to read https://en.wikipedia.org/wiki/Wikipedia:Assume_good_faith I know wikpedia, blah blah blah words who cares, but its a good article. Its an internal, if you will to Wikipedia, article which has a lot of good info. 

Please close my ticket WNF

**Comment by DandelionSprout** [comment]
It's kinda already closed, I just don't lock conversations entirely unless it's been going on for weeks. 😅

I have some experience with Wikipedia and wikias alike, and I must honestly say that I've come across a fair few repeated vandals on all of them where Assume Good Faith or even gradual warnings and short bans clearly in my eyes wouldn't be the best idea, even if mods and admins on them thought I was a vigilante of sorts.

**Comment by azerial** [comment]
I have sent them an email asking them to prove they do not have titles that are bad.

**Comment by azerial** [comment]
Ugh am I the fool? I think I am.

**Comment by DandelionSprout** [comment]
I'd be pretty surprised if they can prove it, for sure, especially if the game names and/or thumbnails weren't added to the E-mail. 😅

More likely than not they'll just say they're safe for all ages without removing (or even acknowledging) any of the games in question.

**Comment by azerial** [comment]
What are punch doll games? I mean im going to google it, but WAT?

**Comment by DandelionSprout** [comment]
"Kick the Buddy" seems to be most quote-unquote famous one, and Desura does have 1 listing in that genre too (Torture the Trollface).

**Comment by azerial** [comment]
Sent a message offline. I'm glad i created this issue.

**Comment by DandelionSprout** [comment]
I'm just glad this issue got resolved as nicely as it did. I feared it'd get much more angry at one point.

**Comment by azerial** [comment]
Someone else can have that angst.
