### ISSUE TITLE
instagram profiles broken with "🚪 Browse websites without logging in" filter

### ISSUE THREAD

**Issue by zxsldfjsalkdf** [DandelionSprout/adfilt#1011]
## Which entry/entries are you submitting?

`www.instagram.com##script ~ div[class*=" "][style^=--][style*="255"]:style(scroll-behavior: unset !important; overflow: scroll !important)`

## Which things do they block, hide, or unbreak?

While logged in and directly viewing someone's profile, if you click on a picture that the person posted there is supposed to be a window that is supposed to open within Instagram in order to show a larger version of the picture, and this window does not open while the filter/list is running - nothing happens when you click on the picture. Additionally, if you are already following someone and want to unfollow them from their profile, clicking on the unfollow button is supposed to open a mini window within Instagram to give you all the options you can take with a user, like blocking them, unfollowing, etc. This window will not open while the filter/list is active.
The filter was identified using the Logger of uBO, and disabling the filter fixed the problem that it was causing.

## Which of my lists are you submitting it to?
🚪 Browse websites without logging in

## Which adblocker(s) and version did you use when writing and testing the entries?

- [ ] uBlock Origin (Version 1.56.0)

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
![firefox_0542DwkRtZ](https://github.com/DandelionSprout/adfilt/assets/153876500/f30ef962-6395-4197-8c15-c03effe20f73)

## (Optional) Which browser(s) and version did you use?

Firefox 123.0 (64-bit)

**Comment by DandelionSprout** [comment]
Thanks for the heads-up. The entry was a desperate move to resolve the ever-more demanding, impatient, and to some extent unreasonable OP of #1004 (who also kept deleting his own comments, and who seemed unaware that uBO and AdGuard also maintained lists that did the same things as mine)

And while the entries I came up with after I was finally able to check profile feeds while not logged in, seemed to work on my end, it was of course a gamble for me to tell whether people who were logged **in** would into any problems with it.

I'll give AdGuard a forwarding heads-up, as they know stuff like scriptlets and very, very advanced adblocker functionalities.

**Comment by zxsldfjsalkdf** [comment]
I'm sorry that you have to deal with people like that. I cannot imagine how frustrating it can be, especially on the scale with which you have to maintain so many filter lists. People often forget that filter lists and extensions like uBO are offered completely free, run by ones such as yourself who simply want to make a better browsing experience for everyone, and it is so disrespectful that some treat you that way without keeping that in mind.

For me personally, it's no rush on whether an issue gets fixed or how fast. I don't want to pressure anyone. I understand that you/AdGuard are only human and need time to find a fix, eat, sleep, etc. I also know that I can easily and temporarily disable the filter list or uBO if I need to. I appreciate what you do and I am sure many others do as well even if all you see here are just issues being opened and no thanks whatsoever.

**Comment by DandelionSprout** [comment]
Thanks for the very kind words. I'm certainly more human than most others who are at this high level of adblock list work; my stamina has been near-zero for some years by now, making it ever more harder to process issue reports.

To make matters additionally worse, Team AdGuard seemingly couldn't reproduce this whole situation and closed my forwarding without any additional notes on it, so now I have to figure out how to limit the entries above to some kind of "Not logged in" element or such.
