### ISSUE TITLE
I wish to help to write the list

### ISSUE THREAD

**Issue by chirag127** [DandelionSprout/adfilt#1015]
I wish to be contributor on your lists.

**Comment by DandelionSprout** [comment]
Good to hear. I recognise your username, and you seem good enough at submitting pull requests.

I'm unsure which topics you specialise most in, so you can try submitting a PR for almost any list on https://github.com/DandelionSprout/adfilt (but not any of the subfolders) and see where you feel you can add the most new details.

**Comment by neer9** [comment]
> Good to hear. I recognise your username, and you seem good enough at submitting pull requests.
> 
> I'm unsure which topics you specialise most in, so you can try submitting a PR for almost any list on https://github.com/DandelionSprout/adfilt (but not any of the subfolders) and see where you feel you can add the most new details.

I have submitted the pull request to different repositoriee like the adguard, dandalian sprout, ublock origin etc.

I have also submitted many issues on github.

Maybe you know me by my issues.

I'm a issue creating man.

**Comment by neer9** [comment]
My most used user name is chirag127

(to show to the companies, to get hired) .

Neer9 for the NSFW stuff.

**Comment by DandelionSprout** [comment]
So… uh… which topics do you feel you are best at (and specialises at) when you make lists or want to edit lists?

**Comment by chirag127** [comment]
No specialisation yet.

Regards,
Chirag Singhal


Note;Please check if any attachment is there in the email.

**Comment by DandelionSprout** [comment]
So, I've thought of this for a couple weeks, I did think really hard about it, and I've concluded that the "I wish to help" form had become massively outdated (if not ancient) as filterlists became more advanced and were covering ever more adblocker softwares.

So, overall, I'll close the thread, but you are welcome to submit pull requests or to some extent issue reports whenever you feel it's needed.
