### ISSUE TITLE
Wikia: fandom trivia

### ISSUE THREAD

**Issue by NotaInutilis** [DandelionSprout/adfilt#1019]
## Which entry/entries are you submitting?

Seems like fandom had another brilliant idea with pushing promotion with "fandom trivia". I've encountered it on pretty much every page of the Kamen Rider Wiki, just down of the TOC.
I'm not quite sure how to identify the div as it has no class nor id.
I tried `fandom.com##div:has-text(Fandom Trivia)` but the whole page went blank which is clearly not ideal.
After some trial and error, I found that `fandom.com##div:has(>[href*="fandom.com/trivia"])` seems to work.

## Which things do they block, hide, or unbreak?

![image](https://github.com/DandelionSprout/adfilt/assets/9675966/9351cdff-450c-4f71-91b7-3f43e0ae0022)
Source url https://kamenrider.fandom.com/wiki/Kamen_Rider_Gotchard

## Which of my lists are you submitting it to?
Wikia list

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Wikia list

## (Optional) Which browser(s) and version did you use?

Firefox latest

**Comment by DandelionSprout** [comment]
Puzzlingly on Fandom's part, the section only shows up if cookies are accepted, so on paper, *AdGuard Cookie Notices Filter* and (the already somewhat collapsed) *I Still Don't Care About Cookies* project would prevent that section from showing up at all.

Nevertheless, I'll come up with a fix pretty soon now, hopefully.
