### ISSUE TITLE
IPs ipset Line 387

### ISSUE THREAD

**Issue by RicoHeat** [DandelionSprout/adfilt#1021]
https://github.com/DandelionSprout/adfilt/blob/2e9b8d47d38e7641a1b73ccc2ea6f15f1e28c6a5/Alternate%20versions%20Anti-Malware%20List/Dandelion%20Sprout's%20and%20other%20adblocker%20lists'%20IPs.ipset#L387

Just a bit of cleanup 🧹 required. "="

Have a great day my friend! 👍

**Comment by DandelionSprout** [comment]
I'll be looking into it, hopefully soon-ish.
