### ISSUE TITLE
Stop Autoplay on Dailymotion

### ISSUE THREAD

**Issue by Metrokoto** [DandelionSprout/adfilt#1023]
## Which entry/entries are you submitting?
`||static1.dmcdn.net/playerv5/dmp.end_screen.*.js$script`
`||geo.dailymotion.com/player/xjnde.html$1p,3p,frame,redirect=click2load.html`

## Which things do they block, hide, or unbreak?
- Disables the endscreen to prevent the next video automatically playing
- Redirects the frame for the video player to click2load.html to prevent the video automatically playing

## Which of my lists are you submitting it to?
`https://github.com/DandelionSprout/adfilt/blob/master/StopAutoplayOnYouTube.txt`

## Which adblocker(s) and version did you use when writing and testing the entries?
- [x] uBlock Origin
- [x] I Still Don't Care About Cookies (The extension)

Adblocker version(s):
uBlock Origin 1.57.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
uBlock filters
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list

## Additional information
Due to limitations with how their code works, it breaks any page on their website which embeds the video player, unless it's a /video/ page, and additionally, I can't seem to make the click2load redirect take effect after you click to load the first video, meaning if you click through on the sidebar, it won't prevent autoplay, but this is as close as I think we will get to preventing autoplay on Dailymotion.

**Comment by DandelionSprout** [comment]
My apologies for getting to this a week late; I somehow managed to end up busy with [Super Mario Wiki](https://www.mariowiki.com/User:DandelionSprout#To-do) of all possible things, and I also thought _"This is going to get difficult to test._ 😅"

Somehow, it didn't seem to me that the 2nd entry was needed, as I got quite some better results with just the first entry, from what I could determine, so I'll add that one now, at least.

**Comment by DandelionSprout** [comment]
There seem to have been no issues so far from what I can tell, so I'll call this a successful and closed case. Comments will remain open.
