### ISSUE TITLE
||adobe.com^$removeparam=mv breaks opening pdfs in browser

### ISSUE THREAD

**Issue by SESNut** [DandelionSprout/adfilt#1025]
## Which entry/entries are you submitting?

||adobe.com^$removeparam=mv

## Which things do they block, hide, or unbreak?

Kind of breaks opening pdfs in chrome, it tries to connect to adobe multiple times before actually opening the pdf with the message below

It looks like the webpage at https://acrobat.adobe.com/proxy/chrome-viewer/index.html?locale=en-US&logAnalytics=true&callingApp=elhekieabhbkpmcefcoobjddigjcaadp&betaOptOut=false&enableCaretMode=false&rvu=true&version=24.4.1.2%3Aupdate&installSource=normal&storage=%7B"dmCmShown"%3A"true"%2C"editNewTag"%3A"%7B%5C"value%5C"%3A%5C"newTag%5C"%2C%5C"timestamp%5C"%3A1700358703.482%7D"%2C"embedViewerVersion"%3A"1.6.6"%2C"fillSignNewTag"%3A"%7B%5C"value%5C"%3A%5C"newTag%5C"%2C%5C"timestamp%5C"%3A1700358703.482%7D"%2C"guidedTourShown"%3A"true"%2C"openInDesktopTooltipShown"%3A"true"%2C"ratingWidgetData"%3A"%7B%5C"usageWaitCount%5C"%3A26%2C%5C"widgetShown%5C"%3A2%2C%5C"cooldown%5C"%3A1674409644710%7D"%2C"renderPrompt"%3A"%7B%5C"value%5C"%3A%5C"fragment%5C"%2C%5C"expiry%5C"%3A1714452023564%7D"%2C"signInExperimentShown"%3A"true"%2C"theme"%3A"dark"%2C"usage"%3A"139"%2C"userPrefs"%3A"%7B%5C"genAICoachmarkPrefs%5C"%3A%7B%5C"session%5C"%3A%5C"active%5C"%2C%5C"numOfTimesGenAIQnACoachmarkShown%5C"%3A1%2C%5C"lastCoachmarkShown%5C"%3A%5C"GenAIQnA%5C"%2C%5C"lastPromotionType%5C"%3A%5C"AnimatedTooltip%5C"%2C%5C"timestamp%5C"%3A1714365624953%2C%5C"numOfTimesDefaultType1TooltipShown%5C"%3A1%2C%5C"lastTooltipShown%5C"%3A%5C"Type2%5C"%2C%5C"defaultTooltipTimestamp%5C"%3A1713944531271%2C%5C"numOfTimesGenAIType2TooltipShown%5C"%3A1%7D%7D"%2C"yoloCooldown"%3A"%7B%5C"timestamp%5C"%3A1703415220215%2C%5C"cooldown%5C"%3A%5C"noActionCooldown%5C"%7D"%2C"yoloData"%3A"%7B%5C"usage%5C"%3A7%7D"%7D&sdp=1&sds=1&docState=%7B"x"%3A0%2C"y"%3A0%2C"rotationAngle"%3A0%2C"pageNumber"%3A1%2C"zoomLevel"%3A127.64961192810456%7D&nu=0&rs=1&nm=1&dpt=0&isReadAloudEnable=true&isDeskTop=true&isAcrobat=true&theme=auto&sessionId=ff96525d-8f34-4203-8212-7af90d487207&sgd=true&sl=true&ev=true&fsm=true&ao=false&ip=true&rate=false&genAI=true&mv=false&pi=false&ks=true&edd=false&tpt=false might be having issues, or it may have moved

## Which of my lists are you submitting it to?
Legitimate url shortener

## Which adblocker(s) and version did you use when writing and testing the entries?

- [ ] AdGuard (Paid desktop version)

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

i disabled every filter except legitimate url shortenr and it breaks with that one rule enabled

**Comment by iam-py-test** [comment]
I get a blank page with or without the Actually Legitimate URL Shortener Tool when accessing that URL in Firefox.
Is there a specific URL to test with, or is an account required?
Thanks

**Comment by SESNut** [comment]
that url is the what it shows as the error message that its trying to connect to. It happens with any online pdf like this one https://ir.tesla.com/_flysystem/s3/sec/000119312524036110/d64998dsc13ga-gen.pdf

I did some more tests and it looks like it only breaks when the acrobat extension is enabled which they stopped making for firefox

**Comment by iam-py-test** [comment]
I should have realized this was a Chrome issue...
> Kind of breaks opening pdfs in **chrome**

Whoops, I missed that important detail when reading your initial issue report (we apologize for the fault in the issue triage. Those responsible have been sacked.).
Thank you. I have disabled the problematic rule.
Please wait a few hours and retest to see if the problem can still be reproduced.
Thanks
