### ISSUE TITLE
tu.no

### ISSUE THREAD

**Issue by Schanzation** [DandelionSprout/adfilt#1027]
## Beskriv problemet under denne linjen så detaljert og utdypende som mulig (inkl. nettlenker hvis det er noen):

https://www.tu.no/artikler/slik-blir-den-nye-nettleia-pris-grenser-pa-5-og-10-kw/514897

Masse ads

## Hvilken reklameblokkerer og versjon brukte du da du testet dette?

- [x] uBlock Origin
- [ ] AdGuard (Betalt skrivebordsversjon)
- [ ] AdGuard (Nettleserutvidelse)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (Utvidelsen)

Andre:

Reklameblokkererversjon(er):

## (Valgfritt) Hvilket OS og versjon brukte du?
- [ ] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux
- [ ] Android

Andre:

OS-versjon:

**Comment by DandelionSprout** [comment]
Det hadde knapt gått 24t siden jeg forsøkte å fikse TU engang (skjønt mest som følge av https://github.com/uBlockOrigin/uAssets/issues/23510 og at de 2 nettstedene har samme infrastruktur), så her må jeg begynne å tenke litt på eventuelle planer.

**Comment by kbergha** [comment]
Trur disse reglene burde knerte det meste:
```
digi.no,tu.no##div.lcs_tA
digi.no,tu.no###brandBoardTop
digi.no,tu.no###brandBoardBottom
digi.no,tu.no###brandBoardTopMobile
digi.no,tu.no###skyscraperLeft
digi.no,tu.no###skyscraperRight
```

**Comment by DandelionSprout** [comment]
Når me gjorde research i går kveld, kunne eg ha svergja på at i alle fall 2 av oppføringane eg la til var meint å fikse dei semste aspektane. Dei fungerade i "Mine filtre", men me har problemar i augeblikket med å få dem til å virke fra lista:
```
digi.no,tu.no##main > div > div[class*=" "]:has(:is([id*=skyscraper i],[id^=brand i]))
tu.no,digi.no##div.relative:has(+ footer) > div:not([class*=bg])
```
Eg ser førre me 2 eller 3 ekstra oppføringar å leggje til attpå, men me har vore på grensa av å kaste inn håndkleet på dei 2 nettstadene i månader allerede, og hadde hoppast på at uAssets eller Team AdGuard kunne ha tatt litt av byrden frå mine skuldre.

**Comment by Schanzation** [comment]
Ja, det håper jeg de kan gjøre. La de inn i "Mine filtre" nå og sånn umiddelbart ser det ut til å funke veldig bra.

**Comment by DandelionSprout** [comment]
Jeg planlegger å supplere med én eller 2 til, mens jeg er avventende til `digi.no,tu.no##div.lcs_tA`, så får vi se hvordan i gudenes navn dette ender opp.

**Comment by DandelionSprout** [comment]
Det ser ut til å ha endt med å gå fullstendig på ræva, selv om 2 oppføringer som forårsaket store falske positiver ironisk ikke engang var med i fiksen min… 😅

Så hvis noen noen gang skulle slite med `TU` noen gang i fremtiden, så spør disse i stedet:
* https://reports.adguard.com/no/new_issue.html
* https://github.com/uBlockOrigin/uAssets/issues

Jeg har totalt gitt opp å håndtere `TU` og `Digi`. Og de 2 hjelpelenkene ovenfor skal for en gangs skyld ikke bare kunne bortforklare det med "De 2 nettavisene må fikses av den norske listen, lol, lmao."
