### ISSUE TITLE
Actual Legitimate URL Shortener appears to interfere with Save to Pocket Chrome extension login

### ISSUE THREAD

**Issue by BionicBison05** [DandelionSprout/adfilt#1028]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

When the Actual Legitimate URL Shortener filter list is enabled, I am unable to log into the Pocket extension. This occurs on both Chrome and Brave, and is reproducible with uBlock Origin's default filter set plus the problematic list.

### Add a screenshot of the extension's logger

Logger output:

<img width="1009" alt="logger1" src="https://github.com/DandelionSprout/adfilt/assets/93722725/f4b1090a-592f-4e0b-9a32-6194693a51c4">

Expanded views:

<img width="636" alt="logger2" src="https://github.com/DandelionSprout/adfilt/assets/93722725/b5b9dacd-4581-4d91-a407-6eff0c28a308">

<img width="640" alt="logger3" src="https://github.com/DandelionSprout/adfilt/assets/93722725/7a423582-c062-48a1-9118-347ba52d6f54">

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.57.0

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

uBlock Origin default filter lists, Actual Legitimate URL Shortener.

<img width="521" alt="image" src="https://github.com/DandelionSprout/adfilt/assets/93722725/93c56526-ccd9-4b1f-ab28-09b7cb8f51cf">

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2), Brave Browser

### Browser version(s)

Brave 1.65.126, Chrome 124.0.6367.156

### Which OS(s) did you use when testing this?

macOS

### OS version(s)

Sonoma 14.4.1

**Comment by iam-py-test** [comment]
Sorry for the delay; I have been very busy lately.
Please wait a few minutes, update the Actually Legitimate URL Shortener, and retest.
Thank you

**Comment by DandelionSprout** [comment]
If you were to really need to get weight off your shoulders, I could take on occasional situations; although I too have much weight on my shoulders in general life. 😓

**Comment by BionicBison05** [comment]
Everything functions as expected now, thanks! Appreciate your hard work maintaining these lists.

**Comment by iam-py-test** [comment]
> If you were to really need to get weight off your shoulders, I could take on occasional situations; although I too have much weight on my shoulders in general life. 😓

It's fine. Anyway, after next week I will have a lot more time.
Thanks
