### ISSUE TITLE
ksu.no

### ISSUE THREAD

**Issue by Schanzation** [DandelionSprout/adfilt#1029]
## Beskriv problemet under denne linjen så detaljert og utdypende som mulig (inkl. nettlenker hvis det er noen):

Masse ads
https://ksu.no/artikler/ksu-no/124262-norges-bank-husholdningene-er-sarbare-for-okonomisk-tilbakeslag-20240508

## Hvilken reklameblokkerer og versjon brukte du da du testet dette?

- [x] uBlock Origin
- [ ] AdGuard (Betalt skrivebordsversjon)
- [ ] AdGuard (Nettleserutvidelse)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (Utvidelsen)

Andre:

Reklameblokkererversjon(er):

## (Valgfritt) Hvilket OS og versjon brukte du?
- [ ] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux
- [ ] Android

Andre:

OS-versjon:

**Comment by DandelionSprout** [comment]
Simpelthen bare `ksu.no##.ads` ser ut til å fungere, smått overraskende tatt i betraktning at selve mediefilene er i praksis umulige å fjerne med `||`-oppføringer.

Jeg skal få lagt det til innen en time-ish.
