### ISSUE TITLE
open.spotify.com(breakage)

### ISSUE THREAD

**Issue by juarez-spa3** [DandelionSprout/adfilt#1031]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

click the link
https://secondhandsongs.com/performance/1296583

click album cover, this will redirect you to open.spotify.com but the spotify page constantly refreshes itself
![2024-05-13 16_20_12](https://github.com/DandelionSprout/adfilt/assets/153795294/19160053-63d6-4ed0-bdb8-5d1dc5e5335c)

---

please also add these 5 parameters to the list
||open.spotify.com^$removeparam=go
||open.spotify.com^$removeparam=sp_cid
||open.spotify.com^$removeparam=t
||open.spotify.com^$removeparam=nd
||open.spotify.com^$removeparam=dlsi

Click the link below for `go`, `sp_cid`, `nd`, `dlsi` parameters

https://open.spotify.com/intl-tr/track/5auJMxZRvleLvY8z3wFaTW?go=1&sp_cid=a3fe73f5a9295a068a85a17e5a62cfbc&t=29&nd=1&dlsi=110fcc275108418c

---

to see the parameter `t`
Press the Play button once and stop the track. Then click the `Get Spotify` button.
<details>
 <summary>Screenshot</summary>

![getsp](https://github.com/DandelionSprout/adfilt/assets/153795294/225a9ab5-fec6-476b-9882-210bcb8355ad)

</details>

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.57

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

 Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

Win10

**Comment by iam-py-test** [comment]
Sorry for the delay.
Please update the Actually Legitimate URL Shortener and retest.
Thanks
