### ISSUE TITLE
michaelapplysome.com

### ISSUE THREAD

**Issue by FadeMind** [DandelionSprout/adfilt#1032]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

michaelapplysome.com is VOE Player domain.
Sample: https://michaelapplysome.com/e/rrgnfg4o46e9

### Add screenshots below if needed

Adguard DNS Log:
![20240514-1715707381](https://github.com/DandelionSprout/adfilt/assets/9846948/2ab3c00a-7559-4734-8fed-26a76114e236)
Issue:
![20240514-1715707340](https://github.com/DandelionSprout/adfilt/assets/9846948/89c2259a-00da-470a-b284-c32bbb6eed54)
Manual Whitelist:
![20240514-1715707354](https://github.com/DandelionSprout/adfilt/assets/9846948/41c480b7-00bc-4211-9291-5c6034573700)

### Which adblocker(s) did you use when testing this?

<i>(Other)</i>

### Adblocker version(s)

Adguard DNS

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

![20240514-1715707752](https://github.com/DandelionSprout/adfilt/assets/9846948/52909fae-41f1-4a61-98f0-2b30073cf86d)

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Browser version(s)

125.0.6422.41 

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

Windows 11 Version 23H2 (Build 22631.3527)

**Comment by DandelionSprout** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/179170 seemed to imply michaelapplysome was a redirection scam site, though its OP did not explain the situation properly at all (I should probably have realised it from their incorrect screenshot). I'll look into it after I've had some breakfast.
