### ISSUE TITLE
Invalid relative path in `AntiMalwareAdGuard.txt` (only AdGuard related)

### ISSUE THREAD

**Issue by Alex-302** [DandelionSprout/adfilt#1034]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hi
It seems the relative path is incorrect in `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuard.txt`:

```
!#include uBO%20list%20extensions/Dandelion%20Sprout's%20Anti-Malware%20List%20—%20AdGuardOnlyEntries.txt
```
because `uBO%20list%20extensions/Dandelion%20Sprout's%20Anti-Malware%20List%20—%20AdGuardOnlyEntries.txt` does not exist in `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/`

I think the correct relative path is `../uBO%20list%20extensions/Dandelion%20Sprout's%20Anti-Malware%20List%20—%20AdGuardOnlyEntries.txt`

### Add a screenshot of the extension's logger

Invalid relative path in `AntiMalwareAdGuard.txt` - filter does not build by AdGuard's Filters Compiler.

### Which adblocker(s) did you use when testing this?

AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)

### Adblocker version(s)

AdGuard 4.3.46

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

`Dandelion Sprout's Annoyances List`

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Browser version(s)

Chrome 122 x64

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

Windows 10 x64

**Comment by Alex-302** [comment]
No, it is not an error according to uBO specs. Our is a bit different.

**Comment by Alex-302** [comment]
Thanks)

**Comment by iam-py-test** [comment]
Wait, AdGuard allows including files outside the current directory? uBo doesn't.
Thanks

**Comment by DandelionSprout** [comment]
…Oh. That explains a bit. I was occupied with other things (mostly to complain about diet soda to my secretary), and didn't realise at the time that the folder system was unusual like that. I'll handle a proper !#include system once I've had some breakfast; thanks for the heads-up, iam-py-test.

**Comment by DandelionSprout** [comment]
https://github.com/DandelionSprout/adfilt/commit/9a8c78847181b329da0b9a61c1e147bf3fd971a9 should probably make the situation better overall.

**Comment by Alex-302** [comment]
@DandelionSprout 

> [a8c788](https://github.com/DandelionSprout/adfilt/commit/9a8c78847181b329da0b9a61c1e147bf3fd971a9) should probably make the situation better overall.

Thanks) Will look on the next build (3p filters compiled every 4 hours)

**Comment by Alex-302** [comment]
All good)
