### ISSUE TITLE
digi.no - content is hidden

### ISSUE THREAD

**Issue by Alex-302** [DandelionSprout/adfilt#1035]
## Which entry/entries are you submitting?

`https://www.digi.no/`
Content is hidden by `tu.no,digi.no##div:first-of-type[class*=" "]:has(> div:empty)`

Related to https://github.com/AdguardTeam/AdguardFilters/issues/179122

## Which adblocker(s) and version did you use when writing and testing the entries?

- [ ] uBlock Origin
- [ ] AdGuard (Paid desktop or Android version)
- [x] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Still Don't Care About Cookies (The extension)
- [ ] AdNauseam
- [ ] AdGuard Private DNS

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Nordic Filters

**Comment by DandelionSprout** [comment]
Okay, sure thing.
