### ISSUE TITLE
blog.checkpoint.com breakage

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [DandelionSprout/adfilt#1036]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Your Annoyances filter list breaks articles in blog.checkpoint.com.

Indicative URL:
https://blog.checkpoint.com/security/extending-sase-protection-into-the-browser/

### Add screenshots below if needed

![Screenshot 2024-06-04 at 12-52-39 Extending SASE Protection Into the Browser - Check Point Blog](https://github.com/DandelionSprout/adfilt/assets/101707608/8565fe54-2554-4a4b-90f1-8036e552cbb8)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.58.0

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

All filters offered by uBO + your Annoyances list.

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

115.11.0esr

### Which OS(s) did you use when testing this?

Windows 7

### OS version(s)

Pro 32bit SP1

**Comment by DandelionSprout** [comment]
I think I found the cause *spectacularly* quickly, and am hoping I can add a hotfix within minutes now.
