### ISSUE TITLE
.top domains get blocked

### ISSUE THREAD

**Issue by haleeth91** [DandelionSprout/adfilt#1037]
one of the lines blocked all the ".top" tld extensions

**Comment by DandelionSprout** [comment]
That blocking is intentional, due to .top domains being frequently used for malware.

**Comment by haleeth91** [comment]
then the domain should found and blocked not the entire extension!

**Comment by iam-py-test** [comment]
Malicious domains change very quickly, and blocking each individual malicious domain is impractical, given .top is commonly abused.
Imre does maintain an allowlist of known legitimate domains on the `.top` TLD. Is there a specific domain you believe should be unblocked?
Thank you

**Comment by haleeth91** [comment]
I don't think it is not a problem, since I have added the domains to my whitelist also it is not a problem since those domains belong to me and are used by me and my clients!

Thanks anyway
