### ISSUE TITLE
Anti-Malware list breaks ISBN search on Google

### ISSUE THREAD

**Issue by squeak9** [DandelionSprout/adfilt#1039]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Url: `https://www.google.com/search?tbm=bks&q=isbn:9781421579153`

The results of the search is hidden, if you disable the Anti-Malware list then it works. 

Got the link from `https://en.m.wikipedia.org/wiki/Special:BookSources?isbn=9781421579153`

### Add a screenshot of the extension's logger

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +3 | `##.g:has(a[href^="https://books.google."])` |  | `www.google.com` |  | get | dom | `https://www.google.com/search?tbm=bks&q=isbn:9781421579153` |
| +3 | ###main a[href][ping^="/url?"]:remove-attr(ping) |  | `www.google.com` |  | get | dom | `https://www.google.com/search?tbm=bks&q=isbn:9781421579153` |
| +0 | `@@\|\|www.google.*/search?$generichide` | ++ | `www.google.com` | 1 | get | generichide | `https://www.google.com/search?tbm=bks&q=isbn:9781421579153` |
</details>

![519c79ce-e1a4-4459-9cbc-7e6ada42abdb](https://github.com/DandelionSprout/adfilt/assets/73029732/1d0b8b4b-8e00-4937-affa-d695cd8dce10)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.58.0

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout%27s%20Anti-Malware%20List.txt

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

Firefox Android 127.0 (Build #2016024687), hg-81170fe36cb2+
GV: 127.0-20240603152359
AS: 127.0

### Which OS(s) did you use when testing this?

Android

### OS version(s)

Android 14

**Comment by DandelionSprout** [comment]
I remember there was a pretty big problem a couple years ago, in which bot-generated and/or otherwise fake Google Books results would flood the results for ordinary search terms. But you're certainly correct in that ISBN searches would be heavily negatively affected by this. Give me 24 hours.

**Comment by squeak9** [comment]
Thanks for the quick response!
