### ISSUE TITLE
tek.no

### ISSUE THREAD

**Issue by Schanzation** [DandelionSprout/adfilt#1041]
## Hvilke(n) oppføring(er) sender du inn?
Hei! Får ads her:
https://www.tek.no/nyheter/nyhet/i/wgOQBP/baade-kina-og-eu-aapne-for-samtaler-om-straffetoll-paa-kinesiske-elbiler

## Hvilke ting blokkerer, skjuler, eller fikser de(n)?
![image](https://github.com/DandelionSprout/adfilt/assets/19490515/02b0f384-aa30-4a36-b27a-25605364c529)

## Hvilke av mine lister sender du den inn til?
Dandelion Sprouts nordiske filtre

## Hvilken reklameblokkerer og versjon brukte du da du skrev og testet oppføringen(e)?

- [x] uBlock Origin
- [ ] AdGuard (Betalt skrivebordsversjon)
- [ ] AdGuard (Nettleserutvidelse)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (Utvidelsen)

Andre:

Reklameblokkererversjon(er):

## Hvilke filterlister brukte du? Å ikke fortelle dette, vil føre til at saken blir midlertidig lukket frem til dette blir fortalt.
![image](https://github.com/DandelionSprout/adfilt/assets/19490515/3a3949e6-7810-4d7a-bb5d-41cdec986eb9)

## (Valgfritt) Hvilke(n) nettleser(e) og versjon(er) brukte du?
Brave
[Version 1.67.119 Chromium: 126.0.6478.114 (Official Build) (64-bit)

**Comment by DandelionSprout** [comment]
`||elton.app/widget/$domain=tek.no` ser ut som det vil fungere i hvert fall. Jeg skal få håndtert det snart nå.
