### ISSUE TITLE
Anti-Malware list false positive for sig-ge.ch 

### ISSUE THREAD

**Issue by jeremie-arcidiacono** [DandelionSprout/adfilt#1044]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

`ww4.sig-ge.ch` is blocked by Dandelion Sprout's Anti-Malware List. 
This subdomain is used for the authentication process of the main website at https://ww2.sig-ge.ch/

As long as it's blocked, you can't log in with an account on the website.

I think this line is responsible:
https://github.com/DandelionSprout/adfilt/blob/b4fd0acecdd72cc111cc9da7d8dadf954f714d29/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt#L24421

### Add a screenshot of the extension's logger

![tmp-IssueAdGuard](https://github.com/DandelionSprout/adfilt/assets/49244181/b00437f4-b1da-4921-a77d-85ec4d90f4f1)

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

AdGuard Home v0.107.36

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

![image](https://github.com/DandelionSprout/adfilt/assets/49244181/f3bf8aba-25d2-4a6a-be08-4f29d29c2e0b)

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

Firefox Developer Edition 128.0b9 (64 bits)

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

22H2

**Comment by DandelionSprout** [comment]
Sounds like a perfectly valid whitelisting request indeed. 🌞 I'll take care of it later this morning.
