### ISSUE TITLE
aspor.com.tr: breakage

### ISSUE THREAD

**Issue by punisher018** [DandelionSprout/adfilt#1047]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

`.smartbanner.js` filter in Dandelion Sprout's Annoyances List is blocking the 20 image banner sections on the homepage of the news site I mentioned.  (aspor.com.tr)

### Add screenshots below if needed

![dan](https://github.com/user-attachments/assets/54c6802b-955b-4ad7-99df-8f33090fc112)
![broken](https://github.com/user-attachments/assets/0ff960d9-f713-4d57-ad9a-86aabd32344c)

### Add a screenshot of the extension's logger

The part that prevents the site from working by being blocked due to the filter;

https://iaspr.tmgrup.com.tr/site/v3/j/jquery.smartbanner.js?v=18031

### Which adblocker(s) did you use when testing this?

AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)

### Adblocker version(s)

Adguard v4.3.64

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

Dandelion Sprout's Annoyances List

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

128.0 (x64)

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

22H2

**Comment by DandelionSprout** [comment]
Good point, especially since `.smartbanner.js` is only meant to block "Download phone apps" banners and not any other banners. I'll take a look at it within the next few days.
