### ISSUE TITLE
[Anti-Malware] Allow mirrors.advancedhosters.com

### ISSUE THREAD

**Issue by Retold3202** [DandelionSprout/adfilt#1049]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

`mirrors.advancedhosters.com` is a legitimate & important domain that provides mirrors for various Linux distros. Looks like it's being blocked by the [`||advancedhosters.com^` rule](https://github.com/DandelionSprout/adfilt/blob/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt). I'd propose changing the rule to something like `||advancedhosters.com^$denyallow=mirrors.advancedhosters.com` instead if possible. 

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

[💊 Dandelion Sprout's Anti-Malware List (for AdGuard Home, AdGuard for Android/Windows/macOS' DNS filtering, and Pi-Hole FTL ≥5.22)](https://github.com/DandelionSprout/adfilt/blob/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt)

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Which OS(s) did you use when testing this?

Linux

**Comment by DandelionSprout** [comment]
Understandable. It appears the domain got sweeped up by mostly-mistake, since a lot of the other domains that had been added alongside it were also of the `||(random word)(random word).(TLD)^` format and could be easily determined to be malware. I'll come up with something this morning.
