### ISSUE TITLE
add 123notes.com to whitelist

### ISSUE THREAD

**Issue by ousigui123** [DandelionSprout/adfilt#1050]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

some users of our web reported that Dandelion Sprout blocks our site:  www.123notes.com.

our site is a sticky notes app ,is very simple notes list like 1,2,3,  so called 123notes.com

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

other

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

 
[Adblock Plus 3.13]
! Title: 💊 Dandelion Sprout's Anti-Malware List (for AdGuard Home, AdGuard for Android/Windows/macOS' DNS filtering, and Pi-Hole FTL ≥5.22)
! Version: 20August2024v1
! Expires: 2 days
 

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Browser version(s)

other

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

windows 10

**Comment by DandelionSprout** [comment]
I can't find `123notes.com` in the list, and I can't find its IP address (`129.227.60.74`) in the list either.

Are you sure that it's that list that is causing the blocking?

**Comment by ousigui123** [comment]
reported by users from :  https://www.reddit.com/r/selfhosted/comments/1exqf7j/comment/lj7pdqb/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by DandelionSprout** [comment]
Good to know.

So from what I can understand of the replies to that post, a-hellrasier (the Reddit user) is talking crap. He seems to have completely hallucinated when he claimed that `123notes.com` is listed as a domain in that list.

**Comment by hagezi** [comment]
`123notes.com` CNAME  `1593677.vhost96.mianbeian.top`
`top` tld ist blocked and `mianbeian.top` is not excluded. ;)

**Comment by DandelionSprout** [comment]
…Oh. 😅

Okay, so, uh, I need to get slightly clever on how to fix it. I think I have an idea…ish.

**Comment by hagezi** [comment]
The top tld domains are 98% malicious, malware, scam, phishing, badware and the top tld should therefore be blocked. So if someone chooses a “service” that uses top as tld, don't be surprised if it is blocked somewhere.
