### ISSUE TITLE
Uber Eats login redirect breaking

### ISSUE THREAD

**Issue by ctp9** [DandelionSprout/adfilt#1051]
## Which entry/entries are you submitting?

https://www.ubereats.com/

## Which things do they block, hide, or unbreak?

Upon logging in, the URL https://www.ubereats.com/login-redirect/ gets affected by Actually Legitimate URL Shortener Tool and fails to redirect to logged in account.

## Which of my lists are you submitting it to?
Actually Legitimate URL Shortener Tool

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop or Android version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Still Don't Care About Cookies (The extension)
- [ ] AdNauseam
- [ ] AdGuard Private DNS

Adblocker version(s):
1.59.0

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Actually Legitimate URL Shortener Tool

## (Optional) Which browser(s) and version did you use?

Firefox Developer Edition version 130.0b9 (64-bit)

**Comment by DandelionSprout** [comment]
While I have an idea for a fix, could you post a screenshot of the uBO logger for the time period from when you enter the login page to when the redirection breaks, so I could also do an additional better fix?

**Comment by DandelionSprout** [comment]
Since I haven't heard of the same problem from anyone after the fix I added a month ago, it seems to have been fixed in my eyes.

**Comment by ctp9** [comment]
Apologies for a slow reply. I just tested it and can confirm that it has been fixed. Thank you!
