### ISSUE TITLE
Browse websites without logging in - New Entry

### ISSUE THREAD

**Issue by zkisaboss** [DandelionSprout/adfilt#1053]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Include magma.com
```
magma.com##modals-box
```

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.59.0

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

![](https://i.gyazo.com/96dcfb157de915972f6fb67e9fc9d014.png)

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

130.0

### Which OS(s) did you use when testing this?

macOS

### OS version(s)

14.6.1 on ARM64

**Comment by DandelionSprout** [comment]
I can't find anything on the frontpage (The listed example page), and I can't readily see that `##modals-box` matches any visible parts of the pages I've found on that site so far.

Do you have a screenshot of the page, and an example link for the exact page where the entry is needed?

**Comment by zkisaboss** [comment]
> I can't find anything on the frontpage (The listed example page), and I can't readily see that `##modals-box` matches any visible parts of the pages I've found on that site so far.
> 
> 
> 
> Do you have a screenshot of the page, and an example link for the exact page where the entry is needed?

They might have updated the site, or it appears after you've drawn a certain amount of brushstrokes. I'll test it tomorrow and see if the login message still appears.

**Comment by bitsper2nd** [comment]
Maybe he was referring to this modal?

![image](https://github.com/user-attachments/assets/216d11d5-4cc9-4149-8973-a27ca8325043)

I encountered on this page from the website.

https://magma.com/art-jams/browse

Here is how it looks in the preview after applying it on AdGuard web extension in Firefox.

![image](https://github.com/user-attachments/assets/86eef817-fe5a-476e-a400-2742032b1a7c)
