### ISSUE TITLE
Burp Labs broken

### ISSUE THREAD

**Issue by wassim-devel** [DandelionSprout/adfilt#1054]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

If you click "access the lab" in a burp suite lab, with "Actually Legitimate URL Shortener Tool" enabled in uBO, you will get redirected to a page that says "bad request"

here is an example link:
https://portswigger.net/web-security/csrf/bypassing-samesite-restrictions/lab-samesite-strict-bypass-via-client-side-redirect

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Which OS(s) did you use when testing this?

macOS

**Comment by iam-py-test** [comment]
Thank you for reporting this. I have fixed it in https://github.com/DandelionSprout/adfilt/commit/51b6b12a05af35bb0ed5c9218ed2fb16b5929a5c.
Please wait a few minutes, update your filterlists, and retest to see if the problem still can be reproduced.
