### ISSUE TITLE
Browse websites without logging in - New Entry - substack

### ISSUE THREAD

**Issue by bitsper2nd** [DandelionSprout/adfilt#1056]
## Which entry/entries are you submitting?

```
##article > [class*="_subscribeDialog_"]
##article > [class*="_background_"]
```

## Which things do they block, hide, or unbreak?

![image](https://github.com/user-attachments/assets/bbf6e3c4-79f7-4cef-a2a4-0cd1e67ad0e0)

![image](https://github.com/user-attachments/assets/e7a6df00-65b7-4542-ad32-d4d24d101680)

## Which of my lists are you submitting it to?
Browse websites without logging in

## Which adblocker(s) and version did you use when writing and testing the entries?

- [ ] uBlock Origin
- [ ] AdGuard (Paid desktop or Android version)
- [x] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Still Don't Care About Cookies (The extension)
- [ ] AdNauseam
- [ ] AdGuard Private DNS

Other(s):

Adblocker version(s):
4.4.22 

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

AGuard Base filter (Optimized version) and the following custom filters:
![image](https://github.com/user-attachments/assets/a7a4b34c-108c-41dc-a9d2-f678cc6a441d)

## (Optional) Which browser(s) and version did you use?

Firefox 130.01 (Microsoft Store version) on Windows 11

**Comment by bitsper2nd** [comment]
## Additional entry

```
##.intro-popup
###main:style(visibility: visible !important;)
##html.modal-in, html.show-intro-popup:style(overflow: auto !important;)
##.has-intro-popup.show-intro-popup body:style(height: auto !important; width: auto !important; overflow: auto !important;)
```

## Description 

Hides substack intro page 

![image](https://github.com/user-attachments/assets/05405295-b8f1-4f0e-9cd6-631c67be3715)

![image](https://github.com/user-attachments/assets/5066cde6-7f28-435b-a654-c1da8247e02c)


## References

- https://www.microsoftsecurityinsights.com/
- https://mbcloudteck.substack.com/
- https://www.chipstrat.com/p/understanding-intel

**Comment by DandelionSprout** [comment]
It seems a fair few other annoyances lists out there have entries for that site already, so I'll combine theirs along with `##.intro-popup`, and then we'll see how well it goes.
