### ISSUE TITLE
Legitimate URL Shortener - breaking legitimate forum URLs

### ISSUE THREAD

**Issue by he-pennypacker** [DandelionSprout/adfilt#1058]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Many forums identify the thread with a t=nnnnnn parameter as part of the URL. Legitimate URL Shortener is removing the t=nnnnnn parameter, which the forum then doesn't know what to do with.

For example Linux Mint:
https://forums.linuxmint.com/viewtopic.php?t=388943

VirtualBox:
https://forums.virtualbox.org/viewtopic.php?t=103107

Ubuntu:
https://ubuntuforums.org/showthread.php?t=2393166

### Add screenshots below if needed

![image](https://github.com/user-attachments/assets/9eecefcb-9fdf-459b-8029-f112c0fd63f4)

![image](https://github.com/user-attachments/assets/74cd457d-2374-481e-94f5-680d5772d445)

### Which adblocker(s) did you use when testing this?

AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)

### Adblocker version(s)

AdGuard Browser extension
Version 4.4.22

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

Legitimate URL Shortener version: 2.0.8.21

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

Mozilla Firefox Debian Package
130.0.1 (64-bit)

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

24.04 LTS (64-bit)

**Comment by he-pennypacker** [comment]
I should add, the t= parameter is removed when following a Duckduckgo search result. E.g.

1. Search for something using DDG
2. Click on result
3. Forum is broken due to removed threadid parameter

**Comment by DandelionSprout** [comment]
I found what *appears* to be a pretty easy fix for this (which I've now added), as I narrowed down the possible causes very quickly. 🌞

**Comment by he-pennypacker** [comment]
Awesome, it 's sorted out on DuckDuckGo searches from what I've seen so far. Thanks for the speedy resolution :smile:
