### ISSUE TITLE
`://` Filter Breaks Asset Loading for All Websites

### ISSUE THREAD

**Issue by ThisNekoGuy** [DandelionSprout/adfilt#1064]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

This one is really hard to miss because I literally can't even load github without just plain HTML staring back at me, using the Domains version if the Anti-Malware list. I'm forced to either turn off the list or otherwise use a different browser/device.

Steps to Reproduce:

- Go to literally any website.

### Add a screenshot of the extension's logger

![screenshot](https://github.com/user-attachments/assets/35f2601e-2608-4ae5-9686-825dcb86c326)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.60.0

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

- https://github.com/DandelionSprout/adfilt/blob/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareDomains.txt

### Which browser(s) did you use when testing this?

<i>(Other)</i>

### Browser version(s)

Browser: Librewolf (version 130.0.1-1)

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

OS: Gentoo Linux (x86_64, rolling release)

**Comment by iam-py-test** [comment]
This issue should have been already fixed: https://github.com/DandelionSprout/adfilt/issues/1062
Please update your filterlists and check if the issue still exists.
Thanks

**Comment by DandelionSprout** [comment]
While I acknowledge that the core problem is entirely caused by me (though I fixed it in the list itself around 10 hours ago), I admit I'm surprised by that a fair number of users out there are using list versions (e.g. raw-domains, Hosts) in adblocker tools for which specifically tailored list versions have existed for many years (e.g. AdGuard Home, uBlock Origin). 😓

**Comment by ThisNekoGuy** [comment]
I switched to the regular adblock one; I had actually already tried to update the domains list in uBlock but for whatever reason it just loading spinned for a few seconds then stopped and didn't seem to actually be updating the list for me. :/
No idea why

**Comment by DandelionSprout** [comment]
Doesn't seem like anyone else have run into any additional problems with this situation, so I'll declare it a solved case.
