### ISSUE TITLE
Adguard Home List: Alibaba/Aliexpress

### ISSUE THREAD

**Issue by nightznero** [DandelionSprout/adfilt#1066]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Helloz Dandi,

Yesterday I noticed that **AdGuard Home List** blocks by CNAME **Alibaba.com** However,not only on Alibaba,from CNAME clocking we can see its also blocks `pl.aliexpress.com` & `global.aliexpress.com`
Could You please in free time unlock it?
Best Regards, NIGHTZNERO.

### Add screenshots below if needed

![Screenshot_20241020_035258](https://github.com/user-attachments/assets/df98501d-82ff-4578-abf2-2592ccfe910b)

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop/Android versions - Standard filtering + DNS Blocking™™©)

### Adblocker version(s)

Adguard Home List on Android ADG in DNS Section

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

Too much to say but only one list blocks it

### Which browser(s) did you use when testing this?

Vivaldi, Brave Browser, It's about a phone app, TV app, or console

### Browser version(s)

Newest

### Which OS(s) did you use when testing this?

Android

### OS version(s)

A13 OneUI 5.1

**Comment by iam-py-test** [comment]
Caused by https://github.com/easylist/easylist/blob/8729b63680d55e4570bf1c5182a4673be24117cb/easylist/easylist_thirdparty_popup.txt#L51
smed79 noted this behivor on the commit: https://github.com/easylist/easylist/commit/fb38d5be20cb2159cb5ba7b0429afde735e3f798#commitcomment-145338073
Maybe `$popup` filters should be excluded from the DNS list?
Thanks

**Comment by DandelionSprout** [comment]
I feel I should be able to remove all entries with the word `akamaiedge` in them, hopefully tomorrow (Monday-ish).

**Comment by nightznero** [comment]
> I feel I should be able to remove all entries with the word `akamaiedge` in them

I guess 90% of `akamaiedge` AND `akamai` should be deleted cause I noticed A LOT products uses that CNAME clocking like Sporify,Microsoft(Windows especially),Games on Android like a Apex,Wild Rift and so on
![Screenshot_20241020_200944](https://github.com/user-attachments/assets/e26403ad-4313-4546-a247-0967541c4fb0)
