### ISSUE TITLE
Don't block top domains

### ISSUE THREAD

**Issue by LittleChest** [DandelionSprout/adfilt#1067]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Many website beginners use top as their starting point, but the list is very simple and crude and blocks all top domains.

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop/Android versions - Standard filtering + DNS Blocking™™©)

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

https://github.com/DandelionSprout/adfilt/blob/master/AnnoyancesList

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Which OS(s) did you use when testing this?

Windows 11, Android

**Comment by DandelionSprout** [comment]
I normally whitelist individual .top sites if all 3 of these conditions are met:
1) Contains proper content (Sites with "Coming soon", "Apache config", etc. are not whitelisted).
2) The .top site is not an instant redirect to a site that isn't `.top`.
3) There are no immediate indications that the site contain malware, spam, or fraud.

Should a site meet all 3 conditions, I'd whitelist such a site pretty fast, so if any individual sites are found then they can be reported to me easily.

**Comment by xianhongtao** [comment]
Such an aggressive blocking strategy will affect the installation rate of your list, please seriously consider it.  
You know what? Actually, I don't care whether you change it or not. I definitely won't install your list anyway.
