### ISSUE TITLE
pCloud site

### ISSUE THREAD

**Issue by nightznero** [DandelionSprout/adfilt#1068]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Helloz Dandi,Your `ip rule` breaks `pCloud` site.
Best Regards, NIGHTZNERO.

### Add screenshots below if needed

![Screenshot_20241105_000645_AdGuard](https://github.com/user-attachments/assets/600c6b09-0cd8-4cf9-8edb-37bd5a04cc56)

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop/Android versions - Standard filtering + DNS Blocking™™©)

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

AdGuard Home List

### Which browser(s) did you use when testing this?

Brave Browser

### Which OS(s) did you use when testing this?

Android

### OS version(s)

A13 OneUI 5.1

**Comment by DandelionSprout** [comment]
You seem fully correct in that the site (Pcloud) is 100% fully legitimate and major site. But which exact method I'd use to fix that incorrect IP blocking is something I'm not yet fully sure about.
