### ISSUE TITLE
small typo in element hiding filter

### ISSUE THREAD

**Issue by avanikaein** [DandelionSprout/adfilt#1070]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

existing filter `tu.no,digi.no##div[id^=brandboard *:has(> i])` seems to have `]` in the incorrect spot
should correct to close the `:has()` and then `]`
suggestion: `tu.no,digi.no##div[id^=brandboard *:has(> i)]`

### Which adblocker(s) did you use when testing this?

Adblock Plus (Firefox or Manifest V2)

### Adblocker version(s)

4.7.1

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

Dandelion Sprout's Nordic Filters+EasyList

### Which browser(s) did you use when testing this?

Microsoft Edge (Manifest V2)

### Which OS(s) did you use when testing this?

macOS

### OS version(s)

Sonoma 14.6.1

**Comment by DandelionSprout** [comment]
I've struggled with stomach and cold problems for 2 days after eating some foul-quality meatballs, but I hope to be able to properly look into it this weekend, hopefully this Saturday UTC+1.

**Comment by avanikaein** [comment]
thanks for the update @DandelionSprout, wishing you a speedy recovery.
