### ISSUE TITLE
[Question] .gvt2.com

### ISSUE THREAD

**Issue by nightznero** [DandelionSprout/adfilt#1071]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Helloz Dandi,

I noticed that Your list (AdGuard Home List) includes `@@://beacons*.gvt2.com^` While @StevenBlack on his List blocks all (i guess) `*.gvt2.com`
I would like to know; 
it's especially made  `@@://` instead of `@@||` to not collide with each other ?
If its not about the syntax I would like to know why it's unblocked,does it's breaks anything in Android/Google? Bcs we know that Steven blocks adware and guess its any Analytics but if it's unblocked is there any sync or so underneath?
Best regards, NIGHTZNERO.

### Add screenshots below if needed

![Screenshot_20241108_074725_Brave](https://github.com/user-attachments/assets/da1a424e-2578-4b07-beac-eaab9204bc10)

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

AdGuard Home List

### Which OS(s) did you use when testing this?

Android

**Comment by StevenBlack** [comment]
@nightznero to clarify ⬆️ my hosts files don't block `*.gvt2.com` because wildcards are not a thing in hosts files. So domains must be blocked individually, and explicitly.

The domains explicitly blocked by my hosts files are:

```
beacons.gcp.gvt2.com
beacons.gvt2.com
beacons2.gvt2.com
beacons3.gvt2.com
beacons4.gvt2.com
beacons5.gvt2.com
```

**Comment by DandelionSprout** [comment]
Furthermore (and about the OP's specific question), :// is to specify that the domain starts with that text.

`://` would cover `beacons*.gvt2.com`, but not for example `johnmadden.beacons*.gvt2.com`.

`||` would cover both.

`://` would be in theory be possible to replace with a single `|` line, which'd have the same effect in AdGuard DNS tools but which'd leave the entry useless in regular adblockers, though that list of mine is strongly discouraged from use in regular adblockers except in the most hardcore of debugging situations.

**Comment by nightznero** [comment]
> @nightznero to clarify ⬆️ my hosts files don't block `*.gvt2.com` because wildcards are not a thing in hosts files.

Included screen to avoid misunderstanding,also i think Dandi know what i mean if he works with filter lists but still thanks fir clarify Steven 🫱🏻‍🫲🏼


> `://` would cover `beacons*.gvt2.com`, but not for example `johnmadden.beacons*.gvt2.com`.
> 
> `||` would cover both.

Thanks for explaination 🫡
but i still have a one tiny question 😅

> though that list of mine is strongly discouraged from use in regular adblockers except in the most hardcore of debugging situations.

Does that mean that `beacons*.gvt2.com` & `beacons.gcp.gvt2.com` (or just whole `gvt2.com`) can be freely blocked if i dont mind Debug? Or its necessary for something to not break and You know smthg that Steven doesn't?🤔
If can be blocked one last question,how to overwrite Your whitelisted rules? Cause there is no specific modifies like `$important` or `$badfilter`that would be higher than simple whitelist,am I right? (We don't talk about deleting ur list,it's stays with me,looking for another "exit" from that scenario)

**Comment by DandelionSprout** [comment]
Essentially:

1) Do not use the list in regular adblockers ***unless*** it is to test out how to fix a problem caused by the list.
2) `$important` does indeed override whitelistings.
2b) For `$badfilter` it gets a bit different, but `@@||example.org^$badfilter` will make the adblocker decide to not use `@@||example.org^`. It will however continue to use entries that are spelled even slightly differently, like `@@example.org|`

**Comment by DandelionSprout** [comment]
With the general situation(s) having seemingly gone well enough since the last comment(s), I think I can declare this case closed. 🌞

**Comment by nightznero** [comment]
> 2. `$important` does override whitelistings.
>    2b) For `$badfilter` it gets a bit different, but `@@||example.org^$badfilter` will make the adblocker decide to not use `@@||example.org^`. It will however continue to use entries that are spelled even slightly differently, like `@@example.org|`
I know how adb syntax works(at least in that case😅) But Your list is created for DNS adblockers(if im not wrong),so i wanted to know how to `un-whitelist` beacons pings in gvt2.com domain in DNS blockers like;
1. AdGuard Android -> DNS filtering
2. AdAway
3. Nebulo
etc.
In DNS syntax there is no rules like `$badfilter` or `$important` right? This is reserved for ADB syntax,Domain & Hosts are very limited.
So only to give more priority for StevenBack rules is to delete ur list,or i still miss something?


> With the general situation(s) having seemingly gone well enough since the last comment(s), I think I can declare this case closed. 🌞

Exams before X-Mas and totally forgot about this,issue sure can be already closed but if You don't mind in free time answer with more clarification would be awesome
Best Regards, NIGHTZNERO.

**Comment by DandelionSprout** [comment]
• *"In DNS syntax there is no rules like $badfilter or $important right? This is reserved for ADB syntax,Domain & Hosts are very limited."*
That is correct.

• *"So only to give more priority for StevenB[l]ack rules is to delete ur list,or i still miss something?"*
That is unfortunately also correct. Alternately, adding `@@://beacons*.gvt2.com^$badfilter` to your custom user rules in "AdGuard for Android" → "DNS Protection" → "DNS filters" → "User Filter" would **on paper** work to nullify that one specific entry in my list.
