### ISSUE TITLE
Kino.dk

### ISSUE THREAD

**Issue by kimsey0** [DandelionSprout/adfilt#1072]
## Hvilke(n) regle(r) sender du ind?
```
kino.dk##.ads-topscroll
kino.dk##.layout-block--advertisement
```

## Hvilke ting blokerer, skjuler, eller fikser de(n)?
Store, tomme områder:
![billede](https://github.com/user-attachments/assets/35ac8913-2394-432a-948e-d335e3a28cc2)
![billede](https://github.com/user-attachments/assets/749c264a-693d-4bd1-ba1f-b9510660a73d)

## Hvilke af mine lister sender du den/dem ind til?
Dandelion Sprouts nordiske filtre

## Hvilken reklameblokkerer og version brugte du da du skrev og testet reglen(e)?
- [x] uBlock Origin
- [ ] AdGuard (Betalt skrivebordsversion)
- [ ] AdGuard (Webbrowserudvidelse)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (Udvidelsen)

Andre:

Reklameblokerer-version(er):
uBlock Origin 1.60.0

## Hvilke filterlister brugte du? At ikke fortælle dette, vil føre til at sagen bliver midlertidigt lukket frem til dette bliver fortalt.
![billede](https://github.com/user-attachments/assets/13b20d4a-b420-4069-868d-990d7dcba962)

## (Valgfrit) Hvilke(n) webbrowser(e) og version(er) brugte du?
Firefox 132.0.1

**Comment by DandelionSprout** [comment]
Mange tak, specielt for de foreslåede reglerne. Jeg skal få håndteret den webside inden nogre timer.
