### ISSUE TITLE
Euroinvestor.dk

### ISSUE THREAD

**Issue by kimsey0** [DandelionSprout/adfilt#1073]
## Hvilke(n) regle(r) sender du ind?
```
www.euroinvestor.dk##.topscroll-wrapper
www.euroinvestor.dk##.topbanner-desktop
www.euroinvestor.dk##.banner-mb-20
```

## Hvilke ting blokerer, skjuler, eller fikser de(n)?
Tomme områder:
![billede](https://github.com/user-attachments/assets/2294ff96-584f-438f-8540-9a71554d7f3c)

Inklusive nogle områder der ikke vises lige nu, men nogle gange gør.

## Hvilke af mine lister sender du den/dem ind til?
Dandelion Sprouts nordiske filtre

## Hvilken reklameblokkerer og version brugte du da du skrev og testet reglen(e)?
- [x] uBlock Origin
- [ ] AdGuard (Betalt skrivebordsversion)
- [ ] AdGuard (Webbrowserudvidelse)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (Udvidelsen)

Andre:

Reklameblokerer-version(er):
uBlock Origin 1.60.0

## Hvilke filterlister brugte du? At ikke fortælle dette, vil føre til at sagen bliver midlertidigt lukket frem til dette bliver fortalt.
![billede](https://github.com/user-attachments/assets/13b20d4a-b420-4069-868d-990d7dcba962)

## (Valgfrit) Hvilke(n) webbrowser(e) og version(er) brugte du?
Firefox 132.0.1

**Comment by DandelionSprout** [comment]
Jeg havde glemt, at også mærke "fix" i kodeendringsnavnet for denne rapport, som jeg nu også har fixet.

**Comment by kimsey0** [comment]
Tak!

> Det har gået nogle år, siden sidst jeg skrev dansk i semiproffe situationer, så jeg kan bare gætte på, at udfaldet gik bra.

Næsten! "bra" er svensk. På dansk hedder det "godt".
