### ISSUE TITLE
tek.no ads

### ISSUE THREAD

**Issue by Torsteinws** [DandelionSprout/adfilt#1074]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

If you scroll a bit down at [tek.no](https://www.tek.no/), then you will see an ad in the middle of the page

### Add screenshots below if needed

![Screenshot 2024-11-18 154127](https://github.com/user-attachments/assets/3a78b371-7efc-47eb-ab42-7ddb58718148)

### Add a screenshot of the extension's logger

![Screenshot 2024-11-18 154245](https://github.com/user-attachments/assets/739a3315-0c88-47ad-8272-c27e6ac7f8b8)

<details><summary>Logger output</summary>

```
+22
##body::before
www.tek.no
get
dom
https://www.tek.no/
```
```
+4
*$ping,3p
--
www.tek.no
3
post
beacon
https://dc.schibsted.io/api/v1/track/sdrn:schibsted:client:tekno
```
```
+4
##main:style(min-height: unset !important)
www.tek.no
get
dom
https://www.tek.no/
```
```
+4
##main > div > section + div:last-of-type
www.tek.no
get
dom
https://www.tek.no/
```
```
+4
##div[class^="advertory-" i]:not(html, body, :empty)
www.tek.no
get
dom
https://www.tek.no/
```
```
+4
##body::before
www.tek.no
get
dom
https://www.tek.no/
```
```
+4
##a[href^="https://ad.doubleclick.net/"]
www.tek.no
get
dom
https://www.tek.no/
```
```
+4
###topAd
www.tek.no
get
dom
https://www.tek.no/
```
```
+2
*$ping,3p
--
www.tek.no
3
post
beacon
https://dc.schibsted.io/api/v1/track/sdrn:schibsted:client:tekno
```
```
+1
||hotjar.com^
--
www.tek.no
3
get
script
https://static.hotjar.com/c/hotjar-1477401.js?sv=6
```
```
+1
##+js(remove-attr, class, .dfp-loaded)
www.tek.no
get
scriptlet
https://www.tek.no/
```
```
+1
##+js(abort-on-property-write, __AB__)
www.tek.no
get
scriptlet
https://www.tek.no/
```
```
+1
*$ping,3p
--
www.tek.no
3
post
beacon
https://dc.schibsted.io/api/v1/track/sdrn:schibsted:client:tekno
```
```
+1
||cmp.tek.no^
--
www.tek.no
1
get
script
https://cmp.tek.no/unified/wrapperMessagingWithoutDetection.js
```
```
+1
||log.medietall.no^
--
www.tek.no
3
get
script
https://log.medietall.no/analytics.js
```
```
+1
googletagmanager_gtm.js:5
<<
www.tek.no
3
get
script
https://www.googletagmanager.com/gtag/js?id=UA-258878-18
```
```
+1
||googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5
--
www.tek.no
3
get
script
https://www.googletagmanager.com/gtag/js?id=UA-258878-18
```
```
+1
||googletagmanager.com^
--
www.tek.no
3
get
script
https://www.googletagmanager.com/gtag/js?id=UA-258878-18
```
```
+0
||datadoghq-browser-agent.com^$3p
--
www.tek.no
3
get
script
https://www.datadoghq-browser-agent.com/datadog-logs.js
```
```
+0
||mrf.io/statics/marfeel-sdk.js
--
www.tek.no
3
get
script
https://sdk.mrf.io/statics/marfeel-sdk.js?id=6453
```
```
+0
##+js(remove-attr, class, .dfp-loaded)
www.tek.no
get
scriptlet
https://www.tek.no/
```
```
+0
##+js(abort-on-property-write, __AB__)
www.tek.no
get
scriptlet
https://www.tek.no/
```
```
+0
||datadoghq-browser-agent.com^$3p
--
www.tek.no
3
get
script
https://www.datadoghq-browser-agent.com/datadog-logs.js
```
```
+0
https://www.tek.no/
```
</details>

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.60.0

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

![Screenshot 2024-11-18 154358](https://github.com/user-attachments/assets/14b61d00-9000-4d8b-a056-72cfbac0228b)
![Screenshot 2024-11-18 154413](https://github.com/user-attachments/assets/27b98725-8890-4935-b89e-1b796936d328)
![Screenshot 2024-11-18 154439](https://github.com/user-attachments/assets/3a0e85ea-46d0-4726-8441-d4df20ce775b)

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

132.0.1

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

22H2

**Comment by DandelionSprout** [comment]
I've traditionally tended to be lenient on sliders for jobs, apartments, Prisjakt, etc., but something seems different about this particular slider ("Dagens anbefalte fra NetOnNet", and that almost all of the buttons lead to different sites and/or tracker redirection).

I'll come up with something, but am not 100% sure when or how just yet.

**Comment by THEtomaso** [comment]
Either one of these will do the job:
```
tek.no##section:has-text(Dagens gode kjøp)
tek.no#?#section:-abp-has(span:-abp-contains(annonse))
```
I'll be adding both, for good measure. :)

**Comment by DandelionSprout** [comment]
While THEtomaso's entries do work to remove that section, for me it has been a 50:50 call whether for me too to remove that section. I very narrowly landed on no, with the decisive factor being their note on the bottom of `https://www.tek.no/beste-tilbud`:

• *"Har vi testet produktet vil du se vår tek.no-logo med karakteren vi har gitt. Slik kan du også se hvilke varer vi mener er verdt å investere i."*

Accordingly, it doesn't seem that Prisjakt is simply messing around on its own, but that there is at least *some* extent of editorial control by Tek.
