### ISSUE TITLE
auslogics.com blocked

### ISSUE THREAD

**Issue by timkgh** [DandelionSprout/adfilt#1076]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

AdGuard Home using Dandelion Sprout's Anti-Malware List blocks auslogics.com

### Add screenshots below if needed

![65236](https://github.com/user-attachments/assets/3aea1a75-ae8d-4f84-acf3-fca375b3facd)

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

Dandelion Sprout's Anti-Malware List

### Which browser(s) did you use when testing this?

<i>(Other)</i>

### Which OS(s) did you use when testing this?

<i>(Other)</i>

**Comment by DandelionSprout** [comment]
As of 2021, the software was considered less-than-ideal PUP, so I'd be surprised if they have got any better since then: #422 #251

**Comment by timkgh** [comment]
I see. I was just trying to read an article on their site, not use their software.
https://www.auslogics.com/en/articles/how-to-check-ssd-health-a-guide-for-windows-10-and-windows-11-users/
