### ISSUE TITLE
Google map website not opening

### ISSUE THREAD

**Issue by sankhababu** [DandelionSprout/adfilt#1077]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Google map site not opening when Legitimate URL Shortener is enabled with UblockOrigin in android Firefox.

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

Default UblockOrigin setting.

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Which OS(s) did you use when testing this?

Android

### OS version(s)

14

**Comment by DandelionSprout** [comment]
Considering the lack of both a screenshot and an example link, that I can't easily reproduce it on my phone, and that Legitimate URL Shortener isn't part of uBO's default settings and therefore can't be correct, I'll unfortunately choose to close this issue report.

The situation is that I'm hoping for more GitHub users out there to know that they'd have to use my report forms at least a little bit more detailed, so I'm hoping to set a base example for what counts as too little info.
