### ISSUE TITLE
Not a valid selector

### ISSUE THREAD

**Issue by johand199** [DandelionSprout/adfilt#11]
Don't want to mess around with things i dint make, 
happens when visiting f-b.no
https://img.johand.io/f/bK4r9.png
Error handling response: Error: Failed to execute 'querySelectorAll' on 'Document': '.spklw-post:-abp-contains(Annonsørinnhold)' is not a valid selector.
    at ElementHidingTracer.checkNodes (chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js:469:34)
    at ElementHidingTracer.addSelectors (chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js:455:12)
    at browser.runtime.sendMessage.response (chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js:767:21)

**Comment by DandelionSprout** [comment]
Which adblocker extension are you using? ABP, AdBlock, uBlock Origin, or something else?

**Comment by johand199** [comment]
ABP

**Comment by DandelionSprout** [comment]
I am seeing contradictory information on whether ABP supports Unicode characters in _-abp-contains_ entries, but I know that uBlock Origin does.

It shouldn't cause any critical problems for viewing the page, but it may or may not cause some ads to slip through. If you visit e.g. https://www.f-b.no/nyheter/grensehandel/godteri/ellevill-vekst-for-svensk-godteriselskap/s/5-59-1222679, do you see any adticles (ad articles) in the "Flere saker" section, or are they blanked out like in this screencap? 
![image](https://user-images.githubusercontent.com/22780683/44607631-6e0b6e80-a7f1-11e8-97b8-326a621b8bf5.png)

**Comment by DandelionSprout** [comment]
Though it now appears to me that Fredrikstads Blad doesn't even use Spklw for its "Flere saker" section, so it shouldn't cause any real problems on that site, at least.

**Comment by johand199** [comment]
Yeh, just seems to be the console error, no issues
