### ISSUE TITLE
ssl.bblck.me

### ISSUE THREAD

**Issue by lightswitch05** [DandelionSprout/adfilt#113]
It looks like you are blocking `https://ssl.bblck.me/blacklists/hosts-file.txt` - which is a hosts file listed on https://firebog.net/

Perhaps this is a false positive?

## Describe the problem below this line as meticulously and detailed as possible:

It blocks another hosts file from being downloaded.

## Add a screenshot of the extension's logger:

![image](https://user-images.githubusercontent.com/598803/93248202-8b576080-f75d-11ea-8512-6c53f5cea479.png)

## Which adblocker(s) and version did you use when testing this?

- [ ] Nano Adblocker
- [ ] Nano Defender
- [ ] uBlock Origin
- [ ] uBlock Origin Plus
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdGuard Home
- [ ] Blokada
- [X] Pihole

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to write this will result in instant report closing.

Hosts: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt

## (Optional) Which OS and version did you use?
- [ ] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux
- [ ] Android

Other(s):

OS version:

**Comment by lightswitch05** [comment]
I would just like to add that this ticket is mostly a question as to why its blocked. If you believe it should be blocked, then I will not disagree with you. Perhaps Wally3K might want to consider removing it from his list if there are issues with it.

**Comment by llacb47** [comment]
It's not a false positive.

`Domains that used to host lists for adblockers or "hosts" tools, but which are now either used by malware pushers, or could potentially be snapped up by them.`

The domain is expired.

**Comment by lightswitch05** [comment]
Oh, I whitelisted it and I see now:

![image](https://user-images.githubusercontent.com/598803/93249342-256bd880-f75f-11ea-8bd0-d653042e58ca.png)


Thank you !

**Comment by krystian3w** [comment]
IMO now no possible buy and upload malware, Poland `cba.pl` have similar dotations as this "page expired".

**Comment by DandelionSprout** [comment]
I'm not personally an expert on expired pages, so I have to ask: What is it that you think would prevent it from being bought by anyone anywhere on the planet?

**Comment by krystian3w** [comment]
Lock/ban on "high" level by "ICANN"?
