### ISSUE TITLE
overblocking legit website: inwx.de

### ISSUE THREAD

**Issue by HorayNarea** [DandelionSprout/adfilt#114]
## Describe the problem below this line as meticulously and detailed as possible:
in the Anti-Malware lists you block `104.24.116.74`, this also blocks the legit german website of the domain registrar INWX `www.inwx.de` (although one can workaround by using `www.inwx.com/de`)

Also: this IP belongs to Cloudflare's DDoS Protection stuff… blocking any Cloudflare IP will probably block a lot more legit websites

## Add screenshots below if needed:
```
drill www.inwx.de @8.8.8.8
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 13911
;; flags: qr rd ra ; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; www.inwx.de.	IN	A

;; ANSWER SECTION:
www.inwx.de.	118	IN	A	172.67.206.196
www.inwx.de.	118	IN	A	104.24.117.74
www.inwx.de.	118	IN	A	104.24.116.74

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 25 msec
;; SERVER: 8.8.8.8
;; WHEN: Fri Sep 18 13:10:03 2020
;; MSG SIZE  rcvd: 77
```

## Add a screenshot of the extension's logger:
![Screenshot from 2020-09-18 13-16-11](https://user-images.githubusercontent.com/1871153/93591724-2eec7f00-f9b1-11ea-9cd3-ff8d6f0c17e8.png)

## Which adblocker(s) and version did you use when testing this?

- [ ] Nano Adblocker
- [ ] Nano Defender
- [ ] uBlock Origin
- [ ] uBlock Origin Plus
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [x] AdGuard Home
- [ ] Blokada

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to write this will result in instant report closing.
Uhm… a lot, but see Screenshot above that it for sure comes from this list :D

## Which browser(s) and version did you use?
Not relevant since it's DNS-blocking.

## (Optional) Which OS and version did you use?
Not relevant since it's DNS-blocking.

**Comment by DandelionSprout** [comment]
Thanks for pointing this out. My own criteria for adding IP addresses to lists have become considerably more strict in the time since both `104.24.116.74` and `104.24.117.74` were added, so I'll remove those entries now.
