### ISSUE TITLE
Invalid entry.

### ISSUE THREAD

**Issue by pallebone** [DandelionSprout/adfilt#117]
Hi there,
 
adfilt/Alternate versions Anti-Malware List/AntiMalwareHosts.txt 

Has an invalid entry:

[i] Target: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  [✓] Status: Retrieval successful
  [i] Received 137 domains, 1 domains invalid!
      Sample of invalid domains:
      - id.server|

I believe '|' character should be removed to fix.

Kind regards
Pete

**Comment by DandelionSprout** [comment]
Thanks for the headsup. A fix will be created and go live within 90min.

**Comment by pallebone** [comment]
Thank you for your reply :)
