### ISSUE TITLE
TwitterPureReadingExperience hides lists of followes and following

### ISSUE THREAD

**Issue by Jorengarenar** [DandelionSprout/adfilt#122]
## Describe the problem below this line as meticulously and detailed as possible:

When checking the list of followers/following, it appears empty. Disabling filter list makes them appear again.

## Which adblocker(s) and version did you use when testing this?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada

Adblocker version(s): v1.30.2

## Which filterlists did you use? Failing to write this will result in instant report closing.

* [🐥 Twitter: Pure Reading Experience](https://github.com/DandelionSprout/adfilt/blob/b1c4b29330befc259812464b4f4fa579c346cd33/TwitterPureReadingExperience.txt)

## Which browser(s) and version did you use?
* Firefox 81.0.1 (64-bit)

## (Optional) Which OS and version did you use?
- [ ] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [X] Linux
- [ ] Android

OS version: `5.8.14-arch1-1`

**Comment by DandelionSprout** [comment]
It will be pretty difficult for me to test this, since I haven't had a Twitter account since June 2017 (Nowadays I just browse a small handful of comedy accounts there). Nevertheless I can try to make the existing entries more narrow within a couple hours in the hope that it'll go better.

**Comment by DandelionSprout** [comment]
Okay, I've now given it a shot as per list version `11October2020v2-Alpha`.

**Comment by Jorengarenar** [comment]
Followers are back, but so is "Who to follow"

**Comment by Jorengarenar** [comment]
Lists are visible, but the only thing removed from 'Who to follow" it this text itself

**Comment by DandelionSprout** [comment]
In addition to the above stuff, I've recently moved my main setup from Nano Adblocker to uBlock Origin, and was surprised to see that the `</>` button in uBO's logger didn't re-display most of the hidden elements, making it considerably harder for me to see what turned-on entries are actually hiding.

As such, I apologise in advance for how this will take me considerably longer to fix than usual.

**Comment by DandelionSprout** [comment]
Okay, so having now checked out the list on Firefox, and googling around to remember what the "Who to follow" menu was:

Can you (or other Twitter account owners) see if `twitter.com#?#div:not([class*=" "]) > div > div:-abp-has(> aside [data-testid$=-follow])` work for you?

**Comment by Jorengarenar** [comment]
Still the same

**Comment by Yuki2718** [comment]
I'm not sure if I understand what is the issue correctly, but if it's that Who to follow in Twitter Home is not hidden, on my account it's perfectly hidden by Pure Reading Experience List as well as What's happening.

**Comment by Jorengarenar** [comment]
The ones from sidebar are hidden. The problem are the "Who to follow" suggestions appearing in feeds (especially on users' profiles). Tweet, tweet, tweet and then "Who to follow".

**Comment by Yuki2718** [comment]
@Jorengarenar Test `twitter.com##div[aria-label^=Timeline] > div[style] > div[style]:has([data-testid$=-follow])`

**Comment by Jorengarenar** [comment]
This is it. "Who to follow" is no more

**Comment by peace2000** [comment]
I would change it to this `twitter.com##nav[aria-label][role="navigation"] + div > section > div[aria-label^=Timeline] > div[style] > div[style]:has([data-testid$=-follow])` because otherwise there will be breakages on a separate page that lists similar people to follow.

Sample page: https://twitter.com/i/connect_people?user_id=18932374

Breakage:
![kuva](https://user-images.githubusercontent.com/17256841/96509846-51e6a900-1265-11eb-89ae-b2b0000bfb18.png)

No breakage:
![kuva](https://user-images.githubusercontent.com/17256841/96509740-28c61880-1265-11eb-8b38-d55f66e4e53a.png)

**Comment by Yuki2718** [comment]
FYI now "Who to follow" in timeline is not always under `##nav[aria-label][role="navigation"] + div`. cf. `https://old.reddit.com/r/uBlockOrigin/comments/kcawz5/is_this_possible/`

**Comment by kqvanity** [comment]
@Yuki2718 Your solution does work, however there's a quirk to it. When opening to inspect a retweet and if i'm not following the original author, the entire tweet will essentially vanish.
