### ISSUE TITLE
Some sites/pages using Visual Composer (WordPress plugin) are broken

### ISSUE THREAD

**Issue by stiang** [DandelionSprout/adfilt#124]
## Describe the problem below this line as meticulously and detailed as possible:

Hi,

I manage a WordPress for a client (https://bardola.no/en) and we’ve noticed that certain pages don’t look right when people use an ad-blocker (margins and padding disappearing).

After some investigation, I discovered that the issue is caused by the following rule in **NorwegianList.txt**:

```
##.vc_empty_space
! demokraten.no, avisa-hordaland.no, blv.no, gat.no, lp.no, osogfusa.no, raumnes.no, setesdolen.no, sunnhordland.no, vaksdalposten.no, vtb.no
```

This removes all elements with that class, which is a problem since the WordPress plugin [Visual Composer](https://visualcomposer.com/) has a separate element called Empty Space that our client uses frequently to get the look-and-feel that they want. It simply inserts a div with the class `vc_empty_space` and some styles to generate the desired empty space.

## Add screenshots below if needed:
![bardola-rule-issue](https://user-images.githubusercontent.com/94665/97151338-ac08d200-176f-11eb-98d8-dad175d07868.jpg)

The button should have white-space below it, like so:
![bardola-rule-ok](https://user-images.githubusercontent.com/94665/97151379-b75bfd80-176f-11eb-9264-773fd76f8672.jpg)

## Add a screenshot of the extension's logger:

![image](https://user-images.githubusercontent.com/94665/97151694-276a8380-1770-11eb-9c08-6d60a9036e13.png)
![image](https://user-images.githubusercontent.com/94665/97150063-deb1cb00-176d-11eb-92de-77338fa297d1.png)

## Which adblocker(s) and version did you use when testing this?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada

Other(s):

Adblocker version(s):
1.30.6

## Which filterlists did you use? Failing to write this will result in instant report closing.

![image](https://user-images.githubusercontent.com/94665/97150431-639ce480-176e-11eb-9447-c64973f55998.png)

## Which browser(s) and version did you use?

Google Chrome Version 86.0.4240.111 (Official Build) (x86_64)

## (Optional) Which OS and version did you use?
- [ ] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [X] macOS
- [ ] Linux
- [ ] Android

Other(s):

OS version:
macOS Cataline Version 10.15.7 (19H2)

**Comment by DandelionSprout** [comment]
Thanks for reporting this to me.

The entry is 3-ish years old, back when it was presumed to be the element name for an ad box instead of a spacer box. Additionally, of its 3 source pages that I've visited (`steigan.no`, `allers.no`, `icelandreview.com`), I could only reproduce the need for an entry on the former two sites.

As such, I'll fix the problem right away by making the entry a specific one, e.g. it'll only apply to `steigan.no` and `allers.no`.
