### ISSUE TITLE
"mine annonser" på finn.no

### ISSUE THREAD

**Issue by jlbrkntr** [DandelionSprout/adfilt#125]
## Describe the problem below this line as meticulously and detailed as possible:

Når man logger inn på finn.no og går inn på "Min Finn" og deretter "Mine annonser"...viser ingen av annonsene, kun antall annonser i venstre meny. Vanligvis kommer en liste på høyre delen av siden med thumbnails av hovedbilder og titler for hver annonse. Mistenker at det kan ha noe å gjøre med at filteret skjuler de store firkantet annonsene som kommer i søkeresultater, at kanskje det samtidig påvirker visning av egne annonser på Min Finn? Vedlegger noen skjermbilder.

## Add screenshots below if needed:

![Nordic Filters (på)](https://user-images.githubusercontent.com/35241025/97643205-5d955500-1a47-11eb-84b4-36cc56a4a821.jpg)

![Nordic Filters (av)](https://user-images.githubusercontent.com/35241025/97643221-64bc6300-1a47-11eb-880f-9715bef5a53a.jpg)

![søkeresultater](https://user-images.githubusercontent.com/35241025/97643236-6be37100-1a47-11eb-8dc5-57c88a305196.jpg)

## Which adblocker(s) and version did you use when testing this?

- AdGuard extension for Google Chrome
- latest version (updates automatically)

## Which filterlists did you use? Failing to write this will result in instant report closing.
- AdGuard Base filter
- Dandelion Sprout's Nordic Filters

## (Optional) Which OS and version did you use?
- Windows 7 SP1

**Comment by DandelionSprout** [comment]
Tusen takk for å ha rapportert inn dette til meg.

Jeg var i stand til å finne årsaken ganske fort: `finn.no##div.ads__unit` i 'Nordiske filtre', som jeg la til for et par uker siden for å fjerne tomme bokser i "Andre ting på Torget"-strømmene.

Jeg skal gjøre om den oppføringen til `finn.no####.ads__unit[aria-hidden]`, som ser ut til å få 'Mine annonser' til å vises riktig igjen.
