### ISSUE TITLE
gamer.no tu.no

### ISSUE THREAD

**Issue by okiehsch** [DandelionSprout/adfilt#13]
Ads at `gamer.no` and `tu.no`
![image](https://user-images.githubusercontent.com/16838044/47202570-dd2eba80-d37d-11e8-8c0e-dea696752495.png)
![image](https://user-images.githubusercontent.com/16838044/47202625-00596a00-d37e-11e8-9141-26558aafaaf9.png)

Both sites use the same inline-script to push those ads.
````
gamer.no,tu.no##+js(abort-current-inline-script.js, dfpConfig, loadAds)
gamer.no##.top-poster
tu.no##.top-poster-wrap
tu.no##.frontpage-top-poster-wrap
````
works on my end.
- Browser/version: Chrome 70
- uBlock Origin: 1.17.0

**Comment by DandelionSprout** [comment]
I had to investigate through the sites a bit further, and found a need for similar entries in the articles as well. Making the matter furthermore complicated, was that AdGuard Base Filters already had a mostly complete coverage of those ads, but with entries that were difficult for me to cross-check.

I'll get right to adding the entries I've found, which includes all those that you've found.
