### ISSUE TITLE
Being Blocked by Tinypass from viewing news articles

### ISSUE THREAD

**Issue by ArtexJay** [DandelionSprout/adfilt#131]
## Describe the problem below this line as meticulously and detailed as possible:
Even when i use Browse websites without logging in (Domains version), i still get blocked from reading articles on the websites and asking me to subscribe without letting me move on. It appears to be using buy.tinypass.com type. Would be great if you could add that to the domain lists for blocking. An example of website that does this is www.washingtontimes.com

## Add screenshots below if needed:
![image](https://user-images.githubusercontent.com/32932497/99693705-a8f4bf00-2a59-11eb-82af-4da78e74672d.png)

## Which adblocker(s) and version did you use when testing this?

- [ ] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [x] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to write this will result in instant report closing.

Browse websites without logging in (Domains version) 

## Which browser(s) and version did you use?

Microsoft Edge  Version 88.0.704.0 (Official build) canary (64-bit)

## (Optional) Which OS and version did you use?
- [ ] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux
- [ ] Android

Other(s):

OS version:

**Comment by llacb47** [comment]
`||buy.tinypass.com/checkout/offer/show?displayMode=modal$subdocument,domain=washingtontimes.com`

**Comment by DandelionSprout** [comment]
In browser setups, I heavily recommend using the regular version of *Browse Websites Without Logging In* instead at https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt. The domains version is intended for tools that support no form of adblocker lists whatsoever (e.g. Pi-hole, Blokada).
