### ISSUE TITLE
Invalid include path

### ISSUE THREAD

**Issue by slavaleleka** [DandelionSprout/adfilt#135]
there is invalid include path in [NordicFiltersAdGuard.txt:](https://github.com/DandelionSprout/adfilt/blob/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersAdGuard.txt#L1951)
```
!#if env_legacy
!#include uBO%20list%20extensions/TemporaryWaterfoxClassicFixForNordicFilters.txt
!#endif
```

since it's not absolute path, AdGuard filters compiler is considering it as relative one but `uBO list extensions` is not on the same dir level regarding the NordicFiltersAdGuard.txt

it should be:
`!#include ../uBO%20list%20extensions/TemporaryWaterfoxClassicFixForNordicFilters.txt`

**Comment by DandelionSprout** [comment]
Many thanks for reporting this to me.

Since the file in question solely consists of specific versions of entries that normally have wildcards in `$domain`, the file ideally shouldn't have been in the AdGuard list version to begin with. Give me 20min to fix it.
