### ISSUE TITLE
Remove jspenguin2017.github.io from Anti-malware List

### ISSUE THREAD

**Issue by yokoffing** [DandelionSprout/adfilt#137]
There was [an issue](https://www.reddit.com/r/oisd_blocklist/comments/itfhom/oisd_domain_blocklist/g9oe13w) with an outdated entry for your Anti-Malware list on my favorite curated domain blocklist, [OISD](https://oisd.nl/). I see it is still listed, so I wanted to make you aware.

![osid fix](https://user-images.githubusercontent.com/11689349/99988372-8cb99080-2d7f-11eb-96fb-fa857538dc6b.jpg)

**Comment by DandelionSprout** [comment]
If I remember somewhat correctly, I added `jspenguin2017.github.io` during a very chaotic time in the whole Nano transfer scandal. Its "uBlock Protector" was still a prominent guide on how to install Nano Defender, at a time where it had been revealed some days previously to have become Instagram-snooping malware.

Moreover, at the time, there was confusion on whether he had sold his entire GitHub account to the scammers and not just the Nano repos; had the former been the case, `jspenguin2017.github.io` would have been in the hands of malware pushers who could've done all sorts of bad things with that domain.

If the situation on one or both counts has changed in the past month, I'd be likely to remove that entry after all.

**Comment by DandelionSprout** [comment]
Okay, so it turns out that `jspenguin2017.github.io` is listed as an inactive domain by PyFunceble now, so that entry will be removed from my lists within an hour from now anyway.
