### ISSUE TITLE
PornHub" 

### ISSUE THREAD

**Issue by yokoffing** [DandelionSprout/adfilt#150]
## Describe the problem below this line as meticulously and detailed as possible:
Pornhub is now showing "paid videos" selections to the right of the video player. Consider adding some cosmetic filters to remove these.

## Add screenshots below if needed:
https://postimg.cc/F1M5Mh69
## Which adblocker(s) and version did you use when testing this?

- [X ] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Pornhub: Pure Trail Mix Experience

**Comment by DandelionSprout** [comment]
I struggle to reproduce it in a hurry. If it's limited to certain pages on your end, I'd need an example URL; if not, then I'll keep an eye on the site a couple times a week and see if it eventually shows up for me too.

**Comment by DandelionSprout** [comment]
Things seem to have taken some problematic turns today:

1) I've concluded that the "Paid Videos" box seems to be region-specific, possibly to the US.
2) https://github.com/DandelionSprout/adfilt/commit/fc48c0faf07b16daaa04d9014b91a6db4b13aa35

As a result of №2 in particular, I'm going to close this issue report for the time being, sadly.

**Comment by chirag127** [comment]
@DandelionSprout  please takedown PornHub: Pure Trail Mix Experience

 list from the filterlists.com if it is no longer avaliable.

**Comment by DandelionSprout** [comment]
FilterLists.com has been a total mess for the past half-year that take painful amounts of time to correct the data of, so it's simply not worth spending 40min just to remove merely 1~3 lists there.
