### ISSUE TITLE
proshop.dk

### ISSUE THREAD

**Issue by Hvalfisk** [DandelionSprout/adfilt#161]
## Hvilke(n) regel/regler sender du ind?
```
www.proshop.dk###raptor-GetCookieRecommendations
www.proshop.dk##.site-campaigns-area
www.proshop.dk##.hidden-xs.row
www.proshop.dk##.hidden-sm.hidden-xs
www.proshop.dk##.pull-right.col-sm-9 > .site-row-margin-top-small
www.proshop.dk##.site-background-banner a.site-background-cta
www.proshop.dk##body:style(background-image:none!important)
```

## Hvilke ting blokerer, skjuler, eller fikser de(n)?
Campaigns, ads, recommendations
![2021-02-19 11_35_52-Settings](https://user-images.githubusercontent.com/4579377/108494176-874ce300-72a7-11eb-9433-a40fddb5932e.png)
![2021-02-19 11_36_44-Settings](https://user-images.githubusercontent.com/4579377/108494203-8caa2d80-72a7-11eb-9e36-96a0d3da3218.png)
![2021-02-19 11_37_10-Settings](https://user-images.githubusercontent.com/4579377/108494192-8a47d380-72a7-11eb-9ff5-d1d18de33f6b.png)
![2021-02-19 11_38_01-Settings](https://user-images.githubusercontent.com/4579377/108494183-8916a680-72a7-11eb-9929-33aa0bd89794.png)
![2021-02-19 11_37_36-Settings](https://user-images.githubusercontent.com/4579377/108494187-89af3d00-72a7-11eb-8edc-cf7c4b0df28e.png)

## Hvilken reklameblokkerer og version brugte du da du skrev og testet reglen(e)?
- [X] uBlock Origin 1.33.2
- [ ] AdGuard (Betalt skrivebordsversion)
- [ ] AdGuard (Webbrowser-udvidelse)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (Udvidelsen)

Andre:

Reklameblokerer-version(er):

## Hvilke filterlister brugte du? At ikke fortælle dette, vil føre til at sagen bliver midlertidigt lukket frem til dette bliver fortalt.

![2021-02-19 11_40_53-uBlock₀ — Dashboard — Mozilla Firefox](https://user-images.githubusercontent.com/4579377/108494182-887e1000-72a7-11eb-812f-a014cc0ed2d8.png)

## (Valgfrit) Hvilke(n) webbrowser(e) og version(er) brugte du?
Firefox 86.0

**Comment by DandelionSprout** [comment]
Beklageligvis, bliver de bannere ikke anset som annoncer af reklameblokkeringsteamene, eftersom de leder til produkter der bliver solgt hos den samme webshop. Jeg personlig tror dette er noget, der ville ha passet bedre hos [AdGuard Annoyances filter](https://reports.adguard.com/da/new_issue.html) (Vælg "Andre" som produkttypen hos de).
