### ISSUE TITLE
Small typo in the anti malware filter

### ISSUE THREAD

**Issue by DevShubam** [DandelionSprout/adfilt#166]
Hi!

https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt

In the filter above, it shows that the version is "11April2021v1-Beta"

It should be 11March2021v1-Beta

**Comment by DandelionSprout** [comment]
Ah, thanks for the heads-up. I must've been sleepy when I wrote "April".

**Comment by DevShubam** [comment]
No worries!
