### ISSUE TITLE
W10Privacy doesn't load.

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [DandelionSprout/adfilt#168]
## Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any):

[The W10Privacy site](https://www.w10privacy.de/) will not load with ⚙️ Dandelion Sprout's Annoyances List.

## Add screenshots below if needed:

![White Screen with the W10Privacy tab open.](https://i.postimg.cc/cH3PyD2N/problem.png)

https://postimg.cc/TLRtncTk

## Add a screenshot of the extension's logger:

![##[class*=ShareButton i]:not(button) and .adsbygoogle filters blocking the site.](https://i.postimg.cc/c1Mf9RCg/log.png)

https://postimg.cc/Cd5ZdfjS

The second blocked element is the result of EasyList and the last 3 from my custom rules, but they do not affect the issue in any way.

## Which adblocker(s) and version did you use when testing this?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):

uBlock Origin v1.34.1b1

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

⚙️ Dandelion Sprout's Annoyances List 

## Which browser(s) and version did you use?

Firefox Nightly 88.0a1

## (Optional) Which OS and version did you use?
- [X] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux
- [ ] Android

Other(s):

OS version:

Windows 10 Version 20H2 Build 19042.867

**Comment by DandelionSprout** [comment]
Thanks for the heads-up. Turns out the site's `body` element had an astonishing 43 classes, so I'd have been more surprised if it had loaded correctly. A fix has now been added and should go live within a few minutes at most. 
![image](https://user-images.githubusercontent.com/22780683/111053767-ec3ec780-8466-11eb-85ac-8b6417c85d57.png)
