### ISSUE TITLE
question removed (adfilt/RedditTrashRemovalService.txt)

### ISSUE THREAD

**Issue by whyiswhen** [DandelionSprout/adfilt#170]
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RedditTrashRemovalService.txt

## Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any): 
https://www.reddit.com/r/youtube/comments/957o6k/how_do_i_disable_recommended_for_you_videos/
https://www.reddit.com/r/youtube/comments/9fla83/extension_to_remove_recommended_for_you/
as seen in these screenshot the question get removed. I HAVE CHECKED BY ENABLING AND DISABLING 🎛 Reddit Trash Removal Service list and i'm pretty much sure that the question get removed because of this list.
![image](https://user-images.githubusercontent.com/76880977/113439140-91feaa00-9407-11eb-90a4-22dffdda2e13.png)
![image_34](https://user-images.githubusercontent.com/76880977/113439147-95923100-9407-11eb-8708-5514da5eca4c.png)

## Add screenshots below if needed: here is intended behavior
![image](https://user-images.githubusercontent.com/76880977/113439222-c6726600-9407-11eb-81b4-8132d77587bc.png)
![image_35](https://user-images.githubusercontent.com/76880977/113439231-c96d5680-9407-11eb-902a-fbe6e4854ace.png)

## Add a screenshot of the extension's logger:

![image](https://user-images.githubusercontent.com/76880977/113439196-b22e6900-9407-11eb-9bca-4fcc03518108.png)

## Which adblocker(s) and version did you use when testing this?

- [ ] uBlock Origin this one
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):
![image](https://user-images.githubusercontent.com/76880977/113439520-5d3f2280-9408-11eb-813d-d4ad3a509638.png)

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![image](https://user-images.githubusercontent.com/76880977/113439385-181af080-9408-11eb-9f76-3135c29bd06e.png)
![image_36](https://user-images.githubusercontent.com/76880977/113439392-1bae7780-9408-11eb-801c-50ec24891c0c.png)

## Which browser(s) and version did you use?

![image](https://user-images.githubusercontent.com/76880977/113439551-6d570200-9408-11eb-8b7e-e728b7136e5e.png)

## (Optional) Which OS and version did you use?
- [ ] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux
- [ ] Android

Other(s):

OS version:

**Comment by DandelionSprout** [comment]
I can confirm that this is a known problem, due to the pretty high difficulty involved in fixing it, and because I mostly stopped visiting Reddit a year ago.

Nevertheless, I'll now try to see if a decent fix can be created.

**Comment by whyiswhen** [comment]
> I can confirm that this is a known problem, due to the pretty high difficulty involved in fixing it, and because I mostly stopped visiting Reddit a year ago.
> 
> Nevertheless, I'll now try to see if a decent fix can be created.

@DandelionSprout should i unsubscribe from the list ?

**Comment by DandelionSprout** [comment]
Not yet. Give me an hour to come up with something.

**Comment by DandelionSprout** [comment]
It has now been fixed as of list version 02April2021v1-Beta. Thanks for the tip.

**Comment by whyiswhen** [comment]
Thank you
