### ISSUE TITLE
remove explore in guide menu ikn youtube (▶️ YouTube: Even More Pure Video Experience)

### ISSUE THREAD

**Issue by chirag127** [DandelionSprout/adfilt#172]
https://github.com/DandelionSprout/adfilt/blob/7ed89c028e5735ea149aa7bce4fa21ad838eaeeb/YouTubeEvenMorePureVideoExperience.txt#L14 has become obselete as trending seection is chaged to explore .

![image_89](https://user-images.githubusercontent.com/76880977/113508925-58957e00-9570-11eb-87eb-cf83258cbd1f.png)

**Comment by DandelionSprout** [comment]
Thanks for the headsup. Note that the mobile browser version of YouTube still uses "Trending"; although I've fixed it for desktop browsers now.

**Comment by chirag127** [comment]
please add rules to Removes the Explore button in the left-hand menu.

**Comment by DandelionSprout** [comment]
Oh, right. I am absolutely exhausted and have been for the past 4 weeks.

**Comment by DandelionSprout** [comment]
https://github.com/DandelionSprout/adfilt/commit/554f77b29ead6b476395dcd9f1d4af6732c64ce4
