### ISSUE TITLE
"Browse websites without logging in" breaks "Subscribe" button on samharris.org

### ISSUE THREAD

**Issue by mimmiechan** [DandelionSprout/adfilt#173]
## Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any):
Clicking any of the "Subscribe Now" buttons on `https://samharris.org/subscribe/` (only appears if you are not logged in to an account that is already subscribed) should open a frame to create an account or to pay for a subscription. Instead, nothing happens. This is due to the filter:
`||tinypass.com^$third-party`
Adding an exception like so:
`@@||tinypass.com^$domain=samharris.org`
fixed the issue for me.

Related: #131

## Which adblocker(s) and version did you use when testing this?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):
1.3.4.0

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

I've already narrowed it down to "Browse websites without logging in", plz.

## Which browser(s) and version did you use?

Firefox Browser 87.0

## (Optional) Which OS and version did you use?
- [X] Windows 10 Home
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux
- [ ] Android

Other(s):

OS version:
20H2

**Comment by DandelionSprout** [comment]
Thanks for the headsup. It has now been fixed.
