### ISSUE TITLE
Legitimate URL Shortener breaks Facebook media uploading

### ISSUE THREAD

**Issue by wefalltomorrow** [DandelionSprout/adfilt#175]
## Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any):

Attempting to upload an image on Facebook (either as a post or in comments) results in an error, same as when inserting an emoji using the emoji picker. It asks you to refresh the page, as you can see in the screenshots below, but that doesn't fix it. Disabling the filter list fixes it.

## Add screenshots below if needed:

![image](https://user-images.githubusercontent.com/45746576/114117073-44170400-9929-11eb-84d0-1ed303ff258c.png)

![image](https://user-images.githubusercontent.com/45746576/114117187-77599300-9929-11eb-8580-e63e863139aa.png)

## Which adblocker(s) and version did you use when testing this?

- [X] uBlock Origin

Other(s):

Adblocker version(s): uBlock Origin v1.34.0

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Legitimate URL Shortener 

## Which browser(s) and version did you use?

Firefox 87.0

## (Optional) Which OS and version did you use?
- [X] Windows 10

Other(s):

OS version: x64 LTSC

**Comment by DandelionSprout** [comment]
Since I don't have a Facebook account to test image uploads or emoji reactions with, I'll tag this issue report as wishing for help from someone in the community who does have one.

**Comment by llacb47** [comment]
In all cases this is the filter at fault:
`*$queryprune=/^fb_dtsg/`

That is a legitimate parameter apparently needed by facebook's legacy API endpoints (the ones not using graphql).

**Comment by wefalltomorrow** [comment]
Thanks heaps, c997f21 fixed it! Much appreciated for the quick help and responses from both of you.

**Comment by Hackerpcs** [comment]
It breaks media uploading again

![Untitled](https://user-images.githubusercontent.com/17467335/183340926-9748e2f9-1154-4c85-b882-257d31fd2e66.png)

![p2](https://user-images.githubusercontent.com/17467335/183341413-9d8616f6-2d6d-40b4-ba6c-899e5a6fd604.png)

**Comment by wefalltomorrow** [comment]
> It breaks media uploading again
> 
> ![Untitled](https://user-images.githubusercontent.com/17467335/183340926-9748e2f9-1154-4c85-b882-257d31fd2e66.png)
> 
> ![p2](https://user-images.githubusercontent.com/17467335/183341413-9d8616f6-2d6d-40b4-ba6c-899e5a6fd604.png)

Yup, can confirm. Been happening to me for a few days now, just forgot to report it.

**Comment by DandelionSprout** [comment]
Thanks for the headsup. Since the cause of the problem `$removeparam=source,domain=facebook(...)` was added fairly recently (20 days ago), I have now removed that entry from the list.
