### ISSUE TITLE
https://twitter.com/home(pm 🐥 Twitter: Pure Reading Experience)

### ISSUE THREAD

**Issue by chirag127** [DandelionSprout/adfilt#176]
## Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any):
page not load at https://twitter.com/ 
but i have noticed that the page load as soon as i scroll down
## Add screenshots below if needed:
![image](https://user-images.githubusercontent.com/76880977/114848896-d40eef00-9dfc-11eb-8d36-8bb09886e34f.png)
![image](https://user-images.githubusercontent.com/76880977/114849898-db82c800-9dfd-11eb-9296-90dd3ce60d44.png)
![image](https://user-images.githubusercontent.com/76880977/114849944-e9d0e400-9dfd-11eb-9422-5505d194aed5.png)

## Which adblocker(s) and version did you use when testing this?

![image](https://user-images.githubusercontent.com/76880977/114849362-497abf80-9dfd-11eb-8f0a-3a378019bf6c.png)
+ 
![image](https://user-images.githubusercontent.com/76880977/114849529-77600400-9dfd-11eb-9099-6235a70e23e8.png)
+
![image](https://user-images.githubusercontent.com/76880977/114849764-b2face00-9dfd-11eb-96c0-9a7473a8bf57.png)

**Comment by DandelionSprout** [comment]
If I understand your explanation correctly:

My list does (intend to) remove many things near the top of Twitter feeds, such as "Trending", "Who to follow", and similar things. On various websites (Not just Twitter), stuff like this can cause the vertical content to be so low that it's sometimes hard to trigger the load/show of it; especially on tall monitors.

I know from my experiences with a 1440x2560 monitor in portrait mode on e.g. Tumblr, that there are no known fixes to make pages autoload if the bottom of the window doesn't hit the load trigger. Your case on Twitter can be solved by scrolling; on Tumblr I actually have to reduce the window size to trigger the loading.

**Comment by krystian3w** [comment]
But reporter have only Full HD screen.

AdGuard support inline media queries.

**Comment by chirag127** [comment]
> But reporter has only Full HD screen.

how did you know that?



> AdGuard support inline media queries.

can you please explain it ?

**Comment by krystian3w** [comment]
> can you please explain it ?

2 examples by AdamWr added in 2019 and 2020:

https://github.com/AdguardTeam/AdguardFilters/commit/9fed3dcbf5d1b961a9b178dc4504a4a79c9b5db3#diff-d20ec77c0772e67892d7366da61b9474368b0700ae60aac3e4d323af1b195d41R1450
https://github.com/AdguardTeam/AdguardFilters/commit/17f342fa0a0eb8fd7066a00b44ba443423816f9d#diff-d20ec77c0772e67892d7366da61b9474368b0700ae60aac3e4d323af1b195d41R2859

tutorial: https://developer.mozilla.org/pl/docs/Web/CSS/Media_Queries/Using_media_queries

---

> how did you know that?

Form origin size of screenshot, you forget minimize size to "last" good readable (e.g. 816 x 367 pixels). Or 1920 is false and you have `1920 * x%` (bigger resolution compatible with `16:9` or  `19:12` like `1900x1200`).

**Comment by chirag127** [comment]
> you forgotten ![Imgur](https://camo.githubusercontent.com/7d9fde261f1b52ffd82d4cd4872feae5a03692b5909ed0919dc2bd5d1ece0afe/68747470733a2f2f692e696d6775722e636f6d2f685073736762332e706e67) ![Imgur](https://camo.githubusercontent.com/d9807c66d891eab76193f25c8178e17974f215eace3ce01249676b7d8ff86f6c/68747470733a2f2f692e696d6775722e636f6d2f4132616b4d76782e706e67) ![Imgur](https://camo.githubusercontent.com/162fb2c5943a58c1358d51e126defd44909695f35ffec69fa4cb0e1d882e8f78/68747470733a2f2f692e696d6775722e636f6d2f6e66457731684f2e706e67) ![Imgur](https://camo.githubusercontent.com/043047a9cea814316bd16197e3acb5facdba72a2a2d6f7a1f70f421aaabf8646/68747470733a2f2f692e696d6775722e636f6d2f377870416b45342e706e67) minimize size

should I always minimize it?

**Comment by krystian3w** [comment]
As you assume that your monitor resolution betrays your privacy, the screenshots you upload should have an unusual width and height (so that it's harder to match the most popular ones).

And sorry for spoiler from <a id="tboi" href="#user-content-tboi" title="the binding of isaac">TBOI</a> game.

**Comment by DandelionSprout** [comment]
If there had been a general total failure to load the Twitter logged-on userfeed, I can only presume that people would've told me about it after Dandelion Sprout's Annoyances List became an included opt-in list in most AdGuard products.

As I/we have yet to hear of such stories, and with my vacation coming up in 1½ days, I'll declare this a cold case for now.

**Comment by chirag127** [comment]
> List became an included opt-in list in most AdGuard products

Hmm.... I have not seen your lists on Adguard repository reports on GitHub BTW.

**Comment by krystian3w** [comment]
AG have limited numbers for lists, see troubles with number for AdGuard China Filter:

https://github.com/AdguardTeam/FiltersRegistry/pull/333#pullrequestreview-408103153

**Comment by DandelionSprout** [comment]
* https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_250_DandelionSproutAnnoyances
* AdGuard for Windows: ![image](https://user-images.githubusercontent.com/22780683/128644486-1f6dabba-6082-4887-bea9-5510c8899b61.png)

I am not sure why it's not showing up in the AdGuard browser extensions, however.

**Comment by krystian3w** [comment]
I suppose we will see AdGuard Addon 4.0 instead version 3.7 / 3.8 / 3.9.
