### ISSUE TITLE
https://timesofindia.indiatimes.com/

### ISSUE THREAD

**Issue by chirag127** [DandelionSprout/adfilt#177]
## Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any):
unblocked astrology button  at https://timesofindia.indiatimes.com/videos/in-depth/haemophilia-explained-rare-but-life-threatening-disorder/videoshow/82087861.cms inspite of anti astrology list.
## Add screenshots below if needed:
![image](https://user-images.githubusercontent.com/76880977/115141859-30237e80-a05c-11eb-829b-9fc79161cf88.png)
![image](https://user-images.githubusercontent.com/76880977/115141862-3285d880-a05c-11eb-9f1d-27f71ad7427d.png)

![image](https://user-images.githubusercontent.com/76880977/115141869-3f0a3100-a05c-11eb-880f-bc4b2caed83e.png)
![image](https://user-images.githubusercontent.com/76880977/115141870-40d3f480-a05c-11eb-90b3-bd6eec1c3bb4.png)

**Comment by chirag127** [comment]
@DandelionSprout I can still reproduce it .

**Comment by DandelionSprout** [comment]
Which version number of that list are you currently using?

**Comment by chirag127** [comment]
![image](https://user-images.githubusercontent.com/76880977/116345736-5e485180-a806-11eb-91ac-c763de899d2e.png)
yes , i'm using old version . do you know how to force update it.

i don't know ,why it is not updating.

**Comment by DandelionSprout** [comment]
The 🔁 button in the upper right of the "Filters" page is the intended way to force list updates: 
![image](https://user-images.githubusercontent.com/22780683/116346050-b6248f80-a7e9-11eb-93d2-5a7d7b018af7.png)

**Comment by chirag127** [comment]
That button doesn't seems to work for your list,so i deleted the list and then reinstalled it.
