### ISSUE TITLE
AGH Disallowed IPs Overblocking

### ISSUE THREAD

**Issue by HorayNarea** [DandelionSprout/adfilt#182]
in the latest change to the Disallowed IPs list you added:
https://github.com/DandelionSprout/adfilt/blob/646918a00663762341bed7827d8de7b9a49629c5/AdGuardHomeDisallowedIPs.txt#L9671-L9672

This IP range is only used by the ISP 1&1 for their DSL customers, anyone who is a customer or serves the customers of 1&1 can not use this list now :(

What was the reasoning behind adding that range? Are you sure you need to block the whole thing?

I think it is in general a bad idea to block normal customer IP ranges even if a few IPs from that network are doing abusive stuff, maybe reporting them to the ISP would be a better way of handling this?

Edit:
German ISPs are usally very responsive and quick when you report abuse from their networks, in the whois record of this IP range 1&1 even writes:

> Please contact abuse@versatel.de in case of abuse

**Comment by DandelionSprout** [comment]
I've grown rather paranoid about `version.bind` port scanners in the past 2 months: 
![image](https://user-images.githubusercontent.com/22780683/117553028-5337c180-b04f-11eb-851c-8fca00e9468a.png)

Where I did step wrong, however, was that I glanced at `https://www.1und1.net/` in a hurry back then and somehow mistook it for a dataserver hosting service. I'll attempt to correct it now.

**Comment by DandelionSprout** [comment]
I generally have high confidence in ones like Arbor Observatory, Hurricane Electric, Censys, and indeed Shodan.

However, when e.g. 40 Romanian IPs from 25 ISPs all perform exactly 6 queries each for `version.bind` within 48 hours (Which happened to me for most of April), general logic indicates that they're planning something sinister.

**Comment by DandelionSprout** [comment]
And to my disappointment, "Disallowed clients" does not actually prevent the IPs from appearing in the AdGuard Home frontpage statistics.

**Comment by HorayNarea** [comment]
It shows up in statistics & logs but otherwise the query is completely ignored, the clients never get an answer …we should probably send a feature request to AGH to handle them exactly like queries from disallowed clients :D

**Comment by DandelionSprout** [comment]
That was actually a really good idea. I'm unsure if I have time to submit a request tonight; I'll have better time tomorrow.

**Comment by HorayNarea** [comment]
I'm currently on it! :)

**Comment by HorayNarea** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/3115
