### ISSUE TITLE
Browse Websites Without Logging In no longer works with Instagram?

### ISSUE THREAD

**Issue by levicki** [DandelionSprout/adfilt#183]
I have noticed that your list [Browse Websites Without Logging In](https://github.com/DandelionSprout/adfilt/blob/master/BrowseWebsitesWithoutLoggingIn.txt) which I am using for quite a while (btw, thanks for creating and sharing it!) no longer seems to work for Instagram -- I am being redirected to the login page `https://www.instagram.com/accounts/login/` (although at this point I am not sure if it is for all Instagram pages or just for some).

If it is of any importance, I am using Microsoft Edge 90.0.818.56 (official stable build) on Windows 10 64-bit with uBlock Origin v1.35.2 installed from Chrome Web Store.

**Comment by DandelionSprout** [comment]
Are there any example pages where you're getting auto-redirected to `https://www.instagram.com/accounts/login/`?

As I haven't noticed any major redirection issues myself, it's possible that I could borrow entries from *uBlock Filters - Annoyances* into my list.

**Comment by levicki** [comment]
I do have a [possibly NSFW example](https://www.instagram.com/zaayquality/), maybe the redirection is for accounts flagged as NSFW?

**Comment by DandelionSprout** [comment]
Oh, okay. Now I can reproduce the problem, testing with that page in Vivaldi.

It seems the page has much the same problem as what all of `Pinterest` had until recently: That links to images can only be opened by right-clicking and choosing "Open in new tab".

**Comment by levicki** [comment]
As I said, I cannot even get to the images, I get instantly redirected to login page.

i am not quite sure I understand what behavior are you observing?

**Comment by DandelionSprout** [comment]
When going to `https://www.instagram.com/zaayquality/`, and clicking on the upper left image (The one with the Mercedes): 
![image](https://user-images.githubusercontent.com/22780683/118418226-d7c1ba00-b6b7-11eb-8f4f-7967f728380c.png)

When clicking on the image normally, a login prompt overlay (Not a full redirection) is loaded, but is accidentally blanked out by the list.

• The overlay rendered normally: 
![image](https://user-images.githubusercontent.com/22780683/118418146-80234e80-b6b7-11eb-9ac5-c40072945e4a.png)

When I right-click on the image to open in new tab: `https://www.instagram.com/p/COT1196J1Zz/` 
![image](https://user-images.githubusercontent.com/22780683/118418189-a8ab4880-b6b7-11eb-9a1a-fce62a1d3577.png)

**Comment by levicki** [comment]
Sorry for the late reply, I did some more testing and research in the meantime.

On my desktop PC and on my iPhone when both are connected via my home network (cable ISP) or on my laptop at work (fiber ISP), I am getting redirected to the login page immediately.

On the other hand, if I use cellular data (i.e. 4G/LTE) on my iPhone instead of Wi-Fi via my home ISP I am not getting redirected anymore and I can see the page.

I have found this [Reddit thread](https://www.reddit.com/r/uBlockOrigin/comments/jz5o3f/instagram_links_redirect_to_login_page_anyway_to/) in uBlockOrigin community that mentions the same issue with people chiming in over the past few months and saying the same started happening to them as well.

There is also another [Reddit thread](https://www.reddit.com/r/Instagram/comments/ksfilu/instagram_forcing_me_to_log_in_to_do_anything_at/) which is more recent in Instagram community about it as well.

It seems Instagram is rolling out this change, and there won't be a way around it. Given that this does not seem to be something that anyone can fix on the application layer, you can treat this issue as informative and we can close it.

**Comment by DandelionSprout** [comment]
I guess that explains it. I have no idea why on earth Instagram would try to lock posts in that way, but at least that means we can close the issue report now.
