### ISSUE TITLE
Video Ads on VG

### ISSUE THREAD

**Issue by fosam** [DandelionSprout/adfilt#186]
## Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any):
Hello Imre!

Just last week ads are displayed just after you click play on a video in a VG article, does not happen on VGTV.

I really wanted to inspect the ads using the logger but unfortunately i don't know where/how to do it, i wish i knew.

Here is the [link](https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten) to the video in the article where i got the ads.

Keep in mind that the video ads are displayed only on videos found in articles, on VGTV for example the issue does not exist.

## Add screenshots below if needed:
![Capture 19_05_2021_23_02_40](https://user-images.githubusercontent.com/52612348/118884716-201aeb00-b8f7-11eb-8362-f8e433749fed.png)
## Add a screenshot of the extension's logger:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +27 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vg` |
| +22 | \|\|scorecardresearch.com^$3p | -- | `www.vg.no` | 3 | image | `https://sb.scorecardresearch.com/p?c1=2&c2=15236236&ns_type=hidden&ns_st_sv=6.3.0.180917&ns_st_pv=1.2.6.200828&ns_st_smv=5.10&ns_st_it=c&ns_st_id=1621458547536&ns_st_ec=4&ns_st_sp=1&ns_st_sc=0&ns_st_psq=2&ns_st_asq=2&ns_st_sq=2&ns_st_ppc=1&ns_st_apc=1&ns_st_spc=1&ns_st_cn=1&ns_st_ev=pause&ns_st_po=6610&ns_st_cl=76926&ns_st_mp=jwplayer&ns_st_mv=8.19.1&ns_st_pn=1&ns_st_tp=0&ns_st_ci=0&ns_st_pt=5251&ns_st_dpt=5220&ns_st_ipt=5220&ns_st_ap=5605&ns_st_dap=4920&ns_st_et=18568&ns_st_det=5220&ns_st_upc=5605&ns_st_dupc=4920&ns_st_iupc=4920&ns_st_upa=5605&ns_st_dupa=4920&ns_st_iupa=4920&ns_st_lpc=4920&ns_st_dlpc=4235&ns_st_lpa=4920&ns_st_dlpa=4235&ns_st_pa=5251&ns_st_ldw=0&ns_st_ldo=0&ns_ts=1621458567863&ns_st_bc=0&ns_st_dbc=0&ns_st_bt=28&ns_st_dbt=0&ns_st_bp=28&ns_st_skc=0&ns_st_dskc=0&ns_st_ska=0&ns_st_dska=0&ns_st_skd=0&ns_st_skt=0&ns_st_dskt=0&ns_st_pc=2&ns_st_dpc=1&ns_st_pp=2&ns_st_br=0&ns_st_rt=100&ns_st_ub=0&ns_st_ki=1200000&ns_st_pr=*null&ns_st_sn=*null&ns_st_en=*null&ns_st_ep=*null&ns_st_ct=*null&ns_st_st=*null&ns_st_pu=*null&c3=*null&c4=*null&c6=*null&c7=https%3A%2F%2Fwww.vg.no%2Fnyheter%2Futenriks%2Fi%2Fwea8v4%2Fvg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten&c8=VG%20p%C3%A5%20grensen%20til%20Israel%3A%20Frykter%20regional%20krise%20i%20Midt%C3%B8sten%20%E2%80%93%20VG&c9=` |
| +22 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vgtv` |
| +22 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vg` |
| +21 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vgtv` |
| +20 | \|\|click.vgnett.no^ | -- | `www.vg.no` | 3 | image | `https://click.vgnett.no/svp.gif?s=vgtv&d=desktop&v=218461&p=5&cb=3389.9380594606223` |
| +20 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vgtv` |
| +19 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vgtv` |
| +18 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vgtv` |
| +17 | /?sentry_key= | -- | `www.vg.no` | 3 | xhr | `https://sentry.app.osl.pubops.net/api/14/store/?sentry_key=41aef1bc64c847a9a3c1856612e9a727&sentry_version=7` |
| +17 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vgtv` |
| +17 | \|\|scorecardresearch.com^$3p | -- | `www.vg.no` | 3 | image | `https://sb.scorecardresearch.com/p?c1=2&c2=15236236&ns_type=hidden&ns_st_sv=6.3.0.180917&ns_st_pv=1.2.6.200828&ns_st_smv=5.10&ns_st_it=c&ns_st_id=1621458547536&ns_st_ec=3&ns_st_sp=1&ns_st_sc=0&ns_st_psq=2&ns_st_asq=2&ns_st_sq=2&ns_st_ppc=1&ns_st_apc=1&ns_st_spc=1&ns_st_cn=1&ns_st_ev=play&ns_st_po=1690&ns_st_cl=76926&ns_st_mp=jwplayer&ns_st_mv=8.19.1&ns_st_pn=1&ns_st_tp=0&ns_st_ci=0&ns_st_pt=31&ns_st_dpt=0&ns_st_ipt=0&ns_st_ap=685&ns_st_dap=0&ns_st_et=13348&ns_st_det=13317&ns_st_upc=685&ns_st_dupc=0&ns_st_iupc=0&ns_st_upa=685&ns_st_dupa=0&ns_st_iupa=0&ns_st_lpc=685&ns_st_dlpc=0&ns_st_lpa=685&ns_st_dlpa=0&ns_st_pa=31&ns_st_ldw=0&ns_st_ldo=0&ns_ts=1621458562643&ns_st_bc=0&ns_st_dbc=0&ns_st_bt=28&ns_st_dbt=3&ns_st_bp=28&ns_st_skc=0&ns_st_dskc=0&ns_st_ska=0&ns_st_dska=0&ns_st_skd=0&ns_st_skt=0&ns_st_dskt=0&ns_st_pc=1&ns_st_dpc=0&ns_st_pp=1&ns_st_br=0&ns_st_rt=100&ns_st_ub=0&ns_st_ki=1200000&ns_st_pr=*null&ns_st_sn=*null&ns_st_en=*null&ns_st_ep=*null&ns_st_ct=*null&ns_st_st=*null&ns_st_pu=*null&c3=*null&c4=*null&c6=*null&c7=https%3A%2F%2Fwww.vg.no%2Fnyheter%2Futenriks%2Fi%2Fwea8v4%2Fvg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten&c8=VG%20p%C3%A5%20grensen%20til%20Israel%3A%20Frykter%20regional%20krise%20i%20Midt%C3%B8sten%20%E2%80%93%20VG&c9=` |
| +16 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vgtv` |
| +16 | \|\|click.vgnett.no^ | -- | `www.vg.no` | 3 | image | `https://click.vgnett.no/svp.gif?s=vgtv&d=desktop&v=218461&p=-2&cb=9308.132906627116` |
| +16 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vgtv` |
| +7 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vg` |
| +5 | \|\|click.vgnett.no^ | -- | `www.vg.no` | 3 | image | `https://click.vgnett.no/svp.gif?s=vgtv&d=desktop&v=218461&p=-1&cb=2626.2841702971064` |
| +4 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vgtv` |
| +4 | \|\|scorecardresearch.com^$3p | -- | `www.vg.no` | 3 | image | `https://sb.scorecardresearch.com/p?c1=2&c2=15236236&ns_type=hidden&ns_st_sv=6.3.0.180917&ns_st_pv=1.2.6.200828&ns_st_smv=5.10&ns_st_it=c&ns_st_id=1621458547536&ns_st_ec=2&ns_st_sp=1&ns_st_sc=0&ns_st_psq=1&ns_st_asq=1&ns_st_sq=1&ns_st_ppc=1&ns_st_apc=1&ns_st_spc=1&ns_st_cn=1&ns_st_ev=pause&ns_st_po=685&ns_st_cl=76926&ns_st_mp=jwplayer&ns_st_mv=8.19.1&ns_st_pn=1&ns_st_tp=0&ns_st_ci=0&ns_st_pt=31&ns_st_dpt=31&ns_st_ipt=31&ns_st_ap=685&ns_st_dap=685&ns_st_et=31&ns_st_det=31&ns_st_upc=685&ns_st_dupc=685&ns_st_iupc=685&ns_st_upa=685&ns_st_dupa=685&ns_st_iupa=685&ns_st_lpc=685&ns_st_dlpc=685&ns_st_lpa=685&ns_st_dlpa=685&ns_st_pa=31&ns_st_ldw=0&ns_st_ldo=0&ns_ts=1621458549326&ns_st_bc=0&ns_st_dbc=0&ns_st_bt=25&ns_st_dbt=0&ns_st_bp=25&ns_st_skc=0&ns_st_dskc=0&ns_st_ska=0&ns_st_dska=0&ns_st_skd=0&ns_st_skt=0&ns_st_dskt=0&ns_st_pc=1&ns_st_dpc=1&ns_st_pp=1&ns_st_br=0&ns_st_rt=100&ns_st_ub=0&ns_st_ki=1200000&ns_st_pr=*null&ns_st_sn=*null&ns_st_en=*null&ns_st_ep=*null&ns_st_ct=*null&ns_st_st=*null&ns_st_pu=*null&c3=*null&c4=*null&c6=*null&c7=https%3A%2F%2Fwww.vg.no%2Fnyheter%2Futenriks%2Fi%2Fwea8v4%2Fvg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten&c8=VG%20p%C3%A5%20grensen%20til%20Israel%3A%20Frykter%20regional%20krise%20i%20Midt%C3%B8sten%20%E2%80%93%20VG&c9=` |
| +4 | \|\|scorecardresearch.com^$3p | -- | `www.vg.no` | 3 | image | `https://sb.scorecardresearch.com/p?c1=2&c2=15236236&ns_type=hidden&ns_st_sv=6.3.0.180917&ns_st_pv=1.2.6.200828&ns_st_smv=5.10&ns_st_it=c&ns_st_id=1621458547536&ns_st_ec=1&ns_st_sp=1&ns_st_sc=0&ns_st_psq=1&ns_st_asq=1&ns_st_sq=1&ns_st_ppc=1&ns_st_apc=1&ns_st_spc=1&ns_st_cn=1&ns_st_ev=play&ns_st_po=0&ns_st_cl=76926&ns_st_pb=1&ns_st_mp=jwplayer&ns_st_mv=8.19.1&ns_st_pn=1&ns_st_tp=0&ns_st_ci=0&ns_st_pt=0&ns_st_dpt=0&ns_st_ipt=0&ns_st_ap=0&ns_st_dap=0&ns_st_et=0&ns_st_det=0&ns_st_upc=0&ns_st_dupc=0&ns_st_iupc=0&ns_st_upa=0&ns_st_dupa=0&ns_st_iupa=0&ns_st_lpc=0&ns_st_dlpc=0&ns_st_lpa=0&ns_st_dlpa=0&ns_st_pa=0&ns_st_ldw=0&ns_st_ldo=0&ns_ts=1621458549295&ns_st_bc=0&ns_st_dbc=0&ns_st_bt=25&ns_st_dbt=25&ns_st_bp=25&ns_st_lt=1758&ns_st_skc=0&ns_st_dskc=0&ns_st_ska=0&ns_st_dska=0&ns_st_skd=0&ns_st_skt=0&ns_st_dskt=0&ns_st_pc=0&ns_st_dpc=0&ns_st_pp=0&ns_st_br=0&ns_st_rt=100&ns_st_ub=0&ns_st_ki=1200000&ns_st_pr=*null&ns_st_sn=*null&ns_st_en=*null&ns_st_ep=*null&ns_st_ct=*null&ns_st_st=*null&ns_st_pu=*null&c3=*null&c4=*null&c6=*null&c7=https%3A%2F%2Fwww.vg.no%2Fnyheter%2Futenriks%2Fi%2Fwea8v4%2Fvg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten&c8=VG%20p%C3%A5%20grensen%20til%20Israel%3A%20Frykter%20regional%20krise%20i%20Midt%C3%B8sten%20%E2%80%93%20VG&c9=` |
| +3 | \|\|adnxs.com^$3p | -- | `www.vg.no` | 3 | xhr | `https://secure.adnxs.com/getuidj` |
| +3 | \|\|click.vgnett.no^ | -- | `www.vg.no` | 3 | image | `https://click.vgnett.no/svp.gif?s=vgtv&d=desktop&v=218461&p=0&cb=6958.1095064160145` |
| +3 | \|\|click.vgnett.no^ | -- | `www.vg.no` | 3 | image | `https://click.vgnett.no/vgtv.gif?d=desktop&v=218461&cb=3090.9717198009166` |
| +2 | ##+js(no-floc) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +2 | ##+js(addEventListener-defuser, load, concat) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +2 | ##+js(abort-on-property-write, __AB__) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +2 | @@\|\|vg.no^$generichide | ++ | `www.vg.no` | 1 | generichide | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +2 | ##+js(no-floc) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +2 | ##+js(addEventListener-defuser, load, concat) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +2 | ##+js(abort-on-property-write, __AB__) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +2 | @@\|\|vg.no^$generichide | ++ | `www.vg.no` | 1 | generichide | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +2 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vgtv` |
| +2 | @@\|\|scorecardresearch.com/internal-c2/plugins/streamingtag_plugin_jwplayer.js | ++ | `www.vg.no` | 3 | script | `https://sb.scorecardresearch.com/internal-c2/plugins/streamingtag_plugin_jwplayer.js` |
| +2 | \|\|ssl.p.jwpcdn.com^*/jwpsrv.js$script,important,domain=eurosport.*\|gamereactor.*\|vg.no | -- | `www.vg.no` | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.19.1/jwpsrv.js` |
| +2 | \|\|ssl.p.jwpcdn.com^*/vast.js$script,important,domain=eurosport.*\|gamereactor.*\|vg.no | -- | `www.vg.no` | 3 | script | `https://ssl.p.jwpcdn.com/player/plugins/vast/v/8.8.6/vast.js` |
| +2 | @@\|\|scorecardresearch.com/c2/plugins/streamingtag_plugin_jwplayer.js | ++ | `www.vg.no` | 3 | script | `https://sb.scorecardresearch.com/c2/plugins/streamingtag_plugin_jwplayer.js` |
| +2 | @@\|\|youbora.com/*/js/adapters/jwplayer$script | ++ | `www.vg.no` | 3 | script | `https://smartplugin.youbora.com/v6/js/adapters/jwplayer/6.5.0/sp.min.js` |
| +2 | ##.webboard |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +2 | \|\|collector.schibsted.io^ | -- | `www.vg.no` | 3 | ping | `https://collector.schibsted.io/api/v1/track/sdrn:schibsted:client:vg` |
| +1 | \|\|adnxs.com^$3p | -- | `www.vg.no` | 3 | image | `https://secure.adnxs.com/getuid?https://cis.schibsted.com/api/v1/sync?ANID=$UID` |
| +1 | \|\|log.medietall.no^ | -- | `www.vg.no` | 3 | script | `https://log.medietall.no/analytics.js` |
| +1 | ##p[data-test-tag=lead-text] ~ p[class] ~ div[class]:before |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +1 | ##div[id^=adPlacement] |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +1 | ##div[id^="adPlacement_"] |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +1 | ##.bundle li[class^=css-]:has(div[data-ad-subtype]) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +1 | ###main > div:has([data-ad-subtype^=skyscraper]) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +0 | \|\|brandmetrics.com^$3p | -- | `www.vg.no` | 3 | script | `https://cdn.brandmetrics.com/survey/script/958329b0909545fe8f0cdc6dc8ba49d0.js` |
| +0 | \|\|acdn.adnxs.com/ast/ast.js$script,important,domain=vg.no | -- | `www.vg.no` | 3 | script | `https://acdn.adnxs.com/ast/ast.js` |
| +0 | @@\|\|vg.no^$generichide | ++ | `www.vg.no` | 1 | generichide | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +0 | ##+js(no-floc) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +0 | ##+js(addEventListener-defuser, load, concat) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +0 | ##+js(abort-on-property-write, __AB__) |  | `www.vg.no` |  | dom | `https://www.vg.no/nyheter/utenriks/i/wea8v4/vg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten` |
| +0 | \|\|scorecardresearch.com^$3p | -- | `www.vg.no` | 3 | ping | `https://sb.scorecardresearch.com/p?c1=2&c2=15236236&ns_type=hidden&ns_st_sv=6.3.0.180917&ns_st_pv=1.2.6.200828&ns_st_smv=5.10&ns_st_it=c&ns_st_id=1621458248092&ns_st_ec=5&ns_st_sp=1&ns_st_sc=0&ns_st_psq=2&ns_st_asq=2&ns_st_sq=2&ns_st_ppc=1&ns_st_apc=1&ns_st_spc=1&ns_st_cn=1&ns_st_ev=end&ns_st_po=7532&ns_st_cl=76926&ns_st_mp=jwplayer&ns_st_mv=8.19.1&ns_st_pn=1&ns_st_tp=0&ns_st_ci=0&ns_st_pt=6154&ns_st_dpt=0&ns_st_ipt=0&ns_st_ap=6527&ns_st_dap=0&ns_st_et=294753&ns_st_det=275237&ns_st_upc=6527&ns_st_dupc=0&ns_st_iupc=0&ns_st_upa=6527&ns_st_dupa=0&ns_st_iupa=0&ns_st_lpc=5825&ns_st_dlpc=0&ns_st_lpa=5825&ns_st_dlpa=0&ns_st_pa=6154&ns_st_ldw=0&ns_st_ldo=0&ns_ts=1621458545503&ns_st_bc=0&ns_st_dbc=0&ns_st_bt=29&ns_st_dbt=0&ns_st_bp=29&ns_st_skc=0&ns_st_dskc=0&ns_st_ska=0&ns_st_dska=0&ns_st_skd=0&ns_st_skt=0&ns_st_dskt=0&ns_st_pc=2&ns_st_dpc=0&ns_st_pp=2&ns_st_br=5766000&ns_st_rt=100&ns_st_ub=0&ns_st_ki=1200000&ns_st_pr=*null&ns_st_sn=*null&ns_st_en=*null&ns_st_ep=*null&ns_st_ct=*null&ns_st_cs=1920x1080&ns_st_st=*null&ns_st_pu=*null&c3=*null&c4=*null&c6=*null&c7=https%3A%2F%2Fwww.vg.no%2Fnyheter%2Futenriks%2Fi%2Fwea8v4%2Fvg-paa-grensen-til-israel-frykter-regional-krise-i-midtoesten&c8=VG%20p%C3%A5%20grensen%20til%20Israel%3A%20Frykter%20regional%20krise%20i%20Midt%C3%B8sten%20%E2%80%93%20VG&c9=` |
</details>

## Which adblocker(s) and version did you use when testing this?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [X] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s): 1.35.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

```
- uBlock filters 
- uBlock filters – Privacy 
- EasyList 
- AdGuard Tracking Protection
- EasyPrivacy
- 🏔️ Dandelion Sprouts nordiske filtre for ryddigere nettsider (uten sporerhvitelisting)
```

## Which browser(s) and version did you use?

Chrome v90.0
## (Optional) Which OS and version did you use?
- [X] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux
- [ ] Android

Other(s):

OS version: 2004

**Comment by DandelionSprout** [comment]
I can reproduce the problem with ease, but I found myself unable to create a good fix for it. I've now asked experts on `##+js`-type entries if they can help me out with this.

**Comment by fosam** [comment]
Thank you!

Just for info: i have just installed Brave browser and activated every single filter that comes with it and switched the blocking mode in the settings to aggressive, but the issue is still there, I thing VG is willing to reach to extreme lengths to put an anti-adblock on its site. :)

In my opinion VG has some of the most resilient and aggressive ads out there.

**Comment by DandelionSprout** [comment]
Among Norwegian sites, it's `VG` and `Tek` that are in a league of their own when it comes to anti-adblocker techniques, with `ITavisen` on third.

**Comment by fosam** [comment]
That's correct,
`🏔️ Dandelion Sprouts nordiske filtre for ryddigere nettsider` in my experience beats all the ads on those sites you mentioned, except the video ads on VG that appeared since last week.

**Comment by llacb47** [comment]
How about `||cdn.vgc.no/js/libs/homad-config.json$xhr,redirect=noop.js`. Probably doesn't work in firefox.

**Comment by DandelionSprout** [comment]
Works like a charm in Chrome.

In Firefox I get a blacked-out video screen after half a second.

**Comment by mapx-** [comment]
test
`vg.no##+js(no-fetch-if, damoh)`

**Comment by DandelionSprout** [comment]
Seems to work like a charm on both browsers.

**Comment by fosam** [comment]
@DandelionSprout @mapx-

`vg.no##+js(no-fetch-if, damoh)` worked

I'm not good with the logger, but i run it and i filtered the requests by the "not allowed", there was something like `https://ssl.2.damoh.vgtv.no/08335dd2515d1ec2c5e377606c9158f3954e3ee0/` but i could not come closer to anythink like `vg.no##+js(no-fetch-if, damoh)` 

How do you use the logger to find the exact issue?

**Comment by DandelionSprout** [comment]
The logger is unable to provide *any* hints regarding how to write `##+js` entries, sadly; as those are fairly advanced JavaScript files that are (usually) meant to cancel a site's own scripts.

**Comment by fosam** [comment]
OK
