### ISSUE TITLE
Phishing domain report

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#189]
## Which entry/entries are you submitting?

`||lnks.gd^$all`
## Which things do they block, hide, or unbreak?

These are intended to block the phishing attempt seen in this email:
![InkedScreenshot 2021-05-26 215046_LI](https://user-images.githubusercontent.com/84232764/119821346-745a3800-bec0-11eb-83bd-c4f8f180f93f.jpg)
There are recent community report stating this domains is involved in government-targeted-phishing:
https://www.virustotal.com/gui/url/aee7bb5e1d0fb852ffe97f6a2b230cc545d2acf5410aa683e486cf7e20669901/detection
https://safeweb.norton.com/reviews?url=lnks.gd
Also, some of the AVs said _reconsidering_ when I scanned it

Redirect Detective shows 0 redirects, so it is not just a url shortened government link (also if it was a url shortened, it would not be extremely long). 
Test url:
```
hxxps[:]//lnks[.]gd/l/eyJhbGciOiJIUzI1NiJ9.eyJidWxsZXRpbl9saW5rX2lkIjoxMDAsInVyaSI6ImJwMjpjbGljayIsImJ1bGxldGluX2lkIjoiMjAyMTA1MjYuNDExMTIyODEiLCJ1cmwiOiJodHRwczovL2V2ZW50cy5pbi5nb3YvZG5yL2NhbGVuZGFyL2RheS8yMDIxLzYvNT9jYXJkX3NpemU9c21hbGwmZGF5cz0yIn0.T83aQZaaCtpbz76UMp6kmdV8v-dYO75GN63zBfFxi-A/s/493293146/br/106994476275-l
```
## Which of my lists are you submitting it to?
Antimalware
## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s): uBlock Origin development build v1.35.3b6

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![](https://user-images.githubusercontent.com/84232764/119387510-0c74d900-bc97-11eb-8301-b47f7880148b.png)

![](https://user-images.githubusercontent.com/84232764/119387645-37f7c380-bc97-11eb-879f-a6ab45d12e25.png)

![](https://raw.githubusercontent.com/iam-py-test/Assets-001/main/images/Screenshot%202021-05-24%20135147.jpeg)

## (Optional) Which browser(s) and version did you use?

N/A

**Comment by llacb47** [comment]
Not phishing 🙄

**Comment by iam-py-test** [comment]
> Not phishing 🙄

What do you mean?

**Comment by iam-py-test** [comment]
@llacb47 Sorry for wasting your time.

**Comment by iam-py-test** [comment]
Is there a way I can delete this issue?

**Comment by DandelionSprout** [comment]
It seems that only repo owners can delete reports, so I can take care of that real quick.
