### ISSUE TITLE
Browse Facebook Without Logging In

### ISSUE THREAD

**Issue by rgiotxy** [DandelionSprout/adfilt#197]
Hi,
Are there instructions for using it to browse Facebook without logging in? I'm trying it on AdGuard AdBlocker 3.6.6 in Firefox for Android 68.9.0 and I still can't browse without logging in…

**Comment by DandelionSprout** [comment]
Which other filterlists are you using?

**Comment by DandelionSprout** [comment]
I'll close the case due to failure to provide a filterlist screenshot/table, as well as an example page. Replies will remain open.

**Comment by kowith337** [comment]
Sadly, it seems like `Facebook` wants to force throwing sign-in page at any chance that they can do, so we can't getting rid of any kind of redirections that done by network and API level.

**Comment by DandelionSprout** [comment]
My findings over the past few months (Very roughly calculated):

* Account timelines: Requires logging in after circa 6 page reloads. Can be temporarily bypassed by switching to `[original prefix].beta.facebook.com` or to [a different tier from my Facebook GUI guide](https://github.com/DandelionSprout/adfilt/blob/master/Wiki/Facebook%20domain%20functionality%20tiers.md).
* A few accounts' posts: Always requires login.
* Tor domains: Always requires login.
* Image galleries: Does *not* require login.

**Comment by rgiotxy** [comment]
Sorry, I'm new to GitHub and haven't figured out how to be notified that someone responded to my questions (there's a bell icon, but it never displays new responses to my threads). My filterlists are:

AdBlock Warning Removal List
AdGuard Base filter
AdGuard Mobile Ads filter
AdGuard Russian filter
AdGuard Spanish/Portuguese filter
AdGuard Tracking Protection filter
AdGuard URL Tracking filter
Anti-AdBlock Killer list (and userscript)
BarbBlock
Browse websites without logging in
CPBL filters for ABP/uBO
Distractions and clickbait filter
NoCoin Filter Must
Online Malicious URL Blocklist
Peter Lowe's Blocklist
PUP Domains Blocklist (AdGuard)
Spam404
Staying On The Phone Browser
Wikia: Pure Browsing Experience

**Comment by krystian3w** [comment]
here enable notifications on page and disable e-mail notify (imo useless):

https://github.com/settings/notifications

**Comment by rgiotxy** [comment]
https://www.facebook.com/kimcartoonfp/

![Screenshot_20210725-132553_Firefox](https://user-images.githubusercontent.com/85282872/126906293-a62723bd-3f29-4405-a293-21cb289118e2.jpg)

Will these suffice?

PS: thanks for the tip!!! just implemented it today!
PPS: step by step? well, basically, I subscribed to the list via filterlists.com (a website I believe you yourself are one of the administrators of), then tried accessing this webpage via Firefox for Android 68.9.0 with AdGuard AdBlocker 3.6.6 running the lists aforementioned and Tempermonkey 4.13.6136 running the aforementioned userscripts, and the result is what is depicted in this screenshot (taken today, minutes ago)… is this it?

**Comment by krystian3w** [comment]
I mean what action is needed on facebook domain to reproduce pop-ups. I suppose enough is a little swipe or waiting without any touching screen.

E.g.:

If you watch saved livestream on Facebook to reproduce login wall needed is click somewhere to show video/player in lagger view space (e.g. with public commets in right column) and these pop-ups for video may need scriptlet or better for start something wrote in `*.user.js` for Tampermonkey (Custom scripting gives you freedom as far as how much you know JavaScript and possible Facebook api - then you can evaluate if it can be simplified to ramp up some JavaScript actions using the scriptlets built into uBO and AdGuard; if you can't see the simplification, it's more like you're left analyzing at what stage the film doesn't get interrupted).

**Comment by rgiotxy** [comment]
@krystian3w could you please restate that assuming I have zero knowledge of JavaScript and just use Tempermonkey to apply pre-made userscripts instead of making my own? I'm only basic-level on AdGuard, and I'm assuming Tempermonkey is much more complex… Also, the way you say it makes it seem like I _want_ to see a popup, I don't, I just want to read the comments, not watch video (I mean, it would be nice if I could, but I'd be content with just reading the textual content, which is impossible because a popup pops up in front of the content and won't let go until I log in, which I can't because I don't have an account).

PS: sorry if this sound rude, it wasn't my intention, I get nervous when I'm talking about subjects I know next to nothing of, and I'm not good with words when I'm nervous

**Comment by krystian3w** [comment]
Try put this into "user rules" in AdGuard addon settings:

`facebook.*,fb.*#?#div#scrollview ~ div div[role="dialog"] form#login_popup_cta_form:upward(div#scrollview ~ div)`

If does not work I should better symulate use Firefox 68.

**Comment by rgiotxy** [comment]
I'm not an expert on Facebook, but I fear the new user rule might have made it worse

**Comment by krystian3w** [comment]
Maybe Possible is write pure JavaScript filter ("AG Rule") to fastly click in right "❌". 

Path to button on my PC is:

> `body > div > div:has(form#login_popup_cta_form) > div > div > div > div > div > div > div > div > div > div > div > div > div[role="button"][class*=" tdjehn4e "]`

if `[class*=" tdjehn4e "]` is really bad, maybe possible add mini-database with "Close" word in all FB supported languages or risk with deletion class attrib and add some "`:only-child`"

>`body > div > div:has(form#login_popup_cta_form:only-child) > div > div:only-child > div > div:only-child > div:only-child > div > div:only-child > div > div:only-child > div:only-child > div:only-child > div > div[role="button"]:only-child`

But this works in only AdGuard after allow filter "list" as Trusted:

>> Trusted filters can use powerful filtering rules modifiers which can be dangerous in the wrong hands. Do not check this box unless you fully trust it.
>
> ![obraz](https://user-images.githubusercontent.com/35370833/127916615-f8422999-6b95-434c-8573-cf0f0cc1e4d3.png)

or copied into "User rules" section in AdGuard.

---

For uBO maybe faster translate AG rule into "`*.user.js`" file.

If nobody can found/tried wrote solution with only allowed resoruces:

https://github.com/gorhill/uBlock/wiki/Resources-Library
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#scriptlets

**Comment by DandelionSprout** [comment]
Having looked up https://github.com/DandelionSprout/adfilt/issues/197#issuecomment-891182396 a few days late and figured out that the example page was `https://www.facebook.com/kimcartoonfp`, I ***finally*** see why no one were able to see this before: I didn't know it was physically possible to browse the `www.` version of Facebook on an Android phone.

I can now replicate the problem and then some, and will see if I have any luck removing the exceptionally obnoxious login prompts.

**Comment by DandelionSprout** [comment]
Considering I am unable to load past the first post on the page in question, I can only vaguely presume that the fix I did above is the best I can do for now.
