### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#199]
## Which entry/entries are you submitting?

Warning: R1ckroll.
```
https://www.youtube.com/watch?v=rW7hXs-81hM
```
## Which things do they block, hide, or unbreak?

This is a r1ckroll link (1 not i used to prevent detection). I am not sure how this should be added, so I will leave that up to @DandelionSprout .
## Which of my lists are you submitting it to?
R1ckroll link identifier 
## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):uBlock Origin development build v1.35.3rc3

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Same as #198
## (Optional) Which browser(s) and version did you use?

N/A

**Comment by DandelionSprout** [comment]
Nominally they're supposed to be submitted to https://rickrolldb.com/ , but [their list](https://rickrolldb.com/ricklist.txt) hasn't been updated since March 2019.

Whereas https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RickrollLinkIdentifier.txt only really covers videos that are used pretty frequently in 'rolling.

So I don't have any immediate solutions.

**Comment by iam-py-test** [comment]
@DandelionSprout based on the comments, that video has been used often for rickrolling

**Comment by iam-py-test** [comment]
Also, I tried visiting the site you posted & got a warning.

**Comment by krystian3w** [comment]
Maybe darude sandstorm need similar filter list.

**Comment by krystian3w** [comment]
@DandelionSprout new:

`youtube.com/watch?v=iik25wqIuFo`

**Comment by iam-py-test** [comment]
> @DandelionSprout new:
> 
> `youtube.com/watch?v=iik25wqIuFo`

General rule to fix it: `||youtube*.com/*iik25wqIuFo$all` 
Should cover embeds & directly visiting the url

**Comment by krystian3w** [comment]
I suppose not in this repo due "1%" chance for false positive.

**Comment by iam-py-test** [comment]
> I suppose not in this repo due "1%" chance for false positive.

How can I decrease that chance?

**Comment by krystian3w** [comment]
Longer ID for other video in the future like: "Z*iik25wqIuFo*7"
 or trolling friend by HTML anchors: `#iik25wqIuFo`

**Comment by iam-py-test** [comment]
> Longer ID for other video in the future like: "**Z**`iik25wqIuFo`**7**"
> or trolling friend by HTML anchors: `#iik25wqIuFo`

Also I realized this would also break websites with YouTube and .com in their name (I.e. maybe something like http://iloveyoutubevideos.com/iik25wqIuFo)

**Comment by iam-py-test** [comment]
Is there a way to limit to use in query params and path? (As that would not block the second use case)
I don’t know what can be done about the first apart from using two filters

**Comment by krystian3w** [comment]
Anybody create list for `SponsorBlock`:

start in: `https://youtu.be/byz_0l9RbYc?t=87`
and gone in 90 second.

**Comment by krystian3w** [comment]
1 Bilion/miliard (one thousand million) views has been planted:

https://www.instalki.pl/aktualnosci/internet/48982-rick-astley-never-gonna-give-you-up-youtube.html
