### ISSUE TITLE
SMP.no - Sport page issue

### ISSUE THREAD

**Issue by THEtomaso** [DandelionSprout/adfilt#2]
This filter is too aggressive:
**smp.no###content > .x10.gridRow:nth-of-type(1) > .textSize10.span10.gridUnit**

Test URL:
http://www.smp.no/100Sport/

**Comment by DandelionSprout** [comment]
Thanks for the headsup. After all, I'm very dependent on feedback from users who use Norwegian newssites a whole lot more often than what I do, in order to tell me if the filters are good or not.

It should be solved now (as I have tested it myself), upon a filter refresh or by waiting some hours.
