### ISSUE TITLE
Modify `://ww38.$document` filter to only apply to domains

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#200]
## Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any):
The filter ://ww38.$document causes any url containing that to be blocked. This prevents me from using https://www.siteadvisor.com/sitereport.html?url=http://ww38.coolstats1.net/?subid1=20210616-0828-13e0-974a-e3edd89fe7ec to analyze a malware domain

## Add screenshots below if needed:
Will add if my description is not enough. 
## Add a screenshot of the extension's logger:

N/A
## Which adblocker(s) and version did you use when testing this?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s): uBlock Origin development build v1.35.3rc4

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Same as https://github.com/DandelionSprout/adfilt/issues/198
## Which browser(s) and version did you use?

N/A
## (Optional) Which OS and version did you use?
- [ ] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux
- [ ] Android

Other(s):

OS version:

**Comment by DandelionSprout** [comment]
It should be pretty easy to click through the warning screen that shows up for uBO and AdGuard users: 
![image](https://user-images.githubusercontent.com/22780683/122133118-6a32b600-ce3c-11eb-9f35-4d272202cb32.png)

For e.g. Adblock Plus users, I'll try to think of something tomorrow after I've had a night of sleep.

**Comment by iam-py-test** [comment]
> It should be pretty easy to click through the warning screen that shows up for uBO and AdGuard users:
> ![image](https://user-images.githubusercontent.com/22780683/122133118-6a32b600-ce3c-11eb-9f35-4d272202cb32.png)
> 
> For e.g. Adblock Plus users, I'll try to think of something tomorrow after I've had a night of sleep.

Ok. Sorry for posting 3 issues at the name time.

**Comment by krystian3w** [comment]
How works:

```
|https://ww38.$doc
|http://ww38.$doc
```

**Comment by iam-py-test** [comment]
Could it be replaced with `||ww38.^$document`?

**Comment by krystian3w** [comment]
Seemingly yes.

Then it is left to determine the merits of searching "`://`" - I suppose Kris don't try block these url:

```
http://super.ww38.coolstats1.net/?subid1=20210616-0828-13e0-974a-e3edd89fe7ec
```

but this redirect into:

```
http://ww38.super.ww38.coolstats1.net/?subid1=20210619-0846-076c-836f-606aceb8d497
```

**Comment by iam-py-test** [comment]
> Seemingly yes.
> 
> Then it is left to determine the merits of searching "`://`" - I suppose Kris don't try block these url:
> 
> ```
> http://super.ww38.coolstats1.net/?subid1=20210616-0828-13e0-974a-e3edd89fe7ec
> ```
> 
> but this redirect into:
> 
> ```
> http://ww38.super.ww38.coolstats1.net/?subid1=20210619-0846-076c-836f-606aceb8d497
> http://ww16.super.ww38.coolstats1.net/?subid1=20210616-0828-13e0-974a-e3edd89fe7ec&sub1=20210619-0846-5004-8163-15bade24d52c
> ```

@DandelionSprout do those filters look ok?
@krystian3w who is _Kris_?

**Comment by krystian3w** [comment]
https://github.com/DandelionSprout/DandelionSprout/blob/main/README.md

But maybe no like shortened name.

**Comment by iam-py-test** [comment]
> https://github.com/DandelionSprout/DandelionSprout/blob/main/README.md
> 
> But maybe no like shortened name.

Ok, Thanks.

**Comment by DandelionSprout** [comment]
>Could it be replaced with ||ww38.^$document / do those filters look ok?

There'd be no point in doing so, because the sites I intend to block, are only those who begin with `ww38.`, with no further subdomains.

>I suppose Kris don't try block these url:

I vastly prefer Dandelion, Dandee, or Imre as nicknames.
