### ISSUE TITLE
 norgesavisen.no is parked

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#201]
The following entry in the TabloidRemover is parked.
https://github.com/DandelionSprout/adfilt/blob/eb13043726c8299a150c4d5d5bf720dd7f9ab05b/Sensitive%20lists/TabloidRemover.txt#L101
When I visited it, it showed `NORGESAVISEN.NO IS
PARKED` (translated by my browser) with a link to more information.
If this can be confirmed, it should be removed from this list

**Comment by DandelionSprout** [comment]
I'll see if I'm able to run that list through https://github.com/funilrys/PyFunceble sometime tomorrow.
