### ISSUE TITLE
Legitimate URL Shortener Tool breaks Google Hangouts and Google Chat

### ISSUE THREAD

**Issue by 1zaman** [DandelionSprout/adfilt#202]
## Which entry/entries are you submitting?

```
@@||client-channel.google.com/client-channel/channel/bind$removeparam=SID
@@||chat.google.com$removeparam=SID
```

## Which things do they block, hide, or unbreak?

1. Removing the `SID` param breaks Google Hangouts (inside Gmail), which stops receiving incoming calls and messages.

   This is shown in the UI as well, as the sidebar shows a message saying that it's trying to reconnect, and individual chat panels have a warning banner at the top saying that incoming messages may be delayed.

   This is a sample of the URL that is affected, with sensitive IDs snipped:
   ```
   https://29.client-channel.google.com/client-channel/channel/bind?authuser=1&ctype=hangouts&prop=gmail&appver=babel-chat.frontend_20210615.07_p0&gsessionid=<snip>&VER=8&RID=rpc&SID=<snip>&CI=0&AID=0&TYPE=xmlhttp&t=1
   ```

   Both `SID` and `AID` params are removed by the Legitimate URL Shortener Tool filter. Removing the `AID=0` param doesn't seem to have any negative effects though.

   Excluding requests to `client-channel.google.com/client-channel/channel/bind` from having the `SID` parameter removed (my first exclusion filter) fixes the issue.

2. The standalone Google Chat page (`mail.google.com/chat`) is also similarly broken by the generic removal of the `SID` param.

   This is also shown in the UI, as the sidebar shows a toast message saying that it's unable to connect to chat, and after a while it shows a dialog saying that chat was unable to load due to a problem.

   This is a sample of the URL that is affected, with sensitive IDs snipped:
   ```
   https://chat.google.com/u/1/webchannel/events?VER=8&RID=rpc&SID=<snip>&CI=1&AID=0&TYPE=xmlhttp&t=1
   ```

   Like the previous URL, this contains both `AID` and `SID` params, but only the removal of the `SID` param seems to cause the issue.

   Excluding requests to `chat.google.com` from having the `SID` parameter removed (my second exclusion filter) fixes the issue.

   Interestingly, the Google Chat page does also send requests to the previous URL that was used in Hangouts (`client-channel.google.com`), but these requests don't seem to be necessary for it's functionality, and the chat works fine even if that request is blocked.

## Which of my lists are you submitting it to?

Legitimate URL Shortener Tool

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s): uBlock Origin 1.35.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

 - All uBlock built-in filters.
 - EasyList
 - EasyPrivacy
 - Online Malicious URL Blocklist
 - uBlock filters – Annoyances
 - AdGuard Annoyances
 - Fanboy’s Annoyance
 - Peter Lowe’s Ad and tracking server list
 - AdGuard URL Tracking filter
 - Actually Legitimate URL Shortener Tool
 - Actually Legitimate URL Shortener Tool - Affiliate tag allowlist
 - Stop Autoplay On Video Sites
 - YouTube: Even More Pure Video Experience

## (Optional) Which browser(s) and version did you use?

Google Chrome 91.0.4472.101 (Official Build) (x86_64)

**Comment by DandelionSprout** [comment]
I applaud you for the very detailed explanation and for pinpointing the exact affected entries, since I no longer use Google Hangouts on any real basis. I'll take care of this right away as a respect for your effort.

**Comment by krystian3w** [comment]
`@@` now working good with queryprune?

If yes maybe good add AdGuard Project as stock:

https://filters.adtidy.org/extension/ublock/filters/17.txt
