### ISSUE TITLE
Scam domain

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#210]
## Which entry/entries are you submitting?

```
||whynotwin11.com^$document
```
## Which things do they block, hide, or unbreak?

This is a fake domain impersonating  https://github.com/rcmaehl/WhyNotWin11.
See https://github.com/rcmaehl/WhyNotWin11/issues/66 for more information.
## Which of my lists are you submitting it to?
Antimalware
## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):uBlock Origin v1.36.0

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![image](https://user-images.githubusercontent.com/84232764/123673061-06ca6000-d80e-11eb-9c20-f130362cf8d4.png)
![image](https://user-images.githubusercontent.com/84232764/123673135-1ea1e400-d80e-11eb-86d9-c51082b22c39.png)

## (Optional) Which browser(s) and version did you use?

Firefox 89.0.2

**Comment by DandelionSprout** [comment]
This seems like a very good fit for the https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt#L287-L293 subcategory, but I need to take care of some post-rugby-practice stuff before I can add that entry.

**Comment by iam-py-test** [comment]
Update: The download has been confirmed to be malware
