### ISSUE TITLE
Youtube Comments Break with Dandelion Sprout's Annoyances List

### ISSUE THREAD

**Issue by BabisZan** [DandelionSprout/adfilt#214]
## Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any):
When i try to watch i video the youtube comments doesnt show up ..... I use the ublock origin medium mode my only 3d party filter (i use almost all the main filters of ublock origin though)  is the Dandelion Sprout's Annoyances List. 

I disable it and i tried the  Actually Legitimate URL Shortener Tool and the youtube comments work again.
So the problem should be with annoyances list.

## Which adblocker(s) and version did you use when testing this?

Ublock  origin medium mode 
Adblocker version(s): 1.36.0

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
Block filters – Resource abuse
uBlock filters – Unbreak
AdGuard Base
EasyList 
AdGuard Tracking Protection
AdGuard URL Tracking Protection
EasyPrivacy
Online Malicious URL Blocklist
AdGuard Annoyances
Anti-Facebook
EasyList Cookie
uBlock filters – Annoyances
Dan Pollock’s hosts file
MVPS HOSTS
Peter Lowe’s Ad and tracking server list
GRC: Greek AdBlock Filter
⚙️ Dandelion Sprout's Annoyances List 

i want to add again that the same configuration work fine with the  Actually Legitimate URL Shortener Tool  and annoyance disabled.

## (Optional) Which OS and version did you use?
- [ ] Windows 10 windows 10 

Other(s):

OS version: 21H1

**Comment by BabisZan** [comment]
i want to add that the same problem  is happening with microsoft edge on almost the same ublock origin configuration (the diffeence is that the microsoft edge ublock origin  is at the easy mode) the filter list is the same though ..... and again the comments works fine  with actually legitimate url shortner tool. also on both browser my addons is ublock origin/ bitwarden / clearurls.

**Comment by DandelionSprout** [comment]
From what I understand about annoyances lists and about things that annoy people online, I thought strange comment sections were well within the limits of what such lists could block, and were in some cases even recommended to block?

**Comment by BabisZan** [comment]
So it works like intended? ok i thought that the breakage wasnt intentional.
im gonna keep the  the Actually Legitimate URL Shortener Tool then and unregister the annoyance list i would like to keep the youtube comment section.
