### ISSUE TITLE
PUP domain

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#223]
## Which entry/entries are you submitting?

`||speedupmypcfree.com^$all`
## Which things do they block, hide, or unbreak?

This is a PUP. See the scans of the downloaded files:
https://www.virustotal.com/gui/file/e66db6f687eacf9852542ab583f4d77191965f3a8d6c2e726f4e6b8b83b4f390/detection
https://www.virustotal.com/gui/file/93f1afd730eb30421d8e7cae9fc79cbee918c4b0a75d68bf64d34d2cc99d29f0/detection
## Which of my lists are you submitting it to?
Antimalware
## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):uBlock Origin v1.36.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

The same as my last report

**Comment by DandelionSprout** [comment]
I'll add that entry when I wake up tomorrow. Thanks in advance.
