### ISSUE TITLE
OneDrive phishing

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#224]
## Which entry/entries are you submitting?

`onedrive.interestmy.tech`
## Which things do they block, hide, or unbreak?

This is a phishing domain which pretends to be a OneDrive login, as seen in the screenshot below (taken from a VM):
![image](https://user-images.githubusercontent.com/84232764/126164630-13e6c012-3682-4766-a9b7-fc612a5dd053.png)
This is clearly _not_ a Microsoft signin.
See https://www.joesandbox.com/analysis/450654/0/html#deviceScreen for more info.

## Which of my lists are you submitting it to?
Antimalware
## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):uBlock Origin v1.36.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![image](https://user-images.githubusercontent.com/84232764/126165119-de7f5d82-72d5-42ed-a9f9-b3d18bd4caa0.png)
![image](https://user-images.githubusercontent.com/84232764/126165169-8384b8a0-b4ee-4880-ae51-fb8f7fff25e0.png)
Plus BlockList Project ransomware, although it did not want to fit in the screenshot
## (Optional) Which browser(s) and version did you use?

Firefox 89.0.2 (it wanted to update as I wrote this)
Tested in VM using Microsoft Edge 91.0.864.67

**Comment by iam-py-test** [comment]
@DandelionSprout where did the other domains come from? Reverse DNS?

**Comment by DandelionSprout** [comment]
It was a stepwise procedure:
1) Search for `interestmy.tech` at https://securitytrails.com/
2) The search results show an "A records" of `69.49.231.244`
3) Going through https://securitytrails.com/list/ip/69.49.231.244, I analysed which other sites that were hosted on the IP, and I concluded that it was reasonable to assume that they were all malicious.
4) I copied all 623 results into Sublime Text, and used RegEx to reduce them to those that started with `onedrive.` or `www.onedrive.`
5) Since it appears the domains are used to spoof other Microsoft products as well (e.g. `office.`), I added the subdomain-less versions of the domains to Anti-Malware List.

**Comment by DandelionSprout** [comment]
>Is it ok if I use copy those domains into my lists?

Yes.

**Comment by iam-py-test** [comment]
> 
> 
> It was a stepwise procedure:
> 
>     1. Search for `interestmy.tech` at https://securitytrails.com/
> 
>     2. The search results show an "A records" of `69.49.231.244`
> 
>     3. Going through https://securitytrails.com/list/ip/69.49.231.244, I analysed which other sites that were hosted on the IP, and I concluded that it was reasonable to assume that they were all malicious.
> 
>     4. I copied all 623 results into Sublime Text, and used RegEx to reduce them to those that started with `onedrive.` or `www.onedrive.`
> 
>     5. Since it appears the domains are used to spoof other Microsoft products as well (e.g. `office.`), I added the subdomain-less versions of the domains to Anti-Malware List.

@DandelionSprout thanks!

**Comment by iam-py-test** [comment]
@DandelionSprout new domains:
 `accessoffice365.knorish.com`
`00ffice354.weebly.com`
The top one look identical to the original domain which linked to the reported domain.
The second looks a lot like Phishing
