### ISSUE TITLE
Show YouTube comments and Video Suggestions

### ISSUE THREAD

**Issue by yokoffing** [DandelionSprout/adfilt#226]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

I'm enjoying the `Dandelion Sprout's Annoyances List`. I used to have over six filter lists from your database in my `Custom Filters` until I realized you had them all in your annoyances list. Nice!

Only problem I'm facing is on YouTube: **I want to see YouTube comments and suggestions on video pages**. Everything else that is hidden on YouTube is fine (including Live Chats, which are annoying).

I believe these are the filters hiding these sections. Correct me if I'm wrong:
```
! Removes comments on video pages

||youtube.com/comment_service_ajax?$domain=youtube.com|youtu.be|youtube-nocookie.com
youtube.com###comments

! Removes video suggestions on video pages
youtube.com##.watch-sidebar-body > #watch-related > .related-list-item
```
Do you know if it's possible to negate these rules in uBlock Origin?

I can go back and add those six filter lists again in uBlock Origin; but for simplicity, I'd like to only use your annoyances list.

Thank you for your time!

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![Screenshot 2021-07-23 213631](https://user-images.githubusercontent.com/11689349/126853875-8bb7ea95-ca70-4c04-98bb-370d86542fb6.jpg)

### Which browser(s) did you use when testing this?

Firefox

**Comment by DandelionSprout** [comment]
I admit to have been surprised by how high of a percentage of the feedback I've got for Annoyances List, that were requesting to unblock YouTube comments, as you're not the first person to have requested that. I think I've got requests from 4 different users in 2 months now, so now I pretty much have to consider it pretty seriously.

On the other hand, `youtube.com##.watch-sidebar-body > #watch-related > .related-list-item` doesn't seem to be part of Annoyances List that I can see. Instead it is part of https://raw.githubusercontent.com/DandelionSprout/adfilt/master/YouTubeEvenMorePureVideoExperience.txt, which from what I can see is not one of Annoyances List's component lists.

**Comment by yokoffing** [comment]
Regarding `youtube.com###comments`: Hiding YouTube comments is overly aggressive for a generalized annoyances list; it should stay relegated to niche lists like the `YouTube Pure Video Experience` list and derivatives. The comments section is inherently baked into the YouTube experience for a significant portion of users.

Unlike comment section on news articles or other locations that I'd regard as obtrusive/annoying/out-of-focus, YouTube is both a video streaming site _and_ social media. Creators interact with subscribers and even post links that are sometimes found only in the comments section. Hiding comments also prevents users from posting legitimate questions in response to videos. Personally, I almost always glean something useful (or humorous!) from the comments section in the videos I watch, and I really can't say that from any other video streaming site's comment section. 

Sorry for the confusion regarding `youtube.com##.watch-sidebar-body`; I was looking at the wrong tab. However, there is _something_ in `Dandelion Sprout's Annoyances List` that's hiding recommended videos on the right side of the YouTube video player.

I would prefer to have videos to the right of the player restored as well, but I can compromise as long as the comments section returns. Doing this would also encourage me to add the `Annoyances List` to my family and friend's computers.

**Comment by DandelionSprout** [comment]
Anti-'YouTube comments' entries are now under reconsideration and have been deactivated in the meantime.

However, when it comes to suggestions, I think you'll have to look into and use uBO's logger tool to get any closer to which list that are causing it, because I'm stumped on that one.

**Comment by yokoffing** [comment]
> However, when it comes to suggestions, I think you'll have to look into and use uBO's logger tool to get any closer to which list that are causing it, because I'm stumped on that one.

Apologies. I found what was causing this, and it was not the `Annoyances List` after all.

> Anti-'YouTube comments' entries are now under reconsideration and have been deactivated in the meantime.

This is much appreciated!

**Comment by yokoffing** [comment]
I see that the rules in question come from the `Anti-'Awful comments' list`.

In the `Description`, you say that the purpose of the list is to _not_ be "the usual anti-comment-section list", which is what hiding YouTube comments feels like. I could see validity in hiding YouTube comments if we were hiding _all_ comments sections. Thankfully, we are not in `Annoyances`.

Rather, `Anti-'Awful comments' list` seeks to only remove comment sections littered with "exceptionally bad comments." I don't have data for this, but I think you will find that most people would disagree that YouTube is filled with trash comments, especially for channels a user subscribes to. (Maybe they are junk on super popular videos, but those channels tend to be trash, anyway). Comments are inherently apart of the YouTube experience.

If YouTube is filled with awful comments, then we must go after Twitch and similar sites, too. But that feels more in line with your `Pure Video` lists and most anti-comment section lists you mentioned.

The other rules in `Anti-'Awful comments' list` are valid (e.g., Disqus and others) -- they are inline with your intention for the list, which in turn plays fine with `Annoyances List`.

Therefore, I propose we:
1. keep `!#include AntiAwfulCommentsList.txt` in `Annoyances List`
2. remove the YouTube rules in `Anti-'Awful comments' list`.

I see you've already commented them out:

```
! —!!!— Highly contentious among end-users and are under re-consideration —!!!—
!!!youtube.com###watch-discussion
!!!youtube.com##ytd-live-chat-frame
!!!m.youtube.com##ytm-comment-section-renderer
!!!youtube.com###comments
!!!||youtube.com/live_chat_fragments_ajax?$xmlhttprequest
!!!||youtube.com/comment_service_ajax?$domain=youtube.com
!!!invidious.snopyta.org,yewtu.be,invidious.tube,invidious.kavin.rocks,tube.connect.cafe,invidious.zapashcanon.fr,invidious.fdn.fr,invidiou.site,vid.mint.lgbt,invidious.site,invidious.048596.xyz,invidious.zee.li,vid.puffyan.us,c7hqkpkpemu6e7emz5b4vyz7idjgdvgaaa3dyimmeojqbgpea3xqjoid.onion,w6ijuptxiku4xpnnaetxvnkc5vqcdu7mgns2u77qefoixi63vbvnpnqd.onion,kbjggqkzv65ivcqj6bumvp337z6264huv5kpkwuv6gu5yjiskvan7fad.onion,invidious.3o7z6yfxhbw7n3za4rss6l434kmv55cgw2vuziwuigpwegswvwzqipyd.onion,grwp24hodrefzvjjuccrkw3mjq4tzhaaq32amf33dzpmuxe7ilepcmad.onion,tube.incognet.io###comments
```

**Comment by DandelionSprout** [comment]
I've now actually reinstated the blocking of YouTube suggestions, hinging on these sources:
```
! https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Images/YouTube%20suggestion%20feed%20block%20reason.png (Found by me personally)
! https://techcrunch.com/2021/07/07/youtubes-recommender-ai-still-a-horrorshow-finds-major-crowdsourced-study
! https://assets.mofoprod.net/network/documents/Mozilla_YouTube_Regrets_Report.pdf
! https://www.techtimes.com/articles/252624/20200917/youtubes-horrible-recommendations-could-affect-younger-users-and-you-could-help-fix-it.htm
```

**Comment by yokoffing** [comment]
> I've now actually reinstated the blocking of YouTube suggestions

I will go back to using separate filter lists since blocking YouTube suggestions is too heavy-handed for my use-case.

Thank you for listening to the users on the `Anti-'Awful comments' list`. I will continue to use this list as long as YouTube comments aren't blocked.

**Comment by DandelionSprout** [comment]
I suppose `youtube.com#@#ytd-watch-next-secondary-results-renderer` would've worked to re-allow suggestions on your end, should you ever wish to return to Annoyances List.

**Comment by DandelionSprout** [comment]
In order for YouTube comments to be re-blocked, there'd need to have been substantial problems with comments that were either dangerous (à la "Eating mouldy fish makes you lose weight"), racist, and/or extraordinarily dumb, on videos whose videomakers did not intend for any of those kinds of comments, within the past 6 months.

As I have been unable to stumble across such in the past week, the comments will remain unblocked indefinitely in Annoyances List.
