### ISSUE TITLE
RBKWeb.no ødelagt

### ISSUE THREAD

**Issue by esmorun** [DandelionSprout/adfilt#238]
Kan du være vennlig å endre linje 1246 i NorwegianList.txt fra:
`parcferme.no,rbkweb.no##.adsbygoogle:upward(2)`
Til:
`parcferme.no##.adsbygoogle:upward(2)`

Dette fikser problem med at det ikke vises noe innehold på førstesiden på rbkweb.no.

Takk!

**Comment by DandelionSprout** [comment]
Det kan jeg fort ordne. Takk for tipset.
