### ISSUE TITLE
mobile.twitter.com

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#24]
`https://mobile.twitter.com/theraymondltd`

No unlocked scroll with: 

`🚪 Browse websites without logging in`

**Comment by krystian3w** [comment]
```html
<body style="height: 100%; width: 100%; overflow-y: hidden; overscroll-behavior-y: none; background-color: rgb(255, 255, 255);">
```

**Comment by DandelionSprout** [comment]
It took me half an hour to confirm and test out a fix for this problem, but I believe I've got it to work now, so I'll be adding it to the list pretty soon.

Thanks for telling me about this. 🙂
