### ISSUE TITLE
Browse AntenaPlay without logging in

### ISSUE THREAD

**Issue by andreewmat** [DandelionSprout/adfilt#243]
## Which entry/entries are you submitting?

https://antenaplay.ro/
https://antenaplay.ro/mr-wrong-episoadele-41-42-si-43/I7tGZE7Ab0C (here is the log-in pop-up after I press on the play button).
## Which things do they block, hide, or unbreak?

The log-in pup-up.
## Which of my lists are you submitting it to?
"Browse websites without logging in".
## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):
HTTPS Everywhere and Cookies AutoDelete.

Adblocker version(s):
Ublock 1.37.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![screen](https://user-images.githubusercontent.com/79897301/128606284-ccd19cc9-acb9-455e-8e30-7ab7ea726f0f.jpg)
![screen01](https://user-images.githubusercontent.com/79897301/128606286-81bebaff-3efd-4a51-84e0-4fce73a51a57.jpg)

## (Optional) Which browser(s) and version did you use?

Firefox 90.0.2 on Windows 10 Pro 64bit.

**Comment by DandelionSprout** [comment]
I sadly don't think this one is physically possible to bypass, since the video's play button leads directly to the login page.
