### ISSUE TITLE
Broken link?

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#245]
https://github.com/DandelionSprout/adfilt/blob/25604dbb13f1f2f697c14b0926bd68ca7e218e77/AdRemovalListForUnusualAds.txt#L38
returns a 404 when visited for a unknown reason.

**Comment by DandelionSprout** [comment]
I can only presume that the latter issue report was completely deleted by its repo owners. I'll modify that line now.

**Comment by DandelionSprout** [comment]
Which I've done now in https://github.com/DandelionSprout/adfilt/commit/42f552a8fbfec33d7040e43028116fc347302dc6
