### ISSUE TITLE
Ticketmaster ad leftovers

### ISSUE THREAD

**Issue by peace2000** [DandelionSprout/adfilt#246]
https://www.ticketmaster.no/
https://www.ticketmaster.se/
https://www.ticketmaster.dk/

![kuva](https://user-images.githubusercontent.com/17256841/129092256-d7c8623a-e06b-4940-93bc-58fd9e0d4f1a.png)

![kuva](https://user-images.githubusercontent.com/17256841/129092390-d9a6f28e-99a6-49ba-a9c8-d8fa6221c75c.png)

Suggestion: `#?#div:-abp-has(> [id|="ad-slot"])` (used the same for the Finnish Ticketmaster)

## Which of my lists are you submitting it to?

NOR, DNK, ISL: Dandelion Sprouts nordiske filtre

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):

1.37.3b8

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Easylist
NOR, DNK, ISL: Dandelion Sprouts nordiske filtre

## (Optional) Which browser(s) and version did you use?
Firefox 90.0.2

**Comment by DandelionSprout** [comment]
I've delegated this to https://github.com/easylist/easylist/issues/8677 for the time being, since the placeholders are present on 20 other `Ticketmaster` versions as well.

**Comment by peace2000** [comment]
Oh.. Didn't realize they aren't just a nordic company... :D
