### ISSUE TITLE
IDEA: Add support for DuckDuckGo/Bing in the antimalware list

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#247]
Currently, the antimalware list removes malware domains from Google's results, but it does not block results in DuckDuckGo & Bing search results.
You could use the following filters to remove from DuckDuckGo results, but I don't know how to do the same for Bing:
```
duckduckgo.com##[data-domain$=".top"]
```

**Comment by hirorpt** [comment]
> `duckduckgo.com##.sitelink:has(a[href*=".top/"])`

Can you tell me the page where this filter is valid? I'm currently creating on similar filters that works with multiple search engines.

**Comment by iam-py-test** [comment]
> > `duckduckgo.com##.sitelink:has(a[href*=".top/"])`
> 
> Can you tell me the page where this filter is valid? I'm currently creating on similar filters that works with multiple search engines.

This should work for the smaller sub-results (i.e. on https://duckduckgo.com/?q=ublock&ia=web with uBlock Origin disabled)

> 
> > `duckduckgo.com##.result:has(a[href*=".top/"])`
> 
> It should be `duckduckgo.com##.result[data-domain$=".top"]`. [Reference](https://old.reddit.com/r/uBlockOrigin/comments/meflfv/rules_to_block_sites_from_search_results/gsgs7yn/)

@hirorpt Thank you! I will correct it

**Comment by hirorpt** [comment]
> This should work for the smaller sub-results (i.e. on https://duckduckgo.com/?q=ublock&ia=web with uBlock Origin disabled)

Thank you, @iam-py-test . I decided to use`duckduckgo.com##[data-domain$="ublock.org"]` as proposed by gorhill, which supports both of `.sitelink` and `.result`.

**Comment by iam-py-test** [comment]
> > This should work for the smaller sub-results (i.e. on https://duckduckgo.com/?q=ublock&ia=web with uBlock Origin disabled)
> 
> Thank you, @iam-py-test . I decided to use`duckduckgo.com##[data-domain$="ublock.org"]` as proposed by gorhill, which supports both of `.sitelink` and `.result`.

Updating using [data-domain]

**Comment by DandelionSprout** [comment]
It is unlikely I can fix this before Wednesday night UTC, which is the earliest possible time I could get back home from vacation to Finland and Sweden.

Once I do get home, it's of reasonably high priority.

**Comment by hirorpt** [comment]
Maybe
`:not([data-domain$="..."], ...)`

**Comment by DandelionSprout** [comment]
Oh, right. I was slightly sleepy when I added those DDG entries. Give me 3min.
