### ISSUE TITLE
DandelionSprout DNS breakage 

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#248]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

When DandelionSprout DNS is enabled/installed, `blog.malwarebytes.com` returns a NX_DOMAIN, while once it is disabled, I can reach the website.
I have experienced first on Windows, but once this problem on ChromeOS after I added it as my main DNS server, and then when I eventually disabled it, the website loaded.

### Add screenshots below if needed

My main computer without DandelionSprout DNS enabled:
![image](https://user-images.githubusercontent.com/84232764/129629746-0027ab38-d58c-4632-8ca4-f48b7a234276.png)

A VM with DandelionSprout DNS enabled (ping command shown to prove the internet works):
![image](https://user-images.githubusercontent.com/84232764/129629888-815da7f1-f9fa-4e91-a568-ec242c1a01fd.png)

### Add a screenshot of the extension's logger

N/A

### Which adblocker(s) did you use when testing this?

Other

### Adblocker version(s)

DandelionSprout DNS (uBlock Origin not installed in the VM)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Whatever filters are on the DNS server

### Which browser(s) did you use when testing this?

Google Chrome, Chromium for Linux, Other

### Browser version(s)

Edge in the VM: 91.0.864.67 (I did update Edge and it made no difference) 
I can not get the Chrome on ChromeOS version as I do not have access to that computer right now

### Which OS(s) did you use when testing this?

Windows 10, Linux, Other

### OS version(s)

ChromeOS: Latest (I can not provide more details as I lack access to it right now)
VM Windows: 21H1

**Comment by DandelionSprout** [comment]
I can confirm that site was indeed false-positived in the server's query log due to `://130.211.` in Compilation List. I've whitelisted that entry at the moment, and will look into a more permanent fix in 1-2 days.

**Comment by iam-py-test** [comment]
@DandelionSprout Thanks
I will test once it is live

**Comment by iam-py-test** [comment]
@DandelionSprout it seems the problem has been resolved.
I have enabled DandelionSprout DNS & blog.malwarebytes.com still loaded
Thank you for the quick response and fix!

**Comment by DandelionSprout** [comment]
I did my utmost to ensure that entries that'd equal `/16` in CIDR syntax, will never be a part of https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AdGuard%20Home%20Compilation%20List/AdGuardHomeCompilationList.txt ever again; and I haven't heard of such entries being present in any of the other lists that the server is using.
