### ISSUE TITLE
[🇪🇺 GDPR 451 List of Mostly American Websites Who Hate Europe and Privacy Rights] New entry

### ISSUE THREAD

**Issue by CyanoTex** [DandelionSprout/adfilt#249]
https://www.wavy.com/news/trending/alcoholic-mountain-dew-drink-hard-mtn-dew-in-the-works/

Here's the website in question.

![msedge_JFJ3pJbjGY - 17-08-2021 at 04-27-07 PM](https://user-images.githubusercontent.com/62466866/129744540-c6b57409-3708-44ee-bc7e-f0086e7de45a.png)

**Comment by peace2000** [comment]
"Our European visitors are important to us."

No, we aren't... :D
