### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#25]
`https://www.instagram.com/p/BsvEQfhh14i/`

![image](https://user-images.githubusercontent.com/35370833/51472663-650bd280-1d7a-11e9-8924-dd96aef96906.png) |
--- |

with `🚪 Browse websites without logging in`

###### mechanical translation:

> ### Log in to Instagram
> Log in to see your friends' photos and videos and discover other accounts you like.

---

###### may works but instagram have terrible code (uses only random "compressed" classes).

```
instagram.com#?#div[class*=" "]:-abp-has(> div > div > div > a[class][href^="/accounts/login/?next="][href$="&source=logged_out_half_sheet"])
```

**Comment by DandelionSprout** [comment]
At least they're not quite as bad as what the godawful classes that Twitter Mobile is using.

Although your entry seems to work pretty well, I've shortened it down to `instagram.com##.ZUqME:-abp-has(a[href^="/accounts/login/"])`, which as far as I can tell works just as well.

**Comment by krystian3w** [comment]
OK, it works for me too.

**Comment by DandelionSprout** [comment]
As I've now applied the fix to the list, this issue will now be closed.

**Comment by krystian3w** [comment]
Show if no disable logon as safe "image" (without write password in login form):


![obraz](https://user-images.githubusercontent.com/35370833/51873503-b4936500-235d-11e9-8a70-436bd920cf88.png) |
--- |

```
instagram.com#?#.ZUqME:-abp-has(a[href^="/accounts/emailsignup/"])
```

`#?#div[class*=" "]:-abp-has(> div > div > div > a[class][href^="/accounts/emailsignup/"])`

**Comment by DandelionSprout** [comment]
I find it to be slightly unusual that a user of that list, would want to use it on a website that (s)he does actually have an account for.

But I'll look into the matter right away anyway.

**Comment by DandelionSprout** [comment]
Or, no, wait, I don't have an Instagram account, so I'll have to take your word for it.

**Comment by krystian3w** [comment]
I changed detection to second link "zarejestruj się" / "Sing up", because it's no changing.
