### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by peace2000** [DandelionSprout/adfilt#250]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Filter `##.ad-container` removes non-ad elements.

Removed ad-elements are found in these links:

https://www.kuopio.fi/etusivu

https://www.kuopio.fi/-/viksu-kuopio-tunnus-ymparistovastuullisille-toimijoille-haku-on-kaynnissa?inheritRedirect=true&redirect=%2Ffi%2Fetusivu

Possible fix:

`##.ad-container` -> `##.ad-container:not(.portlet-column)`

### Add screenshots below if needed

![kuva](https://user-images.githubusercontent.com/17256841/129764225-048a42e1-3d3e-4c96-8ef2-998297f13e34.png)

![kuva](https://user-images.githubusercontent.com/17256841/129764302-7f16a368-c3ab-4a2f-85db-b2dcacca06cd.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.37.3b9

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Easylist
NOR, DNK, ISL: Dandelion Sprouts nordiske filtre

(disabled others)

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

91.0

### Which OS(s) did you use when testing this?

Windows 10

**Comment by DandelionSprout** [comment]
Considering that entry already had two whitelisted domains, this 3rd one meant it was time for me to replace the entry as a whole.

**Comment by peace2000** [comment]
That might be good solution. That rule is probably among those "sounds good but causes false positives" rules... Just like filter `##.ad`.

The main Easylist doesn't either have `##.ad-container` as a generic entry, but it has many entries that where it's followed by a hyphen:

![kuva](https://user-images.githubusercontent.com/17256841/129805519-741db106-c396-4f7f-8f90-ff27e28ac19c.png)
