### ISSUE TITLE
Some kind of adware

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#253]
## Which entry/entries are you submitting?

```
||mediaget.com^$all
```
## Which things do they block, hide, or unbreak?

This blocks an website which promotes and hosts a PUP.
See https://www.virustotal.com/gui/file/af7b36c0f9f48f35315877e3cd5efb83c1a122a043ea9228db7da9c1c3c3120b/community
Screenshot:
![image](https://user-images.githubusercontent.com/84232764/130523494-069028d2-cbe7-4362-b228-424e719d2ad8.png)

## Which of my lists are you submitting it to?
Antimalware
## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s): uBlock Origin 1.37.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

N/A

**Comment by iam-py-test** [comment]
@DandelionSprout is it ok if I copy the additional entries into my own lists?
I figure it probably is, but I wanted to make sure

**Comment by DandelionSprout** [comment]
It is indeed OK.

**Comment by iam-py-test** [comment]
@DandelionSprout Thanks!
