### ISSUE TITLE
filter blocks all .ml domains

### ISSUE THREAD

**Issue by gautamkrishnar** [DandelionSprout/adfilt#259]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

.ml is a free domain extension that anyone can register via https://www.freenom.com/. Currently the following filter rute:
https://github.com/DandelionSprout/adfilt/blob/e2f9d85e323c56af42495217e18deeee1eb1ce02/Dandelion%20Sprout's%20Anti-Malware%20List.txt#L16
Is blocking all the .ml websites

### Add screenshots below if needed

App: Adguard

![2021-08-30 17 19 05](https://user-images.githubusercontent.com/8397274/131334629-881bb1cf-2102-4a6a-81cb-49431a61d550.jpg)

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop version)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Adguard filters

### Which browser(s) did you use when testing this?

Google Chrome, It's about a phone/TV app

### Which OS(s) did you use when testing this?

Android

**Comment by DandelionSprout** [comment]
The blockage is intentional, because I think ≥95.0% of `.ml` domains are malware in some way. I am however perfectly willing to add exceptions for individual sites, and will look into `nothingprivate.ml` real quick now.

**Comment by gautamkrishnar** [comment]
@DandelionSprout it would be great if you can whitelist nothing private in the filter. It is an open-source project hosted at: https://github.com/gautamkrishnar/nothing-private

**Comment by DandelionSprout** [comment]
I was quickly able to check and see that the site is good, so I've whitelisted it by now: https://github.com/DandelionSprout/adfilt/commit/2d79c3b56caa9426abc09566c4047f7dde496991#diff-deec8786cbfd5714487695e0570454f992bd318cee5efacc7633aace9f311838

If I understand AdGuard's filter mirroring correctly, the whitelisting will go live there in maybe 2 hours' time.

**Comment by gautamkrishnar** [comment]
Thanks a lot 👍🏻

**Comment by gautamkrishnar** [comment]
@DandelionSprout the website is getting blocked by one of the other entries in your filter now:
![image](https://user-images.githubusercontent.com/8397274/133502566-71abc150-959f-4bfe-a230-89ac4c285d6f.png)

![image](https://user-images.githubusercontent.com/8397274/133502603-f5e09b85-ffde-4868-949b-d1fc09b2c140.png)

Is this an adguard bug?
