### ISSUE TITLE
https://www.pinterest.com/

### ISSUE THREAD

**Issue by Schanzation** [DandelionSprout/adfilt#26]
Hello!

I have BrowseWebsitesWithoutLoggingIn filter enabled in ublock origin still I can't browse these two sites without logging in. Haven't tested any other sites yet.

https://www.pinterest.com/
https://no.pinterest.com/

**Comment by DandelionSprout** [comment]
In the absence of any feedback on whether it's working better or not when taking my above advices into consideration, I'll assume for now that it does unless I hear otherwise, and will consider this issue report to be marked as "Closed".

**Comment by krystian3w** [comment]
https://greasyfork.org/pl/scripts/6325-pinterest-without-registration maybe works better as CSS hide elements and overidde by uBO Annoyance: https://github.com/uBlockOrigin/uAssets/issues/2044
