### ISSUE TITLE
ie=UTF-8 string on Google search

### ISSUE THREAD

**Issue by pawelkoszalin** [DandelionSprout/adfilt#260]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

When i wants to search something on my mobile, with chrome browser, your rules adds "ie=UTF-8" string to search link, and it broke polish specific characters.

### Add screenshots below if needed

![20210830_203921](https://user-images.githubusercontent.com/89804483/131388317-537af4b9-45c9-4724-92f0-9a20e055b8ee.jpg)

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop version)

### Adblocker version(s)

Adguard for Android (pro version)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![Screenshot_20210830-201536_AdGuard](https://user-images.githubusercontent.com/89804483/131388500-b7608003-fdb3-400b-9929-2f934f49784c.png)

### Which browser(s) did you use when testing this?

Google Chrome

### Which OS(s) did you use when testing this?

Android

**Comment by Faisalnd** [comment]
Even in Arabic the same thing 
![Screenshot_20210830-232100_Chrome](https://user-images.githubusercontent.com/31592656/131400221-db3ad7be-abd1-4a8f-a406-f88c53592aa2.jpg)
![Screenshot_20210830-232046_Chrome](https://user-images.githubusercontent.com/31592656/131400226-fb682dec-49f0-41e3-bf41-6cfa4b685667.jpg)

**Comment by krystian3w** [comment]
How this works with uBO + Google Search Fixer?

**Comment by pawelkoszalin** [comment]
> How this works with:
> 
> * uBO + Google Search Fixer + Firefox Fenix or Legacy 68.X
> * uBO + Kiwi (based on Chromium 93) or Yandex Browser
> 
> ?

uBO + Firefox beta (Android) - works well
uBO + Kiwi - works well

**Comment by DandelionSprout** [comment]
I'm having problems reproducing this in Chrome 92.0.4515.159 for Android 10 so far this morning. When using Chrome, are you searching from either:
1) The Google search line widget on the homescreen.
2) Chrome's URL bar.
3) By going to `google.com` and searching from there.

**Comment by pawelkoszalin** [comment]
2. Chrome's URL bar.

**Comment by krystian3w** [comment]
OK, so AdGuard remove 'param' harder or Chrome have very different code of page then compare what we see in Kiwi.

Maybe the best is comment line:

https://github.com/DandelionSprout/adfilt/blob/0f6d27cb47af837675a19228af99024db73b08d2/LegitimateURLShortener.txt#L937

Into adguard own/personal rules temporarily possible copy:

`||google.$~xmlhttprequest,removeparam=ei,badfilter`


And in free time tests pre procedurual grouping like: `env_ublock` (or only `env_desktop`), 'Adguard Windows', 'AdGuard macOS' (can be simplfed to exclude Android app in the safest scenario).

**Comment by DandelionSprout** [comment]
Can you (pawel) paste the whole URL you get in the "Filter on" scenario in a comment below?

**Comment by pawelkoszalin** [comment]
On:
https://www.google.com/search?ie=UTF-8&client=ms-android-samsung-ss&sourceid=chrome-mobile&oq=%C3%85%C2%BC%C3%83%C2%B3%C3%85%C2%82ty&q=%C3%85%C2%BC%C3%83%C2%B3%C3%85%C2%82ty&no_sw_cr=1&ved=1t%3A46160&zx=1630391050463

Off:
https://www.google.com/search?q=%C5%BC%C3%B3%C5%82ty&oq=%C5%BC%C3%B3%C5%82ty&aqs=chrome.0.69i59l3j0i512l2.921j0j9&client=ms-android-samsung-ss&sourceid=chrome-mobile&ie=UTF-8

Search term is: żółty - that's yellow in polish

**Comment by pawelkoszalin** [comment]
![Screenshot_20210831-083426_Chrome](https://user-images.githubusercontent.com/89804483/131453755-1bdd6f2e-6176-4551-b6ba-4ae03aaadc21.png)
![Screenshot_20210831-083327_Chrome](https://user-images.githubusercontent.com/89804483/131453762-9d105392-7acc-43eb-8fed-daa81b17825a.png)

**Comment by DandelionSprout** [comment]
Okay, I am now clued on to something of some sort. Seems to be a pretty major bug with Google itself, where it converts `%C5%BC%C3%B3%C5%82ty` into `%C3%85%C2%BC%C3%83%C2%B3%C3%85%C2%82ty`, causing HTML entity failures.

Are you able to paste `@@||www.google.$removeparam=aqs` into your AdGuard user filters and see if that fixes anything at all?

**Comment by pawelkoszalin** [comment]
Works!

https://www.google.com/search?q=%C5%BC%C3%B3%C5%82ty&oq=%C5%BC%C3%B3%C5%82ty&aqs=chrome.0.69i59l3j0i512l2.940j0j9&client=ms-android-samsung-ss&sourceid=chrome-mobile&ie=UTF-8

![Screenshot_20210831-090909_Chrome](https://user-images.githubusercontent.com/89804483/131458776-6c49b00e-f1f0-4941-8e22-4fd784820396.png)
