### ISSUE TITLE
Position(s) for collaborators for 4 of my most backlogged lists are open

### ISSUE THREAD

**Issue by DandelionSprout** [DandelionSprout/adfilt#264]
I, Dandelion Sprout, have had frequent coldths and fevers in the past 1½ years, and while I can maintain a lot of my lists on my own will, some of the backlog has now become more than what I can easily handle as a one-man army anymore.

### This concerns:
* [Actually Legitimate URL Shortener Tool](https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt)
* [Actually Legitimate URL Shortener Tool - Affiliate tag allowlist](https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener-AffiliateTagAllowlist.txt)
* [Dandelion Sprout's Nordic Filters (uBO version)](https://github.com/DandelionSprout/adfilt/blob/master/NorwegianList.txt)
* [Staying On The Phone Browser](https://github.com/DandelionSprout/adfilt/blob/master/stayingonbrowser/Staying%20On%20The%20Phone%20Browser) (Included because I lack time to find enough new entries for it.)

None of my other lists are in need of help on this scale, but collaborator rights are only handed out on a per-repo basis, seemingly.

### Position info:
• Unpaid/Voluntary.
• Requires high understanding of [uBlock Origin syntax](https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md) (`##+js` understanding is optional).
• I still want to be the person to ask before adding entries to any other lists than the above.
• To submit an application, write your previous experiences with adblocker listmaking below.
• There is no actual job contract nor job performance quotas involved in this at all.

Applicants will be examined as they are submitted; though applications submitted prior to 24th of September 15:00 CEST are preferable.

**Comment by iam-py-test** [comment]
As stated in #263, I am willing to help.
I have submitted entries (mainly malware domains) to this repo, in addition to [uAssets](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+author%3Aiam-py-test), [BlockList Project](https://github.com/blocklistproject), and [some other repos](https://github.com/My-External-Stuff/ublockorigin-rules/issues/9).
I also [have my own blocklists](https://github.com/iam-py-test/my_filters_001) and have some experience in Python and JS/HTML.
I am not sure if I am qualified enough to really help, but I am willing to devote some of my spare time to this project
I can provide more if needed

**Comment by DandelionSprout** [comment]
It looks like it'll be a trivial matter to approve you (iam-py-test) for collaborator status sometime tomorrow, but you can read through https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md to see if there are any syntaxes you've missed out on (You can safely skip ones like `:xpath`, `:min-text-length`, and `:watch-attr`).

**Comment by iam-py-test** [comment]
> 
> 
> It looks like it'll be a trivially simple matter to approve you (iam-py-test) for collaborator status sometime tomorrow, but you can read through https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md to see if there are any syntaxes you've missed out on (You can safely skip ones like `:xpath`, `:min-text-length`, and `:watch-attr`).

@DandelionSprout ok! I will do
Right now I will be leaving my computer so I will not see any notifications

**Comment by iam-py-test** [comment]
@DandelionSprout invite received
Thank you

**Comment by HankAviator** [comment]
Relating to [Staying On The Phone Browser](https://github.com/DandelionSprout/adfilt/blob/master/stayingonbrowser/Staying%20On%20The%20Phone%20Browser) , I am submitting some QR code promo entries of Chinese apps, Chinese company's service WeChat subscription account (channel) and their WeChat miniapps which function as a regular app. The borderline is still very blurry for me but I once decided to move all above mentioned entries to [AdRemovalListForUnusualAds](https://github.com/DandelionSprout/adfilt/blob/master/AdRemovalListForUnusualAds.txt) . Advice is welcomed upon this, but all entries I submitted were discovered on PC browser so I think they won't qualify.

Off-topic but @DandelionSprout did you try to find out why you got your colds and fevers? Suppose you're around my age your immune system should be robust already :/ Can't resist asking since I graduated in clinical medicine...

**Comment by DandelionSprout** [comment]
>(…) their WeChat miniapps which function as a regular app. The borderline is still very blurry for me (…)

I lack experience with WeChat, but the general rule of thumb, is that if a button or link tells you "Download our app", "Download on Google Play", or anything similar, it's going into *Staying on the Phone Browser*.

>did you try to find out why you got your colds and fevers? (…)

So far I've been to many practitioner visits, and have ruled out diabetes, gout, blood allergies, low/high metabolism, COVID, and vitamin deficiencies. The main remaining possibilities are sinus oxygen blockage, fibromyalgia, and everyday stress.

**Comment by shenzhiming88** [comment]
I want to join and help maintain the `Actually Legitimate URL Shortener Tool`.
I think this project is very good, but it may not be localized enough for China. Therefore, I have submitted more than twenty PRs over time to maintain the `Actually Legitimate URL Shortener Tool`. (See https://github.com/DandelionSprout/adfilt/pulls?q=is%3Apr+author% 3Ashenzhiming88+is%3Aclosed+ )
I don't know much about syntax and only know some basic syntax. However, I only maintain this list of filters and I don't think I need any other knowledge.
In addition, my maintenance time may be short and I may only be able to maintain it on holidays. However, I think one advantage is that the time in China is opposite to yours, so I can simply deal with other people's feedback during your nights. But I will still mainly maintain the rules about the Chinese site.

**Comment by iam-py-test** [comment]
@DandelionSprout any thoughts?
> I only maintain this list of filters

Sadly, there is no way to only grant you access to that list. That would be a nice feature though :)
You do seem to have a track record of contributing to the adblocking community. 
One way you can contribute is to help with the translations on Crowdin. 

(I can't add you as a contributor, only the owner can)

**Comment by shenzhiming88** [comment]
Okay, if you need another collaborator at that time, you can come back to me. In this case now, I will submit PRs from time to time.

**Comment by DandelionSprout** [comment]
With none of the currently qualified potential members having submitted applications after 3½ months, I think it's time for me to close this thread for the time being.

**Comment by iam-py-test** [comment]
@DandelionSprout do you think this can be unpinned?

**Comment by DandelionSprout** [comment]
Ah, good point. I'll unpin it right away.
