### ISSUE TITLE
bhaskar.com

### ISSUE THREAD

**Issue by chirag127** [DandelionSprout/adfilt#268]
**Issue URL (Annoyance)**:
https://www.bhaskar.com/international/news/chinas-peoples-liberation-armys-preparation-for-war-explained-by-us-army-128896329.html  has "today's Horoscope"
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132254937-d3552894-176b-4000-8df7-41609d9352d2.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)+🛤️ Anti-Astrology List
</details><br/>

**Comment by iam-py-test** [comment]
@chirag127 does `www.bhaskar.com##.f0b88488` seem to get rid of it?
![image](https://user-images.githubusercontent.com/84232764/132255634-fdfd9bfb-4551-47b5-ac2c-746e34e8520b.png)

**Comment by chirag127** [comment]
Well if I knew if it will work properly and not create FP , I would have simply added to my personal filters.

**Comment by iam-py-test** [comment]
> Well if I knew if it will work properly and not create FP , I would have simply added to my personal filters.

I don't see any breakage 
I am assuming the element is named the same on your side as well?

A possible option to reduce FPs would be to use :has-text, but that would have to language-specific

**Comment by DandelionSprout** [comment]
I'm tempted to go with `bhaskar.com##div[class]:not([class^=_], [style], :last-of-type):-abp-has(a[href*=rashifal])`, just in the case the element's name tend to differ.

**Comment by iam-py-test** [comment]
@DandelionSprout your filter works on my end
