### ISSUE TITLE
YT filters

### ISSUE THREAD

**Issue by crazyyzarc** [DandelionSprout/adfilt#269]
Preciser filters on YouTube web
```
! Remove video count
www.youtube.com##.ytd-video-view-count-renderer.style-scope.view-count

! Remove Owner Sub
www.youtube.com###owner-sub-count

! Remove dot between counts and date
www.youtube.com###dot

! Remove like/dislike button
www.youtube.com##.ytd-toggle-button-renderer.style-scope
```

**Comment by DandelionSprout** [comment]
I must say that all 4 of these entries seem like overkill to me. I need a few days to consider whether to create a new _"YouTube: Even More Pure Video Experience - Overkill"_ list in order to cover these and https://gist.github.com/gidoBOSSftw5731/15721a09a8be4191baeb4c5606d1a199

**Comment by THEtomaso** [comment]
> I must say that all 4 of these entries seem like overkill to me.

Pff..
That's nothing compared to what I've removed! :)

**Comment by DandelionSprout** [comment]
I have now opted against an overkill-specific list, instead implementing 3 additional gists from https://gist.github.com/gidoBOSSftw5731/15721a09a8be4191baeb4c5606d1a199 into the regular Even More Pure Video Experience list. Comments will remain open.
