### ISSUE TITLE
VG.no

### ISSUE THREAD

**Issue by Odinist** [DandelionSprout/adfilt#27]
Hei igjen. Håper du har fått tid til å leke i snøen.

Jeg bruker Vivaldi og uBlock Origin med de vanlige filtrene og ditt:

NOR, DNK, ISL: Dandelion Sprouts nordiske filtre​​​​​893 used out of 907​​​​

Reklame blir ikke blokkert på VG.no. Siden laster også tregt mens den venter på at annonsene skal lastes inn.

**Comment by DandelionSprout** [comment]
Hvilke andre lister bruker du når du tester? Bruker du f.eks. EasyList, AdGuard Base Filters, og/eller uBlock Filters?

Listen min tar utgangspunkt i at brukerne i det aller minste bruker EasyList i tillegg.

**Comment by Odinist** [comment]
![untitled](https://user-images.githubusercontent.com/7525178/51803507-24b6c380-2256-11e9-8c36-1e8b7fe8f146.jpg)

Som du ser på bildet, bruker jeg EasyList og uBlock Filters. AdGuard Base Filters har jeg prøvd uten hell.

**Comment by Odinist** [comment]
Takk. Det fungerte ved å legge til "vg.no##.appnexus". De to tilleggene du nevner er også interessante.

**Comment by DandelionSprout** [comment]
Da denne saken ser ut for meg til å være løst, og at jeg ikke har hørt noe som tilsier noe annet, så lukker jeg denne saken nå. 🙂
