### ISSUE TITLE
livehindustan.com

### ISSUE THREAD

**Issue by chirag127** [DandelionSprout/adfilt#273]
https://www.livehindustan.com/career/story-aktu-upcet-2021-counseling-schedule-released-for-engineering-pharmacy-management-colleges-4454142.html  has "leftover"
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133186810-7aca9410-8c99-48f1-a795-cd94bb64f8f1.png)
![image](https://user-images.githubusercontent.com/76880977/133186865-35e544a2-e085-48ab-a834-47fe114667e5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)+🛤️ Anti-Astrology List
</details><br/>

**Comment by DandelionSprout** [comment]
Seemingly fixed by the attached pull request.
