### ISSUE TITLE
avgle.com => false positive

### ISSUE THREAD

**Issue by S-a-l-a-d** [DandelionSprout/adfilt#284]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

This is a porn website but is listed in Alternate versions Anti-Malware List. The result is the website is blocked as a whole.

### Which adblocker(s) did you use when testing this?

DNS adblocking server(s)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt

### Which browser(s) did you use when testing this?

(Other)

**Comment by DandelionSprout** [comment]
I struggle to remember why I even added that website in the first place. I apparently listed it in the category for websites hosted by `192.243.59.12`, but SecurityTrails indicate that it's not the case. I'll remove it in a couple minute.
