### ISSUE TITLE
Persistent ads "Annonsørinnhold"

### ISSUE THREAD

**Issue by fosam** [DandelionSprout/adfilt#285]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hello Imre!

I tried to block the ads called "Annonsørinnhold" that appear in articles but when i refresh the page they re-appear.

[Example Article](https://e24.no/naeringsliv/i/lVv2a9/reagerer-paa-norwegian-innstramming-nei-nei-nei)

Do you have any tips on how to stop these kind of ads? they are so disturbing when reading an article.

Thanks!

### Add screenshots below if needed

This is the element i blocked:

<details>
<summary>Screenshot</summary>
<img src=https://user-images.githubusercontent.com/52612348/135531600-5894779f-b1f1-4a43-b08b-e22f1ff3c0ec.png>
</details>

### Add a screenshot of the extension's logger

<details>
<summary>Logger Screenshot</summary>
<img src=https://user-images.githubusercontent.com/52612348/135532500-5cb68ae5-66c3-4095-863b-011edb6acb90.png
>
</details>

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

`1.38.0`

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

```
Built-in:

uBlock filters 29,078 used out of 29,204

uBlock filters – Privacy 164 used out of 182


Ads:

EasyList 59,845 used out of 59,900


Privacy:

AdGuard Tracking Protection 23,014 used out of 23,627

EasyPrivacy 14,386 used out of 25,681


Custom:

🏔️ Dandelion Sprouts nordiske filtre for ryddigere nettsider (uten sporerhvitelisting) 2,233 used out of 2,233

Fanboy's Enhanced Tracking List 3,012 used out of 3,022
```

### Which browser(s) did you use when testing this?

Google Chrome

### Browser version(s)

`Version 94.0 (Official Build) (64-bit)`

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

`20H2`

**Comment by iam-py-test** [comment]
First, verify that My Filters is enabled under the filters panel
This happened to me once and that was the problem

Try backing up your settings and then resetting to defaults, and trying again

Then scan your computer with https://malwarebytes.com/adwcleaner

**Comment by DandelionSprout** [comment]
I can reproduce this with ease. A simple `e24.no##.teaser__preview` seems sufficient at first glance, I just need to test it for a couple minutes.

**Comment by fosam** [comment]
@DandelionSprout But do they re-appear when you refresh the page?

**Comment by DandelionSprout** [comment]
Not on my end, at least. iam-py-test may have been on to something when he suggested checking if "My Filters" was turned on, although a fix in Nordic Filters will be added in approx. 2min anyway.

**Comment by fosam** [comment]
Yes, i made sure `My Filters` was turned on.

I see that you added the fix, how do i update? uBlock doesn't show "update now" yet.

**Comment by DandelionSprout** [comment]
Generally speaking, you can click on the clock logo on the list's row in the uBO settings. This will trigger the update prompt's appearance.

**Comment by iam-py-test** [comment]
> 
> 
> Yes, i made sure `My Filters` was turned on.
> 
> I see that you added the fix, how do i update? uBlock doesn't show "update now" yet.

Wait a little while and click Purge Caches and then update now:
![image](https://user-images.githubusercontent.com/84232764/135535672-d0e6f365-5438-41c9-b18b-e0c66d4c3a54.png)

**Comment by fosam** [comment]
@DandelionSprout @iam-py-test 

Thank you very much guys! i usually don't play alot with uBlock hence my update question, now i forced an update and refreshed the page many times but the ad did not appear, so i think maybe i was blocking the wrong element, Thanks again 👍

**Comment by iam-py-test** [comment]
> 
> 
> @DandelionSprout @iam-py-test
> 
> Thank you very much guys! i usually don't play alot with uBlock hence my update question, now i forced an update and refreshed the page many times but the ad did not appear, so i think maybe i was blocking the wrong element, Thanks again 👍

Glad we could help
