### ISSUE TITLE
Scammers 

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#287]
I visited a YouTube typo-squatt in a VM, and this was what happened:
![image](https://user-images.githubusercontent.com/84232764/135685234-42cb6776-9928-473f-a4be-bdb584e896ae.png)
![image](https://user-images.githubusercontent.com/84232764/135685249-7a09e298-92d5-4299-a724-081778191378.png)
![image](https://user-images.githubusercontent.com/84232764/135685262-b4a2020d-76a8-4bb4-b489-677cc17e3d73.png)
I don't think there is a point of showing scan results of the VM
Full redirect urls (I did remove the legit McAfee website it redirected me to at the end, as it made a ton of requests and none of them were relevant): [redirect_urls_1.txt](https://github.com/DandelionSprout/adfilt/files/7270116/redirect_urls_1.txt)
 Domains: [redirect_domains_1.txt](https://github.com/DandelionSprout/adfilt/files/7270138/redirect_domains_1.txt) (Updated as jQuery is not a scam)

My guess is that these scammers earn some kind of _affiliate commission_ from McAfee by getting people to go to McAfee's website. I wish there was a way to alert McAfee so they can shutdown these scammers. I bet they aren't happy (not a McAfee user)

**Comment by DandelionSprout** [comment]
`dotomi` is already in several major lists, but I'll add the other 8 real quick.

**Comment by iam-py-test** [comment]
Ok. I didn't filter those at all apart from removing legit and redundant domains
