### ISSUE TITLE
Can't update filter in MS Edge + Ublock Origin.

### ISSUE THREAD

**Issue by seba2282** [DandelionSprout/adfilt#3]
Hello. I cań't update this filter. I have orange triangle and symbol "error connection". 
![bez tytulu](https://user-images.githubusercontent.com/16944478/39099222-2905e7ec-4677-11e8-9332-9bcf1e5aeced.png)
Can Help?

**Comment by DandelionSprout** [comment]
Unfortunately I don't find myself able to help or test much on this, since I myself have had filter list problems with Edge+uBO on multiple computers, in which I haven't been able to use _any_ lists that weren't on EasyList's servers... 😞

Quick questions:
• Has that list been properly downloaded at any previous point in time?
• If you're able to test on another browser (presuming that you're not on a school laptop or anything like that), can the list be downloaded there? Just to see if it works there?
• If you open uBO's log function, is the text "?_=211729" being added to end of the connection error message?

**Comment by seba2282** [comment]
Ad.1 I see your filter few days. I used long time Adguard. If back to UBO and tried updade this filter, all time error update.
Ad.2 i have updated your filter example in Firefox Android + UBO.
Ad.3 Error number 211731

**Comment by DandelionSprout** [comment]
Ah, okay, thanks for the answers.

Edge's F12 console didn't help in my digging, but you could try to report the issue to https://github.com/nikrolls/uBlock-Edge, describing it as a list download issue. Just make sure to provide all the information that their issue template asks you to write, or else they likely won't consider your issue to be a legit one.

**Comment by seba2282** [comment]
Ok. I tried report it.

**Comment by DandelionSprout** [comment]
Does the list load any better after you've installed Windows 10's _April 2018 Update_ update? If not, then I'm unfortunately stumped and will have to close this issue, since I'm not getting anywhere with it.

And also, I took a look at the report you wrote to Nik Rolls, and I feel fairly certain that it doesn't have anywhere nearly enough info for him to look into it (e.g. browser version, OS version, etc.). He doesn't seem to want to invest much time into the Edge version of uBlock Origin anyway, so I suppose it doesn't make that much of a difference.

**Comment by seba2282** [comment]
Maybe it is stupid but UBO is hmmm... Doesn't work perfect in MSEdge, so I changed my Adblocker on Adguard. People from Adguard Team work with great with different people. I don't know, have you filter for Adguard? :)

**Comment by DandelionSprout** [comment]
While I haven't yet decided to work with Adguard's team, I am 90% certain that my filter lists should work with Adguard. At least those versions of Adguard that have "Add custom list" or "Import list" or similar functions. 🙂 

For the Norwegian list that you've been struggling with, paste the following URL into it:

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ExperimentalNorwegianList.txt

**Comment by seba2282** [comment]
Ok. I will test if I will turn my PC.

**Comment by DandelionSprout** [comment]
I'll choose to mark this issue as _Closed_, since it's not an issue for you anymore, as well as that the issue was too hard to fix outright. Just so you know that I consider this situation to have been resolved unless I hear otherwise.

**Comment by krystian3w** [comment]
Maybe overload uBO with activate all regional lists.

**Comment by seba2282** [comment]
In Nano Adblocker have the same problem. @DandelionSprout autor NANO said, I should write to you for fix. Look on this screen. Can you fix filter for NanoAdblocker MS Edge? 
![norske filter](https://user-images.githubusercontent.com/16944478/40556549-62d3db4c-604d-11e8-8230-fb4d24c08a4f.png)

**Comment by seba2282** [comment]
Both links don't work. Look on it: 
![norske](https://user-images.githubusercontent.com/16944478/40560704-1ded26a6-605b-11e8-921c-875dd0bd4836.png)

**Comment by DandelionSprout** [comment]
Hmm..........

Are you able to open and view the above TXT links on your PC? Just so we can be certain that they aren't blocked on your PC or anything like that?

**Comment by seba2282** [comment]
I can open, but I see clear site ready for write rules. Look: 
![norsk](https://user-images.githubusercontent.com/16944478/40561444-9914b5f4-605d-11e8-8358-1821bea9d7f2.png)
 The same second link and integrate filter in Nano Adblocker

**Comment by DandelionSprout** [comment]
No, I mean, can you open its GitHub link? NOT the uBlock link. Click this button and see what happens: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt.

**Comment by seba2282** [comment]
I see all rules with sites.

**Comment by DandelionSprout** [comment]
Ah, okay. In that case I'm actually stumped. I give up. I have no idea what the problem could be, and have no ability to figure out either. Sorry.

**Comment by seba2282** [comment]
Autor Nano Adblocker hasn't any problem... I have… I don't know why...

**Comment by DandelionSprout** [comment]
Things to try out, if it hasn't been done already:

• Trying on other PCs.
• Trying on other networks.
• Trying while on Tor or a VPN to assure that it's not an all-of-Poland problem.

But by now I doubt that we'd get all that much closer to a solution. I've essentially given up on this.

**Comment by seba2282** [comment]
Ok.

**Comment by seba2282** [comment]
First and second - my brother in laptop the same problem. Third - I don't know. I don't use and my  brothers tors or vpns.

**Comment by seba2282** [comment]
Any suggest?

**Comment by DandelionSprout** [comment]
Which part of "I give up" is it that you don't understand?

Have you tried to do it while on a LAN or on your school's Wi-Fi?

**Comment by seba2282** [comment]
In my network lan, Ethernet, wifi and without home wifi and lan Ethernet in my friend house. I have the same problem. Can you try use vpn and look on my region? I see penguin any problem, you any problem... But I have still problem and norske filter (list sites) not load 0/0 and if I cliick on name filter, show me clear site.
