### ISSUE TITLE
prestashop.com

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#31]
`https://www.prestashop.com/forums/topic/947407-prestashop-1750-is-available/`

>> ###  Create an account or sign in to comment
>
> You need to be a member in order to leave a comment

![obraz](https://user-images.githubusercontent.com/35370833/53516432-99d31e00-3acc-11e9-92ca-456af96ace06.png) |
--- |

###### Cross blocker:

`prestashop.com#?#.cTopicPostArea:-abp-has(> div > .cGuestTeaser)`

badly generic for more forums:

`##.cTopicPostArea > div > .cGuestTeaser`

###### uBO only:

`prestashop.com##.cGuestTeaser:xpath(../..)`

**Comment by DandelionSprout** [comment]
Looks good enough to me, and the entry has now been added.

If you stumble across any other forums that use the `.cTopicPostArea` format, give me a headsup and I'll look into generic entries for them.

**Comment by krystian3w** [comment]
PS: `.cTopicPostArea` must have "`:-abp-has(> div > .cGuestTeaser)`" / "` > div > .cGuestTeaser`" to no cut for logged users option "`quick answer`" after logon.
