### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#32]
> ### You are not using a YouTube account
> Log in to like the video, leave a comment or subscribe to the channel.
>
> <kbd>Reject</kbd>, <kbd>log in</kbd>

![obraz](https://user-images.githubusercontent.com/35370833/53825772-61718b00-3f77-11e9-87dd-b8df72249cee.png) |
--- |

Sorry for no better i18n (English / Norsk)

[YouTube_files.zip](https://github.com/DandelionSprout/adfilt/files/2932137/YouTube_files.zip)

https://gist.githubusercontent.com/krystian3w/877f7d3faee61ca07368306c5fe61673/raw/7768da5529b086831c95fe3e60f7f334fd46a85d/mainpage.html

**Comment by krystian3w** [comment]
```
youtube.com#?#paper-dialog.ytd-popup-container[role="dialog"][style]:-abp-has(a[class][href^="https://accounts.google.com/ServiceLogin?service=youtube"])
```

**Comment by DandelionSprout** [comment]
This is the first time I've ever seen local HTML versions of a webpage be used for this purpose, and I congratulate you for coming up with such an idea.

Does `youtube.com#?#paper-dialog:-abp-has(ytd-mealbar-promo-renderer)` work as intended for you? Because extensions don't seem to work well on local HTML files, I can't truly test on my own if an entry works or not.

**Comment by DandelionSprout** [comment]
I do see your suggestion above, but it seems very windy and long, unless there's some good reasons for it to be that much long.

**Comment by krystian3w** [comment]
Also works:

![obraz](https://user-images.githubusercontent.com/35370833/53829726-1197c180-3f81-11e9-9267-7c571b1d0749.png)

**Comment by DandelionSprout** [comment]
That settles the deal, then. 😎 

This will be added to not only *Browse Websites Without Logging In*, but also to *YouTube: Even More Pure Viewing Experience*.

**Comment by krystian3w** [comment]
Hello I found this on mobile:

I cannot zip...

**Comment by krystian3w** [comment]
![Screenshot_2019-04-14-02-52-10](https://user-images.githubusercontent.com/35370833/56086901-89022000-5e60-11e9-94cb-e9ad3fabf82b.png) | ![Screenshot_2019-04-14-02-52-16](https://user-images.githubusercontent.com/35370833/56086903-97503c00-5e60-11e9-9e60-0ec04994fda1.png)
--- | ---

**Comment by krystian3w** [comment]
AdGuard addon generated filter:

[rules.txt](https://github.com/DandelionSprout/adfilt/files/3076900/rules.txt)

**Comment by krystian3w** [comment]
filter now cut privacy policy:

![obraz](https://user-images.githubusercontent.com/35370833/59793496-028e1280-92d7-11e9-9e21-0bb65e62bff8.png)

`youtube.com#?#paper-dialog:-abp-has(ytd-mealbar-promo-renderer)` - "bad".
