### ISSUE TITLE
community.spiceworks.com - fake annoyance login pop-ups

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#324]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://community.spiceworks.com/topic/336962-changing-time-server-w32tm-resync-rediscover-access-is-denied-0x80070005`

### Describe the issue

Pop-up are back after  "3-rd" visit at page (more than two): https://github.com/uBlockOrigin/uAssets/issues/7550

Reproduction is still hard, becasue needed is generate count marked at visit "3-rd".

After while time should be prompt new version  at "3-rd" visit.

```js

  var SignupTypes = {
    default:        'default',
    fromPhoto:      'default from photo modal',
    fromNavbar:     'default from navbar',
    fromPanel:      'default from message panel',
    fromFooter:     'default from footer',
    fromRepeatVisit:'Default from 3 visit modal',
    photoModalDelay: '25',
    repeatVisitModalEnabled: false,
    joinFooterEnabled: true,
    photoModalEnabled: true,
    marketingPage: false,
    connectProduct: 1,
  };
```

```js
showRepeatVisitModal: function() {
    JoinAltModal.delayedShowAltJoinModal('repeat-visit', 6000, {}, JoinAltModal.setRepeatVisitCookie);
  },
```

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/140218547-d1f51cfe-6828-4b91-8905-f24dc94947fa.png)

have locked scroll on Full HD monitor but body was longer than 1080px.

### uBlock Origin version

1.38.7b12

### Browser name and version

Firefox 94

### Settings

- Enabled: uBo Annoyances

### Notes

Oldie "uBo Annoyances" filters still needed, because page use both pop-ups and both have locked scroll.

<a href="https://github.com/uBlockOrigin/uAssets/blob/7f79636caf436c6e53f7d446ba906d66263186ff/filters/annoyances.txt#L3929-L3932" title="https://github.com/uBlockOrigin/uAssets/blob/7f79636caf436c6e53f7d446ba906d66263186ff/filters/annoyances.txt#L3929-L3932">

> 
> ```css
> ! https://github.com/uBlockOrigin/uAssets/issues/7550
> community.spiceworks.com##.zd-privacy-content
> community.spiceworks.com##.join-login-wrapper.join-login-alt--six-second[data-alt-modal]
> community.spiceworks.com##.sui-u-no-scroll:style(overflow:auto !important;)
> ```
> 

</a>

Addition can be: "`repeat-visit`"

```css
community.spiceworks.com##.join-login-wrapper.join-login-alt--repeat-visit[data-alt-modal]
```

I no tested `cookie-remove` named by `visit_count` with value "3"  or stop it "set-timeout" (~6000 ms).

**Comment by krystian3w** [comment]
uAssets closed without wrote arguments by **mapx-** hands.

**Comment by iam-py-test** [comment]
I can't see to reproduce

**Comment by krystian3w** [comment]
Because "looks a familliar" need analyse JS how works:

`visit_count`

Fastest is force edit cookie and refresh any topic on that page, but nobody prefere malform cookies to reproduce anything.

**Comment by iam-py-test** [comment]
> 
> 
> Because "looks a familliar" need analyse JS how works:
> 
> `visit_count`
> 
> Fastest is force edit cookie from value 0-2 or 4-99+ to **3** and refresh any topic on that page, but nobody prefere malform cookies to reproduce anything.

Yep, I can repro. Thanks

**Comment by iam-py-test** [comment]
Let me look into it

**Comment by DandelionSprout** [comment]
I had initial problems reproducing it an hour ago, sadly.

**Comment by iam-py-test** [comment]
> 
> 
> I had initial problems reproducing it an hour ago, sadly.

I have found a solution

**Comment by iam-py-test** [comment]
I found the following filters fix it:
```
community.spiceworks.com##+js(cookie-remover,visit_count)
community.spiceworks.com##+js(cookie-remover,last_visit)
community.spiceworks.com##.u-faded-in.is-shown.join-login_alt-modal.sui-u-fadeable.sui-modal_overlay.sui-opt-in
```

**Comment by krystian3w** [comment]
Last may break scroll for users with disable uBO annoyances if `cookie-remover` works too late on pages.

**Comment by iam-py-test** [comment]
> Last may break scroll for users with disabled uBO annoyances if `cookie-remover` works too late on pages.

Ok. You can just add the first two.
I think all thats needed is 1 but I figured that other cookie is useless anyway

**Comment by DandelionSprout** [comment]
With what seems to me to be a consensus on `community.spiceworks.com##+js(cookie-remover,visit_count)`, I'll add that one to *Browse Websites Without Logging In* now. Thanks to you all again.

**Comment by krystian3w** [comment]
Maybe better mark filter line as incompatible with `annoyances.txt` by uAssets uBO team, mapx- maybe reject your Issue with mass addition new filters.
