### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#33]
`https://www.investing.com/currencies/eur-pln-converter`
`https://fi.investing.com/currencies/eur-pln-converter`
`https://se.investing.com/currencies/eur-pln-converter`

...

`https://pl.investing.com/currencies/eur-pln-converter`

![obraz](https://user-images.githubusercontent.com/35370833/54080747-1fd63c80-42f7-11e9-8c48-d117f82b4698.png) |
--- |

**Comment by krystian3w** [comment]
investing.com###PromoteSignUpPopUp

or

investing.com##.signupWrap

**Comment by DandelionSprout** [comment]
The first submission seems good enough for me, and has now been added to *Browse Websites Without Logging In*. Thanks again.
