### ISSUE TITLE
$removeparam=ei causes the video in google drive cant play

### ISSUE THREAD

**Issue by nkoc6a15** [DandelionSprout/adfilt#342]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Here is the rule to fix that: @@||google.*/videoplayback$removeparam=ei,~xmlhttprequest. Can you update it into your filter?

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.38.6

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![ảnh](https://user-images.githubusercontent.com/85343481/141671402-a958b770-14c6-46cb-b562-cd87b77f70ee.png)

![ảnh](https://user-images.githubusercontent.com/85343481/141671421-fc29de82-6706-4e67-90af-02a45a5599b9.png)

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

94.0.1

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

21H1

**Comment by DandelionSprout** [comment]
Sure thing. Give me 5min.
