### ISSUE TITLE
Blocking custom cursors may break functionality

### ISSUE THREAD

**Issue by ameshkov** [DandelionSprout/adfilt#347]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Currently, you block custom cursors using this rule:
`.cur|$image` (Dandelion Sprout's Annoyances List)

For example, you're blocking standard Google Maps cursors like this one:
https://maps.gstatic.com/mapfiles/openhand_8_8.cur

It kind of hurts the functionality since it's unclear when you can drag the map or not.
Example: https://www.idealista.pt/en/comprar-casas/funchal/sao-pedro/mapa-google

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop version), AdGuard (for browsers)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Annoyances List

### Which browser(s) did you use when testing this?

Google Chrome

### Which OS(s) did you use when testing this?

macOS

**Comment by DandelionSprout** [comment]
I have occasionally been thinking about whitelisting Google Maps in that list, but was worried it could potentially be interpreted by super-hardcore security enthusiasts as that I was caving in to Google.

Though since I personally feel it should be whitelisted, I'll indeed do so now.
