### ISSUE TITLE
Github-repos for finn-no are blocked

### ISSUE THREAD

**Issue by datagutt** [DandelionSprout/adfilt#35]
## Describe the problem below this line as meticulously and detailed as possible:
I cant visit any repos under https://github.com/finn-no/.
This seems to be due to the anti-scam entries in your filter. In particular this line:
``
||*/finn-no/$document
``
Possibly add a whitelist for the github domain?

## Which adblocker(s) and version did you use when testing this?

- [X ] uBlock Origin

Other(s):

Version(s):

## Which filterlists did you use?

NOR, DNK, ISL: Dandelion Sprouts nordiske filtre
## Which browser(s) and version did you use?

Google Chrome 75.0.3766.2 
## (Optional) Which OS and version did you use?
- [X] Windows 10

**Comment by DandelionSprout** [comment]
Thanks for giving me a headsup about it. I was completely unaware that Finn.no even had a GitHub repo, as the entry had originally been solely intended for scam domain subpages that pretend to be Finn. Additionally, I only very recently managed to make anti-scam entries actually work, as it turned ouy that `$document` was in most cases required to be added to entries to make them show access warnings.

I've now hopefully added a fix for that (and for their Medium blog as well). If you were to find any other problems regarding Finn or anything else, don't hesitate to tell me about it.

**Comment by DandelionSprout** [comment]
As I've not heard of anything more about this in a couple of days, I'll assume that the fix went well and that this issue can be marked as closed for now.
