### ISSUE TITLE
Bing ads

### ISSUE THREAD

**Issue by Schanzation** [DandelionSprout/adfilt#36]
Using Edge Developer browser on Windows 10 Pro.
ublock origin 1.19.6

Getting ads in bing search results.
https://imgur.com/a/mtvjl18

**Comment by DandelionSprout** [comment]
Because Bing is an international website, I'll bring it up with [the *uBlock Filters* team](https://github.com/uBlockOrigin/uAssets) and possibly also the EasyList team. You can most likely expect a fix in the former guys' lists within a day or two.

**Comment by Schanzation** [comment]
Takk skal du ha!

**Comment by DandelionSprout** [comment]
Bare hyggelig. 🙂

**Comment by DandelionSprout** [comment]
Det tok litt tid før de fikk reprodusert problemet, da reklamer når man søkte på `nrk` kun dukket opp for norske brukere. Jeg ga dem etter hvert `nintendo switch` som et internasjonalt søkeeksempel i stedet, og dermed ser det ut til at EasyList skal få lagt til en fiks i sin liste innen 2 timer.

**Comment by DandelionSprout** [comment]
Hvis du har hastverk med å få blokkert reklamene i mellomtiden, kan du legge til `bing.com#?##b_results > li :-abp-has(span.b_aslcpy)` i «Mine filtre».
