### ISSUE TITLE
Remove r3.o.lencr.org

### ISSUE THREAD

**Issue by brknkfr** [DandelionSprout/adfilt#361]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

The domain lencr.org belongs to Letsencrypt and is used for OCSP verification, see https://letsencrypt.org/docs/lencr.org/.

The problem arised in the letsencrypt forums aswell: https://community.letsencrypt.org/t/r3-o-lencr-org-is-seen-as-malware/153205

There was probably once a malware with that name.

When r3.o.lencr.org is blocked, ssl ocsp verification doesn't work anymore.

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt

### Which browser(s) did you use when testing this?

(Other)

### Browser version(s)

NGINX webserver version 1.18.0

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Debian Bullseye 11.0

**Comment by iam-py-test** [comment]
I think this was my fault. 
I get these by looking at raw network logs, so it’s my fault for not verifying my domains
