### ISSUE TITLE
"Legitimate URL Shortener" vs "ClearURLs for uBo"

### ISSUE THREAD

**Issue by rubaboo** [DandelionSprout/adfilt#374]
What is the difference? Do you recommend adding both to uBO?

**Comment by DandelionSprout** [comment]
It's complicated. The former is made pretty much entirely from scratch, whereas the latter is a (mostly) direct conversion of the filters used by the ClearURLs extension.

From what I can tell, and have heard of from other users, it is feasible to use both lists at the same time.

**Comment by DandelionSprout** [comment]
With the question answered, and no words back from the OP after 4 days, I'll declare this a solved case. Comments will remain open.

**Comment by iam-py-test** [comment]
@DandelionSprout maybe we should pin this or at least add a better explanation
