### ISSUE TITLE
Your filter it's blocking the upload test in Speedtest.net

### ISSUE THREAD

**Issue by Minasti7** [DandelionSprout/adfilt#376]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

When this filter it's activated on my firefox browser (the latest version) it just block the upload during a test in speedtest.net

### Add screenshots below if needed

![Screenshot_1115](https://user-images.githubusercontent.com/61472697/142980356-ef7196d1-3441-4df9-977c-55aac4db853d.png)
![Screenshot_1117](https://user-images.githubusercontent.com/61472697/142980384-409daa24-be34-419d-8375-27c25a45e160.png)
![Screenshot_1113](https://user-images.githubusercontent.com/61472697/142980395-4bee5c1f-6acf-4e7a-8e1d-16501d695b2a.png)

### Add a screenshot of the extension's logger

![Screenshot_1118](https://user-images.githubusercontent.com/61472697/142980711-54555128-39a1-4ea8-9f84-5563c24431eb.png)

### Which adblocker(s) did you use when testing this?

AdGuard (for browsers)

### Adblocker version(s)

Versión 3.6.13

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Many of them but I write you because I confirmed was your list the one that it's causing the block, a block reported by users yesterday in the Adguard forum, altough I've found the root, and it' your extension

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

94.0.2

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

Windows 10 Pro 21h1

**Comment by DandelionSprout** [comment]
I seem to have found the problems: AdGuard's browser extensions seem to try to apply every single `$removeparam` rule to all `wss://` requests (which I can only presume is a bug), which for some reason only cause Speedtest to break when using Firefox.

**Comment by gwarser** [comment]
> I seem to have found the problems: AdGuard's browser extensions seem to try to apply every single `$removeparam` rule to all `wss://` requests (which I can only presume is a bug), which for some reason only cause Speedtest to break when using Firefox.

https://github.com/DandelionSprout/adfilt/commit/9488da6bca52e986c4f9383b8d219dcbea173906 also whitelists on uBO because `adguard_ext_firefox` is true here too, "for compatibility". Will something like this work:

```
!#if adguard
!#if adguard_ext_firefox
! https://github.com/DandelionSprout/adfilt/issues/376
@@|wss://$removeparam
!#endif
!#endif
```
?

**Comment by DandelionSprout** [comment]
Good question. I can just as well try it out.
