### ISSUE TITLE
123mc.dk

### ISSUE THREAD

**Issue by spirillen** [DandelionSprout/adfilt#378]
## Hvilke(n) regel/regler anmelder du?
`<!-- `text`-kodetekstfunksionen kan være nyttig, hvis du ikke ønsker at lave en link til webstedet; som regle ved et uheld. -->` 

Kommentar: Hvor i på norsk typisk bruger `j` inde i et ord, er dette for groft sagt 100 år siden skiftet på dansk til `i` som i `is`

```css
123mc.dk##.magacin-row-wrp
123mc.dk##.boxpadmarleft
123mc.dk##.nopadmarright
123mc.dk##.margintop20
123mc.dk##.wrp_magacin_search_results_bottom
```

## Hvilke ting blokerer, skjuler, eller fikser de(n)?

![image](https://user-images.githubusercontent.com/44526987/143034220-5b44a06f-e5be-459b-a745-c3776c8fcde1.png)
Og lignende

## Hvilke av mine lister sender du den/dem ind til? (Hvilke af mine lister ønsker du regle(n|erne) optaget i?)
Her kunne en liste være praktist, da jeg slet ikke kan overskue din mode at genere og administrerer dine lister.

## Hvilken adblokker og version brugte du da du skrev og testede regle(n|erne)?
- [x] uBlock Origin
- [ ] AdGuard (Betalt skrivebordsversion) `(=> s/skrivebordsversion/desktop version/g)`
- [ ] AdGuard (Webbrowser udvidelse) `Ingen bindestreg`
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (Udvidelsen)

Andre:

Reklameblok(~~er~~)er-version(er): => `s/Reklame/adblocker/g bloker version(er):`

## Hvilke filterlister brugte du? At ikke fortælle dette, vil føre til at sagen bliver midlertidigt lukket frem til dette bliver fortalt.
`<!-- Hvis du vil spare tid, kan du tage et skærmbillede af dine adBlocker listeindstillinger. -->`
- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Resource abuse
- EasyList
- EasyPrivacy
- Online Malicious URL Blocklist
- Peter Lowe’s Ad and tracking server list
- Spirillen's – Adblock Rules (https://mypdns.org/my-external-stuff/ublockorigin-rules/)

## (Valgfrit) Hvilke(n) webbrowser(e) og version(er) brugte du?
`<!-- Hvis du er i tvivl, se i *Om*-siden i  din webbrowser. -->`

- OS/version: Ubuntu 20.04.2
- Browser/version: Tor-Browser & FF latest stable from Ubuntu repo
- Adblock Extension/version: uBlock Origin 1.38.6

Something else, you should rename the template title to something danish...

`(Dansk) Listeregelsforslag` => `(Dansk) Blacklist forslag` | `(Dansk) Forslag til Blacklist`

Som vi tidligere har snakket om så er det engelseke domminerende i det danske IT navngivning/sprogbrug

Se også PR https://github.com/DandelionSprout/adfilt/pull/377

**Comment by iam-py-test** [comment]
Sorry, but I'm confused. Is this what you are taking about:
![image](https://user-images.githubusercontent.com/84232764/143061418-5985119a-acdd-4ceb-8fd0-77489a4aa802.png)
Because I'm not sure if this is an ad...

**Comment by spirillen** [comment]
It is ads to third party site `https://www.magacin.dk/motorcykler/test/test-ktm-890-adventure-r-eventyrcykel-med-hang-til-offroad/`

The second part of the script removes these
insurance / over taxed loans (200% pa)

![image](https://user-images.githubusercontent.com/44526987/143077777-1c252a85-aaee-4399-9129-3b51c204a4ca.png)

**Comment by iam-py-test** [comment]
Ah, thanks :)

**Comment by DandelionSprout** [comment]
>`hvis du ikke ønsker at lave en link til webstedet; som regle ved et uheld.`

Danish may only be my 5th language, but I still know that suggestion is flatout wrong, as it thinks "link = rule", when it's supposed to be "the link of the rule". Also I'm 100.0% sure nowadays it's `funktion` in Danish, not `funksion` (and admittedly not `funksjon` either).

>Hvis du er i tvivl, se i *Om*-siden i din webbrowser.

That one looks pretty good to me, and has been added by me to the Crowdin project now.

>(Webbrowser udvidelse) `Ingen bindestreg`

I'm more inclined to go with "Webbrowserudvidelse" after doublechecking with Google Translate (DeepL gave me the strange suggestion "udvidelse af webbrowser"). I know that unnecessary spacing is an epidemic in Norwegian, so I'm presuming it's mostly the same situation in Danish.

>bloker

DeepL gives me `blokker`, while Google Translate and `ordnet.dk` gives me `blokerer`. Had at least one of them gone with `bloker`, then I could've added that.
