### ISSUE TITLE
dba.dk

### ISSUE THREAD

**Issue by spirillen** [DandelionSprout/adfilt#379]
## Hvilke(n) regel/regler sender du ind?

`dba.dk##div[id="dbashopping-widget"]`

Reglen kan simplifiseres, men vælger denne noget mere præcise tilgang for at undgå problemer

## Hvilke ting blokerer, skjuler, eller fikser de(n)?
![image](https://user-images.githubusercontent.com/44526987/143048136-b969a3f4-99c9-4535-affb-f86fd501e6e5.png)

## Hvilken reklameblokkerer og version brugte du da du skrev og testet reglen(e)?
- [X] uBlock Origin
- [ ] AdGuard (Betalt skrivebordsversion)
- [ ] AdGuard (Webbrowser-udvidelse)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (Udvidelsen)

Andre:
Se https://github.com/DandelionSprout/adfilt/issues/378 for øvrig info

**Comment by iam-py-test** [comment]
I'm not fluent in danish, so please tell me if I made an error

**Comment by spirillen** [comment]
> I'm not fluent in danish, so please tell me if I made an error

You are doing it fine "DandelionSprout" :) Didn't knew you got a set of merge-keys to this repo

**Comment by iam-py-test** [comment]
> > I'm not fluent in danish, so please tell me if I made an error
> 
> You are doing it fine "DandelionSprout" :) Didn't knew you got a set of merge-keys to this repo

See https://github.com/DandelionSprout/adfilt/issues/264#issuecomment-913011956
I'm trying to help out with Nordic filters/Legit URL/DandelionSprout antimalware, so I figured I'd try to fix this issue

**Comment by spirillen** [comment]
I just never figured out where you origin from?

**Comment by iam-py-test** [comment]
> I just never figured out where you origin from?

Not sure what you mean...

**Comment by spirillen** [comment]
What is your native tung/language? german polish norsk soumi russian??

**Comment by iam-py-test** [comment]
> What is your native tung/language? german polish norsk soumi russian??

English. I live & grew up in the US.
What about you?

**Comment by spirillen** [comment]
Pretty mush all native Denmark but have traveled most of europe for years so have picked some words here and there. We can walk around thirsty to i can get two beers :beers:  in most languages :laughing: and grab some food.
