### ISSUE TITLE
Tv2.no partitesten

### ISSUE THREAD

**Issue by Schanzation** [DandelionSprout/adfilt#38]
Hei! 

Etter jeg har fylt ut alle svarene mine på denne partitesten så får jeg ikke opp resultatet før jeg skrur av adblockeren.

https://www.tv2.no/politikk/valg/partitesten/?segment=2019

Bruker Windows 10, uBlock Origin 1.20.0 og FF 67.0.4

**Comment by DandelionSprout** [comment]
Såfremt det er mulig, ville jeg ha brukt uBlock Origin sin loggføringsfunksjon i mye større grad til å sile ned mulige årsaker, og liste opp i det minste et skjermklipp av hvilke lister du bruker i hver saksrapport.
![image](https://user-images.githubusercontent.com/22780683/59964975-a14d8580-9508-11e9-8d31-ce358cc63a12.png)
For når jeg da ikke umiddelbart klarer å reprodusere problemet, er det da såpass tidkrevende og vanskelig å identifisere uten slik informasjon, at jeg dessverre ikke ser tilstrekkelig grunnlag for å nøste opp i slike saker.

**Comment by DandelionSprout** [comment]
Det er også verdt å nevne at det langt ifra alltid er mine lister som er problemet i slike saker (Jeg vet spesielt at EasyPrivacy, en liste som jeg ikke bruker, har skapt problemer med TV2 tidligere), så da er det ekstra viktig å oppgi logg- og liste-informasjon, sånn at man også kan vite hvilke listemakere man primært bør henvende seg til.

**Comment by Schanzation** [comment]
Beklager.

Ja, prøvde med NOR filter og EasyPrivacy slått av, da gikk det bra. Også prøvde jeg med dem påslått og tilatte alt. Lurer på om det er adform.net , facebook.net eller doubleclick.net som gjør det.

https://imgur.com/a/kf6eJup

**Comment by DandelionSprout** [comment]
Da jeg mente logg-informasjon, mente jeg i hovedsak å klikke på den knappen jeg hadde merket i brun-oransje i bildet, som da får opp en liste som ser slik ut (Skjermklipp tatt på min PC i starten av undersøkelsen):
![image](https://user-images.githubusercontent.com/22780683/59973844-03f45f00-95a5-11e9-9307-2cf1dd250f15.png)

Den menyen som du lastet opp et Imgur-skjermklipp av, er egentlig den såkalte "dynamiske" filtermenyen til uBO. Det var/er et av gorhill sine kjæleprosjekter (og tett knyttet opp mot uMatrix), og skal sørge for en rask måte å blokkere/tillate hele servere på.

Du har et poeng i at også jeg tror at `adform.net` kan være en faktor i dette, men loggen ville i såfall vist hvilken `adform.net`-fil som hadde forårsaket problemer når du kom til slutten av undersøkelsen.

**Comment by Schanzation** [comment]
Ok skal prøve å huske på til neste gang. Skal jeg bare kopiere alt da og lim inn her?

Skulle til å gjøre det nå, men i dag virket det uten problemer av en eller annen grunn.

**Comment by DandelionSprout** [comment]
I utgangspunktet er det bare nødvendig å lime inn et skjermklipp av loggen i bildeformat, heldigvis.

Dersom det konsist fungerer riktig i dag, er det forsåvidt også mulig at problemet lå hos TV2, og at de i så fall har rettet opp i det siden i går. 🙂
