### ISSUE TITLE
I need help with your lists

### ISSUE THREAD

**Issue by themifuru** [DandelionSprout/adfilt#389]
Hi. I need help with your lists. I use AdGuard with a uBlock Origin and when I open your repository I don’t understand how to use your lists. Too much information and difficult to perceive. Can you advise what is better to add to the block lists and what to add to the AdGuard blocking?

**Comment by iam-py-test** [comment]
First things first, please do not use two ad-blockers/content-blockers together. Both uBlock Origin and AdGuard (the browser extension) are capable of standing on their own, in my experience. If you are using the desktop app or AdGuard Home, then that is probably ok.

Sadly, there is no central directory which can help you decide which lists you should use. I personally use [Nordic filters](https://github.com/DandelionSprout/adfilt/blob/master/NorwegianList.txt) (this one isn't really relevant for people outside Norway, I use it so I can reproduce issues), [DandelionSprout's antimalware list](https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt) (blocks known malicious websites), and [Actually Legitimate URL Shortener](https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt) (makes urls shorter and removes some tracking), but that doesn't mean you should :)

If you aren't from Norway, then I think that [Actually Legitimate URL Shortener](https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt) is probably the one which would add the most to the blocking capabilities of uBlock Origin/AdGuard. 
[DandelionSprout's antimalware list](https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt) is also worth it if you want to add to the default malware/scam protection available in your browser and adblocker (uBlock Origin comes with uBlock badware and URLHaus, AdGuard comes with AdGuard safe browsing).

If you have any questions, feel free to post a comment here or on #63, and @DandelionSprout or I will try to respond. Just be aware that I may not be able to respond quickly and will be on vacation Thursday through Sunday.

**Comment by themifuru** [comment]
> First things first, please do not use two ad-blockers/content-blockers together. Both uBlock Origin and AdGuard (the browser extension) are capable of standing on their own, in my experience. If you are using the desktop app or AdGuard Home, then that is probably ok.

Hi! I don't use two blockers. I use a complex of a blocker at the DNS level and a blocker in the browser.

> Sadly, there is no central directory which can help you decide which lists you should use. I personally use Nordic filters (this one isn't really relevant for people outside Norway, I use it so I can reproduce issues), DandelionSprout's antimalware list (blocks known malicious websites), and Actually Legitimate URL Shortener (makes urls shorter and removes some tracking), but that doesn't mean you should :)

As for my question, I would like to clarify for the general lists. For example, to make structuring by type "this blocker for DNS", "this blocker for the browser".

> Sadly, there is no central directory which can help you decide which lists you should use. I personally use Nordic filters (this one isn't really relevant for people outside Norway, I use it so I can reproduce issues), DandelionSprout's antimalware list (blocks known malicious websites), and Actually Legitimate URL Shortener (makes urls shorter and removes some tracking), but that doesn't mean you should :)

> If you have any questions, feel free to post a comment here or on #63, and @DandelionSprout or I will try to respond. Just be aware that I may not be able to respond quickly and will be on vacation Thursday through Sunday.

Thanks for your recomendation and work for people.

**Comment by iam-py-test** [comment]
> Hi! I don't use two blockers. I use a complex of a blocker at the DNS level and a blocker in the browser.

Ok, then that is fine. I just wanted to make sure
> As for my question, I would like to clarify for the general lists. For example, to make structuring by type "this blocker for DNS", "this blocker for the browser".

Hopefully some of that can be implemented in #391.
To my knowledge, the following lists can be used in a DNS blocker:
- [DandelionSprout's Antimalware list](https://github.com/DandelionSprout/adfilt/blob/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt)
- [Nordic filters](https://github.com/DandelionSprout/adfilt/blob/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersAdGuardHome.txt)

Additionally, these lists work well in your browser but do not work in AdGuard home:
- [Legit URL Shortener](https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt)

This is far from a complete list, there are certainly more that aren't listed here

> Thanks for your recomendation and work for people.

Your welcome.

**Comment by DandelionSprout** [comment]
I've discouraged subscribing to lists straight from this GitHub repo for a couple years now. Instead I recommend going to https://filterlists.com/, settings "Maintainers" to "Imre Kristoffer Eilertsen", and picking the lists that fit your desired tags.

**Comment by iam-py-test** [comment]
> I've discouraged subscribing to lists straight from this GitHub repo for a couple years now. Instead I recommend going to https://filterlists.com/, settings "Maintainers" to "Imre Kristoffer Eilertsen", and picking the lists that fit your desired tags.

...however, (in my opinion) this adds another layer of complexity for us and users. Which is the point of #391

**Comment by iam-py-test** [comment]
Closing this as the OP has not posted anything new.
