### ISSUE TITLE
tv2 videoer

### ISSUE THREAD

**Issue by Schanzation** [DandelionSprout/adfilt#39]
Hei! Usikker hvor jeg skal henvende meg, men med ublock origin aktivert spilles ikke videoer på tv2.no. Avspilleren er bare helt svart. Mener du ba meg post screenshot av events sist gang. 

https://imgur.com/a/dD7FASy

Her f.eks: https://www.tv2.no/sport/10727477/

**Comment by DandelionSprout** [comment]
Siden TV2 er en helnorsk side, har du kommet til rett sted denne gangen.

Jeg sliter med å reprodusere problemet umiddelbart; så har du mulighet til å snevre inn loggskjermklippet, ved å sveve over *Filtrer logginnhold* og velge `Tillatt` og `Blokkert`? Slik som i dette bildet: 
![image](https://user-images.githubusercontent.com/22780683/61337600-66541e80-a836-11e9-90f1-5b63200155f7.png)

I tillegg trenger jeg som vanlig en oppfriskning i hvilke lister du bruker. Det er liksom noe som er ment å nevnes i hver enkel saksrapport på GitHub, for å unngå å behøve å lete gjennom tidligere rapporter.

**Comment by Schanzation** [comment]
Funker for meg i Brave, men ikke Firefox. Her

https://imgur.com/a/qXUd0OM

**Comment by DandelionSprout** [comment]
Når jeg nå har gått igjennom de 5 sakene du har rapportert inn til meg, så slår det meg at du aldri har fortalt eller vist meg hvilke lister du bruker. Og i Imgur-skjermklippet kan jeg se at det brukes flere uvanlige lister (f.eks. *Rickroll Link Identifier*), og at jeg dermed ikke har noen anelse om hvor loggføringsresultatene kommer fra eller hvilke lister jeg bør lete i.

Så jeg har bestemt meg for å gjøre det obligatorisk fra og med nå å fortelle meg hvilke lister man bruker i hver saksrapport, ellers blir det umiddelbart lukket. Om det er tekstkopiering eller skjermklipp går for det samme.

**Comment by Schanzation** [comment]
Okei. Her er ihvertfall filtrene jeg bruker. Alle custom filters er dine utenom den nederste.

3 bilder - https://imgur.com/a/kRkbxrJ

**Comment by DandelionSprout** [comment]
Tusen takk, da skal jeg få gjenåpnet denne saken og tatt en ny og bedre titt på saken.

**Comment by DandelionSprout** [comment]
Har du mulighet til å teste om det hjelper på med `||damoh.tv2.no^$media,redirect=noopmp3-0.1s,domain=tv2.no,badfilter` limt inn i *Mine filtre*-fanen?

**Comment by Schanzation** [comment]
||damoh.tv2.no^$media,redirect=noopmp3-0.1s,domain=tv2.no,badfilter

Videoen spilles av når jeg brukte den, men anonsene vises også.

**Comment by Schanzation** [comment]
Men det går fint. Trenger ikke tulle bort mer tid på det her. Det er sikkert jeg som gjør noe feil. Instillinger jeg har i Firefox ellernoe som gjør at det ikke virker. Bare tenkte det kanskje hadde noe med uBlock Origin å gjøre fordi videoen spilles av med adblockeren avslått. Med reklame da.
