### ISSUE TITLE
New ad server: sannsyn.com

### ISSUE THREAD

**Issue by davidhedlund** [DandelionSprout/adfilt#4]
Can you add this filter:
> ||sannsyn.com^$third-party

**Comment by DandelionSprout** [comment]
I find it to be pretty weird that you chose to repurpose this report to be about Sannsyn but _without_ reopening the issue.

If you believe that the issue is still something that I should deal with, would you be able to reopen it? Just so I can be sure that it's still relevant (or not)?

**Comment by DandelionSprout** [comment]
Ah, okay. Now that you reopened it, I decided to add Sannsyn now.

I have however changed the active URL for the Norwegian list, so in order to see the changes take effect you'll need to use https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt instead of the old link.

**Comment by davidhedlund** [comment]
> I have however changed the active URL for the Norwegian list, so in order to see the changes take effect you'll need to use https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt instead of the old link.

Thank you.
