### ISSUE TITLE
Is `á la` a correct word?

### ISSUE THREAD

**Issue by imba-tjd** [DandelionSprout/adfilt#40]
The wiktionary only has a `à la` entry.

<sub>I'm not sure because my native language is Chinese<sub>

**Comment by DandelionSprout** [comment]
Now that you mention it, I myself only realised like two weeks ago that it really was with an À, and that I had been writing it wrong for the past 15 years. I'll correct it in my repo pretty much now.

As for the term itself in any spelling, I was of the belief it was an Italian loanword that is common in large parts of Europe thanks to spaghetti-eating movie scenes and grocery-store pasta meals, but now I need to ask some Italian friends of mine how they prefer to spell or use it (if at all), and possibly add Italian definitions of it to Wiktionary myself if needed.

**Comment by BoneTone** [comment]
@DandelionSprout it is of French origin actually, as in à la mode de -- in the style of.  I learned it from desserts with ice cream top.  Italian and French being so closely related it would not be surprising if it has similar usage in Italian.  I never paid attention to the diacritic before, and most likely have been writing the wrong way as well, now I know.
