### ISSUE TITLE
Add removal of .amp in url

### ISSUE THREAD

**Issue by ph00lt0** [DandelionSprout/adfilt#408]
## Which entry/entries are you submitting?
Websites like https://www.getsurrey.co.uk/news/surrey-news/surrey-primary-school-says-students-22287166.amp use .amp to load the amp version of website

## Which things do they block, hide, or unbreak?
Stop using of amp. 

## Which of my lists are you submitting it to?
Actually Legitimate URL Shortener Tool

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Adblocker version: 1.39.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
Actually Legitimate URL Shortener Tool

## (Optional) Which browser(s) and version did you use?
Firefox

**Comment by iam-py-test** [comment]
@ph00lt0  Actually Legitimate URL Shortener Tool not can remove the _.amp_, as that would require functions which do not exist in uBlock Origin

**Comment by ph00lt0** [comment]
@iam-py-test ah sorry i see now that you can only remove params. Hope directory support will be added at some point.
