### ISSUE TITLE
dmi.dk

### ISSUE THREAD

**Issue by spirillen** [DandelionSprout/adfilt#41]
The issues is ads on `dmi.dk`
Futher descriptions can be found one of these places

https://github.com/uBlockOrigin/uAssets/issues/6256
or   
https://gitlab.com/AnonymousPoster/ublockorigin-rules/issues/2

**Comment by DandelionSprout** [comment]
Thanks for the headsup. I've added two optimalised entries to the list now. 🙂

**Comment by llacb47** [comment]
The word is optimized/optimised FYI. :)

**Comment by DandelionSprout** [comment]
The rules of the English language are utter nonsense at times, so it does happen that I have to guess at how to bend some words, unfortunately. 😅

**Comment by spirillen** [comment]
> The word is optimized/optimised FYI. :)

I got the point anyway :yum: We are not all us_EN encoded
