### ISSUE TITLE
Wildcard domain removal

### ISSUE THREAD

**Issue by joshpangell** [DandelionSprout/adfilt#420]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

I am the CTO of the website building platform Cargo → https://cargo.site. It seems that our root domain and all wildcard domains (*.cargo.site) have been added to your list. Digging through the lists, it appears that the culprit was a site called postenpakke.cargo.site. They were, indeed, doing a spammy redirection. We've banned this user and taken down their website. 

Can you please remove the wildcard restriction on our domain? We have many customers that are complaining that their legitimate websites are not loading because of this block.

Thank you very much

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop version)

### Adblocker version(s)

Our customers are using the Adblock. I am not sure which ones. 

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Anti-Malware List.txt:
LegitimateURLShortener.txt:
NorwegianList.txt:
AdGuard Home Compilation List/AdGuardHomeCompilationList.txt:
Alternate versions Anti-Malware List/AntiMalwareABP.txt:
Alternate versions Anti-Malware List/AntiMalwareAdGuard.txt:
Alternate versions Anti-Malware List/AntiMalwareAdGuardHome.txt:
Alternate versions Anti-Malware List/AntiMalwareDomains.txt:
Alternate versions Anti-Malware List/AntiMalwareHosts.txt:
Alternate versions Anti-Malware List/AntiMalwareTPL.tpl:
NorwegianExperimentalList alternate versions/AdawayHosts:
NorwegianExperimentalList alternate versions/DandelionSproutsNorskeFiltre.tpl:
NorwegianExperimentalList alternate versions/DandelionSproutsNorskeFiltreDomains.txt:
NorwegianExperimentalList alternate versions/LittleSnitchNorwegianList.lsrules:
NorwegianExperimentalList alternate versions/NordicFilters-uBOLegacy.txt:
NorwegianExperimentalList alternate versions/NordicFiltersABP-Inclusion.txt:
NorwegianExperimentalList alternate versions/NordicFiltersABP.txt:
NorwegianExperimentalList alternate versions/NordicFiltersAdGuard.txt:
NorwegianExperimentalList alternate versions/NordicFiltersAdGuardHome.txt:
NorwegianExperimentalList alternate versions/NordicFiltersDnsmasq.conf:
NorwegianExperimentalList alternate versions/NordicFiltersForMinerBlock.txt:
NorwegianExperimentalList alternate versions/NordicFiltersHostsDeny.deny:
NorwegianExperimentalList alternate versions/NordicFiltersHostsIPv6.txt:
NorwegianExperimentalList alternate versions/NordicFiltersPiHole.txt:
NorwegianExperimentalList alternate versions/NordicFiltersPrivacy.txt:
NorwegianExperimentalList alternate versions/NordicFiltersPrivoxy.action:
NorwegianExperimentalList alternate versions/NordicFiltersRPZ.txt:
NorwegianExperimentalList alternate versions/NordicFiltersSocks5.list:
NorwegianExperimentalList alternate versions/NordicFiltersUnbound.conf:
Dandelion Sprout's Anti-Malware List.txt:
NorwegianList.txt:
Alternate versions Anti-Malware List/AntiMalwareABP.txt:
Alternate versions Anti-Malware List/AntiMalwareAdGuard.txt:
Alternate versions Anti-Malware List/AntiMalwareAdGuardHome.txt:
Alternate versions Anti-Malware List/AntiMalwareDomains.txt:
Alternate versions Anti-Malware List/AntiMalwareHosts.txt:
Alternate versions Anti-Malware List/AntiMalwareTPL.tpl:
NorwegianExperimentalList alternate versions/AdawayHosts:
NorwegianExperimentalList alternate versions/DandelionSproutsNorskeFiltre.tpl:
NorwegianExperimentalList alternate versions/DandelionSproutsNorskeFiltreDomains.txt:
NorwegianExperimentalList alternate versions/LittleSnitchNorwegianList.lsrules:
NorwegianExperimentalList alternate versions/NordicFilters-uBOLegacy.txt:
NorwegianExperimentalList alternate versions/NordicFiltersABP-Inclusion.txt:
NorwegianExperimentalList alternate versions/NordicFiltersABP.txt:
NorwegianExperimentalList alternate versions/NordicFiltersAdGuard.txt:
NorwegianExperimentalList alternate versions/NordicFiltersAdGuardHome.txt:
NorwegianExperimentalList alternate versions/NordicFiltersDnsmasq.conf:
NorwegianExperimentalList alternate versions/NordicFiltersForMinerBlock.txt:
NorwegianExperimentalList alternate versions/NordicFiltersHostsDeny.deny:
NorwegianExperimentalList alternate versions/NordicFiltersHostsIPv6.txt:
NorwegianExperimentalList alternate versions/NordicFiltersPiHole.txt:
NorwegianExperimentalList alternate versions/NordicFiltersPrivacy.txt:
NorwegianExperimentalList alternate versions/NordicFiltersPrivoxy.action:
NorwegianExperimentalList alternate versions/NordicFiltersRPZ.txt:
NorwegianExperimentalList alternate versions/NordicFiltersSocks5.list:
NorwegianExperimentalList alternate versions/NordicFiltersUnbound.conf:

### Which browser(s) did you use when testing this?

Google Chrome

### OS version(s)

Mac

**Comment by iam-py-test** [comment]
> Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Why are you using every format of those lists?

**Comment by DandelionSprout** [comment]
Ah, okay. Good to know that the subdomain was banned on the server-side (which from my loose experience is pretty rare for website builders and link shorteners to do). I'll get it fixed within 20min.

**Comment by joshpangell** [comment]
Thank you for such a quick response. 

Looking through your repo now, there are still few listings of our domain:

https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareABP.txt#L2590

https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuard.txt#L1691

https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt#L1517

https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareDomains.txt#L1297

https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt#L1297

https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareTPL.tpl#L1570

Thank you again

**Comment by iam-py-test** [comment]
> Thank you for such a quick response.
> 
> Looking through your repo now, there are still few listings of our domain:
> 
> https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareABP.txt#L2590
> 
> https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuard.txt#L1691
> 
> https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt#L1517
> 
> https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareDomains.txt#L1297
> 
> https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt#L1297
> 
> https://github.com/DandelionSprout/adfilt/blob/c8bafc9fe9a11b79e8b02df73621768ab990d203/Alternate%20versions%20Anti-Malware%20List/AntiMalwareTPL.tpl#L1570
> 
> Thank you again

Those still need to be auto-generated.

**Comment by DandelionSprout** [comment]
Oh, wait, right. I had mistakenly thought the domain was only ever in *Nordic Filters*. I'll fix in the alternate versions of *Anti-Malware List* too now.
