### ISSUE TITLE
https://www.auslogics.com/

### ISSUE THREAD

**Issue by GdeZsqyAY** [DandelionSprout/adfilt#422]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

`https://www.auslogics.com/` - is wrongly blocked by a rule - **||auslogics.com^$document**

https://github.com/DandelionSprout/adfilt/issues/251

![2021-12-19_8-30-02](https://user-images.githubusercontent.com/58640411/146665090-3d03aed2-b35a-4ef5-9acd-50914f8001ab.png)

### Add screenshots below if needed

![2021-12-19_8-15-44](https://user-images.githubusercontent.com/58640411/146664786-50462ab4-8c91-4928-b253-c287839b5b43.png)

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop version)

### Adblocker version(s)

**AdGuard 7.8**

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

**Dandelion Sprout's Annoyances List**

### Which browser(s) did you use when testing this?

Google Chrome

### Browser version(s)

**Google Chrome 96.0.4664.110 Stable х64**

### OS version(s)

**Windows 8.1 Enterprise x64**

**Comment by iam-py-test** [comment]
Known PUP and unwanted software:
https://blog.malwarebytes.com/detections/pup-optional-auslogics/
https://blog.malwarebytes.com/detections/pup-optional-auslogicsdriverupdater/
https://blog.malwarebytes.com/detections/pup-optional-auslogicsdiskdefrag/
https://blog.malwarebytes.com/detections/pup-optional-auslogicsboostspeed/
Feel free to allowlist it on your own systems
If you can provide creditable evidence that it has changed, we will consider removing that entry

**Comment by iam-py-test** [comment]
This is a fresh install of Windows - I just installed it _yesterday_ and all I did on it was install their cleaner:
![image](https://user-images.githubusercontent.com/84232764/146676563-cbbfbf6f-9007-47f5-9bc7-7115cd8a89cf.png)
![image](https://user-images.githubusercontent.com/84232764/146676580-5b7e2cc2-98e8-4163-9975-f17481937aff.png)
![image](https://user-images.githubusercontent.com/84232764/146676582-84255f6b-12fb-4bd4-9ef6-c29a87736915.png)

I haven't messed with the firewall at all (those are default rules?)

**Comment by iam-py-test** [comment]
If you have this scam software installed, I strongly recommend you uninstall it or remove it using [ADWCleaner](https://malwarebytes.com/adwcleaner). If you have paid, then you need to contact your bank and tell them you were scammed
