### ISSUE TITLE
Legitimate URL Shortener at Pahe.ph

### ISSUE THREAD

**Issue by FinderID** [DandelionSprout/adfilt#423]
please bypass shortlink at the download page of the site :
https://pahe.ph/tokyo-revengers-season-1-complete-web-dl-720p/

sorry if i'm wrong rules when report this, because i'm not agree with program language, and sorry for my bad english, thanks Dandelion

**Comment by DandelionSprout** [comment]
*Legitimate URL Shortener* is unfortunately unable to bypass shortlinks, as it's only able to remove `?` and `&` values from URLs.

**Comment by FinderID** [comment]
oh i see

thanks for the information, and sorry if i'm wrong before
