### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by wireless-r** [DandelionSprout/adfilt#44]
## Describe the problem below this line as meticulously and detailed as possible:

Some websites are being incorrectly blocked. These websites are legit and should not be blocked.

* Arendalfotball.no - This is the official website of Arendal Fotball, a Norwegian footbal club.
* Handelihalden.no - This is an organization for the city of Halden.

The entries are in this file: https://github.com/DandelionSprout/adfilt/blob/master/NorwegianList.txt#L977

## Add screenshots below if needed:

![bilde](https://user-images.githubusercontent.com/28116634/64846087-03032480-d60c-11e9-97cf-dfa8f7459ca4.png)

![bilde](https://user-images.githubusercontent.com/28116634/64846355-bff58100-d60c-11e9-8d87-c914afd5708b.png)

## Which adblocker(s) and version did you use when testing this?

uBlock Origin 1.22.2

## Which filterlists did you use?

NOR, DNK, ISL: Dandelion Sprouts nordiske filtre

## Which browser(s) and version did you use?

Firefox 69

## (Optional) Which OS and version did you use?

Windows 10

**Comment by DandelionSprout** [comment]
Ah, okay.

The story behind those entries, are that I saw them two years ago on another list, and borrowed them from there. I can't easily recall which list it was, however.

I'll now make sure to remove those 2 entries and also a few others that should have become 100% legitimate by now. Thanks for the heads-up.

**Comment by DandelionSprout** [comment]
It should be fixed in all versions of the Nordic list now, so I'll mark the issue as a closed case.

**Comment by wireless-r** [comment]
Thank you for fixing it so fast.

**Comment by DandelionSprout** [comment]
You're welcome. It was probably far overdue that I went through those (by my standards) ancient entries that I hadn't even figured out the specific reasons for blocking.

I also always like it when people use my lists and are willing to help waterproof them through issue reports and such, since it's one of the *very* few ways for me to get to know if anyone uses my lists, and how many who does.
