### ISSUE TITLE
Actually Legitimate URL Shortener Tool breaks Discord Search?

### ISSUE THREAD

**Issue by Darkmaster006** [DandelionSprout/adfilt#445]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

When I try to search in a group, the word does not appear highlighted as it should when you hit enter, and the word is not searched, the only thing that appears is the number of posts (complete) in that Discord channel or wherever you're searching, and nothing gets searched, apparently.

### Add screenshots below if needed

What should happen (filter disabled):
![image](https://user-images.githubusercontent.com/21136515/147896205-174b59c0-7e58-4cdb-bf3b-e28377258bb7.png)
What happens (filter enabled):
![image](https://user-images.githubusercontent.com/21136515/147896230-d94823fa-0c35-40e1-b25a-b2e8686d975f.png)

### Add a screenshot of the extension's logger

![image](https://user-images.githubusercontent.com/21136515/147896262-b4488898-72bd-4f63-ba80-5f1f0e20ab95.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.40.2

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

95.0.1 (64-bit)

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

OS: Linux Mint 20.2 x86_64 (Uma)

**Comment by DandelionSprout** [comment]
Thanks for the headsup. This has been fixed in `03January2022v1-Beta`

**Comment by Darkmaster006** [comment]
Thank you for the quick fix! Tested and works like a charm now.
