### ISSUE TITLE
apis-sklep.pl

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#453]
Floating heart  following system cursor:

`apis-sklep.pl##.cursor`

smilar to banned circle under cursor:

https://github.com/DandelionSprout/adfilt/blob/9ebb7624c71bf1fb0fe271c02bc19818382bcd28/Anti-'Custom%20cursors'%20List.txt#L57-L60

---

off-topic:

IMO `eventy-online.pl` no longer use "cricle under cursor".

**Comment by DandelionSprout** [comment]
I'll add `apis-sklep.pl##.cursor`, since I couldn't come up with any better entries that could've been made generic.

`eventy-online.pl` seems to still use the cursor circles, when I've tested in Vivaldi.

**Comment by krystian3w** [comment]
> when I've tested in Vivaldi.

For me is not loaded in Firefox. Maybe reseted tracking mechanism block too many JavaScript.
