### ISSUE TITLE
Checklist for Nordic Filters unbreakage tempfixes

### ISSUE THREAD

**Issue by DandelionSprout** [DandelionSprout/adfilt#462]
As a logical outcome of THEtomaso often @-ing me to add quick or long-lasting tempfixes for Nordic sites reported to other lists, I realised I needed a checklist to know which quickfixes to add and/or remove from Nordic Filters.

## Still open
* https://github.com/ryanbr/fanboy-adblock/issues/1243
* https://github.com/ryanbr/fanboy-adblock/issues/1339
* https://github.com/ryanbr/fanboy-adblock/issues/1468

## Closed in a perceived-to-be-incomplete state
* https://github.com/ryanbr/fanboy-adblock/issues/1261
* https://github.com/easylist/easylist/issues/12067 (for non-uBO users)

**Comment by THEtomaso** [comment]
@DandelionSprout:

Regarding the Blaklader sites..

The sites are also broken by various other filters, including **EasyList Cookie List**, **EasyPrivacy** and **Fanboy's Annoyance List**:
https://github.com/easylist/easylist/issues/10565/

..so, in addition to the fixes that you've already added, these are needed too:
```
blaklader.*#@#.optanon-show-settings
blaklader.*#@##onetrust-banner-sdk
blaklader.*#@##to-the-top
```

**Comment by THEtomaso** [comment]
@DandelionSprout:
OK, the `Blaklader.*` issues have been fixed in all of the most relevant filters now, so the temp-fix can safely be removed! :)

**Comment by THEtomaso** [comment]
Add these:

```
skousen.no,skousen.dk#@#body,html:style(height: auto !important; overflow: auto !important)
skousen.no,skousen.dk#@##cookie-information-template-wrapper
```
Info:
https://github.com/easylist/easylist/issues/10757#issuecomment-1053603292

**Comment by ryanbr** [comment]
Why not fix it in Adguard rather than a fix it a regional list, if that's the issue

**Comment by DandelionSprout** [comment]
I've just rose up from bed this morning, and am therefore not certain about what AdGuard Annoyances Filter has to do with any of this.

**Comment by THEtomaso** [comment]
@DandelionSprout:

These open issues also affects Nordic domains:
https://github.com/ryanbr/fanboy-adblock/issues/1339/
https://github.com/ryanbr/fanboy-adblock/issues/1372/
https://github.com/ryanbr/fanboy-adblock/issues/1376/
https://github.com/ryanbr/fanboy-adblock/issues/1405/
https://github.com/ryanbr/fanboy-adblock/issues/1410/
https://github.com/ryanbr/fanboy-adblock/issues/1468/

**Comment by THEtomaso** [comment]
@@DandelionSprout:

OK, I went through the reports that I linked to in my previous post, revised where necessary, and closed a couple of them due to site changes.
You should look into the remaining ones.

**Comment by DandelionSprout** [comment]
Okay, so from what I pieced together from multiple conversations spread around, is that in regards to `Skousen`, Fanboy seems to believe (I could be wrong on this) that there's a conflict between EasyList Cookie List and AdGuard Annoyances Filter, with the latter blocking `cookieinformation.com` and the former doesn't.

I'll look into the 4 reports in https://github.com/DandelionSprout/adfilt/issues/462#issuecomment-1054254575 at some point (I'm pretty booked up this evening).

**Comment by THEtomaso** [comment]
Judging from his post here, he seems to believe the sites work, simply because they're browsable:
https://github.com/easylist/easylist/issues/11064#issuecomment-1054126209

Guess he overlooked the reproduction steps, in my first post here:
https://github.com/easylist/easylist/issues/10757/

**Comment by THEtomaso** [comment]
> I'll look into the 4 reports in https://github.com/DandelionSprout/adfilt/issues/462#issuecomment-1054254575 at some point

Regarding #1410:
Under "Other problem filters", I've listed a nasty rule for ekstrabladet.dk, found in **Schacks Adblock Plus liste**.
You should probably override that rule in your filter too, just in case some poor saps (like myself) are crazy enough to still be using that outdated filter! :)

**Comment by THEtomaso** [comment]
> https://github.com/DandelionSprout/adfilt/commit/6623e62931ab68e683d76f6aa1080a04ccd86457

`ekstrabladet.dk#@#body > div[id][style]` won't work, because Schack didn't formulate it that way.
It has to be `ekstrabladet.dk#@#body>div[id][style]` !

**Comment by THEtomaso** [comment]
Fixed:
https://github.com/easylist/easylist/commit/4926fbebd34b6f546dd5bfc6abe6bcd1ee688b50

For some reason, he decided not to remove the `:style` rule.
It doesn't break anything though.

**Comment by THEtomaso** [comment]
@DandelionSprout:
`hvemder.no`:
https://github.com/easylist/easylist/issues/11357/

**Comment by THEtomaso** [comment]
@DandelionSprout:
`e24.no`:
https://github.com/easylist/easylist/issues/11455/

**Comment by THEtomaso** [comment]
`bookworld.no`:
https://github.com/easylist/easylist/issues/11668/

**Comment by THEtomaso** [comment]
`Elektroskandia.no` fixed in https://github.com/easylist/easylist/pull/8431/commits/05d5f7e5e12c2fb4044efcbe471df0484b5f0f2d + https://github.com/easylist/easylist/commit/584a61933c1aa737b3226a41568a878423173ce2

**Comment by THEtomaso** [comment]
https://github.com/easylist/easylist/issues/7805/ fixed in https://github.com/easylist/easylist/commit/544e0548c526ebb4a84419466901e03856cf0d1e

**Comment by THEtomaso** [comment]
`clasohlson.com`:
https://github.com/easylist/easylist/issues/12067/

**Comment by THEtomaso** [comment]
https://github.com/easylist/easylist/issues/12067/ fixed in https://github.com/easylist/easylist/commit/cc74ddc4b38ff44e8e324399caffda7bf3071aba

**Comment by DandelionSprout** [comment]
Krystian pointed out to me at https://github.com/DandelionSprout/adfilt/commit/6340cf0d9857f22093a46089022d030b771592d6#commitcomment-74157847 that https://github.com/easylist/easylist/commit/cc74ddc4b38ff44e8e324399caffda7bf3071aba only seems to cover the uBO extension file, unless I've missed out on something.

**Comment by THEtomaso** [comment]
This seems to have been the case for a while now, with **Easylist Cookie List**.
Many of the fixes that ryanbr has added to it has been for uBO only, despite the fact that I've suggested simple ABP-compatible alternatives.
I really don't understand his policy in this regard though, so I'm waiting for him to clarify it here:
https://github.com/easylist/easylist/issues/12011#issuecomment-1126547259

**Comment by DandelionSprout** [comment]
Closing this thread in favour of #779 and/or a hypothetical future spinoff discussion of that discussion.
