### ISSUE TITLE
Finn.no - old layout

### ISSUE THREAD

**Issue by ColdIce1** [DandelionSprout/adfilt#466]
## Hvilke(n) oppføring(er) sender du inn?
`www.finn.no##+js(rc, ads__unit--premium, .ads__unit, stay)`

## Hvilke ting blokkerer, skjuler, eller fikser de(n)?
Gjeninnfører gammel layout på listen over boligannonser.

## Hvilke av mine lister sender du den inn til?
Der den passer 👍

## Hvilken reklameblokkerer og versjon brukte du da du skrev og testet oppføringen(e)?
- [x] uBlock Origin

**Comment by DandelionSprout** [comment]
Jeg ser ut til å ha problemer med å se forskjell på ny og gammel utforming når jeg tester oppføringen på `https://www.finn.no/bap/forsale/ad.html?finnkode=217092153` i Chrome. Kan du legge ut et skjermklipp og en eksempel-lenke?

**Comment by ColdIce1** [comment]
Beklager, jeg var ikke tydelig nok. Det er spesifikt listen over boliganonnser som endres.
https://www.nettavisen.no/okonomi/raser-over-nye-priser-for-boligsalg-pa-finn-no-forbrukerne-er-fratatt-ethvert-valg/s/12-95-3424235759

**Før**
![firefox_2022-01-26_09-09-03](https://user-images.githubusercontent.com/586280/151125985-0c819024-baa5-4051-a87a-e66ba124d3d0.png)
**Etter**
![firefox_2022-01-26_09-09-14](https://user-images.githubusercontent.com/586280/151125989-2d40db51-ad1a-437d-a632-f2aefa810a46.png)

**Comment by ColdIce1** [comment]
Need to re-open issue @DandelionSprout - "bug" is back.
The `ads__unit--premium` is not used anymore... need to investigate

**Comment by ColdIce1** [comment]
The fact that Finn.no switched to using list of cards instead of a grid of cards complicates this.
The solution here is to create a userstyle as I believe ublock origin is not sufficient anymore.

Note, to revert back to grid layout, swap the div with the following classes `ads ads--list ads--cards` with `ads ads--grid ads--cards`.

**Comment by iam-py-test** [comment]
Imre, you might want to look into this @DandelionSprout
