### ISSUE TITLE
Legitimate URL Shortener Tool breaks Google Chat videos

### ISSUE THREAD

**Issue by 1zaman** [DandelionSprout/adfilt#469]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Actually Legitimate URL Shortener Tool stops Google Chat videos from loading. The culprit seems to be a [filter][] that removes the `source=hangouts_chat` parameter from the URL. See the logger data for an example.

A potential solution would be to exclude the `chat.google.com/videoplayback` domain from this filter. I have verified that adding the following exception filter fixes the issue:

```
@@||chat.google.com/videoplayback$removeparam=source
```

[filter]: https://github.com/DandelionSprout/adfilt/blob/9308c67f5b94b8bc16f00c505fc8f5f4983e2a99/LegitimateURLShortener.txt#L1320

### Add screenshots below if needed

<img width="854" alt="Screen Shot 2022-01-28 at 6 57 36 PM" src="https://user-images.githubusercontent.com/4244109/151559887-31d53447-cde3-4561-856a-cd8df95c7739.png">

### Add a screenshot of the extension's logger

Here's the data of the filter from uBlock Origin's logger:
| | |
| ------------- | ------------- |
| Filter  | `*$removeparam=source,denyallow=googlevideo.com,domain=1sol.io\|ashford.com\|asos.com\|att.com\|awd-it.*\|bankofamerica.com\|barenecessities.com\|bedbathandbeyond.com\|betterprogramming.pub\|blavity.com\|boscovs.com\|boxboat.com\|brownells.*\|burkesoutlet.com\|bybit.com\|choicehotels.com\|chollometro.com\|coinpanel.com\|contabo.com\|cyberghostvpn.com\|despegar.*\|directv.com\|discord.*\|docs.google.com\|docsend.com\|drinkhint.com\|edx.org\|eonline.com\|eventbrite.*\|fiverr.com\|fool.com\|forms.gle\|gethotspotshield.com\|gleam.io\|goodcrypto.app\|googleusercontent.com\|greenhouse.io\|hammacher.com\|hanes.com\|hotspotshield.com\|hottopic.com\|housing.com\|hp.com\|instagram.com\|itnext.io\|jacquielawson.com\|kasta.io\|medium.com\|nautica.com\|onehanesplace.com\|outnorth.fi\|petsupplies.com\|phonesoap.com\|riteaid.com\|runnode.com\|search.brave.com\|sonos.com\|spiceworks.com\|squarespace.com\|subscribe.gq.com\|t.me\|thedailybeast.com\|tiktok.com\|tokopedia.com\|tommybahama.com\|torrid.com\|tous.com\|tradingview.com\|twitter.com\|vimeo.com\|webhint.io\|wilsonsleather.com\|wired.com\|ylighting.com\|youtube.com\|yubo.live`  |
| Filter list  | ➗ Actually Legitimate URL Shortener Tool  |
| Root context  | `mail.google.com`  |
| Context  | `www.youtube.com`  |
| Partyness  | (1,3) `google.com` ⋯ `youtube.com` ⇒ `google.com`  |
| Type  | media  |
| URL  | `https://rr2---sn-4wg7ln76.c.chat.google.com/videoplayback?expire=1643388395&ei=u_PzYdCXM4zx0wXcrrOADw&ip=205.164.153.136&id=40f0c20523bd338f&itag=18&source=hangouts_chat&requiressl=yes&mh=la&mm=32&mn=sn-4wg7ln76&ms=su&mv=m&mvi=2&pl=24&sc=yes&susc=hc&mime=video/mp4&vprv=1&dur=80.433&lmt=1643320458550247&mt=1643377231&txp=0011224&sparams=expire,ei,ip,id,itag,source,requiressl,susc,mime,vprv,dur,lmt&sig=AOq0QJ8wRQIgFHaR_im2ht4ESOh5MRRok7xIGD78STUGoyIUtP9Rf6ACIQDN-S-hYhKVe5drs9FdlpslstQPfTI90cbONIkJeEbEEw%3D%3D&lsparams=mh,mm,mn,ms,mv,mvi,pl,sc&lsig=AG3C_xAwRQIgIfUDCQPJx_rZQAb9-B8Q-PhUnYktdpx3X0TxjDiNMl0CIQDjdMf1LIfQefcXFRxX6cBA97Ce0tdUVN29YpGbwucY-Q%3D%3D`  |

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.40.8

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

 - All uBlock built-in filters.
 - EasyList
 - EasyPrivacy
 - AdGuard URL Tracking Protection
 - Block Outsider Intrusion into LAN
 - Online Malicious URL Blocklist
 - EasyList Cookie
 - uBlock filters – Annoyances
 - AdGuard Annoyances
 - Fanboy’s Annoyance
 - Peter Lowe’s Ad and tracking server list
 - Actually Legitimate URL Shortener Tool
 - Actually Legitimate URL Shortener Tool - Affiliate tag allowlist
 - Stop Autoplay On Video Sites
 - YouTube: Even More Pure Video Experience
 - ClearURLs for uBo

### Which browser(s) did you use when testing this?

Google Chrome

### Browser version(s)

96.0.4664.110 (Official Build) (x86_64)

### Which OS(s) did you use when testing this?

macOS

### OS version(s)

Big Sur 11.6.2

**Comment by DandelionSprout** [comment]
Although I don't currently use Google Chat, I think I know something that has a very high chance of fixing this. Give me 4min.

**Comment by DandelionSprout** [comment]
Or, wait, I now see the logger output considered it a `media` request, as opposed to `xhr` for similar URLs on YouTube proper. I suppose I'll try to whitelist `media` too in that fix.

**Comment by 1zaman** [comment]
I pulled in your changes, and can confirm that the issue is now fixed. Thanks a lot for the speedy resolution!
