### ISSUE TITLE
[Actually Legitimate URL Shortener Tool] Google Play Store search link leads to redirection loop

### ISSUE THREAD

**Issue by Fanolian** [DandelionSprout/adfilt#475]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

With only the list `Actually Legitimate URL Shortener Tool` enabled, a Google Play Store search link results in a redirection loop which Firefox and Chrome end up showing an error page.

### Steps to reproduce
1. In a new user profile in Firefox 96.0.3 (current Release), Firefox Nightly, or Google Chrome 97.0.4692.99, install uBlock Origin.
2. Open https://play.google.com/store/search?q=touchwood&c=apps, either by left-click, middle-click, or pasting the link in the URL bar. Make sure the page opens properly at this point.
3. Keep uBlock settings as default. Enable only [Actually Legitimate URL Shortener Tool](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt). (Or keep other default lists enabled but those are irrelevant.). You may use this settings file (I cannot attach the file directly):

> {
  "timeStamp": 1643693294490,
  "version": "1.40.8",
  "userSettings": {
    "externalLists": "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt",
    "importedLists": [
      "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt"
    ]
  },
  "selectedFilterLists": [
    "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt"
  ],
  "hiddenSettings": {},
  "whitelist": [
    "about-scheme",
    "chrome-extension-scheme",
    "chrome-scheme",
    "edge-scheme",
    "moz-extension-scheme",
    "opera-scheme",
    "vivaldi-scheme",
    "wyciwyg-scheme"
  ],
  "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-large-media: behind-the-scene false\nno-csp-reports: * true",
  "userFilters": ""
}

4. Load https://play.google.com/store/search?q=touchwood&c=apps again.

### Actual result
The page does not load now. Firefox shows the error page with this meesage:

> The page isn’t redirecting properly
>
> Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
>
>   This problem can sometimes be caused by disabling or refusing to accept cookies.

In Chrome it shows:

> This page isn’t workingplay.google.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

### Expected result
The page still loads properly.

### Additional notes
If I visit https://play.google.com directly (which redirects to https://play.google.com/store/games), click the search icon near top right corner, type a search keyword and press `Enter`, I can load the search result page correctly bearing the same URL as the problematic one. But when I click reload, it results in an infinite loop again.

### Add a screenshot of the extension's logger

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | `https://play.google.com/store/search?q=touchwood` | << | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | *$removeparam=c,domain=appsflyer.com\|farfetch.com\|hepsiburada.com\|norton.com\|onelink.me\|play.google.com\|tiktok.com\|shopee.* | -- | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | `https://play.google.com/store/search?q=touchwood` | << | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | *$removeparam=c,domain=appsflyer.com\|farfetch.com\|hepsiburada.com\|norton.com\|onelink.me\|play.google.com\|tiktok.com\|shopee.* | -- | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | `https://play.google.com/store/search?q=touchwood` | << | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | *$removeparam=c,domain=appsflyer.com\|farfetch.com\|hepsiburada.com\|norton.com\|onelink.me\|play.google.com\|tiktok.com\|shopee.* | -- | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | `https://play.google.com/store/search?q=touchwood` | << | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | *$removeparam=c,domain=appsflyer.com\|farfetch.com\|hepsiburada.com\|norton.com\|onelink.me\|play.google.com\|tiktok.com\|shopee.* | -- | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | `https://play.google.com/store/search?q=touchwood` | << | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | *$removeparam=c,domain=appsflyer.com\|farfetch.com\|hepsiburada.com\|norton.com\|onelink.me\|play.google.com\|tiktok.com\|shopee.* | -- | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | `https://play.google.com/store/search?q=touchwood` | << | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | *$removeparam=c,domain=appsflyer.com\|farfetch.com\|hepsiburada.com\|norton.com\|onelink.me\|play.google.com\|tiktok.com\|shopee.* | -- | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | `https://play.google.com/store/search?q=touchwood` | << | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | *$removeparam=c,domain=appsflyer.com\|farfetch.com\|hepsiburada.com\|norton.com\|onelink.me\|play.google.com\|tiktok.com\|shopee.* | -- | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | `https://play.google.com/store/search?q=touchwood` | << | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +1 | *$removeparam=c,domain=appsflyer.com\|farfetch.com\|hepsiburada.com\|norton.com\|onelink.me\|play.google.com\|tiktok.com\|shopee.* | -- | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +0 | `https://play.google.com/store/search?q=touchwood` | << | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +0 | *$removeparam=c,domain=appsflyer.com\|farfetch.com\|hepsiburada.com\|norton.com\|onelink.me\|play.google.com\|tiktok.com\|shopee.* | -- | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +0 | `https://play.google.com/store/search?q=touchwood` | << | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
| +0 | *$removeparam=c,domain=appsflyer.com\|farfetch.com\|hepsiburada.com\|norton.com\|onelink.me\|play.google.com\|tiktok.com\|shopee.* | -- | play.google.com | 1 | doc | `https://play.google.com/store/search?q=touchwood&c=apps` |
</details>

Screenshot of the logger:
![image](https://user-images.githubusercontent.com/771216/151917934-59defc80-edc7-482f-a6b8-84859ac3a20a.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.40.8

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

[Actually Legitimate URL Shortener Tool](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt) only

### Which browser(s) did you use when testing this?

Google Chrome, Firefox, (Other)

### Browser version(s)

Firefox 96.0.3
Firefox Nightly 2022-01-31 build (20220131212843)
Chrome 97.0.4692.99

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

21H2

**Comment by DandelionSprout** [comment]
I applaud you for the stellar-level explanation, reproduction of, and settings for this issue. 👏 

Although I was somehow unable to reproduce an infinite loading loop even then, I did encounter a fairly major problem where it turned out that removing `&c=apps` caused searches to display results across all media categories and not just apps. Accordingly, I'll fix this issue within the next 3 minutes.

**Comment by Fanolian** [comment]
Confirm fixed in 01February2022v1-Beta. Thanks a lot.
