### ISSUE TITLE
dplay login

### ISSUE THREAD

**Issue by Schanzation** [DandelionSprout/adfilt#48]
Hi! I have issue logging in to https://auth.dplay.no/login without disabling uBlockOrigin. Whenever I try to log on to dplay.no I just get a blank white page.

Picture of problem and event logger:
https://imgur.com/a/BZn4NWU

- uBlock Origin 1.22.4 - Standard filters + NOR, DNK, ISL: Dandelion list.
- Same issue in all browsers with ublockO installed.
- Windows 10 Pro v1903.

**Comment by DandelionSprout** [comment]
This was definitely enough info for me to work with, and I applaud you for that.

Based on the logger screenshot, I have every reason to assume that it's EasyPrivacy that is causing havoc again. I've never liked EasyPrivacy, as this isn't the first time it has broken something.

As I do not currently have a `Dplay` account (I'm not the biggest streaming service user ever), can you try out these two entries, one at a time?

```
@@||mparticle.com^$important
@@||adobedtm.com^$important
```

**Comment by Schanzation** [comment]
I tried them both, one at a time. Still just a white blank page unfortunately.

**Comment by DandelionSprout** [comment]
In that case I guess I'll be making an account there overnight to test it out.

**Comment by Schanzation** [comment]
Ok, I can't remember if I have an account there or not. Don't think you need an account to reproduce this problem.

**Comment by DandelionSprout** [comment]
I've now given it my best attempt, so feel free to give me a heads-up about whether it works or not.

**Comment by Schanzation** [comment]
Okay. Doesn't work yet.

**Comment by Schanzation** [comment]
Nevermind. I tried it now in Chrome and it works! Awesome.

**Comment by DandelionSprout** [comment]
Having got confirmation of it working, I'll now declare this a closed case. Thanks again.

**Comment by llacb47** [comment]
> This was definitely enough info for me to work with, and I applaud you for that.
> 
> Based on the logger screenshot, I have every reason to assume that it's EasyPrivacy that is causing havoc again. I've never liked EasyPrivacy, as this isn't the first time it has broken something.
> 
> As I do not currently have a `Dplay` account (I'm not the biggest streaming service user ever), can you try out these two entries, one at a time?
> 
> ```
> @@||mparticle.com^$important
> @@||adobedtm.com^$important
> ```

FYI you do not need `important` for exception rules.

**Comment by DandelionSprout** [comment]
Thanks for the concern, but I mostly just added those `$important` to try to be 100% sure that no other rules would stand in the way of them.

It later turned out that *both* of those entries were needed at the same time, but still.
