### ISSUE TITLE
A Few Anti-Prayer Reports

### ISSUE THREAD

**Issue by bkrucarci** [DandelionSprout/adfilt#484]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Website : https://www.milatgazetesi.com/
SS      : https://i.imgur.com/It66Al0.png

Website: https://www.yeniakit.com.tr/
SS     : https://prnt.sc/26nu33c

Website: https://www.yeniasya.com.tr/
SS     : https://prnt.sc/26nu3n8

### Which adblocker(s) did you use when testing this?

AdGuard (for browsers)

### Adblocker version(s)

4.0.105

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

AdGuard's Base + Tracking + Turkish & Dandelion's Anti-Prayer List

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

96.0.3

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

Win 10 Pro 21H1

**Comment by DandelionSprout** [comment]
I'll add entries for those sites in approx. 3 hours' time. Thanks in advance.

**Comment by bkrucarci** [comment]
@DandelionSprout Do you add dream predictor rules into your astrology filter?

**Comment by DandelionSprout** [comment]
The `milatgazetesi` one seem to be about camera livestreams and not prayer times, so that one is out of scope. The other two I'll add pretty soon now.

>Do you add dream predictor rules into your astrology filter?

Not that I can remember.
