### ISSUE TITLE
A Few Reports for Anti-Astrology & Anti-Prayer Timer Filter 

### ISSUE THREAD

**Issue by bkrucarci** [DandelionSprout/adfilt#485]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

**For Astrology filter**
Website        : https://www.sabah.com.tr/
SS             : https://prnt.sc/26nuhq7
Suggested Rule : sabah.com.tr##.dailyBurcs

**Dream Predictions**
Website        : https://www.sabah.com.tr/roza
SS             : https://prnt.sc/26nul1l
Suggested Rule : sabah.com.tr##.interpretation-dreams

**For Astrology filter**
Website        : https://hthayat.haberturk.com/
SS             : https://prnt.sc/26nupmy
Suggested Rule : hthayat.haberturk.com###advertorial-index

**For Astrology filter**
Website        : https://www.mynet.com/
SS             : https://prnt.sc/26nuvj6
Suggested rule : mynet.com##.astrology-widget-top-section

**Anti-pray Timer Filter**
Website        : https://www.takvim.com.tr/magazin
SS             : https://prnt.sc/26nusf7

**Anti-pray Timer Filter**
Website        : https://www.star.com.tr/
SS             : https://prnt.sc/26nutht

**Anti-pray Timer Filter**
Website        : https://www.haber7.com/
SS             : https://prnt.sc/26nux46 + https://prnt.sc/26nuxzp
Suggested rule : haber7.com##.prayer
Suggested rule : haber7.com##.multimedia-buttons

### Add screenshots below if needed

N/A

### Add a screenshot of the extension's logger

N/A

### Which adblocker(s) did you use when testing this?

AdGuard (for browsers)

### Adblocker version(s)

4.0.105 Beta

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

AdGuard's Base + Tracking + Turkish & 
Dandelion's Anti-Prayer TimerList
Dandelion's Anti-Astrology List
Dandelion's I do not want to download your browser list

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

96.0.3

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

Windows 10 Pro 21H1

**Comment by bkrucarci** [comment]
I like your approach to creating general rules.
Can you please update your "Twitter De-Politificator" list for Turkish politics? I want to use it.
You may block known Turkish polticians with the list. 
Thanks

**Comment by DandelionSprout** [comment]
I can take care of that sometime tonight.

**Comment by bkrucarci** [comment]
These may help,
https://en.wikipedia.org/wiki/List_of_political_parties_in_Turkey
https://en.wikipedia.org/wiki/List_of_Turkish_politicians
Regards
