### ISSUE TITLE
Missed Browser Banner for Dandelion's I do not want to download your browser list

### ISSUE THREAD

**Issue by bkrucarci** [DandelionSprout/adfilt#488]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Website             : https://www.ccleaner.com/ccleaner/download
SS                      : https://prnt.sc/26o2092
Suggested Rule : ccleaner.com##.cc-browser-banner

### Add screenshots below if needed

N/A

### Add a screenshot of the extension's logger

N/A

### Which adblocker(s) did you use when testing this?

AdGuard (for browsers)

### Adblocker version(s)

4.0.105 beta

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

AdGuard's Base + Tracking + Turkish &
Dandelion's Anti-Prayer TimerList
Dandelion's Anti-Astrology List
Dandelion's I do not want to download your browser list
Dandelion's Browse websites without logging in

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

96.0.3

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

Pro 21H1

**Comment by DandelionSprout** [comment]
In this particular case, it's on a site whose sole purpose is to download `CCleaner` products, which includes `CCleaner Browser`, meaning it'd be slightly odd to block that banner. I'll make sure to add a note about to that list, and since the note wasn't there before, I can't blame you for not knowing about that.

**Comment by bkrucarci** [comment]
Thanks for the claficiation.
Regards,
