### ISSUE TITLE
tv2.dk

### ISSUE THREAD

**Issue by spirillen** [DandelionSprout/adfilt#49]
## Which entry/entries are you submitting?
```
! 10/13/2019 tv2.dk
||tv2login.dk/api/login/v1/users/current/consents$xmlhttprequest
||tv2a.dk/analytics/gallup/spring.js$script
||tv2a.dk/ads/*
||tv2a.dk/consent/*$script
||tv2a.dk/oil/*$script
||facebook.net^$script
||adobedtm.com^$script
||tv2net.zendesk.com^$script
```

## Which things do they block, hide, or unbreak?
<details><summary>Logger output for 4 pages on tv2.dk</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +157 | \|\|chartbeat.com^$third-party | -- | nyheder.tv2.dk | 3 | script | `https://static.chartbeat.com/js/chartbeat_video.js` |
| +157 | ##.o-deck:has(div[class^="ad ad-wide"]) |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/politik` |
| +157 | ##.ad-wide |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/politik` |
| +157 | ##.ad-topbanner |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/politik` |
| +157 | ##.ad-sticky |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/politik` |
| +157 | ##.ad-rectangle |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/politik` |
| +157 | ##.ad |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/politik` |
| +157 | \|\|lp4.io^$third-party | -- | nyheder.tv2.dk | 3 | script | `https://pp.lp4.io/app/52/6a/65/526a651fe45a1d475e9019d0.js?pvrg0l` |
| +157 | \|\|tv2a.dk/analytics/gallup/spring.js$script | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/analytics/gallup/spring.js` |
| +157 | \|\|tv2a.dk/consent/$script | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/consent/modal.js?platform=tv2dk` |
| +157 | \|\|tv2a.dk/ads/ | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/ads/tv2ads.js?v1.0.28` |
| +157 | /prebid/* | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/prebid/prebid.js?v1.0.28` |
| +157 | \|\|scripts.tv2a.dk/oil/ | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/oil/oil.js?v1.0.28` |
| +153 | \|\|chartbeat.com^$third-party | -- | nyheder.tv2.dk | 3 | script | `https://static.chartbeat.com/js/chartbeat_video.js` |
| +153 | ##.o-deck:has(div[class^="ad ad-wide"]) |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/seneste` |
| +153 | ##.ad-wide |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/seneste` |
| +153 | ##.ad-topbanner |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/seneste` |
| +153 | ##.ad-sticky |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/seneste` |
| +153 | ##.ad-rectangle |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/seneste` |
| +153 | ##.ad |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/seneste` |
| +153 | \|\|lp4.io^$third-party | -- | nyheder.tv2.dk | 3 | script | `https://pp.lp4.io/app/52/6a/65/526a651fe45a1d475e9019d0.js?pvrg0l` |
| +153 | \|\|tv2a.dk/analytics/gallup/spring.js$script | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/analytics/gallup/spring.js` |
| +153 | \|\|tv2a.dk/consent/$script | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/consent/modal.js?platform=tv2dk` |
| +153 | \|\|tv2a.dk/ads/ | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/ads/tv2ads.js?v1.0.28` |
| +153 | /prebid/* | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/prebid/prebid.js?v1.0.28` |
| +153 | \|\|scripts.tv2a.dk/oil/ | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/oil/oil.js?v1.0.28` |
| +144 | \|\|googleapis.com^ | -- | nyheder.tv2.dk | 3 | script | `https://imasdk.googleapis.com/js/sdkloader/ima3.js` |
| +143 | \|\|chartbeat.com^$third-party | -- | nyheder.tv2.dk | 3 | script | `https://static.chartbeat.com/js/chartbeat_video.js` |
| +141 | ##.ad-wide |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/samfund/2019-10-12-knuthenborg-safaripark-vil-hjaelpe-kamelen-ali` |
| +141 | ##.o-deck:has(div[class^="ad ad-wide"]) |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/samfund/2019-10-12-knuthenborg-safaripark-vil-hjaelpe-kamelen-ali` |
| +141 | ##.o-article_sidebar > div.g-item |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/samfund/2019-10-12-knuthenborg-safaripark-vil-hjaelpe-kamelen-ali` |
| +141 | ##.ad-topbanner |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/samfund/2019-10-12-knuthenborg-safaripark-vil-hjaelpe-kamelen-ali` |
| +141 | ##.ad-sticky |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/samfund/2019-10-12-knuthenborg-safaripark-vil-hjaelpe-kamelen-ali` |
| +141 | ##.ad-rectangle |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/samfund/2019-10-12-knuthenborg-safaripark-vil-hjaelpe-kamelen-ali` |
| +141 | ##.ad-container |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/samfund/2019-10-12-knuthenborg-safaripark-vil-hjaelpe-kamelen-ali` |
| +141 | ##.ad |  | nyheder.tv2.dk |  | dom | `https://nyheder.tv2.dk/samfund/2019-10-12-knuthenborg-safaripark-vil-hjaelpe-kamelen-ali` |
| +140 | \|\|lp4.io^$third-party | -- | nyheder.tv2.dk | 3 | script | `https://pp.lp4.io/app/52/6a/65/526a651fe45a1d475e9019d0.js?pvrg0l` |
| +140 | \|\|tv2a.dk/analytics/gallup/spring.js$script | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/analytics/gallup/spring.js` |
| +140 | \|\|tv2a.dk/consent/$script | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/consent/modal.js?platform=tv2dk` |
| +140 | \|\|tv2a.dk/ads/ | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/ads/tv2ads.js?v1.0.28` |
| +140 | /prebid/* | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/prebid/prebid.js?v1.0.28` |
| +140 | \|\|scripts.tv2a.dk/oil/ | -- | nyheder.tv2.dk | 3 | script | `https://scripts.tv2a.dk/oil/oil.js?v1.0.28` |
| +140 | \|\|facebook.net^$script | -- | nyheder.tv2.dk | 3 | script | `https://connect.facebook.net/da_DK/sdk.js#xfbml=1&version=v4.0` |
| +7 | \|\|chartbeat.com^$third-party | -- | tv2.dk | 3 | script | `https://static.chartbeat.com/js/chartbeat.js` |
| +4 | ##.o-deck:has(div[class^="ad ad-wide"]) |  | tv2.dk |  | dom | `https://tv2.dk/` |
| +4 | ##.ad-wide |  | tv2.dk |  | dom | `https://tv2.dk/` |
| +4 | ##.ad-topbanner |  | tv2.dk |  | dom | `https://tv2.dk/` |
| +4 | ##.ad-sticky |  | tv2.dk |  | dom | `https://tv2.dk/` |
| +4 | ##.ad-sponsor |  | tv2.dk |  | dom | `https://tv2.dk/` |
| +4 | ##.ad-rectangle |  | tv2.dk |  | dom | `https://tv2.dk/` |
| +4 | ##.ad |  | tv2.dk |  | dom | `https://tv2.dk/` |
| +4 | /prebid/* | -- | tv2.dk | 3 | script | `https://scripts.tv2a.dk/prebid/prebid.js?1570923000` |
| +4 | \|\|tv2a.dk/ads/ | -- | tv2.dk | 3 | script | `https://scripts.tv2a.dk/ads/tv2ads.js?1570923000` |
| +4 | \|\|scripts.tv2a.dk/oil/ | -- | tv2.dk | 3 | script | `https://scripts.tv2a.dk/oil/oil.js?1570923000` |
| +4 | \|\|tv2a.dk/consent/$script | -- | tv2.dk | 3 | script | `https://scripts.tv2a.dk/consent/modal.js?platform=tv2dk` |
| +4 | \|\|lp4.io^$third-party | -- | tv2.dk | 3 | script | `https://pp.lp4.io/app/52/6a/65/526a651fe45a1d475e9019d0.js` |
| +4 | \|\|tv2a.dk/analytics/gallup/spring.js$script | -- | tv2.dk | 3 | script | `https://scripts.tv2a.dk/analytics/gallup/spring.js` |
| +4 | \|\|gemius.pl^$third-party | -- | tv2.dk | 3 | script | `https://gadk.hit.gemius.pl/hmapxy.js` |
| +4 | \|\|chartbeat.com^$third-party | -- | tv2.dk | 3 | script | `https://static.chartbeat.com/js/chartbeat_mab.js` |
</details>

## Which of my lists are you submitting it to?
This is the big question... I was trying looking around, but first off... you have more than a few to select from :weary: 

Secondly, most of my submission, is about tracking and then ads.

A domain i personally have blocked on my public facing DNS is `tv2a.dk` as it appears only to be used for serving ads/tracking code. I don't ever never using this **BLIIP** site, but was looking into it in [other matter](https://anonymousposter.gitlab.io/datatilsynet/stat/2019/10/12/TV2-tv2-dk.html) (Dansk). At my test i had no issue blocking `tv2a.dk` so give it a try

## Which adblocker(s) and version did you use when writing and testing the entries?
- [ ] Nano Adblocker
- [ ] Nano Defender
- [x] uBlock Origin
- [ ] uBlock Origin Plus
- [ ] AdNauseam
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] Blokada
- [ ] Pi-hole

Other(s):

Version(s):

## Which filterlists did you use? Failing to write this will result in instant report closing.
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP.txt
https://anonymousposter.gitlab.io/ublockorigin-rules/blockrules.txt

## (Optional) Which browser(s) and version did you use?
FF 69.0.2

**Comment by DandelionSprout** [comment]
This seems like a case for all versions of my Nordic list.

After testing it on a surface level, I will be adding `tv2a.dk` to my Nordic lists.

However, my list does not typically deal with tracking, as a result of how I have had pretty bad experiences with `EasyPrivacy` and similar lists that break sites all over the place. `adobedtm.com` seems to me to be covered by EasyPrivacy already. `||tv2login.dk/api/login/v1/users/current/consents$xmlhttprequest` and `||tv2net.zendesk.com^$script` I would've submitted to [AdGuard Privacy Protection](https://github.com/AdguardTeam/AdguardFilters/issues) for the immediate time being.

Also I'd dare say that I'd rather have read through `tv2.dk` a hundred times than to read through `ekstrabladet.dk` once. I'm honestly doubting if the latter could even possibly be considered news. Half the articles are about models or pornography.

**Comment by spirillen** [comment]
You right that extrabladet.dk = aftonbladet.se empty news and everything is a scandal 

However it is usually eb.dk that find the real heavy stories that breaks through, as you know 
`Blind høne kan også finde korn`

**Comment by DandelionSprout** [comment]
As you didn't seem to have any objections to my entry-wise fix and suggestions in https://github.com/DandelionSprout/adfilt/issues/49#issuecomment-541374979, I'll consider this a resolved case now. Thanks again.

**Comment by spirillen** [comment]
Absolutely not :smile: 

But stumbled on `https://www.forbrukertilsynet.no/netthandel/falske-nettbutikker` on my path through you "few" lists

That list it rather outdated, and i have made a "updated" version of it with those domains that actually still is active, if you like to clean up a bit

The weird list can be found in this repo: https://github.com/Import-External-Sources/Forbrukertilsynet-falske-nettbutikker

**Comment by DandelionSprout** [comment]
I run [PyFunceble](https://github.com/funilrys/PyFunceble) on those Forbrukertilsynet sites every 1-2 months, so the output I've gradually ended up with is very close to yours already.

**Comment by spirillen** [comment]
Super :stuck_out_tongue_winking_eye: 

But which "list" is your master file for submissions? Maybe a little note in a ./CONTRIBUTING.md would help

**Comment by DandelionSprout** [comment]
Sounds like a good idea to me, so I've done that now: https://github.com/DandelionSprout/adfilt/blob/master/.github/CONTRIBUTING.md
