### ISSUE TITLE
Multiple Mixed Reports for Anti-Prayer & Anti-Astrology Filter

### ISSUE THREAD

**Issue by bkrucarci** [DandelionSprout/adfilt#490]
## I collected some rules for the filter's sake. More generic will block more on same type of websites.

+ FOR ANTI-PRAYER FILTER

website : https://www.bursahabermerkezi.com/
SS      : https://i.imgur.com/W6u4Nnx.png
Suggested Rule : ##.namazvakitleri

website : http://www.bingolgazetesi.com.tr/ + http://www.bingolkenthaber.com/ + http://www.burdurilkadim.com/
SS      : https://i.imgur.com/DaYC74V.png
Suggested Rule : ##.namaz

website : https://bingolhaberci.com/
SS      : https://i.imgur.com/w07plyT.png
suggested rule : ##.namazWidget

website : https://www.bingolonline.com/
SS      : https://i.imgur.com/CpiKTw1.png
Suggested Rule : ##.namazVakitleriBlok

website : https://www.cagdasburdur.com/
SS      : https://i.imgur.com/MIbeIBP.png

website : https://www.burdurweb.com/web/ + https://www.herihaber.com.tr/
SS      : https://i.imgur.com/ULFwfkJ.png
Suggested rule : ###namazVakitleri

website : https://www.gunisigigazetesi.net/ + https://www.eskisehirhaber.com/
SS      : https://i.imgur.com/prM7F68.png
Suggested Rule : ###prayer-times

website : https://www.elazigsonhaber.com/ + https://mersinistikbal.net/ + https://www.eskisehirhaber26.com/ + http://www.corumhakimiyet.net/
SS      : https://i.imgur.com/cf1b3PL.png
Suggested Rule : ##.media-prayer

website : http://www.esgundem26.com/ + https://www.esolay.com/
SS      : https://i.imgur.com/MdBSwoo.png
Suggested Rule : ##.panel-namaz

website : http://www.gazeteguncel.com/ + https://www.gaziantep27.net/
SS      : https://i.imgur.com/1c61BdG.png
Suggested Rule : ##.prayer-side

website : https://www.agridogruhaber.com/
SS      : https://i.imgur.com/oQw7KTK.png

website : http://www.tarsusekspres.com.tr/
SS      : https://i.imgur.com/40LdBxJ.png
You may block "vakitci" widgets on all website with a generic rule.

website : https://www.asigazetesi.com/
SS      : https://i.imgur.com/utkPneJ.png

website : https://www.adiyamanhaber.com/
SS      : https://i.imgur.com/hrfzmVh.png

+ FOR ANTI-ASTROLOGY FILTER

website : http://www.oguzeligazetesi.com.tr/
SS      : https://i.imgur.com/Mh9Hl0t.png
Suggested Rule : ##.widget_burc_yorumlari_widget

website : https://www.gundembursa.com/
SS      : https://i.imgur.com/wlpxSZV.png
Suggested Rule : ###astroloji

website : https://www.memohaber.com/
SS      : https://i.imgur.com/dCHeO7b.png

### Which adblocker(s) did you use when testing this?

AdGuard (for browsers)

### Adblocker version(s)

4.0.108

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

AdGuard's Base + Tracking + Turkish &
Dandelion's Anti-Prayer TimerList
Dandelion's Anti-Astrology List
Dandelion's I do not want to download your browser list

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

96.0.3

### Which OS(s) did you use when testing this?

Windows 10 Pro 21H1

**Comment by DandelionSprout** [comment]
I've handled the anti-prayer entries now. I'll take care of the anti-astrology entries later tonight.
