### ISSUE TITLE
buttercup.pw

### ISSUE THREAD

**Issue by flavorgold1** [DandelionSprout/adfilt#493]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

buttercup.pw is being blocked by: `||pw^$denyallow=libgen.pw|petridish.pw|palaugov.pw|dpc.pw|zikrap.pw|demonoid.pw
Dandelion Sprout's Anti-Malware List`.

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

AdGuardHome Edge Version `v0.108.0-a.61+dc480ae7`.

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Anti-Malware List

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

96.0.3 (64-bit)

### Which OS(s) did you use when testing this?

Windows 10, macOS, Linux, Android

**Comment by DandelionSprout** [comment]
As the site seems very legitimate, and that `.pw` is its only domain, I'll add a whitelisting for it pretty soon now.
