### ISSUE TITLE
Legitimate URL Shortener causes an issue on Github traffic page referring links.

### ISSUE THREAD

**Issue by kevinlekiller** [DandelionSprout/adfilt#495]
When clicking on a referring link on the traffic page on Github, the page loads back to the traffic page instead of the stats on the link.

You can test this only on a repository you are a member of.

For example, if you head here : https://github.com/DandelionSprout/adfilt/graphs/traffic

Then scroll to the bottom to the referrer section and click a link that's blue, the page will refresh.

If you disable Legitimate URL Shortener, then click on a link, it shows the stats as expected.

**Comment by krystian3w** [comment]
Bad is remove refferer on xhr requests:

> `/graphs/traffic?referrer=wykop.pl#top-domains`

Form line: https://github.com/DandelionSprout/adfilt/blob/dbfbb7f5657ec07b36b2240d9a880bc1c224ea18/LegitimateURLShortener.txt#L218

**Comment by iam-py-test** [comment]
Let me look into this

**Comment by iam-py-test** [comment]
@kevinlekiller thank you for reporting this and sorry for the delay
@krystian3w thanks for pointing that out
