### ISSUE TITLE
Bing redirect issue

### ISSUE THREAD

**Issue by SeriousHoax** [DandelionSprout/adfilt#508]
## Which entry/entries are you submitting?
 Rule:
$removeparam=cvid,domain=bing.com|msn.com

## Which things do they block, hide, or unbreak?

Redirection.
To reproduce, Enable the LegitimateURLShortener filter in the Adguard Extension and visit this site 
`https://www.bing.com/WS/redirect/?q=novak+djokovic&url=aHR0cHM6Ly93d3cuY2Jzc3BvcnRzLmNvbS90ZW5uaXMvbmV3cy9ub3Zhay1kam9rb3ZpYy1zYXlzLWhlLXdvdWxkLWdpdmUtdXAtZ3JhbmQtc2xhbS10aXRsZS1jaGFuY2VzLWJlZm9yZS1nZXR0aW5nLXZhY2NpbmF0ZWQtYnV0LWhlLWlzbnQtYW50aS12YXgv&form=WSBSTK&cvid=9ea37a27bd114e6399d25878c8a8c39b&rtk=ezrh4ZA0aMAwTKaF5nCuUlpRsPyrBfKh2T9%2FjEAGg7vjBvYizw1JqI6U5IbHCsUJ`
It loads Bing instead of redirecting to the actual cbssports website.
The website/link was found from the startmenu Bing search on Windows 11.
## Which of my lists are you submitting it to?
LegitimateURLShortener
## Which adblocker(s) and version did you use when writing and testing the entries?

- [ ] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [x] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):
AdGuard Browser extension
Version 4.0.108 Beta: `https://github.com/AdguardTeam/AdguardBrowserExtension/releases/`
## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![image](https://user-images.githubusercontent.com/29574622/154318624-4af76383-7171-47ff-9501-fde092f5135d.png)

## (Optional) Which browser(s) and version did you use?

Microsoft Edge
Version 98.0.1108.55

**Comment by Nojuuu** [comment]
That url does not work for me even if I whitelist all parameters for that path with `@@||www.bing.com/ws/redirect/$removeparam`?

**Comment by SeriousHoax** [comment]
> That url does not work for me even if I whitelist all parameters for that path with `@@||www.bing.com/ws/redirect/$removeparam`?
> 
> Maybe the link was just broken?

You're right. It doesn't work anymore. 
Try this one. It's working at the moment. 
`https://www.bing.com/WS/redirect/?q=novak+djokovic&url=aHR0cHM6Ly93d3cuYmJjLmNvbS9uZXdzL3dvcmxkLTYwMzU0MDY4&form=WSBSTK&cvid=d53b40c49f7846d19a97198b8ce5d975&rtk=Q27HzkA%2Bh4nskfCkZ7QBEX6xl1ss%2BQ5UeYU%2BV4Kxsf%2FzVGAscxlnz0kfigKyJPlR`

**Comment by Nojuuu** [comment]
Hard to do testing with these links because they seem to expire super fast... but probably it is enough to just allow it on that specific path.

@iam-py-test

**Comment by SeriousHoax** [comment]
> Hard to do testing with these links because they seem to expire super fast... but it's probably enough that you only allow it on that specific path.
> 
> @iam-py-test

You're right. Easiest way to reproduce is to have Bing search enabled on Windows 10/11's start menu, search something and click on a news link.

**Comment by SeriousHoax** [comment]
> I only get normal Bing search links on Windows 10 and those work fine.
> 
> But does adding `@@||bing.com/ws/redirect/$removeparam=cvid` to your filters fix the issue for you or does it need form parameter too, as it seems it is also being removed?

Adding only this rule didn't fix it. According to ADG log `||bing.com^$removeparam=form` is casuing issue also. So yeah, your guess is correct. 
It gets fixed after adding this rule along with your previous one `@@||bing.com^$removeparam=form`

**Comment by iam-py-test** [comment]
I don't have access to Windows 11 machines and I don't want to go through the hassle of setting up a VM for it.
However, I'm unable to reproduce on my Windows 10 VM with either uBo or AdGuard

**Comment by Nojuuu** [comment]
Maybe just add `@@||bing.com/ws/redirect/$removeparam` to the list for now?

**Comment by iam-py-test** [comment]
Hopefully https://github.com/DandelionSprout/adfilt/commit/b3252c029f879b74eb02a8d3960c2a9d943f796f fixes this

**Comment by SeriousHoax** [comment]
> Hopefully https://github.com/DandelionSprout/adfilt/commit/b3252c029f879b74eb02a8d3960c2a9d943f796f fixes this
> 

Thanks. I'm not on my PC anymore so can't test at the moment. I'll tell you tomorrow after testing. Keep the issue open for now. 

BTW, I just saw that in the ClearURLs for uBO list, this rule is present.  
`@@||bing.*/WS/redirect/$removeparam`
So just letting you know in case using wildcard is better instead of dot com.

**Comment by iam-py-test** [comment]
Wildcard = all TLDs of bing
It looks like there are a ton of other TLDs for bing, so I will add a wildcard

**Comment by SeriousHoax** [comment]
Thanks. Everything is fine now. You may close this issue.
