### ISSUE TITLE
Duckduckgo breaks due to the Anti-Custom-Cursors

### ISSUE THREAD

**Issue by m0ddixx** [DandelionSprout/adfilt#51]
## Description:
The Problem occurs when you focus the text box on Duckduckgo's search results index.
Duckduckgo uses css selectors on the html tag where the filter scripts overrides the style which probably collides with the dynamic dom change which renders the page completely blank.
If i negate the specific filters, the text box shows the auto correct div as designated and nothing of the dom gets corrupted.

## Which adblocker(s) and version did you use when testing this?

- [ ] Nano Adblocker
- [ ] Nano Defender
- [x] uBlock Origin
- [ ] uBlock Origin Plus
- [ ] AdNauseam
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] Blokada
- [ ] Pi-hole

**Comment by DandelionSprout** [comment]
I sadly cannot reproduce the blank page, but I added a makeshift fix attempt yesternight based on your description. Does it work any better for you now?

**Comment by krystian3w** [comment]
For Firefox 70 possible use:

`cursor: revert`

**Comment by DandelionSprout** [comment]
I think that that particular list of mine is in need of a total overhaul, which makes me thankful that I listed numerous example pages inside the list. I'll see if I can look into it later tonight.

**Comment by DandelionSprout** [comment]
As I've now more or less completed a complete re-do of the list from scratch, this issue report is most likely no longer relevant to the list as such, so I'll declare it a resolved case. I will however leave this issue thread open for comments, just in case.
