### ISSUE TITLE
"NorwegianList.txt" broken in DNSBL/pfblockerng/pfsense

### ISSUE THREAD

**Issue by janegilv** [DandelionSprout/adfilt#52]
## Describe the problem below this line as meticulously and detailed as possible:
DNSBL/pfblockerng stops processing files which contain `[Adblock Plus ...]`. Since this was removed from your file DNSBL blocks all dns-lookups to all domains included in this file, which means quite a lot of sites gets broken. This file is probably automatically included in pfblockerng because it is part of easylist.

Any chance this line could be re-added?

## Which adblocker(s) and version did you use when testing this?
Other(s):
DNSBL/pfblockerng/pfsense

**Comment by DandelionSprout** [comment]
I admit to have been completely unaware that PFBlockerNG included my list by default, or that they for some reason still used the uBlock Origin-intended main version of that list.

Although I don't have a PFBlockerNG setup of my own to test all this with: The best solution for this that I can find, would be to tell them to replace it with [the hosts versions of my list](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/AdawayHosts). But first I'd need to find some way to properly contact them. Surely they must have some issue tracker or support E-mail address somewhere on the internet?

**Comment by DandelionSprout** [comment]
I've now attempted to contact them about it though https://github.com/pfsense/FreeBSD-ports/pull/713, which was my best guess as to an easily understandable way to tell them about it (although it doesn't seem to be monitored all that much). In the meantime you can try out [the hosts version](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/AdawayHosts) and/or [the Adblock Plus version](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP.txt) of my list instead.

**Comment by tingvold** [comment]
Well, what determines what is included in your hosts version? AFAIK, the `[Adblock Plus]` is there to tell PFBlockerNG how to treat the entries, and I believe it only includes entries where the rule would match the whole domain (and not a specific URL).

In other words; if you do not do the same logic in your hosts file, the issue would still pertain (just in another way).

**Comment by DandelionSprout** [comment]
With only a few exceptions, the whole-domain entries are almost identical between my uBO version and the Hosts version, except of course for removing wildcard entries and `$` denominators from the Hosts version. This means that e.g. `euroads.no` is blocked in both those versions (and in [the other 14-ish versions I have](https://github.com/DandelionSprout/adfilt/tree/master/NorwegianExperimentalList%20alternate%20versions)).

**Comment by DandelionSprout** [comment]
It'd actually be even more preferable for me to submit [the domains version](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltreDomains.txt) to them instead, as it is slightly more frequently updated, but I'd need some kind of confirmation that the wildcard entries at the bottom doesn't break pfBlockerNG either.

**Comment by DandelionSprout** [comment]
My understanding of the current situation, is that the uBO list version will almost guaranteedly be natively replaced by the hosts version in pfBlockerNG v2.2.5_27 (The next release), if anyone here were to be wondering about it.

**Comment by DandelionSprout** [comment]
So since this matter has (presumably) been fixed in pfBlockerNG-devel for several weeks, but probably won't be fixed in stable pfBlockerNG for several more months, do any of you guys have any opinions on whether this issue has been resolved or should stay open?

**Comment by eN0Rm** [comment]
Updated pfBlockerNG to 2.2.5_27 still had problems with this list.

**Comment by DandelionSprout** [comment]
I'm going to need a bit more information than that to begin to look into that. Does 2.2.5_27 still use the uBlock Origin list version by default? Or does it use the hosts file? Which list version are you using, maybe even both?

**Comment by eN0Rm** [comment]
This is the link to the list in pfBlockerNG 2.2.5_27
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt

**Comment by DandelionSprout** [comment]
I for one was able to confirm on a stock install some days ago that the link was https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/AdawayHosts; however, your comment confirms one of my theories well enough that there'd be no need for me to do a "Word against word" debate by now.

I'll add a note to the uBO version real quick to hopefully mitigate the situation furthermore.

**Comment by DandelionSprout** [comment]
With the release of pfSense 2.4.5 earlier today, and no reported problems with the Hosts version in the past 4 months once it had been applied, it's now time to declare this a resolved case. 🎉
