### ISSUE TITLE
Actually Legitimate URL Shortener Tool, possible broken rule: $removeparam=/^ICID=/i

### ISSUE THREAD

**Issue by BillyJoeJimBob** [DandelionSprout/adfilt#524]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Title: ➗ Actually Legitimate URL Shortener Tool
Version: 25February2022v1
Line: 265 $removeparam=/^ICID=/i,domain=~api.mapbox.com,~microsoft.com

this rule does not remove referrer: ICID
replacing the comma with a pipe after mapbox.com unbreaks the rule, see:

$removeparam=/^ICID=/i,domain=~api.mapbox.com|~microsoft.com

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.41.8

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

<img width="540" alt="Screen Shot 2022-02-25 at 4 56 53 AM" src="https://user-images.githubusercontent.com/11702508/155718969-b94f7a31-3779-4e70-b81a-627cb062e9d0.png">

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

Firefox 97.0.1

**Comment by DandelionSprout** [comment]
Oh, right. Thanks for spotting it. I've been in rough shape this week and was likely pretty distracted when I most recently edited that entry. Give me 3min to fix it.
