### ISSUE TITLE
[False Positive] `lijit.com` in the `Alternate versions Anti-Malware List/`

### ISSUE THREAD

**Issue by PeterDaveHello** [DandelionSprout/adfilt#537]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

It doesn't look like a malware website but just an advertisement/tracking site, a similar case like: #511

All of these secure DNS didn't block it:

 - OpenDNS
 - Cloudflare
 - Yandex
 - AkamaiETP
 - SafeDNS
 - CleanBrowsing
 - Neustar
 - Comodo
 - CONTROL D
 - Quad9

Also found it in some adblocking lists, like:

  - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
  - https://hostsfile.org/Downloads/hosts.txt
  - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts;showintro=0
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
  - https://v.firebog.net/hosts/AdguardDNS.txt
  - https://v.firebog.net/hosts/Prigent-Ads.txt
  - https://hosts.ubuntu101.co.za/domains.list

If you visit `https://lijit.com/`, it says:

> 
> Lijit is an ad serving domain owned by Sovrn Holdings, Inc.
> 
> If you have questions about the purpose of this domain, or about Sovrn, please read our [support documentation](https://knowledge.sovrn.com/what-is-the-lijit-ad-serving-domain).
> 
> For other questions, or to start advertising with Sovrn, [contact us](https://www.sovrn.com/contact/).

Some domain security report reference:

AlienVault - Open Threat Exchange
 - https://otx.alienvault.com/indicator/domain/lijit.com
Google Safe Browsing
 - https://transparencyreport.google.com/safe-browsing/search?url=lijit.com
McAfee SiteAdvisor
 - https://siteadvisor.com/sitereport.html?url=lijit.com
Norton Safe Web
 - https://safeweb.norton.com/report/show?url=lijit.com
OpenDNS
 - https://domain.opendns.com/lijit.com
URLVoid
 - https://www.urlvoid.com/scan/lijit.com/
VirusTotal
 - https://www.virustotal.com/en/domain/lijit.com/information/
Yandex Site safety report
 - https://yandex.com/safety/?l10n=en&url=lijit.com

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Alternate versions Anti-Malware List

**Comment by DandelionSprout** [comment]
I'm thinking "Surely the consequences can't be *that* big if I kept that entry?", but I'll remove that entry either way. Thanks again.

**Comment by iam-py-test** [comment]
This looks like it is my fault for not filtering my logs before reporting them.

**Comment by PeterDaveHello** [comment]
Thank you both!
