### ISSUE TITLE
Deezer account page

### ISSUE THREAD

**Issue by mimmiepower** [DandelionSprout/adfilt#54]
## Describe the problem below this line as meticulously and detailed as possible:
The buttons to change e-mail and password on https://www.deezer.com/account/ does not work due to `deezer.com##.modal-wrapper` in BrowseWebsitesWithoutLoggingIn.txt. The window that is supposed to appear when clicking the button(s) does not appear.

## Add a screenshot of the extension's logger:
I have personally added an exception in my filters to work around this issue, which is good enough for me, just reporting the issue to help, but I don't want to spend all day on it.

## Which adblocker(s) and version did you use when testing this?
- [ ] Nano Adblocker
- [ ] Nano Defender
- [X] uBlock Origin
- [ ] uBlock Origin Plus
- [ ] AdNauseam
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] Blokada
- [ ] Pi-hole

Version(s):
1.20.2

## Which filterlists did you use?
A lot but I have already pinpointed the issue down to BrowseWebsitesWithoutLoggingIn.txt

## Which browser(s) and version did you use?
Firefox Browser 71.0 (64-bit)

## (Optional) Which OS and version did you use?
- [X] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux (Debian-based)
- [ ] Linux (Not Debian-based)
- [ ] Android

Version:
1809

**Comment by DandelionSprout** [comment]
Thanks for the well-written report and for using that list of mine.

I believe I've identified the problem; or more precisely that the uAssets team identified the problem at some previous point in time, so I'll be copying over what I presume was their fix.

I'll try to replace `deezer.com##.modal-wrapper` with `deezer.com###modal_login:nth-ancestor(2)` in the hopes it'll fix the problem.

**Comment by DandelionSprout** [comment]
As there's been no indications in this thread that the fix didn't work, I'll declare this a resolved case. I'll leave the comments open just in case it didn't work after all.

**Comment by mimmiepower** [comment]
> 
> 
> Thanks for the well-written report and for using that list of mine.
> 
> I believe I've identified the problem; or more precisely that the uAssets team identified the problem at some previous point in time, so I'll be copying over what I presume was their fix.
> 
> I'll try to replace `[deezer.com##.modal-wrapper](http://deezer.com##.modal-wrapper)` with `[deezer.com###modal_login:nth-ancestor(2)](http://deezer.com###modal_login:nth-ancestor(2))` in the hopes it'll fix the problem.

Thank you for your kindness. And thanks, it works!
