### ISSUE TITLE
[False Positive] `d.clarity.ms` in the `Alternate versions Anti-Malware List/`

### ISSUE THREAD

**Issue by PeterDaveHello** [DandelionSprout/adfilt#544]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

It's added in 8bb28343d368794ab9b4c465bfa80db1f1cced43, it's not a malware website but just another tracking tool to help webmasters to understand their users.

From https://clarity.microsoft.com/:

> **See what your users want—with Clarity**
> Clarity is a free, easy-to-use tool that captures how real people actually use your site. Setup is easy and you'll start getting data in minutes.
>  GDPR & CCPA ready  No sampling  Built on open source

Checked with these secure DNS services, and none of them blocked it:

 - OpenDNS
 - Cloudflare
 - Yandex
 - AkamaiETP
 - SafeDNS
 - CleanBrowsing
 - Neustar
 - Comodo
 - CONTROL D
 - Quad9

Also found it in another adblocking list, but the domain doesn't exist in many lists: https://block.energized.pro/basic/formats/hosts

Some domain security report references:

AlienVault Open Threat Exchange (Didn't see any harmful indicator)
- https://otx.alienvault.com/indicator/domain/d.clarity.ms

Google Safe Browsing (No available data)
- https://transparencyreport.google.com/safe-browsing/search?url=d.clarity.ms

McAfee SiteAdvisor (Safe)
- https://siteadvisor.com/sitereport.html?url=d.clarity.ms

Norton Safe Web (Safe)
- https://safeweb.norton.com/report/show?url=d.clarity.ms

OpenDNS (Tag: Software/Technology)
- https://domain.opendns.com/d.clarity.ms

URLVoid (Nothing Found)
- https://www.urlvoid.com/scan/d.clarity.ms/

VirusTotal (clean)
- https://www.virustotal.com/en/domain/d.clarity.ms/information/

Yandex Site safety report(not infected)
- https://yandex.com/safety/?l10n=en&url=d.clarity.ms

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Alternate versions Anti-Malware List

May I send a pull request to remove it?

**Comment by DandelionSprout** [comment]
https://github.com/DandelionSprout/adfilt/commit/5ffee9721cb2ae832fcbca0188999b48993ec1aa apparently got to it before I did, so I'll run the script to fix the "Alternate versions" lists too now.

**Comment by DandelionSprout** [comment]
Note to self: I need to set up some kind of colour CSS tagging to prevent uploading to the wrong folders.

**Comment by PeterDaveHello** [comment]
Thanks, @DandelionSprout! Expect to see the improvement 🚀

**Comment by iam-py-test** [comment]
This seems to still be the repercussions of https://github.com/DandelionSprout/adfilt/issues/188#issuecomment-931753495 (which means it's my fault for not filtering my raw network logs
