### ISSUE TITLE
[False Positive] `clickagy.com` in the `Alternate versions Anti-Malware List/`

### ISSUE THREAD

**Issue by PeterDaveHello** [DandelionSprout/adfilt#545]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Just looks like another tracking service domain marked malware here.

Homepage: `https://www.clickagy.com/`

Checked with these secure DNS services, and none of them blocked it:

 - OpenDNS
 - Cloudflare
 - Yandex
 - AkamaiETP
 - SafeDNS
 - CleanBrowsing
 - Neustar
 - Comodo
 - CONTROL D
 - Quad9

Some domain security report references:

AlienVault Open Threat Exchange (Didn't see any harmful indicator, and whiltelisted)
- https://otx.alienvault.com/indicator/domain/clickagy.com

URLVoid (Nothing Found)
- https://www.urlvoid.com/scan/clickagy.com/

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Alternate versions Anti-Malware List

**Comment by iam-py-test** [comment]
I don't like tracking software, but I guess it shouldn't be blocked as malware
