### ISSUE TITLE
Annoyance list seems to break Twitter "block user" prompt

### ISSUE THREAD

**Issue by Admicos** [DandelionSprout/adfilt#547]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

trying to block anyone (by clicking the `...` menu on a reply, if that makes a difference) results in the block prompt quickly flashing away

disabling `twitter.com##.r-1pjcn9w:has(.r-1rnoaur)` seems to work, though i'm not sure what else this may break

### Add a screenshot of the extension's logger

![20220309 083512](https://user-images.githubusercontent.com/5564592/157379258-b61265d2-e1e0-4332-a19e-f23505c6f92f.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.41.8

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

```json
"selectedFilterLists": [
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "adguard-generic",
    "easylist",
    "adguard-spyware",
    "adguard-spyware-url",
    "block-lan",
    "easyprivacy",
    "urlhaus-1",
    "curben-phishing",
    "curben-pup",
    "adguard-annoyance",
    "adguard-social",
    "fanboy-thirdparty_social",
    "fanboy-annoyance",
    "fanboy-social",
    "ublock-annoyances",
    "dpollock-0",
    "mvps-0",
    "plowe-0",
    "TUR-0",
    "https://api.stopmodreposts.org/sites.txt",
    "https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting",
    "https://github.com/DandelionSprout/adfilt/raw/master/AnnoyancesList",
    "https://github.com/DandelionSprout/adfilt/raw/master/ImgurPureImageryExperience.txt",
    "https://github.com/yokoffing/filterlists/raw/main/PrivacyEssentials.txt",
    "https://github.com/yokoffing/filterlists/raw/main/AnnoyanceList",
    "https://raw.githubusercontent.com/llacb47/miscfilters/master/antipaywall.txt",
    "https://www.i-dont-care-about-cookies.eu/abp/",
    "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt",
    "https://abp.oisd.nl/",
    "https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist",
    "https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt"
  ],
```

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

98.0 (64-bit)

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Gentoo ~amd64

**Comment by DandelionSprout** [comment]
The entry seems to be several years old, and was written to match randomised class names (Something I'd never do in 2022). Thus it is most likely safe for me to remove that entry now. Thanks for the headsup.
