### ISSUE TITLE
Make styles optional in “Wikia: Pure Browsing Experience”

### ISSUE THREAD

**Issue by roryokane** [DandelionSprout/adfilt#55]
I like your list [Wikia: Pure Browsing Experience](https://github.com/DandelionSprout/adfilt/blob/master/WikiaPureBrowsingExperience.txt), but I have an issue with it. This rule in it adds styles that widen the body text to fill the width of the window:

https://github.com/DandelionSprout/adfilt/blob/d2ea511aa2dfb7712277d1f024b9b3c622cf6432/WikiaPureBrowsingExperience.txt#L37-L39

I find that this makes the articles hard to read. The problem with long lines is that the eye can get lost when looking for the beginning of the next line. The book [_Practical Typography_ recommends](https://practicaltypography.com/line-length.html) lines of length 45–90 characters, while with your style I get lines with as many as 170 characters.

I have some other nits about how I would change those custom style rules, but I don’t think they’re worth getting into. This is because I assume that since you have been using that full-width style for so long, you’re not interested in replacing it with whatever non-full-width styles I will come up with to make Fandom.com more readable.

Therefore, I only request that you move the custom styles from the “Widens the article bodies” section into another filter list or into a user style, leaving “Wikia: Pure Browsing Experience” with only the ad-blocking rules. That would free me from having to maintain my own fork of your ad-blocking rules. Such a fork would be identical but with the custom styles changed or removed.

If you agree with the idea of splitting out those styles but want help implementing it, I can make a pull request removing those styles from that filter list and editing the description to remove the mention of fixing “narrow article bodies”. I would leave it to you to create a new filter list with only those styles, though, because only you can decide what header comments (title, description, attribution, etc.) you want at the top.

**Comment by DandelionSprout** [comment]
Hmm... normally I'm a huge fan of making Wikia article bodies wider than the default of ~800px, to the point where I wouldn't browse Wikia without such rules. I've also felt that wider bodies help on neck-muscle stiffness and on showing more content on-screen at once.

However, since the exact same rules are also part of *Dandelion Sprout's Website Stretcher*, your request to remove them from *Wikia: Pure Browsing Experience* is in fact perfectly possible for me to do. Give me 10 minutes to do so.

**Comment by roryokane** [comment]
Thanks. FYI, the page-width-modifying styles I ended up adding for myself were these:

~~~
! Force sidebar content below the end of the article so it’s not always visible:
wikia.org,fandom.com###WikiaMainContent:style(width: 100% !important;)

! Restrict the maximum width to prevent overly-long lines:
! 720px plus two 25px margins is the same as the width of the header at the smallest breakpoint.
! With this width, body text seems to have a decent line length both with an infobox present and without one.
wikia.org,fandom.com###WikiaPage:style(max-width: 720px !important;)

! Flow the sidebars (which were moved to the bottom of the page) into 2 columns to save vertical space.
! These rules mostly emulate the website’s rules at a small breakpoint when this happens naturally.
wikia.org,fandom.com##.WikiaRail:style(display: block !important; column-count: 2 !important; width: auto !important;)
wikia.org,fandom.com##.rail-module:style(break-inside: avoid !important;)
wikia.org,fandom.com##.rail-sticky-module:style(position: static !important;)
~~~

I already made [a PR](https://github.com/DandelionSprout/adfilt/pull/58) to add those last three styles to your Website Stretcher styles. Why not the others? My first style already existed in your styles, and my second style is counter to your filter list’s goals.

**Comment by DandelionSprout** [comment]
Having thought about:

```
! Force sidebar content below the end of the article so it’s not always visible:
wikia.org,fandom.com###WikiaMainContent:style(width: 100% !important;)

! Restrict the maximum width to prevent overly-long lines:
! 720px plus two 25px margins is the same as the width of the header at the smallest breakpoint.
! With this width, body text seems to have a decent line length both with an infobox present and without one.
wikia.org,fandom.com###WikiaPage:style(max-width: 720px !important;)
```

—for a couple of hours, I feel it'd be a bad idea for me to add them, since they could directly conflict with *Website Stretcher* if both lists are used at the same time.

**Comment by roryokane** [comment]
Sorry, I hadn’t meant to sound like I was suggesting adding those two styles to this list. My “Why not the others?” question was supposed to be a rhetorical question, with the reasons why not given in my next sentence. I agree that it’s best to keep those styles out of the Wikia filter list.

**Comment by DandelionSprout** [comment]
Ah, okay. I admit to have been uncertain as to what your question had been implying, but it's nice to get it clarified that it was meant to be in the past tense.
