### ISSUE TITLE
Bug, destroyed AdGuard home, all top domain were blocked!

### ISSUE THREAD

**Issue by jayagami** [DandelionSprout/adfilt#551]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Thanks for you great work.
With respect, this filters just ruined my day.

In Adguard home, all .top domain were blocked !

### Add screenshots below if needed

adguard logs: 

```
Response details
Status
Blocked
Elapsed
0.28 ms
Response code
NOERROR
Rule(s)
||top^$denyallow=corriente.top|gdtot.top|nicenature.top|reminder.top|magocoro.top|castlevania.top|suiten.top
Dandelion Sprout's Anti-Malware List
Response
A: 0.0.0.0 (ttl=10)

```

![Snipaste_2022-03-14_20-05-00](https://user-images.githubusercontent.com/40586590/158168609-cedf151e-684a-4a16-9aca-69472437a57c.png)

### Add a screenshot of the extension's logger

Dandelion Sprout's Anti-Malware List

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

Version: 
v0.107.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Rule(s)
||top^$denyallow=corriente.top|gdtot.top|nicenature.top|reminder.top|magocoro.top|castlevania.top|suiten.top
Dandelion Sprout's Anti-Malware List

### Which browser(s) did you use when testing this?

Google Chrome

### Browser version(s)

not important

### Which OS(s) did you use when testing this?

Windows 10, Linux

### OS version(s)

not important

**Comment by DandelionSprout** [comment]
Generally speaking, `.top` domains are blocked due to their massive prevalence in malware sites and malware redirections. However, I am more than willing to whitelist `.top` sites that aren't malware. Which sites do you wish to have whitelisted?

**Comment by krystian3w** [comment]
Test allowed domains:

`corriente.top|gdtot.top|nicenature.top|reminder.top|magocoro.top|castlevania.top|suiten.top`

maybe denyallow/domain is omitted.

**Comment by jayagami** [comment]
> Generally speaking, `.top` domains are blocked due to their massive prevalence in malware sites and malware redirections. However, I am more than willing to whitelist `.top` sites that aren't malware. Which sites do you wish to have whitelisted?


Thanks for replying, actually I own few top domains, and have some private services running on it.

I think it is a bad idea to block all top domains.  
I mean anyone can have a top domain, it is the cheapest domain name I can find. Perhaps using blacklist mode is better.

**Comment by DandelionSprout** [comment]
In that case I suppose adding `||top^$denyallow=corriente.top|gdtot.top|nicenature.top|reminder.top|magocoro.top|castlevania.top|suiten.top,badfilter` into "Custom filtering rules" on your server would work for the immediate time being, but `$badfilter` sadly isn't powerful enough to be a permanently viable solution due to needing to be updated whenever new whitelistings are added upstream, whereas `@@||top^` would've whitelisted *all* `.top` domains.

I'm normally more than a little good with adblockers' syntaxes, but I can't come up with any miracle fixes for this.

**Comment by jayagami** [comment]
> In that case I suppose adding `||top^$denyallow=corriente.top|gdtot.top|nicenature.top|reminder.top|magocoro.top|castlevania.top|suiten.top,badfilter` into "Custom filtering rules" on your server would work for the immediate time being, but `$badfilter` sadly isn't powerful enough to be a permanently viable solution due to needing to be updated whenever new whitelistings are added upstream, whereas `@@||top^` would've whitelisted _all_ `.top` domains.
> 
> I'm normally more than a little good with adblockers' syntaxes, but I can't come up with any miracle fixes for this.
> 
> > Perhaps using blacklist mode is better.
> 
> I don't feel that this would be a viable option either; as despite how several people in the adblocking community have raised their eyebrows at that entry, more than 30,000 domains would've needed to be blocklisted. Twice this week has that entry saved me from malware on fake game ISO download sites.

Emmmm, I got you.

In that case, I think I'll just add my personal top domains to custom whitelist.
In adguard home, `/#custom_rules`, add:

```
@@||mydomain.top^$important
```

![image](https://user-images.githubusercontent.com/40586590/158351451-9277d155-786e-4ae9-a488-cc2f4d06029a.png)

Anyway, it works.

And thanks for your replying again, have a wonderful day.

**Comment by jayagami** [comment]
> Test allowed domains:
> 
> `corriente.top|gdtot.top|nicenature.top|reminder.top|magocoro.top|castlevania.top|suiten.top`
> 
> maybe denyallow/domain (
> 
> https://github.com/DandelionSprout/adfilt/blob/dd0468afda2cc639381d6624d13b3e8731171319/Dandelion%20Sprout's%20Anti-Malware%20List.txt#L24
> 
> ) is omitted.

Thanks, I think I'll just add my personal top domains to custom whitelist.

**Comment by jayagami** [comment]
> Test allowed domains:
> 
> `corriente.top|gdtot.top|nicenature.top|reminder.top|magocoro.top|castlevania.top|suiten.top`
> 
> maybe denyallow/domain (
> 
> https://github.com/DandelionSprout/adfilt/blob/dd0468afda2cc639381d6624d13b3e8731171319/Dandelion%20Sprout's%20Anti-Malware%20List.txt#L24
> 
> ) is omitted.

Thanks, I think  I'll just add my personal top domains to custom whitelist.
