### ISSUE TITLE
9191.ga  error

### ISSUE THREAD

**Issue by lisansas** [DandelionSprout/adfilt#555]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

https://9191.ga/

this is a image hosting web site，but the filter block it.

### Add a screenshot of the extension's logger

||ga^$denyallow=google.ga|filtri-dns.ga|dgdi.ga|voitures.ga|economie-gabon.ga

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

v0.107.5

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Anti-Malware List.txt

### Which browser(s) did you use when testing this?

Google Chrome, Firefox, Vivaldi, Brave Browser, Tor Browser

### Which OS(s) did you use when testing this?

Windows 10, macOS, Android

**Comment by lisansas** [comment]
I read the introduction and decided to close it.

**Comment by iam-py-test** [comment]
As I see no evidence that this domain is malicious, unless someone objects, I am allowlisting it.

**Comment by DandelionSprout** [comment]
Seems to be a Chinese-specific image upload site. While I don't have much confidence in such sites, it's at least not malware, so I won't object to it.
