### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#557]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

That filter may break page with AdBlock / ABP 3.4+:

> `#?#div[class^=css-] > div[tabindex="0"] + div[role=group]:-abp-has(> div)[data-testid`

https://github.com/DandelionSprout/adfilt/blob/7188140ad6cf5864ba59888132502f9395b1bf53/BrowseWebsitesWithoutLoggingIn.txt#L113

Because pop-up now lock scroll very often e.g. on:

`https://twitter.com/gorhill/status/997793137979510784`

### Add screenshots below if needed

No needed

### Add a screenshot of the extension's logger

No needed

### Which adblocker(s) did you use when testing this?

Adblock Plus (Firefox or Manifest V2), AdBlock (Firefox or Manifest V2)

### Adblocker version(s)

3.4+

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

🚪 Browse websites without logging in

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2), Microsoft Edge (Manifest V2)

### Which OS(s) did you use when testing this?

Windows 7

**Comment by DandelionSprout** [comment]
Twitter's recent login prompts are an abominable ungodliness that even I am struggling to write good entries against (Same goes for Facebook desktop-grade site versions, for that matter).

Considering lockscrolling is a cited factor (which ABP can't really fix at all), I presume I won't need to actually test the problem and can instead directly conclude that the problem can only really be solved by moving that one entry to the list's `!#include` extension file, which I'll do pretty quickly now.

**Comment by krystian3w** [comment]
I have report about breakage pop-up "block user" if we are logged:

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/2947

Maybe enough is add warning about problem if you don't have accout to rebuild ExtendedCss `:has()` or add detect classes specific to logged users.
