### ISSUE TITLE
Actually Legitimate URL Shortener blocks reporting on Twitter

### ISSUE THREAD

**Issue by tayloroneill** [DandelionSprout/adfilt#567]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

When trying to report a tweet with the filter list enabled, the popup window is blank. I have this issue both with uBO on desktop Twitter and AdGuard for Android on mobile Twitter. I did not have this issue until a couple of days ago so it appears to be a recent change.

### Add screenshots below if needed

<img width="602" alt="image" src="https://user-images.githubusercontent.com/61822772/161065399-856df278-a40b-4622-b50b-cc3663f6714e.png">

### Add a screenshot of the extension's logger

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/61822772/161065662-ce2a29ad-341e-4c81-96ac-1eb493e6123a.png">

### Which adblocker(s) did you use when testing this?

uBlock Origin, (Other)

### Adblocker version(s)

uBlock Origin 1.41.8
AdGuard for Android 3.6.41

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/61822772/161065770-9f3064a6-5105-4e19-8b15-857a334bec13.png">

### Which browser(s) did you use when testing this?

Brave Browser

### Browser version(s)

Brave beta 1.38.75 for macOS
Brave 1.36.122 for Android

### Which OS(s) did you use when testing this?

macOS, Android

### OS version(s)

macOS 12.3
Android 12

**Comment by DandelionSprout** [comment]
Could you add `@@$removeparam=source,domain=twitter.com` to your custom filters to see if that fixes the case?

**Comment by tayloroneill** [comment]
Yes, that resolves it.
