### ISSUE TITLE
Actually Legitimate URL Shortener breaks Libre.fm Listen

### ISSUE THREAD

**Issue by Elaborendum** [DandelionSprout/adfilt#574]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

If the list is enabled when you try to go to the Listen section of Libre.fm, the page starts rapidly changing through different unplayable songs until it stops at another unplayable song.

### Add screenshots below if needed

![listenfm](https://user-images.githubusercontent.com/71190696/164556186-ae0c5adf-a4ad-4a7b-a82a-aee8f9a31c43.gif)

### Add a screenshot of the extension's logger

![imagen](https://user-images.githubusercontent.com/71190696/164556352-56c43659-ffd7-4901-87c6-cd610205bebe.png)
![imagen](https://user-images.githubusercontent.com/71190696/164556746-d1a8dfd4-c335-4696-8dfc-1ef00a3d840a.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.42.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![imagen](https://user-images.githubusercontent.com/71190696/164556898-b3c4a8e2-1f0d-40eb-8b77-979e2cc4448d.png)

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

99.0.1

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

21H2

**Comment by DandelionSprout** [comment]
I must confess that when I long ago added `$removeparam=trackid` as a generic entry, it didn't dawn on me that the word "track" could also refer to audio tracks.

As such, this will of course be fixed pretty quickly now.
