### ISSUE TITLE
Legitimate URL Shortener breaks Monoprice.com size/color selection

### ISSUE THREAD

**Issue by butterbutts** [DandelionSprout/adfilt#580]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

On monoprice.com any product which comes in multiple versions, such as size, color, weight, etc, is not able to load the new page upon making a selection.
For example, https://www.monoprice.com/product?p_id=15833 is a 3D printer filament in multiple colors and weights. Selecting any of the available options will redirect to a 404 page.

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Firefox

### Which OS(s) did you use when testing this?

Windows 11

**Comment by DandelionSprout** [comment]
On analysis, the problem seems to be with the list's `$removeparam=PID,(...)` entry. I'll look into it pretty quickly now.
