### ISSUE TITLE
segmentfault.com

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#581]
### What happens/happend:

After scroll on first visit we have fake pop-up with recommended logon

### URL-s:

```
https://segmentfault.com/q/1010000003115620
https://segmentfault.com/q/1010000009476561
```

### My CSS/Extended CSS styles solution:

```css
segmentfault.com##.modal:has-text(你知道吗？)
segmentfault.com##.modal-backdrop:has(~ .modal:has-text(你知道吗？))
segmentfault.com##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)
segmentfault.com##.modal-open [style]:is([data-padding-right], [data-margin-right]):style(padding-right: 0 !important; margin-right: 0 !important;)
```

* The weirdest self is navigating with the attributes `[data-padding-right]`/`[data-margin-right]` - firstly I see as combo for `modal-open` pop-ups.

* `Nǐ zhīdào ma` we can change to better detection fake pop-up

* ExtendedCSS is optional for `.modal-backdrop` - cut for all pop-ups is not big fail

* To cover older browsers possible convert `is` to: `.modal-open [style][data-padding-right], .modal-open [style][data-margin-right]` 
Also will works faster if latest `:is` have lags similar to experminental implemenetation as `-moz-any`/`-webkit-any` (`:matches`/`:any`)

**Comment by krystian3w** [comment]
CJX may no support hide fake login pop-ups but recommend test:

`segmentfault.com#$#abort-on-property-read g_useSSR`

In uBo/AG syntax:

`segmentfault.com##+js(aopr, g_useSSR)`

**Comment by DandelionSprout** [comment]
I haven't been able to come up with anything better than the entries you proposed in the OP, so I'll add them verbatim.
