### ISSUE TITLE
Legitimate URL Shortener breaks Startpage search

### ISSUE THREAD

**Issue by bbhtt** [DandelionSprout/adfilt#582]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

1. Add https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt to uBlock Origin
2. Go to https://www.startpage.com
3. Right click on address bar and add it as a search engine (Firefox)
4. Do a search

Startpage will block the search (reduce other network interference, this page will also appear if VPN/Tor is in use):

![image](https://user-images.githubusercontent.com/62639087/165422817-7418d6a4-96ae-45d8-ac61-290dce363c35.png)

Seems they don't like the trimmed URL: https://www.startpage.com/sp/search?query=%s&cat=web&language=english

The original is: https://www.startpage.com/sp/search?query=%s&cat=web&pl=opensearch&language=english

The issue is resolved by adding an exception to:

https://github.com/DandelionSprout/adfilt/blob/457a0416753e1fb0fda522ec144619d1b7e27a77/LegitimateURLShortener.txt#L3279

`@@$removeparam=pl,domain=startpage.com` in uBlock Origin.

### Add a screenshot of the extension's logger

![image](https://user-images.githubusercontent.com/62639087/165423313-9904c44f-0f0b-4a17-8673-f6e86f30e48d.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.42.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

99.0.1

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Arch Linux

**Comment by DandelionSprout** [comment]
On analysis, the problem seems to have been caused by the https://github.com/DandelionSprout/adfilt/discussions/163#discussioncomment-2471760 thread. I'll remove the `||startpage.com^$removeparam=pl` entry right away.

**Comment by bbhtt** [comment]
Thank you. It works now, I force refreshed the list.
