### ISSUE TITLE
Badfilter/typo in LegitimateUrlShortener

### ISSUE THREAD

**Issue by NoMeansNowastaken** [DandelionSprout/adfilt#583]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Theres a typo in ||support.github.com^$removeparm=tag, it should be ||suport.github.com^removeparam=tag

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.42.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
uBlock filters – Annoyances
Adguard Base
EasyList
AdGuard Tracking Protection
AdGuard URL Tracking Protection
Block Outsider Intrusion into LAN
EasyPrivacy
Online Malicious URL Blocklist
AdGuard Annoyances
Fanboy’s Annoyance
Peter Lowe’s Ad and tracking server list
➗ Actually Legitimate URL Shortener Tool
ClearURLs for uBo
JPN: AdGuard Japanese

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

99.0.1

### Which OS(s) did you use when testing this?

Windows 10

**Comment by DandelionSprout** [comment]
The `$` sign is needed to make uBlock Origin recognise `removeparam`, whereas changing `support.` to `suport.` (with one P) wouldn't make sense because GitHub doesn't use a `suport.` subdomain.

**Comment by DandelionSprout** [comment]
Oh, wait, now I see what you mean. The "Removeparm" part. Give me 5min.
