### ISSUE TITLE
positivr.fr

### ISSUE THREAD

**Issue by Lairub** [DandelionSprout/adfilt#587]
## Path:

`https://positivr.fr/plant-moms-les-conseils-pour-verdir-nos-interieurs-fleurissent-sur-tiktok/`

## Which entry/entries are you submitting?

Annoyances - scrolling player: 

```
positivr.fr##.viously-sticked.viously-sticked-top-right
```
".viously-sticked-top-right" is optional, so can works too `##.viously-sticked`.

But filter generate bad look grayish leftover (but page no jumps).

In uBO/AdGuard/Brave possible repair this better.

```
! disable filters for ABP only
positivr.fr#@#.viously-sticked.viously-sticked-top-right
positivr.fr#@#.viously-sticked-top-right.viously-sticked
positivr.fr#@#.viously-sticked
! uBO solution (compatible with Brave/AdGuard)
positivr.fr##.viously-sticked:style(position: absolute !important;  top: 0 !important;  left: 0 !important;  bottom: 0 !important;  right: 0 !important;  width: 100% !important;  height: 100% !important;  z-index: 1 !important;  display: block !important;)
positivr.fr##.viously-sticked #unstick-button
```

## Which things do they block, hide, or unbreak?

(https://user-images.githubusercontent.com/101058844/166271765-b4e49504-9d4c-489c-9c0c-adb2047fdefc.PNG)

## Which of my lists are you submitting it to?

Annoyances?

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [x] AdGuard (Paid desktop version)
- [x] AdGuard (for browsers)
- [x] AdBlock (Firefox or Manifest V2)
- [x] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [x] AdNauseam

Other(s):

Adblocker version(s):

uBlock Origin 1.42b5

## (Optional) Which browser(s) and version did you use?

Firefox 102 Nightly.

**Comment by DandelionSprout** [comment]
Out of curiosity, can you get a screenshot of the grayish leftover too? I'm having some problems seeing it on Chrome when using `positivr.fr##.viously-sticked` and AdGuard French Filter, at least:

<details>

![image](https://user-images.githubusercontent.com/22780683/166394559-a98efc4d-45ed-4af6-87c4-95cc3fed034d.png)

</details>

**Comment by Lairub** [comment]
I mean minimal scroll page generate gray background in place for big player - then better works reset size and position to absolute.

**Comment by DandelionSprout** [comment]
Thanks for the explanation. I can now see the gray background. Upon testing the "uBO solution" entries from the OP and seeing they work surprisingly well, I think I'll go for this approach:

```
!#if false
positivr.fr##.viously-sticked
!#endif
positivr.fr##.viously-sticked:style(position: absolute !important; top: 0 !important; left: 0 !important; bottom: 0 !important; right: 0 !important; width: 100% !important;  height: 100% !important; z-index: 1 !important; display: block !important)
positivr.fr##.viously-sticked #unstick-button
```

(I use `!#if false` as a kinda unintended way to make an entry only apply to ABP and not to uBO/AG.)
