### ISSUE TITLE
Bing suggests the New Edge

### ISSUE THREAD

**Issue by hjstephens09** [DandelionSprout/adfilt#59]
## Which entry/entries are you submitting?
Bing search asks you to download the new Edge browser.
https://www.bing.com/search?pc=MOZI&q=chrome+webstore

## Which things do they block, hide, or unbreak?
https://i.postimg.cc/25knyHXh/edge.jpg

## Which of my lists are you submitting it to?
I Don't Want to Download Your Browser

## Which adblocker(s) and version did you use when writing and testing the entries?
- [x] Nano Adblocker
- [ ] Nano Defender
- [x] uBlock Origin
- [ ] uBlock Origin Plus
- [ ] AdNauseam
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] Blokada
- [ ] Pi-hole

Other(s):

Version(s):

## Which filterlists did you use? Failing to write this will result in instant report closing.
https://i.postimg.cc/x12zF0M9/Annotation-2020-01-24-095337.jpg

## (Optional) Which browser(s) and version did you use?
Firefox Nightly 74

**Comment by DandelionSprout** [comment]
Thanks for the report. It took me 10min to reproduce it (Apparently the banner is only visible when the market locale is set to en-US), but I believe I've written a functional entry for it, which I'll add right now.

**Comment by hjstephens09** [comment]
That was quick. Thanks! From: Imre Kristoffer EilertsenSent: Friday, January 24, 2020 10:10 AMTo: DandelionSprout/adfiltCc: hjstephens09; AuthorSubject: Re: [DandelionSprout/adfilt] Bing suggests the New Edge (#59) Thanks for the report. It took me 10min to reproduce it (Apparently the banner is only visible when the market locale is set to en-US), but I believe I've written a functional entry for it, which I'll add right now.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DandelionSprout** [comment]
Sounds to me like this case has been successfully resolved, in that case! 🎉
