### ISSUE TITLE
LegitimateURLShortener Startpage issue

### ISSUE THREAD

**Issue by Beventar** [DandelionSprout/adfilt#592]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Legitimate URL Shortener list breaks Startpage.

I know there was an issue #582 already opened about this but the problem is still present.

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

- All of the enabled by default uBlock Origin's lists (uBlock filters, Badware risks, Privacy, Quick fixes, Resource abuse, Unbreak) 

plus these:

- "Ads" (AdGuard Base, Mobile Ads, EasyList), 

- "Privacy" (AdGuard Tracking Protection, URL Tracking Protection, Block Outsider Intrusion into LAN, EasyPrivacy), 

- "Malware domains" (Online Malicious URL Blocklist, Phishing URL Blocklist, PUP Domains Blocklist)

- Legitimate URL Shortener

### Which browser(s) did you use when testing this?

Brave Browser

**Comment by DandelionSprout** [comment]
What aspect of that site is broken? The frontpage, the search results, any of the buttons/links, or anything else?

**Comment by Beventar** [comment]
It doesn't even load in it's stuck on the page that says if I'm using a VPN or TOR

![image](https://user-images.githubusercontent.com/51784467/168382391-9e8485a2-d550-4236-910a-328f04222c41.png)

**Comment by DandelionSprout** [comment]
In that case I'm unsure how to look into the problem, because `https://www.startpage.com/` loads normally on my end with that list. 
![image](https://user-images.githubusercontent.com/22780683/168383642-c2fb848a-eaa6-46c1-8c79-09463f3059d6.png)

**Comment by Beventar** [comment]
Do you have set Startpage as a search engine and searched for a query or just opened startpage.com?

Because in that case it also works but if I type a query it doesn't anymore

**Comment by Nojuuu** [comment]
Works fine for me, even if I set it as default.

**Comment by Nojuuu** [comment]
@DandelionSprout 

The only problem I noticed was that the search suggestions do not work if you do not allow the `segment` parameter in that path.

```
@@||www.startpage.com/suggestions$removeparam=segment
```

**Comment by Nojuuu** [comment]
@Beventar

Btw, did you add startpage as a custom search engine or are you using the one that is in the Braves search engine list by default? I was thinking that maybe if you added it as custom the search path has changed and you need to update it?

**Comment by Beventar** [comment]
The default one in Brave

**Comment by iam-py-test** [comment]
@Beventar any idea if `||add.startpage.com^$removeparam=source` breaks anything? I see it on `https://add.startpage.com/protection?source=serp`

**Comment by DandelionSprout** [comment]
Having decided this morning to look extra deeply into this, I've changed the search engines in Brave and Vivaldi to Startpage, enabled a bunch of lists (incl. the ones mentioned in the OP) in uBO and 'AdGuard for Chromium' respectively, and searched for *john madden* (My Lorem Ipsum-esque phrase to type into textboxes during tests), and still can't force the VPN warning to show up, sadly.

**Comment by DandelionSprout** [comment]
With no updates or further problems in the past 6 weeks, I suppose this issue can be closed now. Comments will remain open.

**Comment by Nojuuu** [comment]
@iam-py-test maybe limit it to `$document`?

**Comment by iam-py-test** [comment]
Thanks @c5aba924-b91a-4504-b8e7-9dd81a704703 @Nojuuu 
Fixed in https://github.com/DandelionSprout/adfilt/commit/abe717dde8103b766916963fd54de6e79de4b962. Please update your filterlists and retest.
