### ISSUE TITLE
uBO cant load list

### ISSUE THREAD

**Issue by akasaka99** [DandelionSprout/adfilt#595]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hi, the custom list: https://github.com/DandelionSprout/adfilt/blob/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt is giving me an error message on FF, uBo 1.42.4 => "A network error prevented the resource from being updated".
I have another of your list which updates perfectly fine.

### Add screenshots below if needed

![Screen Shot 2022-05-17 at 11 17 51](https://user-images.githubusercontent.com/7768945/168727994-6fa6f259-f6b9-472a-a305-49fed9ef1528.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.42.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

https://github.com/DandelionSprout/adfilt/blob/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

FF 100.0.1
Librewolf 100.0.1-1

### Which OS(s) did you use when testing this?

macOS

### OS version(s)

Mojave 10.14

**Comment by THEtomaso** [comment]
Try this link:
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt

**Comment by DandelionSprout** [comment]
(To the OP) You're supposed to use `raw.githubusercontent.com` links, not `/blob/` links. This applies to all lists hosted on GitHub.

**Comment by akasaka99** [comment]
Ok understood, it indeed worked.
Many thanks !
