### ISSUE TITLE
Thank you for fix Norske Filter for Nano Adblocker.

### ISSUE THREAD

**Issue by seba2282** [DandelionSprout/adfilt#6]
Only thank you. Autor Nano Adblocker updated version his Adblocker and Norske Filter works fine for me. One more thanks for fix.

**Comment by DandelionSprout** [comment]
Ah, sounds splendid. And also pretty surprising to me. I had decided to lock the original thread since I felt it was getting nowhere and so that I could relax and unwind a bit, so for it to have been resolved the following day is astonishing to me. My congratulations to you, then. 🎉

**Comment by seba2282** [comment]
And after few hours the same problem. I think it is a specific for region and configuration. I think badly driver network crushes and there are blocks and problems with connecting servers... I will try after clean install system.

**Comment by seba2282** [comment]
Hello sorry for too late write back.  Now I test http://repo.or.cz/FilterMirrorRepo.git/blob_plain/refs/heads/master:/NorwegianList.txt
and see work actual. If I will have some problem, will write again.

Best Regards
