### ISSUE TITLE
all .ml Domains are blocked

### ISSUE THREAD

**Issue by Herbertholzkopf** [DandelionSprout/adfilt#606]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hey,
I am using AdGuard Home in Docker and i added some filters (lists).
Before I start explaining my problem: I am not someone who knows how this filters really work and I dont know much about programming :)
I have some websites with .ml endig and all of them are not reachable because [the blocklist](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt) is blocking all of them.
I used the find Option in Visual Studio Code to find something relating to .ml
The line I found was:
`||ml^$denyallow=google.ml|mobili.ml|melody.ml|dcod.ml|info-matin.ml|amap.ml|mastodon.ml|worproject.ml|nothingprivate.ml|lingva.ml|lemmy.ml|bittor.ml|noic.ml|beatbump.ml`
I think that it means that only the given .ml-Domains can be accessed...
So all other .ml-Domains are blocked.
I hope you can understand the problem with this. I am 16 years old and I use these free Freenom Domains for school and little projects and a blog for my mum. 
Many people use those free domains because they can not afford the money to buy a domain...
I dont want to unblock all .ml Domains in AdGuard Home...  so can we delete this restriction and collect like with every other list the bad domains and dont block all?

I hope my English is not to bad :> 
Best wishes from Germany

### Add screenshots below if needed

![image](https://user-images.githubusercontent.com/93044485/173341557-088ce23a-29bc-47de-b8f1-e37ca62d7413.png)

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

AdGuard Home Docker
v0.107.7

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

As in the Screenshot: This blocklist is the only one that blocks the .ml-Domains

Here are all blocklists that I use:
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
https://adaway.org/hosts.txt
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt
https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh-online.txt
https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt
https://phishing.army/download/phishing_army_blocklist_extended.txt
https://v.firebog.net/hosts/Prigent-Malware.txt
https://v.firebog.net/hosts/AdguardDNS.txt
https://v.firebog.net/hosts/Shalla-mal.txt
https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
https://v.firebog.net/hosts/Easyprivacy.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
https://urlhaus.abuse.ch/downloads/hostfile/
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/samsung
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/MS-Office-Telemetry
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Fake-Science
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Win10Telemetry
https://urlhaus.abuse.ch/downloads/text/
https://urlhaus.abuse.ch/downloads/text_recent/

### Which browser(s) did you use when testing this?

Brave Browser

### Browser version(s)

Brave
Version 1.39.122 Chromium: 102.0.5005.115 (Offizieller Build) (64-Bit)

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

Windows 11 Home
21H2
Windows Feature Experience Pack 1000.22000.675.0

**Comment by DandelionSprout** [comment]
I understand your worry, but thankfully it's fairly easy to whitelist the domains you need for your school life and otherwise, by going to the AdGuard Home control panel → Filters → Custom filtering rules, and then add the domains you want to whitelist and add `@@||` before them and `^` afterwards. It'll look something like this: 
![image](https://user-images.githubusercontent.com/22780683/173429863-08e06950-6c3a-47ca-adcc-0ae9950a6aba.png)

**Comment by Herbertholzkopf** [comment]
I have done this for all my domains with .ml-ending but why is it even configuered that all .ml Domains are blocked by default?
Are all of them bad?

**Comment by DandelionSprout** [comment]
Essentially, `.ml` (as well as `.top`, `.cf`, `.pw`, and some others) were very commonly used around 2019 for malware sites and for redirections to malware sites, though it's not as huge of a problem nowadays (except that `.top` still has a whole lot of them).

**Comment by THEtomaso** [comment]
Completely whitelisting sites is far from an ideal solution though.

@Herbertholzkopf:
Perhaps you could provide a list of the domains that you need to access, so that they potetially can be added as exceptions?

**Comment by krystian3w** [comment]
What "all" then these will be allowed to open:

```
google.ml
mobili.ml
melody.ml
dcod.ml
info-matin.ml
amap.ml
mastodon.ml
worproject.ml
nothingprivate.ml
lingva.ml
lemmy.ml
bittor.ml
noic.ml
beatbump.ml
```

IMO AdGuard Home support `badfilter`, uBo reject line due no have generic `domain=ml`.

**Comment by Herbertholzkopf** [comment]
> 

Thanks for the reply :)

What you can see at klasse10a.ml is a Webpage from the notetaking programm [Notion](https://www.notion.so/product). The generated [link of the page](https://adventurous-rat-dd9.notion.site/SRS-Amberg-10a-564443ac379b46b0acc28631e6c3e623) in Notion is that put in a code creator at [Frutionsite](https://fruitionsite.com/). Frutionsite gives me than a code template for a [Cloudflare Worker](https://workers.cloudflare.com/) that creates the site with the klasse10a.ml domain. 

The idea is very good. I will try that out but how can I add a edited list to AdGuard Home? Is there a way to host this .txt-file or whatever the filter is somewhere for free?

**Comment by THEtomaso** [comment]
I get a bunch of errors in my browser console, for both `fruitionsite.com` and `notion.site` (some errors aren't even related to my heavy filtering).
Not my cup of tea this type of stuff..
Perhaps DandelionSprout can look further into things. :)

**Comment by THEtomaso** [comment]
If `klasse10a.ml` is your own closed domain, then the solution that DS suggested is indeed the best one (simply adding `@@||klasse10a.ml^` to your own filter).
If you're aware of any publicly available `.ml` domains that are incorrectly blocked, then you should report them here, so that DS can look into them, and potentially add them to his list of exceptions.

For a better understanding of why some TLDs are blocked by default, take a look here:
`https://www.spamhaus.org/statistics/tlds/`
(you can check the status of any TLD, by selecting them from the "TLD Check" menu, in the left sidebar)

**Comment by DandelionSprout** [comment]
>uBo reject AdGurad Home syntax lines due no have generic domain=ml

Good to know (though it's odd that they'd require such a `$domain` value). I do however advise uBO users to use that list's main version instead of the AGH version, where the entry is changed to `||top^$doc,domain=~corriente.top|~gdtot.top|~nicenature.top|~reminder.top|~magocoro.top|~castlevania.top|~suiten.top|~shucks.top|~1stream.top|~ambr.top`

**Comment by krystian3w** [comment]
I must check block 3-party reguests by `denyallow` on page if these don't help:

`||github.top^$all`

as long converted into:

`$all,domain=github.top`

**Comment by krystian3w** [comment]
https://github.com/DandelionSprout/adfilt/issues/610

**Comment by DandelionSprout** [comment]
With no further problems or concerns about it in the past 1½ months, I suppose this report can be closed for now. Comments will remain open.
