### ISSUE TITLE
New entries for cleaning up Quora

### ISSUE THREAD

**Issue by soystemd** [DandelionSprout/adfilt#609]
## Which entry/entries are you submitting?

```
! Remove quora's "Related" elements that look like regular answers
www.quora.com###mainContent>div>.q-box:has(.q-inlineFlex>.q-text.q-text:contains(Related))

! Remove quora's duplicate "Related questions" boxes that are amongst the answers (a related questions side panel already exists)
www.quora.com###mainContent>div>.q-box:has(div:upward(4)>.q-flex>.q-box>.q-text:contains(Related))
```

## Which things do they block, hide, or unbreak?

Quora's "Related" elements that look like regular answers are removed.
They are very confusing, and most of them are in the "Related questions"
side panel anyway.

![related-boxes](https://user-images.githubusercontent.com/70697865/175363983-eb9f9373-e39e-4831-9f75-ae0d02c59174.jpg)

Quora's "Related questions" boxes that are literally the same as the one
on the right side.

![related-questions-list](https://user-images.githubusercontent.com/70697865/175363851-bf7000b7-3c54-48d4-8343-6e0ecfa72bbf.jpg)

Before and After:

![quora-before-after](https://user-images.githubusercontent.com/70697865/175376158-124646cc-22c9-4c86-80a2-b123512828e0.jpg)

## Which of my lists are you submitting it to?

This could be added to a new list dedicated to Quora
(Quora Pure Browsing Experience maybe?)

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):

- uBlock Origin 1.43.0

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

> Which filterlists did you use?

This question is ambiguous. Which filterlists did I use for what?

> Failing to tell this will temporarily close the report until it has been told.

Why? Why is this information needed? I'm confused.

## (Optional) Which browser(s) and version did you use?

Firefox 101.0.1

**Comment by DandelionSprout** [comment]
I'll add those entries to the https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList parent file for now. Thanks for the headsup and suggestions.

>This question is ambiguous. Which filterlists did I use for what?

Which lists that were turned on in your adblocker during testing. e.g. EasyList, uBlock Filters, Peter Lowe's List, EasyPrivacy, etc. It's something that is nice to know just in case there are problems with making reported entries or problems visible on my PC, or to determine if someone else's list could be at fault if the report was about a problem instead of suggested entries.
