### ISSUE TITLE
Redirector Error: importing DandelionSproutRedirectorList.json

### ISSUE THREAD

**Issue by hjstephens09** [DandelionSprout/adfilt#61]
### Main Issue:
Cannot Import your json file for Redirector. I get the same error every time.

## Which entry/entries are you submitting?

DandelionSproutRedirectorList.json

## Which things do they block, hide, or unbreak?

https://postimg.cc/gwjjycN5

## Which of my lists are you submitting it to?
DandelionSproutRedirectorList.json

## Which adblocker(s) and version did you use when writing and testing the entries?
- [ ] Nano Adblocker
- [x] Nano Defender
- [x] uBlock Origin
- [ ] uBlock Origin Plus
- [ ] AdNauseam
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] Blokada
- [ ] Pi-hole

Other(s):

Version(s):

## Which filterlists did you use? Failing to write this will result in instant report closing.

https://postimg.cc/7GyLF1xv

## (Optional) Which browser(s) and version did you use?

Firefox Beta 73

**Comment by DandelionSprout** [comment]
I seem to be unable to reproduce the error note. Which method do you use to try to import it?

**Comment by hjstephens09** [comment]
My apologies. I was using

`https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout-s%20Redirector%20Assistant%20List/DandelionSproutRedirectorList.json`

instead of

`https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout-s%20Redirector%20Assistant%20List/DandelionSproutRedirectorList.json`

**Comment by DandelionSprout** [comment]
Ah, okay. That explains it.

(Although it's technically also possible to paste the text from the text box at the former link, it's generally vastly recommended to use the latter to ensure that no superfluous text gets mixed in.)
