### ISSUE TITLE
www.gymlibrary.ml blocked?

### ISSUE THREAD

**Issue by LeLunZ** [DandelionSprout/adfilt#610]
I am using AdGuard Home.  And the website got blocked through 'Dandelion Sprout's Anti-Malware List'.

![image](https://user-images.githubusercontent.com/31982496/175382107-99789b97-7a68-469a-b33f-235d09d27ab6.png)

[gymlibrary](https://www.gymlibrary.ml) should propably be unblocked.

**Comment by DandelionSprout** [comment]
On analysis, the site seems perfectly safe to me, so I'll whitelist it pretty quickly now.

**Comment by DandelionSprout** [comment]
Seems to be fixed in list version `24June2022v1`.

**Comment by krystian3w** [comment]
#606
