### ISSUE TITLE
www.googleadservices.com tracking URL 

### ISSUE THREAD

**Issue by hsantanna** [DandelionSprout/adfilt#618]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

If a Google result is an ad result it will come as an tracking URL like this

https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwjlyrnc6-H4AhVBE9QBHQ28CfEYABAHGgJvYQ&ae=2&dsh=1&agsac=gOR7j1M2-y8&cit=CkUKCQjwwo-WBhCCARI0AAu83Y4ij_2JwodI2xucTSB9Sd7MafcWp-40_ewsppOKyx95eTgXmwJZL7tRfHoEwKlGhBoCiCPw_wcB&ohost=www.google.com&cid=CAESa-D28LVhzCKpy-2qOlmyUThfG1PhrXARwi5SmpoSAn2gAXo7bP64-dfXRuX3igFjDjOa2rwD83GDOoUGhI7sl0R6frwpKrLWwcdPocNIlriC-lxfFNZ_TXVCxOmayT-db_ydJVMbYUOtMuvl&sig=AOD64_2NMGw9wdf0Oktc8OZ0MuU2JZtksA&ved=2ahUKEwinn63c6-H4AhUls5UCHQ2hCCUQkPAFegQIBhAB&dct=1&adurl=&ms=CoACabQOAoUy_sq_rwMbUidN34DcLg0c0tNG2P6y8NVm1JAlRCHa9QtfreVwahwhtYfjaFfYoDyNP6-zSfe-0OItXVYWfqHCkn8DB2xGObl7nGMzSUkKOflDS3efO-JWeOPmBzw3dlxwUoj7EaK0TltRG5Wz57SKt2FseUZsJukrqS3LCFgnIpye2q3Rkh_pcRu97fr_Cuj9sNu1hvuWfv1T31Bsfk0nDkUY8TshRCi3YzbWKIM5xzEKqSvNi9YIeM0zkuF2VMFRB7HpkNl83-kyExhE2yZglJqzPoH4knaA7xFA7IcMCsSIF2sB35Ao8uuWfhwse5c9xax_roQHYFPFogqAAnP4mb8X1rbE9Ir15TcQwXi-Whrdwjp8aOnffamEmrbCENmZfI6aZrnyEsEWJCIV2wD3ceBk1w-zGOdl3Ryv8MrFPqHqE6bBsoudnwFHBUFoJt14LlkxOH4_nBe0UiiCIONGr3jCSLukPxXpe_SUurGAgNNWOsr69IICGY_aPWx-lw-qea2YcjbBRILQr_56ZJ10IKMFiKfyxGsNC3YhwHicHtRXTflTmCSmNCD-g-CPfjzNYcIJjwFd0TFgo780v3O2zdo4IKQCBvca6T7C3cT9J22qXSNi30Fxv63x3V2dmTORQGWYv2QmkZC7HQipbMkqws7grUtdSwZFnqi-bRESEA9VaDYpSQq8cjJETARSw3w

I ask, please, if it is possible to clear the URL with a new rule, than include it to your lists. [AdAway ](https://github.com/AdAway/AdAway) blocks connections to the host www.googleadservices.com, so a URL clearing would be great. 
ClearURL once did this, but seems broken now. 

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt
https://github.com/DandelionSprout/adfilt/blob/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

Firefox Nightly for Android 

### Which OS(s) did you use when testing this?

Android

**Comment by hsantanna** [comment]
It's actually a URL redirect, so the purpose of the rule would be to get it to go directly to the destination URL

**Comment by hsantanna** [comment]
From that URL, would be possible to workaround the googleadservices.com server and go directly to the target URL? (I'm sorry if the question is stupid, but my knowledge is limited)

**Comment by DandelionSprout** [comment]
Sadly no. Adblockers lack the ability to change the main domain, and even other tools would struggle when the `googleadservices.com` URL doesn't contain the destination address.
