### ISSUE TITLE
tek.no - Blank white page

### ISSUE THREAD

**Issue by Schanzation** [DandelionSprout/adfilt#62]
Hello! When I open tek.no . It just load a blank white page. When I disable "NOR, DNK, ISL: Dandelion Sprouts nordiske filtre" the website loads normally as it's supposed to. Problem occurs when I am using Firefox, Brave and Vivaldi too.

Windows 10, 64-bit
Microsoft Edge Dev - Chromium version 81.0.416.6 
uBlock Origin 1.24.4

Event viewer:
https://imgur.com/a/clS0RRd

**Comment by DandelionSprout** [comment]
I saw the problem pretty much immediately. Me and my adblocking acquaintances have had some problems working around `Tek`'s new element "names" (They're very short), and I can see that `tek.no##.b` must suddenly have begun to work very poorly.

I'll remove that entry immediately.

**Comment by DandelionSprout** [comment]
With the problem entry removed, and three state-of-the-art entries added in its place as of https://github.com/DandelionSprout/adfilt/commit/ae886df4d64c2ef73e6d539f6c99e5cf8152e484, I declare this case a success.
