### ISSUE TITLE
Legitimate URL Shortener removes message body while quoting a post on PunBB-based forum

### ISSUE THREAD

**Issue by vapaamies** [DandelionSprout/adfilt#627]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

I have [own forum](http://forum.cantorsys.com) powered by PunBB engine ([custom mod](/CantorSystems/PunBB)). That uses regular not friendly links with params, so source post is indicated by `qid` param while quoting. Legitimate URL Shortener removes that, thus prevents message body to appear in the text box.

----

### Информация о запросе
Статус фильтрации:
Изменен

URL:
http://forum.cantorsys.com/post.php?tid=177&qid=981

Тип:
REMOVEPARAM

Источник:
forum.cantorsys.com

Правило:
`$~xmlhttprequest,removeparam=qid,domain=~ebay.*|~zhidao.baidu.com|~tastedive.com|~hkex.com.hk`

Фильтр:
Legitimate URL Shortener

----

[Official PunBB forum](https://punbb.informer.com) uses “pretty” URL scheme, so is not affected. When I disable Legitimate URL Shortener in AdGuard, problem goes off.

### Add screenshots below if needed

When enabled:
![When enabled](https://user-images.githubusercontent.com/4465205/180669747-eec1b271-1ddc-455a-9a2c-9c56f825fc7d.png)

When disabled:
![When disabled](https://user-images.githubusercontent.com/4465205/180669754-fc85b42f-081e-4c63-bc34-47683220d09a.png)

### Add a screenshot of the extension's logger

![Log-dd14299fccd7](https://user-images.githubusercontent.com/4465205/180669394-51bb6601-804c-4285-b8c3-90716f1687fd.png)

### Which adblocker(s) did you use when testing this?

AdGuard (for browsers)

### Adblocker version(s)

4.0.204

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

```json
{
  "protocol-version": "1.0",
  "general-settings": {
    "app-language": "ru",
    "allow-acceptable-ads": false,
    "show-blocked-ads-count": true,
    "autodetect-filters": false,
    "safebrowsing-enabled": false,
    "filters-update-period": 21600000,
    "appearance-theme": "system"
  },
  "extension-specific-settings": {
    "use-optimized-filters": false,
    "collect-hits-count": false,
    "show-context-menu": false,
    "show-info-about-adguard": false,
    "show-app-updated-info": true,
    "hide-rate-adguard": true,
    "user-rules-editor-wrap": false
  },
  "filters": {
    "enabled-groups": [
      1, 2, 4, 6, 7
    ],
    "enabled-filters": [
      14, 17, 1, 2, 3, 118, 201, 251, 207, 215, 204, 229, 241
    ],
    "user-filter": {
      "rules": "",
      "disabled-rules": "",
      "enabled": true
    },
    "whitelist": {
      "inverted": false,
      "domains": [],
      "inverted-domains": [],
      "enabled": true
    }
  },
  "stealth": {
    "stealth_disable_stealth_mode": false,
    "stealth-hide-referrer": true,
    "stealth-hide-search-queries": true,
    "stealth-send-do-not-track": true,
    "stealth-block-webrtc": false,
    "stealth-remove-x-client": true,
    "stealth-block-third-party-cookies": false,
    "stealth-block-third-party-cookies-time": 2880,
    "stealth-block-first-party-cookies": false,
    "stealth-block-first-party-cookies-time": 4320,
    "block-known-trackers": true,
    "strip-tracking-parameters": true
  }
}
```

### Which browser(s) did you use when testing this?

Vivaldi

### Browser version(s)

5.1.2567.73 (Chrome/98.0.4758.141)

### Which OS(s) did you use when testing this?

Windows 7

### OS version(s)

6.1.7601

**Comment by iam-py-test** [comment]
I will look into this...

**Comment by vapaamies** [comment]
Thanks for immediate feedback.

![Updated 03-38](https://user-images.githubusercontent.com/4465205/180673216-6b32d7e4-6a48-492f-9c2e-be4eccd8b07e.png)

Looks like filter has been updated (UTC+3), but nothing changed on the site. How long should I wait for reflection in AdGuard updates? You can also [drop me](mailto:vapaamies@yandex.ru) an email, will send you forum creds if needed for more testing. Registration was closed because of spammers, sorry.

**Comment by DandelionSprout** [comment]
In most cases, it depends on AdGuard's processing process for included lists, which can be kept an eye on at https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_251_LegitimateURLShortener . At the time of writing, it was most recently processed by them 4 hours ago, so the next processing will likely be within the next 1-2 hours at most.

**Comment by vapaamies** [comment]
The issue is fixed now. Thank you.
