### ISSUE TITLE
flows.nodered.org

### ISSUE THREAD

**Issue by Johnnyyr** [DandelionSprout/adfilt#632]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

i think the page should not be blocked, it is an important part of NodeRed 

flows.nodered.org

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

[Adblock Plus 3.13]
! Title: 💊 Dandelion Sprout's Anti-Malware List (for AdGuard Home, and for AdGuard for Android/Windows' DNS filtering)
! Version: 31July2022v1
! Expires: 2 days

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

**Comment by DandelionSprout** [comment]
I have been able to reproduce the problem, and will add a fix for it fairly soon now. 
![image](https://user-images.githubusercontent.com/22780683/182656476-40e02a13-6aa2-45bc-a848-4c259ac16be2.png)
