### ISSUE TITLE
Message hidden on Instagram

### ISSUE THREAD

**Issue by ujjwal123123** [DandelionSprout/adfilt#634]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Steps to reproduce:
1. Install uBlock Origin
2. Install _Browse websites without logging in_ filter list
3. Log in to Instagram and visit https://www.instagram.com/direct/inbox/

Expected result: messages should be shown on the right side

Actual result: messages are hidden by a filter rule `instagram.com##div[class^=" _"][style]`

### Add a screenshot of the extension's logger

![image](https://user-images.githubusercontent.com/8354378/183711839-43d2f693-4bc4-4156-9403-8dba28fd78b6.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.43.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Standard fiterlists pre-installed with uBlcok Origin and version 06August2022v1 of _Browse websites without logging in_ list.

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

Version 103

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Manjaro Linux

**Comment by DandelionSprout** [comment]
I've fixed it for now, as of `10August2022v1`

**Comment by ujjwal123123** [comment]
Thanks for looking into this. However, `instagram.com##div[style*=spectrum-cherry]` rule also causes an issue. It hides the lightbox/popup that Instagram uses to preview posts.

Screenshot with the rule disabled:
![image](https://user-images.githubusercontent.com/8354378/183858927-ee82b7fb-2eb9-4eea-bef6-b2ba7d9b54cc.png)

![image](https://user-images.githubusercontent.com/8354378/183859199-4f663b10-fe8a-41a0-ae37-535c358847a2.png)

**Comment by DandelionSprout** [comment]
If I've got a lucky day, you can try out the new `10August2022v3` version, which should hopefully dramatically reduce the chance for false positives.

**Comment by ujjwal123123** [comment]
I updated the filter list and could not reproduce either of the issues that I mentioned above.
