### ISSUE TITLE
twitter.com remove share link params

### ISSUE THREAD

**Issue by wavygecko** [DandelionSprout/adfilt#635]
## Which entry/entries are you submitting?

The Twitter mobile app includes unnecessary share parameters `s` and `t` for tracking shared links (e.g., `https://twitter.com/kilogramrose/status/1556748153323343873?s=20&t=8XbNa2tcWajX-boLDfZfdw`). I propose adding the following filters to the URL Shortener list:

```
||twitter.com^$removeparam=s
||twitter.com^$removeparam=t
```

## Which of my lists are you submitting it to?

Legitimate URL Shortener

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin

Adblocker version(s): 1.43

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

- Added
  - adguard-spyware-url
  - block-lan
  - curben-phishing
  - curben-pup
  - adguard-annoyance
  - ublock-annoyances
  - LegitimateURLShortener
- Default
  - ublock-filters
  - ublock-badware
  - ublock-privacy
  - ublock-abuse
  - ublock-unbreak
  - ublock-quick-fixes
  - easylist
  - easyprivacy
  - urlhaus-1
  - plowe-0

## (Optional) Which browser(s) and version did you use?

Firefox 103

**Comment by DandelionSprout** [comment]
Those two parameters used to be removed, but had to be un-removed because `s` determines (or determined?) whether tweets load all comments at once or only the top 3 comments; whereas removing `t` caused problems with at least *some* links, though I've forgot which ones.
