### ISSUE TITLE
Dplay

### ISSUE THREAD

**Issue by laurits4** [DandelionSprout/adfilt#64]
## Describe the problem below this line as meticulously and detailed as possible:
When i try to watch Ex on the beach on dplay.dk i cant watch it, either the video wont start og only the audio plays. Sometimes it says "kan ikke afspille video, der skete noget uventet" (cant play video, something unexpected happened) or it the screen just becomes black.

## Add screenshots below if needed:
![image](https://user-images.githubusercontent.com/61914843/76147645-cd149980-609e-11ea-9de4-bc775f6b0814.png)
![image](https://user-images.githubusercontent.com/61914843/76147653-eae1fe80-609e-11ea-8800-cfe5467c5ef1.png)

## Add a screenshot of the extension's logger:

![image](https://user-images.githubusercontent.com/61914843/76147522-778bbd00-609d-11ea-8778-7bbec9a75391.png)

## Which adblocker(s) and version did you use when testing this?

- [ ] Nano Adblocker
- [ ] Nano Defender
- [x] uBlock Origin
- [ ] uBlock Origin Plus
- [ ] AdNauseam
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] Blokada
- [ ] Pi-hole

Other(s):

Version(s):
uBlock Origin v1.24.4

## Which filterlists did you use? Failing to write this will result in instant report closing.

![image](https://user-images.githubusercontent.com/61914843/76147441-7c9c3c80-609c-11ea-8f65-515d4a85889a.png)

## Which browser(s) and version did you use?

Google Chrome

## (Optional) Which OS and version did you use?
- [x] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [ ] macOS
- [ ] Linux (Debian-based)
- [ ] Linux (Not Debian-based)
- [ ] Android

Other(s):

Version:

**Comment by laurits4** [comment]
Sometimes it just plays the video normally with ads. If you want a better screenshot of the logger i can get that.

**Comment by DandelionSprout** [comment]
I can only seem to replicate this with *Dandelion Sprouts nordiske filtre* turned off. Are you sure that you've updated the lists properly? And if you click on the ́`NOR, DNK, ISL: Dandelion Sprouts nordiske filtre` button, which version number is it showing?

**Comment by laurits4** [comment]
I don't know what i clicked but it all seems to work now, also i want to thank you for all the effort you put into this.

**Comment by DandelionSprout** [comment]
Congratulations!

I re-did the entries for `Dplay` entirely earlier this week, so I can only assume that a good ol' list update or other measures was all that was needed.
