### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by DIWesser** [DandelionSprout/adfilt#653]
I'm not very familiar with adblock rules, so sorry if this is a newb question, but this looks off to me. Should this line end with `^$document` rather than `^`?

https://github.com/DandelionSprout/adfilt/blob/5f1f1f1f0bdd026ebd08dca799a1f8808c56dc59/RedditTrashRemovalService.txt#L82

**Comment by iam-py-test** [comment]
> `||reddit.com/r/KotakuInAction^`

Based on the other rules around it, I would guess probably you are right.
Based on my understanding, `||example.com/evil^` should block any website from loading `example.com/evil` (i.e. as an image) but does not prevent you from going to `example.com/evil`, while `||example.com/evil^$document` only blocks you from visiting `example.com/evil`.

**Comment by DandelionSprout** [comment]
Many of my decisions to use (or to not use) `$` values are often done on the spur and on stomach feeling alone.

My faint memory is that I intended `||reddit.com/r/KotakuInAction^` at the time to mean it needed *more* blocking than what `$document` would've done (e.g. by possibly blocking CSS, images, videos, etc.), but I know better nowadays and know that it likely resulted in *less* blocking before that subreddit was banned.
