### ISSUE TITLE
Empty Holders on VG

### ISSUE THREAD

**Issue by fosam** [DandelionSprout/adfilt#655]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Empty ad placeholders appearing in VG articles.

### Add screenshots below if needed

![vg](https://user-images.githubusercontent.com/52612348/193092345-1aa0739b-1d40-4f8b-99e9-4d320d4e3762.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.44.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![list](https://user-images.githubusercontent.com/52612348/193092732-40b89146-8627-4dc2-adac-42745827fced.png)

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Browser version(s)

106.0.5249.62

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

21H2

**Comment by fosam** [comment]
An out of topic question..

Videos are not able to play on VG, and i found out the issues is cause by Fanboys enhanced tracking list, when i uncheck this filter the videos start playing again, so i have to either disable this filter or turn off uBlock to watch a video.

I wanted to report this to Fanboy's issue tracker but i see the issues are not maintained.

Any tips how i can keep this filter without it affecting video playback? i'm not sure how to troubleshoot it.

![image](https://user-images.githubusercontent.com/52612348/193127141-d763adc6-9293-4a39-8b6e-4a096418a197.png)

**Comment by iam-py-test** [comment]
> Any tips how i can keep this filter without it affecting video playback? i'm not sure how to troubleshoot it.

Try adding `@@||time.akamai.com^$xhr,domain=direkte.vg.no` to the "My filters" tab and trying again. That _should_ fix the issue. I think this has something to do with it being CNAMEd to `e1534.dscb.akamaiedge.net`, but not sure.

If not, can you open the [uBlock Origin logger](https://github.com/gorhill/uBlock/wiki/The-logger), reproduce the issue, and post the contents?

**Comment by fosam** [comment]
> Try adding `@@||time.akamai.com^$xhr,domain=direkte.vg.no` to the "My filters" tab and trying again. (Be sure to clear the cache with Control-Shift-R) That _should_ fix the issue. I think this has something to do with it being CNAMEd to `e1534.dscb.akamaiedge.net`, but not sure.

Thanks! it works, i just had to changed it to `@@||time.akamai.com^$xhr,domain=vg.no` instead.

> Off-topic
> Off-topic, but I am curious why "uBlock Origin Badware" and the "Online Malicious URL Blocklist" are disabled in your screenshot, as that isn't default.

To be honest, i want to use as few filters as possible and i also never felt the need to enable these as i'm quiet careful with the sites i visit and i can also spot if something is suspicious on a website easily, and i also have never had a bad experience with some sites while these filters are off, but hey, maybe that's just me.

Any other filter suggestions? i mainly ecounter some Anti-adblock annoyances on some websites these days, so any filters that can help with this be appreciated.

**Comment by DandelionSprout** [comment]
>Any other filter suggestions? i mainly ecounter some Anti-adblock annoyances on some websites these days, so any filters that can help with this be appreciated.

I generally warmly recommend to all uBO users to turn on *AdGuard Base* from the "+ Ads" section, and it baffles me why uBO's dev team still hasn't made it a default-on list.

**Comment by fosam** [comment]
Done. Thanks! 👍🏻

**Comment by iam-py-test** [comment]
> i want to use as few filters as possible and i also never felt the need to enable these as i'm quiet careful with the sites i visit and i can also spot if something is suspicious on a website easily

Just my opinion, but those filters never have slowed anything down for me (though I have a fast system), and I pretty much never notice them. I also consider myself to be careful with what websites I visit, but I figure extra security isn't going to hurt.

**Comment by fosam** [comment]
> > i want to use as few filters as possible and i also never felt the need to enable these as i'm quiet careful with the sites i visit and i can also spot if something is suspicious on a website easily
> 
> Just my opinion, but those filters never have slowed anything down for me (though I have a fast system), and I pretty much never notice them. I also consider myself to be careful with what websites I visit, but I figure extra security isn't going to hurt.
> 
> > Thanks! it works, i just had to changed it to @@||time.akamai.com^$xhr,domain=vg.no instead.
> 
> Sorry, my mistake.

I will also try to enable these.
