### ISSUE TITLE
AdGuard Home Compilation List blocks youtube-ui.l.google.com

### ISSUE THREAD

**Issue by bbhtt** [DandelionSprout/adfilt#656]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

https://github.com/DandelionSprout/adfilt/blob/951519c707263ea201fbd08a2675fc8807a916a7/AdGuard%20Home%20Compilation%20List/AdGuardHomeCompilationList.txt#L42117

Blocks YouTube embedded posts on sites like reddit and also on any YouTube 1st party domain (I guess) as `https://youtube-ui.l.google.com/` is blocked by that filter

For example https://www.reddit.com/r/chess/comments/xscgbq/garry_kasparov_on_magnus_v_hans_cheating/

### Add screenshots below if needed

![image](https://user-images.githubusercontent.com/62639087/193394555-aaa92b71-314e-44a4-8b15-f94901cf0849.png)

### Add a screenshot of the extension's logger

![image](https://user-images.githubusercontent.com/62639087/193394561-f102752f-ddc5-40bd-be35-e2c6ce7b2cd1.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.44.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

All standard uBlock origin filters + 

![image](https://user-images.githubusercontent.com/62639087/193394628-bf6ae105-980d-4e77-ba14-4e7576f7d374.png)

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

Nightly 107

### Which OS(s) did you use when testing this?

(Other)

### OS version(s)

Archlinux

**Comment by bbhtt** [comment]
Adding an exception through the logger works, the embed is displayed correctly

**Comment by DandelionSprout** [comment]
I admit that I did not anticipate a scenario that someone would one day use a list with "AdGuard Home" in its title in uBlock Origin.

I'll think of something to fix the situation with within the next hour or so.

**Comment by bbhtt** [comment]
Ahh, I didn't realize it was only for Adguard Home, filterlists.com shows uBO as supported for this list.

Anyway, thanks!

**Comment by DandelionSprout** [comment]
Well, it does support uBlock Origin perfectly well, it's just not optimised or designed with uBO in mind. 😅
