### ISSUE TITLE
gamecopyworld.com

### ISSUE THREAD

**Issue by p1r473** [DandelionSprout/adfilt#66]
## Describe the problem below this line as meticulously and detailed as possible:
contains game downloads like trainers, cheats, savegames, etc is blocked 

## Which adblocker(s) and version did you use when testing this?

- [ ] Nano Adblocker
- [ ] Nano Defender
- [ ] uBlock Origin
- [ ] uBlock Origin Plus
- [ ] AdNauseam
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] Blokada
- [X] Pi-hole

Other(s):

Version(s): 5.0

## Which filterlists did you use? Failing to write this will result in instant report closing.
 https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt 
 
This website contains game downloads like trainers, cheats, savegames, etc

**Comment by DandelionSprout** [comment]
This is a complicated matter for me to rule on. I recall trying to download a Rayman M trainer (or whatever it was) 2 years ago, upon which I insta-noped out of that site when it instead downloaded some other file with a 20-character-long file extension.

But even with that experience in mind, I am aware that many people seem to successfully use `GameCopyWorld` for its intended purposes, so a full block may have been heavy-handed for me to do after all. Give me an hour or two, and I'll think of something.

**Comment by DandelionSprout** [comment]
I am putting my judgment on hold for a couple days, until I can feel sure if it's safe to even browse that site or not, let alone downloading things on it and its many affiliated hosting servers.

**Comment by p1r473** [comment]
Whatever you wish. I whitelisted on my end, just alerting you FYI.

**Comment by DandelionSprout** [comment]
I was originally hoping for https://github.com/easylist/easylist/issues/5399 to be fixed before I'd resume my research, but it was admittedly just files hosted on the server and not malware ads as such. It also didn't help my case that as a Norwegian fellow, `gamecopyworld.com` redirects me to `gamecopyworld.eu` (thus the entry was virtually useless for myself); or that I don't want to lose my status of being listed on Firebog's curated list of lists.

I'll therefore take a chance and attempt to remove the entry from all list versions *except* the uBlock Origin and raw-domains versions (as I use those two versions especially much), thus it'll likely be fixed for most Pi-Hole users (incl. you) later today.

**Comment by p1r473** [comment]
Thank you!

**Comment by DandelionSprout** [comment]
Presuming my fix has gone live to most users of hosts-file-based tools by now, I'll consider this to be a fixed case now.
