### ISSUE TITLE
Amazon issue

### ISSUE THREAD

**Issue by privacyguy123** [DandelionSprout/adfilt#668]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Selecting size does not bring up "add to basket" menu on the right - lots of console errors. With "Actually Legitimate URL Shortener Tool" list turned off in my Ublock it works fine again.

https://www.amazon.co.uk/gp/product/B08T6C4RVM/ref=ox_sc_act_title_2?th=1&psc=1

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.44.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
AdGuard Base
EasyList
AdGuard Tracking Protection
AdGuard URL Tracking Protection
Block Outsider Intrusion into LAN
EasyPrivacy
AdGuard Annoyances 
EasyList Cookie
uBlock filters – Annoyances
➗ Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

106.0.1

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

21H2

**Comment by Nojuuu** [comment]
Try 
```
@@||amazon.*/gp/twister/ajaxv2$removeparam=psc
```

**Comment by privacyguy123** [comment]
That seems to fix it yep - will this be merged with the uBlock list?

**Comment by DandelionSprout** [comment]
I can try to apply the fix to Legitimate URL Shortener real quick.

**Comment by DandelionSprout** [comment]
Actually, it seems like `$(...)removeparam=psc` has been removed 2 days ago, so a simple list update in your uBO settings should fix it.
