### ISSUE TITLE
blank feed on facebook . com

### ISSUE THREAD

**Issue by manuel-martinez-dev** [DandelionSprout/adfilt#669]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hi @DandelionSprout , :)

it seems that the following filter is causing the main feed to appear blank, so Facebook breaks.

`facebook.com#?#div[role="feed"] > div:-abp-has(a[class][href][role][tabindex]:has-text(Sponsoroitu))`

### Add screenshots below if needed

![FB-broken-Fin-b](https://user-images.githubusercontent.com/40897997/197551739-dfb5ad60-3c4c-4e8d-aa7b-c424531a6e50.jpg)
![FB-broken-Fin](https://user-images.githubusercontent.com/40897997/197551745-f622ffa9-f9a4-4017-accc-c9a09b0dc5d4.jpg)

### Add a screenshot of the extension's logger

you can also see the following report from ABP if needed:

https://reports.adblockplus.org/752d01f6-9bf4-4873-be76-d1e75e5b4d05#tab=filters

### Which adblocker(s) did you use when testing this?

Adblock Plus (Firefox or Manifest V2)

### Adblocker version(s)

Version number 3.14.2

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Easyprivacy
ABP filters
Dandelion Sprout's Nordic Filters+EasyList

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Browser version(s)

Version 106.0.5249.119 (Official Build) (64-bit)

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Ubuntu 22.04.1 LTS

**Comment by DandelionSprout** [comment]
The problem entry containing "Sponsoroitu", a Finnish word, most likely means that you could contact https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues about it as well, since his list is where the ABP version of "Nordic Filters" gets its Finnish entries from.

I should probably contact him about it too, but I'm feeling a bit sleepy this afternoon.

**Comment by manuel-martinez-dev** [comment]
Thanks @DandelionSprout ... I just filed a quick issue on the finnish list as you mentioned.

https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues/429

**Comment by manuel-martinez-dev** [comment]
whoops... I didn't see the previous comment prior to mine... that was quick :)

thanks again

**Comment by peace2000** [comment]
Yeah I fixed this on Saturday. FB made changes that caused this rule to block legit posts.
