### ISSUE TITLE
Can't access any file in TransferNow

### ISSUE THREAD

**Issue by Silejonu** [DandelionSprout/adfilt#678]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

When clicking on a TransferNow link, the URL gets shortened too aggressively and any download link redirects to the error page below.

Example link: https://www.transfernow.net/dl/202211030hGGJZb5 [available until : 2022-11-10 at 8:37 PM (GMT)]

The following lists trigger the issue:
- AdGuard URL Tracking Protection
- https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt
- https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt

### Add screenshots below if needed

![Screenshot from 2022-11-03 21-41-34](https://user-images.githubusercontent.com/48565914/199829835-bc6b3346-8771-4d13-b89c-5e0d46ae81e7.png)

### Add a screenshot of the extension's logger

![Screenshot from 2022-11-03 21-43-53](https://user-images.githubusercontent.com/48565914/199830176-1d0b80c7-8e22-4aed-ae69-8dd6cb674468.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.44.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-quick-fixes",
    "ublock-abuse",
    "ublock-unbreak",
    "adguard-generic",
    "adguard-mobile",
    "easylist",
    "adguard-spyware",
    "adguard-spyware-url",
    "block-lan",
    "easyprivacy",
    "urlhaus-1",
    "curben-phishing",
    "curben-pup",
    "adguard-annoyance",
    "adguard-social",
    "fanboy-thirdparty_social",
    "fanboy-cookiemonster",
    "ublock-annoyances",
    "plowe-0",
    "CHN-0",
    "DEU-0",
    "FRA-0",
    "JPN-1",
    "KOR-1",
    "RUS-0",
    "THA-0",
    "VIE-1",
    "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt",
    "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs for uBo/clear_urls_uboified.txt"

The following lists trigger the issue:
- AdGuard URL Tracking Protection
- https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt
- https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

106.0.2 (64-bit)

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Arch Linux, up-to-date

**Comment by Silejonu** [comment]
Other filters also result in the same behaviour. See https://github.com/AdguardTeam/AdguardFilters/issues/134007

**Comment by DandelionSprout** [comment]
I think I see the possible issue entry, though it's absolute insanity for any website like `TransferNow` to decide to use `utm_source` to determine which page to load.

I'll see if I can whitelist that entry on that site within a few minutes.

**Comment by DandelionSprout** [comment]
@iam-py-test When you have time, would you want to look into whitelisting `transfernow.com` from `$removeparam=/^utm(_[a-z_]*)?=/` in Clear URLs uBOified?

**Comment by iam-py-test** [comment]
> @iam-py-test When you have time, would you want to look into whitelisting `transfernow.com` from `$removeparam=/^utm(_[a-z_]*)?=/` in Clear URLs uBOified?

Doing that right now.

**Comment by iam-py-test** [comment]
> Other filters also result in the same behaviour. See [AdguardTeam/AdguardFilters#134007](https://github.com/AdguardTeam/AdguardFilters/issues/134007)

I have brought that to the attention of the AdGuard URL Tracking Protection filter maintainers, so hopefully it will be fixed soon

**Comment by Silejonu** [comment]
Thank you for the incredibly fast fix!
