### ISSUE TITLE
Allowlist pdcdn1.top for Malware list

### ISSUE THREAD

**Issue by yokoffing** [DandelionSprout/adfilt#681]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Domain needed to download books from PDF Drive. `pdcdn1.top`

When you go to load the book, you get the block page.

Example: `https://www.pdfdrive.com/psychodynamic-psychotherapy-a-clinical-manual-d176061558.html`

Link is clean per URLscan and VirusTotal.

### Add screenshots below if needed

![Screenshot 2022-11-04 at 7 16 03 PM](https://user-images.githubusercontent.com/11689349/200088010-7742f7a5-bf76-4873-8fb7-5cff1ae01709.jpg)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Malware

### Which browser(s) did you use when testing this?

Firefox

### Which OS(s) did you use when testing this?

macOS

**Comment by DandelionSprout** [comment]
The site seems reasonably legitimate and safe, so I'll whitelist it sometime tonight.
