### ISSUE TITLE
Stop autoplay on the channel home pages

### ISSUE THREAD

**Issue by haze2422** [DandelionSprout/adfilt#69]
Is it possible to stop autoplay on the channel home pages?

Windows 7, Vivaldi 3.1.1929.3 ( Chrome/83.0.4103.75 ), Nano Adblocker 1.0.0.148, Nano Defender Pro 15.0.0.199
![2020-05-30_190241](https://user-images.githubusercontent.com/15184981/83333921-b9e32580-a2ab-11ea-8d66-1898bfc2ea2b.png)
![2020-05-30_192300](https://user-images.githubusercontent.com/15184981/83333923-bfd90680-a2ab-11ea-8a09-b39ddbf2c82a.png)
![2020-05-30_193626](https://user-images.githubusercontent.com/15184981/83334057-8fde3300-a2ac-11ea-8e90-ba6dde8fcbfe.png)

**Comment by DandelionSprout** [comment]
I am sadly not aware of any methods to accomplish such a thing, and apparently a fair few people have tried to do so before.

I'll ask some pals of mine if they know of any `##+js`-related ways to do so, but I'm not 100% sure if it's even technically possible, since the video seems to auto-begin within milliseconds of being loaded and may possibly not work the same way as what regular YouTube videos or embeds do.

**Comment by krystian3w** [comment]
Try found code on `Greasy Fork` or `OpenUserJS`? Maybe help convert into available Nano/uBO `snippets`.

https://chrome.google.com/webstore/detail/disable-html5-autoplay-re/cafckninonjkogajnihihlnnimmkndgf - but may no support URL:

`https://www.youtube.com/channel/*`
`https://www.youtube.com/user/*`

---

Heavy workaround, login on YouTube and subscribe your popuplar viewed channels (no works when you open random no subcribed channel) - when YouTube hide promotion video section.

**Comment by DandelionSprout** [comment]
Looking into some scripts that I previously somehow thought was too old, https://greasyfork.org/nb/scripts/29422-disable-youtube-channel-user-home-page-video-autoplay actually seems to work.

Only catch is that [its code is incomprehensible to me](https://greasyfork.org/nb/scripts/29422-disable-youtube-channel-user-home-page-video-autoplay/code), thus I'd need significant help to convert to a single uBO entry.

**Comment by krystian3w** [comment]
If possible remove video (user do not need see this), maybe works good:

```
youtube.com##ytd-channel-video-player-renderer:remove()
```

for very old Nano:

`youtube.com##+js(nano-remove-elements-onready, ytd-channel-video-player-renderer)`

**Comment by haze2422** [comment]
> https://greasyfork.org/scripts/29422-disable-youtube-channel-user-home-page-video-autoplay

thx, this script works but i think easier to just remove like krystian3w suggested

> youtube.com##ytd-channel-video-player-renderer:remove()

**Comment by DandelionSprout** [comment]
(Un)Fortunately, removing all channel trailers completely isn't really something I'd want to do, since most of them form an important part of their channels, after all.

**Comment by DandelionSprout** [comment]
So with the situation being a bit standstilled in the past week, it seems to me that it's time to put the issue report on hiatus. But don't worry, it'll remain open for comments, and a call-for-help has been added to the [Stop Autoplay On Video Sites](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt) list.
