### ISSUE TITLE
GDPR 451

### ISSUE THREAD

**Issue by talizea** [DandelionSprout/adfilt#691]
## Which entry/entries are you submitting?
wrex.com
kadn.com
wktv.com
cbs8.com
5newsonline.com
wtva.com
wdrb.com
kwwl.com
wfxrtv.com
wfft.com
dcnewsnow.com
actionnewsnow.com
wdhn.com
kytim.com
fonbet.gr

## Which of my lists are you submitting it to?
🇪🇺 GDPR 451 List of Mostly American Websites Who Hate Europe and Privacy Rights

## Which adblocker(s) and version did you use when writing and testing the entries?

- [ ] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [x] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
![filters](https://user-images.githubusercontent.com/21116973/201794354-66cc9e95-c0d3-4a2b-98e7-05d3fab5db53.jpg)

not that it's relevant here

**Comment by DandelionSprout** [comment]
`fonbet.gr` is from Greece, a European Union country, so that one seems more like a generic region-lock than a 451-type block. But the other 14 I'll definitely add. Give me 20min.

**Comment by talizea** [comment]
journal-news.com
![image](https://user-images.githubusercontent.com/21116973/202833930-927fb664-f950-485b-b5b2-aadf270d8c8e.png)

newsnationnow.com
![image](https://user-images.githubusercontent.com/21116973/202834318-cb110e39-0781-4f1e-ba8f-efd74b1f846e.png)

**Comment by talizea** [comment]
wsiltv.com
![image](https://user-images.githubusercontent.com/21116973/203208022-f7a53f81-d6ea-4bf5-8068-23c235164898.png)

beloitdailynews.com
![image](https://user-images.githubusercontent.com/21116973/203209890-0d512b29-dadc-4671-94ac-3dcb25986abd.png)

**Comment by talizea** [comment]
manchestertimes.com
![image](https://user-images.githubusercontent.com/21116973/203465697-e141edb3-9ed2-45ed-aab1-6833e1b6178d.png)

daytondailynews.com
![image](https://user-images.githubusercontent.com/21116973/203465932-8c498c04-8c65-43fb-9400-4290c866af16.png)

**Comment by talizea** [comment]
kxly.com
![image](https://user-images.githubusercontent.com/21116973/204961844-2079aaf8-e73f-42a1-b352-a24410548391.png)

I hecking love google news

**Comment by talizea** [comment]
valleybreeze.com
![image](https://user-images.githubusercontent.com/21116973/205179575-7d2aa47d-69cf-455f-821f-7e52e13f1f84.png)

**Comment by talizea** [comment]
All the https://www.tribpub.com/#who-we-are sites except for one are GDPR'd.

![image](https://user-images.githubusercontent.com/21116973/206622622-54b00bd6-03ba-4ac5-817d-db60ebecb460.png)

mcall.com

baltimoresun.com

orlandosentinel.com

sun-sentinel.com

dailypress.com

pilotonline.com

courant.com

**Comment by talizea** [comment]
ncadvertiser.com
![image](https://user-images.githubusercontent.com/21116973/209251309-a5d8f245-8060-404a-9b28-2a865664808d.png)

**Comment by DandelionSprout** [comment]
I'm not 100% sure how, but the TribPub sites seem to be accessible from Norway.

**Comment by talizea** [comment]
journalgazette.net
![image](https://user-images.githubusercontent.com/21116973/210161399-57449c6f-68b6-44ec-9e82-43ff4e51ad5d.png)

**Comment by talizea** [comment]
rheaheraldnews.com
![image](https://user-images.githubusercontent.com/21116973/211176813-63cf3357-377a-478f-8ce9-edbf3e26a123.png)

fergusfallsjournal.com
![image](https://user-images.githubusercontent.com/21116973/211176845-1be8a74d-5992-4a51-9ef0-29ca2c011edf.png)

**Comment by talizea** [comment]
therogersvillereview.com
![image](https://user-images.githubusercontent.com/21116973/211211494-e8c349d0-4323-47fa-8225-5ec7257b2b27.png)

**Comment by talizea** [comment]
wenatcheeworld.com
![image](https://user-images.githubusercontent.com/21116973/212444338-352d0e5e-c6d0-496e-827b-97f5c3b629d1.png)

leadertelegram.com
![image](https://user-images.githubusercontent.com/21116973/212444349-5dbb2538-be62-4149-8654-17136baa565d.png)

**Comment by talizea** [comment]
wjfw.com
![image](https://user-images.githubusercontent.com/21116973/212451825-26690d3b-d41c-4781-ba24-e8054a3028c1.png)

**Comment by talizea** [comment]
406mtsports.com
![image](https://user-images.githubusercontent.com/21116973/212521360-d85346a8-4651-477c-aeb7-3fad67adcb90.png)

**Comment by talizea** [comment]
stlpinchhits.com
![image](https://user-images.githubusercontent.com/21116973/212559631-897f78f0-bbfe-4301-8709-ca335f76a673.png)

**Comment by talizea** [comment]
gwinnettprepsports.com
![image](https://user-images.githubusercontent.com/21116973/212589064-9b32c342-ee06-4c3f-bd98-51c1120e2775.png)

**Comment by talizea** [comment]
miltonindependent.com
![image](https://user-images.githubusercontent.com/21116973/213585975-21aa8e06-c873-472c-a391-d2f367bc6ad7.png)

**Comment by talizea** [comment]
kq2.com
![image](https://user-images.githubusercontent.com/21116973/213586490-fd4972b6-3dc8-4684-9fd3-fd29768b2ba9.png)

**Comment by talizea** [comment]
channel3000.com
![image](https://user-images.githubusercontent.com/21116973/213947221-f2dd7e01-1685-4511-b34c-c6b713465758.png)

**Comment by talizea** [comment]
trumbulltimes.com
![image](https://user-images.githubusercontent.com/21116973/214614187-9c81264b-bcb8-4e4b-be0c-dabb36c1f4c4.png)

**Comment by talizea** [comment]
veronapress.com
![image](https://user-images.githubusercontent.com/21116973/214897068-3f79abb3-61f4-4df8-a29d-a45848308e3e.png)

**Comment by talizea** [comment]
ftimes.com
![image](https://user-images.githubusercontent.com/21116973/215241535-b63b5e9f-9b3e-4412-8d0a-7c0f15b8a8ff.png)

**Comment by talizea** [comment]
news8000.com
![image](https://user-images.githubusercontent.com/21116973/215287854-88ad7c21-3f3a-4e88-8485-832c97783813.png)

**Comment by talizea** [comment]
nbcrightnow.com
![image](https://user-images.githubusercontent.com/21116973/215288759-b0eb61c2-6d68-42c9-b447-226229774b17.png)

**Comment by talizea** [comment]
wboc.com
![image](https://user-images.githubusercontent.com/21116973/215301647-8565816a-eec6-48cb-a184-c6e87537e9a1.png)

**Comment by talizea** [comment]
midfloridanewspapers.com
![image](https://user-images.githubusercontent.com/21116973/215302093-bf15cf3e-bc6f-47cc-a3cc-d99bbfaaf5a2.png)

**Comment by talizea** [comment]
rutlandherald.com
![image](https://user-images.githubusercontent.com/21116973/215343227-db187fa3-7e2b-4d66-b4cf-48b39acdeb1f.png)

**Comment by talizea** [comment]
wiltonbulletin.com
![image](https://user-images.githubusercontent.com/21116973/215343431-728b490c-2602-4a0c-bac3-8f0221147057.png)

**Comment by talizea** [comment]
wrde.com
![image](https://user-images.githubusercontent.com/21116973/215343530-3abee679-7f51-4f3c-b640-d8cb37b6d257.png)

**Comment by DandelionSprout** [comment]
Given how productive you are about finding these domains, would it be possible for you to submit 3 or more at a time, instead of just 1? My stamina isn't exactly "Doing everything the instant I hear about it", and GitHub threads usually only display the recentmost 25 comments in threads with 50+ comments. 😅 

I'll see if I can take care of these ones from the past 2 weeks right now, at least.

**Comment by talizea** [comment]
darientimes.com

milfordmirror.com

theridgefieldpress.com

bristolpress.com

westportminuteman.com

newhavenadvocate.com

**Comment by DandelionSprout** [comment]
>I guess I could simply edit a message instead of posting more?

I suppose that'd be possible.

**Comment by talizea** [comment]
times-georgian.com

wallowa.com

By the way, I think it'd be useful to have the list in the format for https://github.com/iorate/ublacklist so users can just subscribe once and never have to update manually. Appears to be the best solution to filter search engine results.

**Comment by DandelionSprout** [comment]
It seems to be a pretty rare format they're using, so I've opened https://github.com/iorate/ublacklist/issues/317 first, before I'd have to handle alternate list versions and such.

**Comment by DandelionSprout** [comment]
It turns out there's a bit of an issue with this strategy. I don't get E-mail notifications for comment updates, whereas I get notifications for new comments. So I get the feeling that new comments would have to be posted occasionally.

**Comment by talizea** [comment]
Landmark Media Enterprises aka

citysuntimes.com

cannonfallsbeacon.com

hastingsstargazette.com

lasvegasoptic.com

hudsonstarobserver.com

riverfallsjournal.com

republicaneagle.com

theandersonnews.com

pmg-ky1.com

brunswickbeacon.com

newsargus.com

madisoncourier.com

galaxgazette.com

pmg-va.com

kystandard.com

pmg-ky2.com

oldhamera.com

carolinagatewayonline.com

pmg-sc.com

themountainpress.com

morgancountycitizen.com

duboiscountyherald.com

perrytribune.com

pioneernews.net

roanecounty.com

sentinelnews.com

smcitizen.com

spencercountyjournal.com

spencermagnet.com

springfieldnewssun.com

bedfordbulletin.com

thelancasternews.com

laruecountyherald.com

thewakullanews.com

thewakullanews.net

mytrimblenews.com

westmarionmessenger.com

willistonpioneer.com

**Comment by talizea** [comment]
mississauga.com

**Comment by talizea** [comment]
must have found most of them in my random searches, not a whole lot lately (well, except for those above in a few months)

**Comment by DandelionSprout** [comment]
Thanks for the headsup, as I had been pretty busy in the past 2 months and needed a notification for this.

**Comment by talizea** [comment]
appenmedia.com

**Comment by talizea** [comment]
timesnewspapers.com

**Comment by talizea** [comment]
dawsonspringsprogress.com (redirects to the-messenger.com which is already blocked)
on the bright side, I've not seen a lot of new 451 sites lately, on the other hand, part of the list seems to comply with GDPR now and is available again etc

**Comment by talizea** [comment]
shelbynews.com
albianews.com

**Comment by talizea** [comment]
northglenn-thorntonsentinel.com
