### ISSUE TITLE
Unblock monster-domain "fedi.monster"

### ISSUE THREAD

**Issue by AliveDevil** [DandelionSprout/adfilt#696]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

The AdGuardHome-list contains the entry.
```
||monster^$denyallow=egybest.monster|yts.monster|cloudcdn.monster
```
Blocking domains like `files.fedi.monster` which is a valid domain distributing CDN content.

### Add screenshots below if needed

![image](https://user-images.githubusercontent.com/734738/203566765-190f14e0-d200-45ae-9e63-55f590132edb.png)

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

* [AdGuard Home](https://github.com/DandelionSprout/adfilt/blob/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt) (Updated 2022-11-23T00:07+01)

### Which browser(s) did you use when testing this?

(Other)

### Browser version(s)

Browser is not relevant as it is related to AdGuard Home.

### Which OS(s) did you use when testing this?

(Other)

### OS version(s)

Network wide DNS block, such that OS doesn't matter.

**Comment by DandelionSprout** [comment]
The site seems very legitimate, so I'll get it whitelisted within the next 30min.

**Comment by AliveDevil** [comment]
Thank you 🙂
Appreciate the prompt response.
