### ISSUE TITLE
Please add an complete index of your filterlists

### ISSUE THREAD

**Issue by 0xRustlang** [DandelionSprout/adfilt#698]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hello

Previously, maybe one or two years ago I checked all of your repo and found some great interesting blocklists but they weren't in filterlist website (probably two or three of your blocklists are available there).

Then after sometime I reported a bug regarding Legitimate URL shortner in discussions and after I said what blocklists I use, "im-py-test" said there is an ublock origin version of your malware blocklist that I haven't found it although I had checked all of your repo.

This is really waste of your efforts that such great lists are hidden deep in your repo that a proclaimed geek like me couldn't find them.

Although I can understand you want to avoid confusion among normal users, I think an advanced page with a red and threatening warning like "if you use these filterlists, we won't provide you any support and if any website breakage or issues happen when you are visit your important websites, we will not take "any" responsibility and these are advanced lists for those that know what are doing and mostly they are for my personal usage" and such sentences. 

Then provide direct link to those lists please.

They are really great.

I want to find them again but I can't (uBo won't show me all of them in support log because i use many small blocklists (Yes, I prefer many good small lists instead of some big curated ones) So if may please provide direct link to all your great filterlists that are hidden deep in your repo so much that finding them cause headache for me to search for them (just kidding ;))

Thank you very much in advance. 
Best wishes.

And thank you and other contributors that maintain these great lists.

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

Latest version, I don't remember.

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

All uBo defaults plus many small and good ones that didn't caused breakage for years.

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

107.1

### Which OS(s) did you use when testing this?

Windows 11, Windows 10, macOS, Linux, Windows 7, Android

### OS version(s)

Windows: 11, 10, 7, XP

**Comment by iam-py-test** [comment]
Imre prefers that people use filterlists.com and select him:
![image](https://user-images.githubusercontent.com/84232764/204057269-715ad071-f8ef-4f90-9604-6dbf0e6fc0ac.png)
I'm not saying I agree, but this is what he says in the README:
![image](https://user-images.githubusercontent.com/84232764/204057305-96a69b0a-80dc-475a-87a6-bcd8b9afa69c.png)

**Comment by DandelionSprout** [comment]
>"im-py-test" said there is an ublock origin version of your malware blocklist that I haven't found it although I had checked all of your repo.

Such a version was discontinued and deleted within mere weeks anyway back in 2020, after uBlock Origin agreed to replace `$queryprune` with the AdGuard-invented `$removeparam`. So it's little wonder you couldn't find it. 😅

>but they weren't in filterlist website (probably two or three of your blocklists are available there).

I think I've got 120 on that site. You can follow iam-py-test's screenshots above and see if they improve the situation any.

**Comment by iam-py-test** [comment]
> I think I've got 120 on that site. You can follow iam-py-test's screenshots above and see if they improve the situation any.

147 is what I see.

> Such a version was discontinued and deleted within mere weeks anyway back in 2020, after uBlock Origin agreed to replace `$queryprune` with the AdGuard-invented `$removeparam`. So it's little wonder you couldn't find it. 😅

I think (although, due to GitHub's poor design of discussions, I can't find it. The search feature oddly enough only shows it exists but refuses to give me the exact comment) the OP was talking about your antimalware list and not Legit URL.

**Comment by DandelionSprout** [comment]
It appears the exact quote they used was _""im-py-test" said there is an ublock origin version of your **malware** blocklist"_ (Emphasis added), so you remembered correctly.
