### ISSUE TITLE
Feedly: "Lightweight Anti-'Social share' List" breaks adding new sources

### ISSUE THREAD

**Issue by yokoffing** [DandelionSprout/adfilt#70]
I cannot add new sources on Feedly due to this blocklist. This blocklist blocks the **Follow** button on` https://feedly.com/`. Please reference the following three screenshots.

In the following example, I am trying to "follow" 9to5Google for tech news updates.

**Logger from NanoAdblocker (based on uBlock Origin):**

![follow button](https://user-images.githubusercontent.com/11689349/83512888-e317d780-a49e-11ea-8f35-8e757f6d21fc.jpg)

**Broken Feedly source example:**

![broken](https://user-images.githubusercontent.com/11689349/83513138-528dc700-a49f-11ea-804b-dfda757b371d.jpg)

**How it should display:**

![not broken](https://user-images.githubusercontent.com/11689349/83513182-63d6d380-a49f-11ea-9c39-39b4c8ef0841.jpg)

I love this list, but please modify to "Follow" rule for Feedly.

**Comment by DandelionSprout** [comment]
Thanks for the heads-up.

As I myself do not have a Feedly user, I've chose to simply whitelist that entry on Feedly, and am of course hoping that the fix works.
