### ISSUE TITLE
Fandom/wikia new aggressive cosmetic filters for the wikia fandom list

### ISSUE THREAD

**Issue by squeak9** [DandelionSprout/adfilt#701]
## Which entry/entries are you submitting?
Found some great filters in a this reddit post by the user /u/Last_Excuse : https://www.reddit.com/r/uBlockOrigin/comments/z0i6qy/aggressive_fandom_wiki_filter_set/

Maybe they are to aggressive for the list but worth taking a look at least:

```
fandom.com##.global-footer
fandom.com##.mcf-wrapper
fandom.com##.wikia-bar-anon.wikia-bar
fandom.com##.global-navigation
fandom.com##.page-side-edit.page-side-tool
fandom.com##.render-wiki-recommendations
fandom.com##.fandom-sticky-header
fandom.com##.page-header__actions
fandom.com##.page-header__categories
fandom.com##.fandom-community-header__background
fandom.com##.fandom-community-header__image
fandom.com##.explore-menu.wds-dropdown
fandom.com#$#.main-container { margin-left: 0 !important; width: 100% !important; }
fandom.com##a[title="Discuss"]
fandom.com##.unified-search__layout__right-rail
fandom.com##.wikia-bar-collapse
fandom.com#$#.community-header-wrapper { height: 1% !important;}
fandom.com#$#.fandom-community-header__community-name { margin-top:10px !important; }
fandom.com#$#.wds-tabs { margin-top:10px !important; }
fandom.com#$#.fandom-community-header__top-container { padding-right: 10px !important; }
fandom.com#$#.page-counter { margin-left: 9px !important; margin-top: 10px !important; }
fandom.com#$#.fandom-community-header__top-container { white-space: nowrap !important; align-items: center !important; }
fandom.com#$#.fandom-community-header__community-name { height: 100% !important; margin-right: 0 !important; }
fandom.com#$#.wds-button-group { margin-top: 10px !important; }
fandom.com#$#.search-modal::before { left: 0 !important; }
fandom.com##a[title="UTC Clock"]
fandom.com##.search-seeding
fandom.com##.page__right-rail
fandom.com##.page-header__top
fandom.com###BackToTopBtn
fandom.com##.highlight__sticky-container
fandom.com##.notifications-placeholder
fandom.com#$#.wds-dropdown__content { transform: translateX(-10%) !important; left: 0px !important;}
```
Again, I didn't write these so give the credit to /u/Last_Excuse user if possible. :)

PS: Should this list be renamed to include fandom in the name and maybe in the URL?

## Which things do they block, hide, or unbreak?

Screenshots from the reddit post:
https://i.ibb.co/Hn05RNB/rule-before.png
https://i.ibb.co/xg9KqYM/rule-after.png

## Which of my lists are you submitting it to?

Wikia: Pure Browsing Experience

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Default+Wikia: Pure Browsing Experience

## (Optional) Which browser(s) and version did you use?

Latest Firefox desktop.

**Comment by DandelionSprout** [comment]
Sure the entries look pretty good and well-written (though with AdGuard's syntax), but I would very likely need to know *which things* each of the entries do. Mass additions with no categorising or `!`-commenting seems like it could easily cause unintended issues on that site, as me and most others would have nary a clue what the entries were supposed to do in the first place.

If proper explanations are added for what the entries do, I would very likely add them pretty quickly.

**Comment by squeak9** [comment]
Ah, that makes sense. Well I'm in the same boat as you, I don't know either. I just added them for my own sake.

I understand that you don't wanna dump them into the list like this with no comments, it's your list. I guess the issue can be closed, thanks for your time.

**Comment by DandelionSprout** [comment]
I've reached the outcome that none of the Reddit post's suggested non-stylechanging entries seemed relevant to my list, with many of them doing stuff like removing the entire bottom footer, the entire "Popular pages" section on the right, and even the page's categories.

Apart from fairly significant changes done to both the Wikia list and to *Dandelion Sprout's Website Stretcher* in regards to the "Popular pages" bar, I think this report can safely be closed now. Comments will remain open.
