### ISSUE TITLE
Bad behavior of "*$removeparam=ad_id" on "api.chat.olx.ua"

### ISSUE THREAD

**Issue by iG8R** [DandelionSprout/adfilt#706]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hi.
`*$removeparam=ad_id` blocks identifier of the user on the domain `api.chat.olx.ua` in the private chat window of the [www.olx.ua](https://www.olx.ua) hence preventing any possibility to communicate via this chat.
I tried to exclude this filter for this domain via "My filters" of uBlockOrigin `*$removeparam=ad_id,domain=api.chat.olx.ua,badfilter` but to no avail, only `*$removeparam=ad_id,badfilter` worked, but I don't want to remove this filter for all domains.

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.45.2

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

 Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

Firefox 107.0.1 Release November 29, 2022

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

Microsoft Windows [Version 10.0.19043.1415]

**Comment by DandelionSprout** [comment]
On paper, it should be easy for me to change the list's entry to `$removeparam=ad_id,domain=~olx.ua` pretty soon now, which I hope will fix this.

**Comment by iG8R** [comment]
Thank you.
I played with the filter's parameters and through "My filters" the following works well:
`@@$removeparam=ad_id,domain=olx.ua`

**Comment by iam-py-test** [comment]
>  The weird thing is that @@$removeparam=ad_id,domain=api.chat.olx.ua didn't work.

I think this is because $domain matches the top level URL (the one in the address bar), and `api.chat.olx.ua` didn't match that.
https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md#file-blocking-aka-blocking-rules-aka-non--rules

**Comment by DandelionSprout** [comment]
It seems to me that this issue has been fixed now, so I'll mark it as a closed case. Comments will remain open.

**Comment by krystian3w** [comment]
How works this on other languages:

```adb
https://www.olx.bg/
https://www.olx.ro/
https://www.olx.pl/
https://www.olx.pt/
https://fixly.pl/
https://www.otomoto.pl
https://obido.pl/
```

He deprecated use `api.chat.olx.` / `api.chat.fixly.` / `api.chat.otodom.` / `api.chat.obido.`?

**Comment by iG8R** [comment]
@krystian3w 
I don't know since I don't have an account on these sites and it's impossible to evoke chat window without one.
IMHO since these sites are parts of the same parent olx, sooner or later they will roll out the same chat system.
