### ISSUE TITLE
Malware/Phishing URL to report

### ISSUE THREAD

**Issue by yokoffing** [DandelionSprout/adfilt#71]
`https://imgvieweriri.com/g/?5678565867953463634566=f7&look=mypal_hal&ure=https://instagram.fbkk9-2.fna.fbcdn.net/v/t51.2885-19/s150x150/69013703_644272702749406_7283768718696382464_n.jpg?_nc_ht=instagram.fbkk9-2.fna.fbcdn.net&_nc_ohc=yxXDm260USwAX9txkHS&oh=7171c70463001c681263dbb34948ac91&oe=5EF54B98`

The above is a newly registered domain (NRD) that tries to get the user to enter their Instagram credentials. Used in hacked Instagram accounts. Please add to your "Anti-Malware" list and anywhere else you deem appropriate :)

**Comment by llacb47** [comment]
FYI, you might want to redact that URL. I have your instagram profile picture now :P

**Comment by DandelionSprout** [comment]
It's rare for me to add malware domains that would most likely be covered by other anti-malware lists (except for "uBlock Filters - Badware Risks").

However, since I know to appreciate and appeal to those who use my lists, I suppose I can very well add a paragraph for user-submitted entries. Give me 3min.

**Comment by krystian3w** [comment]
> I have your instagram profile picture now

![obraz](https://user-images.githubusercontent.com/35370833/83797208-900e7200-a6a2-11ea-9ae4-db2a806517a7.png) | ![obraz](https://user-images.githubusercontent.com/35370833/83797245-a3214200-a6a2-11ea-81af-ccde31c0cf4f.png) 
--- | ---

**Comment by yokoffing** [comment]
> FYI, you might want to redact that URL. I have your instagram profile picture now :P

Enjoy 😉
