### ISSUE TITLE
{Bug} "Actually Legitimate URL Shortener Tool" not working as expected

### ISSUE THREAD

**Issue by AdishSagarawat** [DandelionSprout/adfilt#710]
Actually Legitimate URL Shortener Tool not working as expected while using it with uBO on FireFox.

Please see the attached image:

![image](https://user-images.githubusercontent.com/69076256/208232370-f4c00d4c-bac9-4d6b-bf5b-4250d9ffcbbc.png)

**Comment by AdishSagarawat** [comment]
![image](https://user-images.githubusercontent.com/69076256/208232452-062aab21-8521-4abb-b791-faa59bebb068.png)

**Comment by iam-py-test** [comment]
FYI, "Dandelion Sprout's Annoyances List" should include Legit URL.
Also, please post the whole URL (like this \`[url]\`); it is hard to read a URL out of an image.
Just looking at it, `q` is needed for the search query and I think `client` causes problems (but GitHub's search makes finding it hard)

**Comment by DandelionSprout** [comment]
I *think* `client` would be safe to block on desktop, but I've long been worried that adding it to the list could implausibly cause issues with making Google show the correct page version to users (as I know that there's at least 4 versions of Google: Standard desktop; Very old desktop; Chrome Android; Other phone browsers).

`ved` has been known to cause truckloads of breakage, from what I can remember in a hurry.

**Comment by Nojuuu** [comment]
I think `ved` could be removed from specific paths but not everywhere and probably would be better to apply to document only?

**Comment by Nojuuu** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/87920 
https://github.com/AdguardTeam/AdguardFilters/commit/293a7d939039c76b0a24cbcfb7e326108442da4c

I can't reproduce any issues removing `ved` from `||google.*/search`

**Comment by iam-py-test** [comment]
@AdishSagarawat please test this rule in your "my filters" tab:
```adblock
||google.*/search$removeparam=ved
```
@Nojuuu thanks for sharing those links. I don't see any issues either on a test profile in Firefox, but maybe it's specific to certain browser configuration or version? (the OP is on Android, I'm on Windows, maybe that makes a difference)

**Comment by Nojuuu** [comment]
I think `/url?` path one was the problem there? Isn't that used redirections or something?

Also `ved` filter in Legit URLs used to be like this `$removeparam=ved,domain=google.*` so that's probably why it had issues.

**Comment by iam-py-test** [comment]
> I think removing it from the /url? path might have been the problem there? Isn't that used for redirections or something?

You are correct; it's used by Google Search and other Google services like Docs (I think...)

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/87455

**Comment by krystian3w** [comment]
`ved` can by tested in https://en.wikipedia.org/wiki/Google_Programmable_Search_Engine

```adb
https://cse.google.com/cse?cx=partner-pub-8345364103968660%3Ahvaj9v-f27m&ie=utf-8&q=chrome&sb=#gsc.tab=0&gsc.q=chrome&gsc.page=1
```

Then don't help uBO: 

```adb
! https://github.com/uBlockOrigin/uAssets/issues/7960
www.google.*##+js(set, rwt, noopFunc)
```

So recommended `||google.*/search$removeparam=ved` corectly omit CSE and `https://www.google.com/url?`.

**Comment by DandelionSprout** [comment]
@AdishSagarawat Are you using Firefox or a non-Firefox browser? Because I'm not sure how I missed for 8 days that Legitimate URL Shortener has this section:
```
!#if env_chromium
||google.$removeparam=ved
@@||google.com/url?$removeparam=ved
(...)
!#endif

**Comment by Nojuuu** [comment]
I use Firefox on PC and Android and haven't noticed any issues yet.

**Comment by AdishSagarawat** [comment]
@iam-py-test This is what I did according to your suggestion, and here is the result:

![image](https://user-images.githubusercontent.com/69076256/209536507-ef7e38c0-d5b2-4320-8875-a5b9d8398bc0.png)

![image](https://user-images.githubusercontent.com/69076256/209536479-0a73c847-14bb-45ce-a200-0d6edc7da814.png)

**Comment by AdishSagarawat** [comment]
@DandelionSprout I use Firefox on desktop.

P.S. - I think that we can also remove 'client' it will not cause any breakage.

**Comment by AdishSagarawat** [comment]
@DandelionSprout , @iam-py-test any update on this issue?

**Comment by DandelionSprout** [comment]
We were waiting for feedback from you, not the other way around.

**Comment by AdishSagarawat** [comment]
@DandelionSprout According to my test , "ved" doesn't seems to break anything.
