### ISSUE TITLE
DeviantArt Missing Sections

### ISSUE THREAD

**Issue by ArtexJay** [DandelionSprout/adfilt#711]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

I use both your Annoyances List and the Browse Website Without Logging In, however there seems to a bug on DeviantArt, when logged into the website, some stacks in the "Deviants You Watch" section do not appear properly.

I managed to find out that this rule causing the issue on both filters
 "deviantart.com##div[style^="width:"][class]:not([class*=" "]) > div[class]:nth-of-type(2):last-of-type"
Disabling this rule fixes the issue.

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop version)

### Adblocker version(s)

7.1.1.3

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

 Annoyances List and the Browse Website Without Logging In

### Which browser(s) did you use when testing this?

Microsoft Edge (Manifest V2)

### Browser version(s)

Canary

### Which OS(s) did you use when testing this?

Windows 11

**Comment by DandelionSprout** [comment]
Is it on `https://www.deviantart.com/watch/deviations` it occurs, or somewhere else? And could you post a screenshot of the missing stacks?

**Comment by ArtexJay** [comment]
> Is it on `https://www.deviantart.com/watch/deviations` it occurs, or somewhere else? And could you post a screenshot of the missing stacks?
Yes, I noticed it on that link. 
![image](https://user-images.githubusercontent.com/32932497/208852950-bfdea064-d151-4fe6-a2a2-78e1fd9c6277.png)
Only the top part of the stack is visible, while the name of the creator and image are not visible. Disabling the rule i mentioned resolves it.

**Comment by DandelionSprout** [comment]
Although I'm having problems reproducing the complete content removal on my end this morning, I think I know how to fix the entry so that it no longer affects the "Deviants You Watch" page. Give me 2min.

**Comment by ArtexJay** [comment]
I updated the filters, but unfortunately the issue still persists for me.
If this isn't an issue affecting others, or hard to reproduce, I'll just have that one rule mentioned earlier disabled.

**Comment by DandelionSprout** [comment]
While it's definitely in the "Hard to reproduce" category, I'm not giving up on the entry just yet, given its high importance to be able to see Mature art without logging in. Luckily I've got many more narrow-down methods to try out.

**Comment by ArtexJay** [comment]
That seemed to have fixed it! Updated the filters and don't see the issue anymore.
