### ISSUE TITLE
 {Bug} "Actually Legitimate URL Shortener Tool" not working as expected on this site.

### ISSUE THREAD

**Issue by Paras6408** [DandelionSprout/adfilt#715]
https://acmetech.in/product/21-5-inch-acer-lcd-monitor-ek220q-vga-hdmi/?srsltid=AeTuncrSUTmNFjsjTTgSp3j41KI5XHYTwaVBHYDwE-nwJujpvxf65d-ohfA

Check out yourself.

**Comment by Nojuuu** [comment]
@iam-py-test 

Another example:
`https://www.antikvaari.fi/teos/uutisista-hyvaa-iltaa-ylen-tv-uutiset-ja-yhteiskun/62a37a6aeaa1ec176c3f5cb6?srsltid=AeTuncom29gZm1BukdReNCNwYSabmtmKdIV8X3ydB3REiZd6--8pWyNFGMs`


Google tracking:
`https://support.google.com/merchants/answer/11127659?hl=en`

**Comment by iam-py-test** [comment]
I will look into this later. Thanks

**Comment by iam-py-test** [comment]
I'm a bit cautious about adding a generic rule, but it seems pretty wide spread (i.e. `https://shop.asus[.]com/us/90ms0252-m00450-asus-chromebox-4.html?srsltid=AeTuncrD7_CjHqzTxkHEt9bjVTiyCmzBETRZRFfoGUbVj3b5vBb9rm3qNXA`), so I have added a rule in https://github.com/DandelionSprout/adfilt/commit/ab8c77bc1f6b427a5903f44bc118d4d131c7c1bc.

**Comment by DandelionSprout** [comment]
The parameter is 7 characters long, so I feel it'd go better than if it had been perhaps 2 characters long.
