### ISSUE TITLE
New filter needed for "I don't want to download your browser"

### ISSUE THREAD

**Issue by yokoffing** [DandelionSprout/adfilt#73]
URL: `https://www.bing.com`

### Vivaldi (logged in):

![bing edge](https://user-images.githubusercontent.com/11689349/84676020-001ac480-aefb-11ea-836b-3035aba4ef5c.jpg)

### Brave (not signed in):

![2 bing edge](https://user-images.githubusercontent.com/11689349/84676408-791a1c00-aefb-11ea-92bf-68f728b2b046.jpg)

**Comment by DandelionSprout** [comment]
I can't seem to trigger the banners in Vivaldi, Chrome, Firefox, nor Tor Browser, with quite a few different uBO setups. So I'm left having to presume the banners could be exclusive to American users. Not even setting Bing's locale to US+English seems to trigger them for me.

**Comment by llacb47** [comment]
https://github.com/DandelionSprout/adfilt/pull/74

**Comment by DandelionSprout** [comment]
Indeed seems to me to take care of this issue report and then some. Marking it as resolved for now; comments will remain open as usual in case it isn't.

**Comment by llacb47** [comment]
I don't know if this is hidden, may need some feedback from @yokoffing.

![image](https://user-images.githubusercontent.com/16567977/84688001-8ee40d00-af0c-11ea-81eb-fffe44df9da9.png)

**Comment by yokoffing** [comment]
It happens when I have Bing has my homepage. (The home button brings me to `https://www.bing.com/`.) I do not know if being signed in also triggers the prompt.

Here's the logger from Nano Adblocker:

![bing](https://user-images.githubusercontent.com/11689349/84794810-b5657f00-afc4-11ea-941d-b2c290f9db40.jpg)

**Comment by llacb47** [comment]
I added that one. https://github.com/DandelionSprout/adfilt/commit/badecf93303613170f626000a7673f13a4a9c83f#diff-be7555a93007b340d76ca04dc43b1c20R19

I need the logger for the smaller one you got when signed in.

**Comment by yokoffing** [comment]
> I need the logger for the smaller one you got when signed in.

I have not been able to reproduce. Perhaps it was sneaking through my filters since I had prefetching enabled at the time?
