### ISSUE TITLE
takvim.tj

### ISSUE THREAD

**Issue by MasterKia** [DandelionSprout/adfilt#731]
`takvim.tj###table_namoz_time_today, #rakaat_div_namaz_name_next`

For the `AntiPrayerTimesList.txt` list.

**Comment by DandelionSprout** [comment]
It appears that the site has prayer times as its main focus by far (as opposed to being a newssite, notwithstanding [the Russian propaganda section they borrow from Lenta](http://takvim.tj/news_view.php)), meaning that it'd be considered strange if I blocked the prayer times there. So while I appreciate the effort and thought, I'll likely have to pass on this.
