### ISSUE TITLE
NZ Post Parcel Tracking Bug - Actually Legitimate URL Shortener Tool

### ISSUE THREAD

**Issue by rjocoleman** [DandelionSprout/adfilt#733]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

New Zealand Post's website uses `trackid` for passing parcel tracking numbers and these are often linked from other sites or in emails etc..

`https://www.nzpost.co.nz/tools/tracking?trackid=1005410001051701ASH003JS`

I'm not 100% certain on syntax sorry as they seem to grab the param into their js app early on. I have `@@||nzpost.co.nz/tools/tracking$removeparam=trackid` in my filter list and it's performing as expected.

I'm not sure that `$document,removeparam=trackid,~domain=nzpost.co.nz` works.

### Add a screenshot of the extension's logger

<img width="1645" alt="CleanShot 2023-01-05 at 18 06 24@2x" src="https://user-images.githubusercontent.com/154176/210705765-6a0d71fe-7232-4974-8af2-34ee00774c8f.png">

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.46.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Title: ➗ Actually Legitimate URL Shortener Tool
Version: 04January2023v2

### Which browser(s) did you use when testing this?

Microsoft Edge (Manifest V2)

### Browser version(s)

Version 108.0.1462.54 (Official build) (arm64)

### Which OS(s) did you use when testing this?

macOS

### OS version(s)

13.1

**Comment by iam-py-test** [comment]
> `$document,removeparam=trackid,~domain=nzpost.co.nz`

This isn't valid syntax; to exclude a domain, you need to put the `~` before the domain name. Also, you would need to add `$document,removeparam=trackID,badfilter` to disable the problematic filter, or completely disable Legit URL. 
Please add these two filters to the "My filters" tab and test:
```adblock
$document,removeparam=trackID,badfilter
$document,removeparam=trackID,domain=~nzpost.co.nz
```

**Comment by rjocoleman** [comment]
Thanks @iam-py-test 

this didn't work, maybe case sensitive? as the below does work for me:

```
$document,removeparam=trackid,badfilter
$document,removeparam=trackid,domain=~nzpost.co.nz
```

**Comment by iam-py-test** [comment]
> Thanks @iam-py-test
> 
> this didn't work, maybe case sensitive? as the below does work for me:
> 
> ```
> $document,removeparam=trackid,badfilter
> $document,removeparam=trackid,domain=~nzpost.co.nz
> ```

Sorry, that's my fault. There is another rule which _is_ trackID, and my search was case-insensitive.

**Comment by rjocoleman** [comment]
thank you!

**Comment by iam-py-test** [comment]
Thank you for reporting this
