### ISSUE TITLE
No redirect to the login page on www.olx.pl

### ISSUE THREAD

**Issue by wojnilowicz** [DandelionSprout/adfilt#739]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Clicking on "Twoje konto" on https://www.olx.pl/ fails to redirect to the login page.

### Add screenshots below if needed

![Screenshot_20230108_142811](https://user-images.githubusercontent.com/22069602/211198636-050b5a47-8bea-4c06-90bf-aaa461dc6734.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.46.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Chromium for Linux (Manifest V2)

### Browser version(s)

108.0.5359.124

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Fedora 37

**Comment by wojnilowicz** [comment]
I have to add that the issue is present when "Skip Redirect" 2.3.6 plugin is enabled.

**Comment by iam-py-test** [comment]
> I have to add that the issue is present when "Skip Redirect" 2.3.6 plugin is enabled.

So this _only_ reproducible when that extensions is installed?
I can't reproduce in Firefox with just uBo (with Legit URL).
I can reproduce with **and** without uBlock Origin enabled. This is a bug in Skip Redirect. Please report it to them.
