### ISSUE TITLE
Invalid Domains (2) detected

### ISSUE THREAD

**Issue by aaronsql2019** [DandelionSprout/adfilt#750]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

this might not be a problem everywhere, maybe it's just showing up for me.
But I was running an update on my pihole, and I saw this popup

  [i] Target: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 12696 domains, 2 domains invalid!
      Sample of invalid domains:
      - 2600:1f18:43d1:2a04:ee05:261e:d408:7ba1
      - 2a02:1668:1034::2

I just wanted to bring this to your attention. I think that those are both properly formatted IPv6 addresses, I'm a bit fuzzy on IPv6. And I don't think that my IPv6 is REALLY working properly.

But I'm new to pihole, and I wanted to report this to see if anyone else was seeing the same thing.

THANKS. I'm new to pihole, but I absolutely love it. I finally got it working on a VM, and it's given me a lot of flexibility so that I don't need to sign into my AD config to do anything.

One of these days, I'll try to setup DHCP IPv6 in my LAN properly. HTH

### Which adblocker(s) did you use when testing this?

(Other)

### Adblocker version(s)

pihole. I just ran pihole -up and saw this message and wanted to report it.

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

If I remember correctly, I used the first 3 options for Malware, Adblocking and Telemetry that were listed in the pihole adlist selectors

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://adaway.org/hosts.txt
https://v.firebog.net/hosts/AdguardDNS.txt
https://v.firebog.net/hosts/Admiral.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
 https://v.firebog.net/hosts/Easyprivacy.txt
https://v.firebog.net/hosts/Prigent-Ads.txt
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt

### Which browser(s) did you use when testing this?

Chromium for Linux (Manifest V2)

### Browser version(s)

I saw this message in a terminal prompt. But I'm currently using Chromium to submit this report. I'm surprised that my piholeOS has this browser and LibreOffice installed, I probably need to slim down my OS in some manner

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

latest raspbian debian 32bit, I just downloaded it about 5 days ago

**Comment by iam-py-test** [comment]
I'm guessing this is caused by the HOSTs version not filtering out IP addresses, including IPv6 addresses. This shouldn't cause issues with normal Linux or Windows HOSTs files, but I guess Pihole thinks differently. Curious that it doesn't complain about the V4 addresses.

**Comment by DandelionSprout** [comment]
While my experience with Pi-hole's UI is limited, I suppose the updater is complaining about one of the two parts:
1) The `::` part.
2) The `2600:1f18:43d1:2a04:ee05:261e:d408:7ba1` part.

Option 1 would be strange if Pi-hole didn't support, while option 2 I could somewhat understand (since it uses colons where PH is likely expecting domains with dots).

I know from my time on https://filterlists.com/ that some Hosts- and domains-file tools could be able to block IPs too with this kind of syntax, but I've long since forgot which ones; which is the main reason why these kinds of entries have remained in those list versions.

**Comment by Lurick73** [comment]
Getting this too:
Sample of invalid domains:
      - 2600:1f18:43d1:2a04:ee05:261e:d408:7ba1
      - 2a02:1668:1034::2
      - demoniacipő.com
      - demoniatürkiye.com
      - gummistøvlerhunter.com

**Comment by DandelionSprout** [comment]
I'll look into this later today. Thanks for the headsup in advance.
