### ISSUE TITLE
Parameters that cannot be removed from the Bilibili website

### ISSUE THREAD

**Issue by DeepChirp** [DandelionSprout/adfilt#751]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

`https://www.bilibili.com/video/BV1g24y1h7zc`
If the user logs in and opens any video page on Bilibili, then a parameter called `vd_source` will be added. Although I added the rule `||bilibili.com^$removeparam=vd_source` in Actually Legitimate URL Shortener Tool, this parameter still cannot be removed. I'm guessing that some script on the site is at work, so someone who knows about scripting needs to be able to deal with this.

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Microsoft Edge (Manifest V2)

**Comment by iam-py-test** [comment]
I can't sign up as it appears to require a phone number

**Comment by shenzhiming88** [comment]
> I can't sign up as it appears to require a phone number. My hypothesis is that it uses [history.replaceState](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) to change the displayed URL without loading the new page (and thus bypassing any browser extensions). If you copy and paste the URL into a new tab, is the parameter removed? That is all speculation, and I probably am wrong.

possible. Parameters were removed first, then reappeared.
When it is convenient for you, I can provide you with the account number.

**Comment by iam-py-test** [comment]
Sorry for the delay. If you feel comfortable with that, you can email it to me at iam-py-test[@]protonmail[.]com
If not, I can try to investigate without an account.

**Comment by shenzhiming88** [comment]
> Sorry for the delay. If you feel comfortable with that, you can email it to me at iam-py-test[@]protonmail[.]com If not, I can try to investigate without an account.

There may be a time difference between the two of us. It is best when you and I are online at the same time, you send the QR code here, and then I scan it to log in. If you log in directly with account number and password, you also need to verify my mobile phone.

**Comment by iam-py-test** [comment]
Sorry for the delay.
I'm in Eastern Timezone, if that matters. I should be available from now to 11:30 (my timezone).
If that doesn't work, can you open the Logger, reproduce the issue, and post back with the log?

**Comment by shenzhiming88** [comment]
> Sorry for the delay. I'm in Eastern Timezone, if that matters. I should be available from now to 11:30 (my timezone). Just tell me when you are ready and I can try to login. If that doesn't work, can you open the Logger, reproduce the issue, and post back with the log? I'm sorry, but working across timezones is hard

You can send me the login QR code as soon as you get online today so I'm still online.

**Comment by iam-py-test** [comment]
Code:
![image](https://user-images.githubusercontent.com/84232764/214033254-3b8fd983-5a31-4c01-8087-b4baf42bd6e0.png)
It will expires fairly soon though

**Comment by shenzhiming88** [comment]
> @shenzhiming88 here is the code (I think I did it right) Code: ![image](https://user-images.githubusercontent.com/84232764/214034033-a51cc6d8-148f-45c3-a9a3-72fe8503b5bf.png)
> 
> It will expire fairly soon though

Oh sorry, I just saw that. Please send it again.

**Comment by iam-py-test** [comment]
![image](https://user-images.githubusercontent.com/84232764/214038030-c3efe957-e5e7-4d45-a4f1-cf6f9c1a60b5.png)

**Comment by shenzhiming88** [comment]
> ![image](https://user-images.githubusercontent.com/84232764/214038030-c3efe957-e5e7-4d45-a4f1-cf6f9c1a60b5.png) Sorry for the delay

Very strange, I scan this QR code and there is no response

**Comment by iam-py-test** [comment]
![image](https://user-images.githubusercontent.com/84232764/214038606-8b6591f3-92ee-404c-a62a-bfe27984d693.png)

**Comment by iam-py-test** [comment]
Looks like it worked. Thanks

**Comment by shenzhiming88** [comment]
> I see it. Investigating...

OK, I guess some script causes this.

**Comment by iam-py-test** [comment]
Off-topic, but does `||bilibili.com^$removeparam=spm_id_from` seem to break anything?
It seems to cause "video not found errors" on my end

**Comment by shenzhiming88** [comment]
> Off-topic, but does `||bilibili.com^$removeparam=spm_id_from` seem to break anything? It seems to cause "video not found errors" on my end Right now, I need to get ready for work, but I will look into this later. Sorry

This parameter doesn't seem to break anything, at least on my computer.

**Comment by iam-py-test** [comment]
Odd. Maybe it has something to do with me using Firefox and you using Edge. Not relevant to this issue, just noticed that.

**Comment by iam-py-test** [comment]
I _think_ I have isolated the script responsible, and that completely removing replaceState is the best solution.
Please try this rule and report back:
```adblock
bilibili.com##+js(set,history.replaceState,noopFunc)
``` 
It's not a great rule, but I don't _think_ it breaks anything

**Comment by shenzhiming88** [comment]
> I _think_ I have isolated the script responsible, and that completely removing replaceState is the best solution. Please try this rule and report back:
> 
> ```
> bilibili.com##+js(set,history.replaceState,noopFunc)
> ```
> 
> It's not a great rule, but I don't _think_ it breaks anything

This rule can indeed remove vd_source, but since uBlock cannot remove the parameters of the video link opened from the recommendation bar on the right, I used a script using the replaceState method. This rule will cause the script to fail. I don't think there is a good way to handle this.

**Comment by iam-py-test** [comment]
Ok, thanks.
I will see if there is a better solution.

**Comment by DandelionSprout** [comment]
Can you (Mostly shenzhiming) post an instance of what a URL *with* `vd_source` in it looks like? For example `https://www.bilibili.com/video/BV1g24y1h7zc/?vd_source=johnmadden`?

**Comment by shenzhiming88** [comment]
> Can you (Mostly shenzhiming) post an instance of what a URL _with_ `vd_source` in it looks like? For example `https://www.bilibili.com/video/BV1g24y1h7zc/?vd_source=johnmadden`?

This parameter is related to the user's personal information, so I found a example on the Internet: `https://www.bilibili.com/video/BV1WZ4y1v7pq/?spm_id_from=333.337.search-card.all.click&vd_source=a0a2bf40b0c968029d22c1cceee21c53`
(from `https://nga.178.com/read.php?tid=34162479&rand=263`)

**Comment by shenzhiming88** [comment]
> Hmm… seems like uBlock Origin successfully removes `vd_source` from that link when I'm _not_ logged in. So I have limited ideas on how to fix this.
> 
> Does the problem remain if you use these entries in User Filters (For almost every non-inline script I could find on the page that didn't break something)?
> 
> ```
> */log/$domain=bilibili.com
> ||cm.bilibili.com^$all
> /bili-collect.js$all
> ||bilibili.com^*/data/collector^$all
> ||boss.hdslb.com^$all
> ||bilibili.com/x/click-interface^$all
> ||bilibili.com/*/is_forbid^$all
> ||bilibili.com/*/log-reporter.js$all
> */laputa-header/$all
> ||hdslb.com/*/pcdn-$all
> ||hdslb.com/*/nc-loader-$all
> ```

Still exists. This seems difficult to deal with.

**Comment by iam-py-test** [comment]
This is caused by the `vf` function on line 197 of `https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js`
<details>
<summary>Trace</summary>
replaceState blob:https://www.bilibili.com/744c15ef-0e23-4c0e-9f6a-7c04d75fdde2:5 (this line can be ignored)<br>
    ht https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/sentry-5.7.1.min.js:2 <br>
    vf https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    mf https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    replace https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    transitionTo https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    confirmTransition https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    f https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    f https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    gf https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    confirmTransition https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    f https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    yf https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    f https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    gf https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    confirmTransition https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    transitionTo https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    replace https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    replace https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    e https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    p https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:190 <br>
    O https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:190 <br>
    x https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:190 <br>
    n https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    s https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    (Async: promise callback) <br>
    n https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    s https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    exports https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    exports https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    checkLoginInfoForHeaderV3 https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    e https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    p https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:190 <br>
    O https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:190 <br>
    x https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:190 <br>
    n https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    s https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    exports https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    exports https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    init https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    e https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    p https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:190 <br>
    O https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:190 <br>
    x https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:190 <br>
    n https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    s https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    (Async: promise callback) <br>
    n https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    s https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    exports https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    exports https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    mounted https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    Bn https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    an https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    insert https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    S https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    ga https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    _update https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    get https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    t https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    $mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    $mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:7 <br>
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    onReady https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    onReady https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:197 <br>
    n https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:180 <br>
    n https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.366216d83af1f0d17e2505f09cab46978fafc9c1.js:1 <br>

</details>

**Comment by KamiyaMinoru** [comment]
I tried 
https://www.bilibili.com/video/*/?spm_id_from=* redirector=https://www.bilibili.com/video/$1?vd_source=0
but it do not help redirect even not remove spm_id_from

**Comment by iam-py-test** [comment]
>  https://www.bilibili.com/video/*/?spm_id_from=* redirector=https://www.bilibili.com/video/$1?vd_source=0

In ClearURLs or uBlock Origin?

**Comment by iam-py-test** [comment]
I have made a (kind-of poorly made) extension which _should_ fix this issue. It's barely been tested, and isn't great code, and I am not extremely happy asking people to install a separate extension just for this (maybe there's still a way to prevent this from happening, or something a custom uBo scriptlet can do?), so buyer beware. Also needs to be loaded as a dev mode extension in FF/Chrome
https://github.com/iam-py-test/bilibili-url-clean

**Comment by KamiyaMinoru** [comment]
> > https://www.bilibili.com/video/*/?spm_id_from=* redirector=https://www.bilibili.com/video/$1?vd_source=0
> 
> In ClearURLs or uBlock Origin?

ubo

**Comment by iam-py-test** [comment]
> ubo

This is not supported in uBo.

**Comment by iam-py-test** [comment]
@shenzhiming88 can you try adding this to your [user resources location in uBo](https://github.com/iam-py-test/bilibili-url-clean/blob/main/scriptlet.js), and then add this to "My filters":
```adblock
bilibili.com##+js(replace-state-clean,vd_source)
```
It's still not pretty (I would have preferred a solution which works in default uBo & in AdGuard), but it's far better than the extension.

**Comment by KamiyaMinoru** [comment]
> @shenzhiming88 can you try adding this to your [user resources location in uBo](https://github.com/iam-py-test/bilibili-url-clean/blob/main/scriptlet.js), and then add this to "My filters":
> 
> ```
> bilibili.com##+js(replace-state-clean,vd_source)
> ```
> 
> It's still not pretty (I would have preferred a solution which works in default uBo & in AdGuard), but it's far better than the extension.

Thanks but not work at all.

**Comment by iam-py-test** [comment]
Can you go to the uBlock Origin settings (I assume you are using uBlock Origin, correct me if I am wrong), enable advanced user settings, click the gear option, and set [userresourceslocation ](https://github.com/gorhill/uBlock/wiki/Advanced-settings#userresourceslocation) to https://raw.githubusercontent.com/iam-py-test/bilibili-url-clean/main/scriptlet.js

**Comment by KamiyaMinoru** [comment]
> Can you go to the uBlock Origin settings (I assume you are using uBlock Origin, correct me if I am wrong), enable advanced user settings, click the gear option, and set [userresourceslocation ](https://github.com/gorhill/uBlock/wiki/Advanced-settings#userresourceslocation) to https://raw.githubusercontent.com/iam-py-test/bilibili-url-clean/main/scriptlet.js

![image](https://user-images.githubusercontent.com/78710607/229100630-1cafda10-49c7-49b7-bdc0-88f0ca57ffcb.png)
![image](https://user-images.githubusercontent.com/78710607/229100850-ca633b4d-4b4d-4f48-b31c-cb07a8f09b40.png)

this one not work

**Comment by KamiyaMinoru** [comment]
> Can you also install https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt as a filterlist

Hi thanks... I will consider (for I can just use a script to close it in tampermonkey, instead of couples install...)
by the way, if I want to remove param etc from copying bilibili (via the share button), do you also have suggestion?

**Comment by iam-py-test** [comment]
>  by the way, if I want to remove param etc from copying bilibili (via the share button), do you also have suggestion?

Sadly, no.

**Comment by shenzhiming88** [comment]
> @shenzhiming88 can you try adding this to your [user resources location in uBo](https://github.com/iam-py-test/bilibili-url-clean/blob/main/scriptlet.js), and then add this to "My filters":
> 
> ```
> bilibili.com##+js(replace-state-clean,vd_source)
> ```
> 
> It's still not pretty (I would have preferred a solution which works in default uBo & in AdGuard), but it's far better than the extension.

Yes, this rule does not work.

**Comment by iam-py-test** [comment]
Sorry, my instructions weren't very clear. You need to check "I am an advanced user" -> click on the gear icon -> set userResourcesLocation to https://raw.githubusercontent.com/iam-py-test/bilibili-url-clean/main/scriptlet.js
Then that scriptlet should be valid.

**Comment by DandelionSprout** [comment]
Was any sort of consensus on a fix ever reached? If not, it's probably sadly time to declare it a closed case.

**Comment by iam-py-test** [comment]
As far as I am aware, the only solution was a custom scriptlet. But if someone smarter wants to take a crack it, there may be another way.

**Comment by DeepChirp** [comment]
I'm sorry I've been missing this message before. I just tried doing this, but the extra parameters still exist unless the webpage is refreshed.

**Comment by DandelionSprout** [comment]
Comments will remain open indefinitely, but I feel the time has arrived for me to get the number of open issues on the top bar of the repo to 0 again.

**Comment by KamiyaMinoru** [comment]
> > by the way, if I want to remove param etc from copying bilibili (via the share button), do you also have suggestion?順便問一下，如果我想從複製bilibili中刪除param等（透過分享按鈕），你還有建議嗎？
> 
> Sadly, no. 可悲的是沒有。

my solution: I installed mouse gesture and call a js to detect/modify/remove nonnecessary params

**Comment by DeepChirp** [comment]
@DandelionSprout @iam-py-test Even though two years have passed... I’ve found that this rule works:

```
||s1.hdslb.com/bfs/static/jinkela/video/video.*$script,replace=/vd_source:this\.vdSource/vd_source:undefined/,domain=bilibili.com
```

See: uBlockOrigin/uAssets#34031

**Comment by iam-py-test** [comment]
Sorry for the delay in responding.
$replace [can only be used in trusted filterlists](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#replace), which means this would not work for most users.
I suppose we could add the filter anyway, since I don't think there's any *harm*, and recommend people make Legit URL a trusted list.
Thanks
