### ISSUE TITLE
De-Politificator for anti-trans tweets

### ISSUE THREAD

**Issue by pixiekat** [DandelionSprout/adfilt#755]
## Which entry/entries are you submitting?

```
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/ tra[s]? /i)
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/Adult[ /_]?Human[ /_]?Female/i)
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/Standing[ _]?For[ _]?XXX/i)
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/Respect[ _]?My[ _]?Sex/i)
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/biological sex/i)
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/what is a woman/i)
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/SexNotGender/i)
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/IfYouWantMyX/i)
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/SexMatters/i)
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/female spaces/i)
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#article:has-text(/Women[ _]?Won[\']?t[ _]?Weesht/i)
```

## Which things do they block, hide, or unbreak?

The growing rise in transphobia among the platform is, quite frankly, annoying and irritating.. not to mention harmful to see every other post. This would try and eliminate things like the following. 

![Screenshot_6](https://user-images.githubusercontent.com/32232155/213871291-bd4f2182-7afc-4131-8a76-090ad16b8810.png)

## Which of my lists are you submitting it to? 
Twitter and Mastodon De-Politificator

## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s): uBlock Origin 1.46.0

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak

EasyList
EasyPrivacy

Online Malicious URL Blocklist

Peter Lowe’s Ad and tracking server list 3,666 used out of 3,668

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive lists/TabloidRemover-MastodonCategoryForImports.csv
🇪🇺 GDPR 451 List of Mostly American Websites Who Hate Europe and Privacy Rights
➕ Actually Legitimate URL Shortener Tool - Affiliate tag allowlist
➗ Actually Legitimate URL Shortener Tool
🌞 Dandelion Sprout's Anti-Racism List
🎙 Rickroll Link Identifier
🎛 Reddit Trash Removal Service
🎬 Stop Autoplay On Video Sites
💐 Anti-'Awful comments' list
📏 Imperial Units Remover
📱 Staying On The Phone Browser
🔮 I Don't Want to Download Your Browser
🔴 Anti-'Unnecessary notification counters' List 
🖥️ Dandelion Sprout's Website Stretcher
🖱 Anti-'PC component price hiders' List
🥒 Anti-'Non-news' List
😌 Anti-'Newsstories about celebs giving birth' List
🚌 Anti-'Bad capitalism' List
Anti-AutoTranslation-List 
iHateCircles

## (Optional) Which browser(s) and version did you use?

Firefox Nightly 110.0a1

**Comment by pixiekat** [comment]
(Hope it's ok, it's my first submission!)

**Comment by DandelionSprout** [comment]
It's a fair request to make; as even though I was unfamiliar with most of the suggested terms and have had to research how they're used on Twitter, the research led me to find a lot of other blockable terms too, which in turn proved why terms why "Adult human female" needs to be blocked by the list too. I'll upload the first update based on this issue report fairly soon tonight.

**Comment by pixiekat** [comment]
Thanks! Sorry for making you have to learn about them ;) I tried to get as many as I could in a workable manner but feel free to adjust!
