### ISSUE TITLE
False positive: ecs.gdn

### ISSUE THREAD

**Issue by L8X** [DandelionSprout/adfilt#756]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

ecs.gdn blocked by Dandelion Sprout's Anti-Malware List

This domain is an upcoming private-access eTLD hosted by my company, Simulhost.
It is completely secure and has no malware distribution on it.

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

108 Alpha

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2), Firefox, Brave Browser, Microsoft Edge (Manifest V2), Kiwi Browser, Internet Explorer 11

### Which OS(s) did you use when testing this?

Windows 10, Linux, Android

**Comment by iam-py-test** [comment]
I get 403 forbidden when trying to access that website. Without an actual website, it's hard to verify the legitimacy of this website.

**Comment by iam-py-test** [comment]
Ok, thanks.
I am going to leave this up to Imre (DandelionSprout)
> Instagram [...] links work fine.

Odd. It showed as down earlier, but now it works. Probably an issue on my end

**Comment by DandelionSprout** [comment]
For much the same reasons as in #709, I'm not entirely comfortable with whitelisting domains that haven't gone properly live yet. If it goes into production use and/or has content on it can be accessed by general users, then I'd whitelist it fairly quickly.

**Comment by DandelionSprout** [comment]
After 6 weeks and no signs of the site going live, I'll close this thread for the time being. Comments will remain open.
