### ISSUE TITLE
Invalid entries seen - PiHole 5.15

### ISSUE THREAD

**Issue by Lurick73** [DandelionSprout/adfilt#757]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

This seems to be an issue with PiHole parsing characters as otherwise everything seems to be working.
  [i] Target: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  [✓] Status: Retrieval successful
  [i] Imported 13656 domains, ignoring 3 non-domain entries
      Sample of non-domain entries:
        - keentürkiye.com
        - nobulltürkiye.com
        - sauconyløbesko.com

### Which adblocker(s) did you use when testing this?

DNS adblocking server(s)

### Adblocker version(s)

PiHole 5.15.1

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://adaway.org/hosts.txt
https://v.firebog.net/hosts/AdguardDNS.txt
https://v.firebog.net/hosts/Admiral.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
 https://v.firebog.net/hosts/Easyprivacy.txt
https://v.firebog.net/hosts/Prigent-Ads.txt
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

Firefox 109.0 (64-bit)

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

Windows 11 22H2

**Comment by DandelionSprout** [comment]
It's far from all adblock tools (or other tech tools) out there that can handle non-English letters in domains. but thankfully it should be easy for me to convert those 3 domains to the IDN format fairly quickly. Give me 10min.
