### ISSUE TITLE
Brave browser crashes when opening "youtu.be" links

### ISSUE THREAD

**Issue by Shutruk** [DandelionSprout/adfilt#758]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Every time I try to open a link that consists of the youtube short version "youtu.be". brave crashes.

### Which adblocker(s) did you use when testing this?

Brave's built-in adblocker

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

CJX
Easylist-Cookie
Fanboy Annoyances
Fanboy's Mobile Notifications
ublock annoyances
AdguardFilters
adfilt

### Which browser(s) did you use when testing this?

Brave Browser

### Browser version(s)

1.47.171 Chromium: 109.0.5414.87 (64 bits)

### Which OS(s) did you use when testing this?

Windows 11, macOS

**Comment by iam-py-test** [comment]
> adfilt

What do you mean by this? All the filters in adflit?

I'm not very knowledgeable about Brave, but it feels a bit odd that a filterlist would crash the browser. Have you tried disabling all custom filters and seeing if it persists?

**Comment by DandelionSprout** [comment]
How do the crashes occur? Is it just the tab that closes/crashes, or does the entire browser close?

**Comment by Shutruk** [comment]
@iam-py-test 
Sorry for not specifying the one I'm using!
It's https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt

@DandelionSprout 

No matter how many tabs or windows are open, brave crashes completely  and closes without any error or notification, when I disable this filter specifically, opening youtu.be links work as intended.

**Comment by iam-py-test** [comment]
>  It's https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt

That makes a bit more sense (although the fact that a filterlist can crash the browser still feels like a browser bug).
The "ClearURLs for uBo" is just the ClearURLs rules converted into a filterlist specially for uBlock Origin (and AdGuard). The conversion script is not flawless, the list will still have any issues from the ClearURLs list (which is known to break websites and gets very little maintenance), and was never designed for (or tested in) Brave's adblocker.
Oddly, I don't see any youtu.be rules in that list though, and only 4 fairly normal rules for youtube.com. I suspect that maybe one of the global rules (maybe a regex?) is applying to that URL and Brave doesn't like it (but that's just speculation).

**Comment by Nojuuu** [comment]
Brave added support for removeparam recently but not everything works yet, for example:
https://github.com/brave/adblock-rust/issues/246
https://github.com/brave/adblock-rust/issues/245

**Comment by Nojuuu** [comment]
Also could be related to this https://github.com/brave/adblock-rust/issues/248 ? If so, you'll need to wait for update.

**Comment by iam-py-test** [comment]
Thank you @Nojuuu 
I don't have time to look into this, but that sounds likely

**Comment by Shutruk** [comment]
Thanks for the help, I will disable it then till a fix is available.

**Comment by Nojuuu** [comment]
Fix should be available now:
https://github.com/brave/brave-browser/releases/tag/v1.47.186

**Comment by iam-py-test** [comment]
@Shutruk can you confirm that there are no issues on the fixed Brave version?
If not, then I can install Brave on a VM and look into what ClearURLs for uBo is doing wrong

**Comment by Shutruk** [comment]
@iam-py-test no more crashes happened after 1.47.186, the issue seems to be fixed.
