### ISSUE TITLE
Dandelion Sprout's Annoyances List breaks YouTube Auto-Play Next video feature when enabled

### ISSUE THREAD

**Issue by AdishSagarawat** [DandelionSprout/adfilt#766]
Works like a charm when not using this list in uBO.

Check Yourself.

**Comment by iam-py-test** [comment]
This is because the annoyances list includes "Stop Autoplay On Video Sites", which prevents autoplay on various websites, including YouTube. Sadly, the easiest solution is to just disable Dandelion Sprout's annoyances list.
You also can add these rules to your "my filters" tab, although they will stop working if Imre ever changes the list:
```adblock
/endscreen.js$script,domain=youtube.com|youtu.be|youtube-nocookie.com,badfilter
youtube.com#@##head.ytd-compact-autoplay-renderer
youtube.com#@#.checkbox-on-off
youtube.com#@#.watch-sidebar-head
m.youtube.com#@#.ytm-autonav-bar
```

**Comment by DandelionSprout** [comment]
I can confirm iam-py-test's explanation, with the added context that the subfile was originally added after I personally witnessed *several* evening course teachers fail to turn off autoplay after showing course videos, resulting in the teachers scrambling to figure out how to turn off clickbait celebrity videos.

**Comment by AdishSagarawat** [comment]
Can''t whitelist youtube from the list?

**Comment by iam-py-test** [comment]
Remove the anti-autoplay list from the larger Annoyances list, or remove YouTube from the autoplay list?
In my opinion, this is the problem with "annoyances" lists, as the definition of "annoyance" is very subjective. 

Imre, the description on the Annoyances list doesn't seem to mention blocking autoplay.

**Comment by DandelionSprout** [comment]
>Imre, the description on the Annoyances list doesn't seem to mention blocking autoplay.

I'll attempt to mention that real quick now.

**Comment by iam-py-test** [comment]
@AdishSagarawat do my rules work?
Can this issue be closed?

**Comment by AdishSagarawat** [comment]
@iam-py-test They are not working

As of now, I have removed the Annoyance List from uBO.

**Comment by iam-py-test** [comment]
Try these:
```adblock
@@/endscreen.js$script,domain=youtube.com|youtu.be|youtube-nocookie.com
youtube.com#@##head.ytd-compact-autoplay-renderer
youtube.com#@#.checkbox-on-off
youtube.com#@#.watch-sidebar-head
m.youtube.com#@#.ytm-autonav-bar
```
They seem to work on my end in Firefox.
Of course, removing the annoyances list (and installing the sublists you want) is also an option.

**Comment by iam-py-test** [comment]
As there has been no response from the OP, I am closing this issue. The comments remain open

**Comment by AdishSagarawat** [comment]
@iam-py-test Thanks! It worked.
ig it should be included in Reradme for users...

**Comment by DandelionSprout** [comment]
I remember I've proposed to uBO to support `@@` for `!#include` rows a few years ago, but they didn't seem eager on the idea at the time.

**Comment by iam-py-test** [comment]
> I remember I've proposed to uBO to support `@@` for `!#include` rows a few years ago, but they didn't seem eager on the idea at the time.

That would be very helpful, but I understand why it is hard to implement
