### ISSUE TITLE
Dandelion Sprout's Annoyances List (URL SHORTNER) Not working fully on Amazon

### ISSUE THREAD

**Issue by AdishSagarawat** [DandelionSprout/adfilt#767]
Not removing s?rrh%n...

![image](https://user-images.githubusercontent.com/69076256/216367546-13084788-98b5-4483-bc15-59c2b5243a2b.png)

**Comment by AdishSagarawat** [comment]
See 
![image](https://user-images.githubusercontent.com/69076256/216368086-af80dce1-cf4c-4d39-a5c5-2f54b03e1f5d.png)

**Comment by AdishSagarawat** [comment]
Same on flipkart
![image](https://user-images.githubusercontent.com/69076256/216368191-8cb3e790-08c9-4d6a-8d62-907e9fdce3aa.png)

**Comment by iam-py-test** [comment]
> See ![image](https://user-images.githubusercontent.com/69076256/216368086-af80dce1-cf4c-4d39-a5c5-2f54b03e1f5d.png)

`/ref` can not be removed. 

Please post **links** instead of images. Reading URLs out of images is difficult.

**Comment by AdishSagarawat** [comment]
Ohh Sorry

**Comment by iam-py-test** [comment]
Can you post the links?

**Comment by DandelionSprout** [comment]
I can see the links well enough (though they're very tricky to write manually), so essentially it's a matter of whether it's safe to remove `rh` and `sbo` from Amazon, and `sid` from Flipkart.

**Comment by DandelionSprout** [comment]
On `https://www.amazon.in/Headphones-Sony-Earbuds-Accessories/s?rh=n%3A1388921031%2Cp_89%3ASony`, `rh=` can't be removed at all, as it seems to cause the page to redirect to the Amazon home page instead.

On `https://www.amazon.in/Sony-WI-XB400-Wireless-Bluetooth-Headphones/dp/B07WNXS613/ref=sr_1_4_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D`, it *seems* safe to remove `sbo` from what I can currently tell.

While on `https://www.flipkart.com/audio-video/headset/sony~brand/pr?sid=0pm%2Cfcn`, removing `sid` causes an error page.

**Comment by AdishSagarawat** [comment]
So,
Will @DandelionSprout add a rule to remove sbo, or I have to do it manually?

**Comment by AdishSagarawat** [comment]
Also, I think that removing ref also will not cause any breakage.

**Comment by iam-py-test** [comment]
>  Will @DandelionSprout add a rule to remove sbo, or I have to do it manually?

sbo is removed from Amazon (https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt#L1623). Please update your lists.
> Also, I think that removing ref also will not cause any breakage.

Do you mean `/ref=sr_1_4_mod_primary_new` from `https://www.amazon.in/Sony-WI-XB400-Wireless-Bluetooth-Headphones/dp/B07WNXS613/ref=sr_1_4_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D`?
If so, then uBlock Origin (and by extension Legit URL) can not remove it. We can only remove query parameters (the stuff after the ?)
