### ISSUE TITLE
Problem with general blocking of .monster

### ISSUE THREAD

**Issue by Tealk** [DandelionSprout/adfilt#771]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

The problem is that .monster is blocked on their list and I run some services with the TSL .monster which are not reachable this way.
https://rollenspiel.monster and all subdomains that are used

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

I do not use the list myself, I have only been pointed to it by users.

### Which browser(s) did you use when testing this?

Firefox

### Which OS(s) did you use when testing this?

Linux

**Comment by DandelionSprout** [comment]
The site seems perfectly legitimate enough to me too, so I'll whitelist it from https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt#L32 fairly quickly today.
