### ISSUE TITLE
##.: Hides page elements, based on one or more class values in the F12 "Elements" filetree (separated with full-stops).

### ISSUE THREAD

**Issue by malicerainbow** [DandelionSprout/adfilt#774]
I’m sorry for bothering you I’m probably just stupid or below average intelligence 

Thank you for your respiratory it does help someone what but I’m still confused on this first one 

##.: Hides page elements, based on one or more class values in the F12 "Elements" filetree (separated with full-stops).

so I know that F 12 is how we get to developer tool or inspect element if using Firefox or chrome 

man’s I have been learning css and html 

so when you said it hides page elements which that part is html based on one or more class values 

do you mean like? Like selector.{property: 
[”value;”] } 

Is this this the value you meant?

so like if I did ##. 

It would block all element with a value? 

meaning 

<button class=btn>click me</button>

.btn {background-color:red;} 

so since this element has a class with a value aka “red”

it gets blocked? As well any other elements with a class of a property and value?

Also I don’t understand what you mean separated with full stops 

Again sorry with even your version I have question I’m probably just too dumb to comprehend what you simplified 

Also I will be happy to a donation 

Any chance could I get 1 on 1 with you? I really want to understand this so that I don’t have to always bother Adguard I’m the kind of person that only wants to take my computer into a shop to get fix after iv tried everything imaginable of searching, learning, reading, trying 

And I really want to understand this!!! I’m just worried I’m too dumb to

**Comment by DandelionSprout** [comment]
I was thinking that linking to that page would be helpful and considered friendly, and not make you continue to extremely panic the way you've done on https://github.com/AdguardTeam/AdguardFilters/issues overnight. Calm down very, very much, or this will be the quickest block I've ever made on a Git site.

I can at least answer the core question regarding `##.`: If we take this screenshot from Dev Tools below:
![image](https://user-images.githubusercontent.com/22780683/217171343-d079549f-c1e7-4f1a-b392-78d253efb602.png)
Then `##.` simply tells the adblocker to look for any `class=` values. For example `page-responsive`. As a result, `##.page-responsive` would hide that element.

**Comment by malicerainbow** [comment]
I’m sorry really I am I’m not at all trying to excuse I swear but I am autistic and I’m getting ABA therapy now as a 26 year old adult when I was supposed to get it as a child. Applied behavioral therapy. I don’t have much social skills or social cues. I’m learning social skills right now through Texana. I actually have another group session Tomorrow. So please know I am not trying to harass anyone. Or cause trouble or troll. I don’t have complete control of my emotions. 


I really am sorry I didn’t mean to upset you! And I really am thankful for what you sent me. I’m sorry

**Comment by malicerainbow** [comment]
> I was thinking that linking to that page would be helpful and considered friendly, and not make you continue to extremely panic the way you've done on https://github.com/AdguardTeam/AdguardFilters/issues overnight. Calm down very, very much, or this will be the quickest block I've ever made on a Git site.
> 
> I can at least answer the core question regarding `##.`: If we take this screenshot from Dev Tools below: ![image](https://user-images.githubusercontent.com/22780683/217171343-d079549f-c1e7-4f1a-b392-78d253efb602.png) Then `##.` simply tells the adblocker to look for any `class=` values. For example `page-responsive`. As a result, `##.page-responsive` would hide that part of the page.

Im sorry I will try to do better for now on!

**Comment by malicerainbow** [comment]
> I was thinking that linking to that page would be helpful and considered friendly, and not make you continue to extremely panic the way you've done on https://github.com/AdguardTeam/AdguardFilters/issues overnight. Calm down very, very much, or this will be the quickest block I've ever made on a Git site.
> 
> I can at least answer the core question regarding `##.`: If we take this screenshot from Dev Tools below: ![image](https://user-images.githubusercontent.com/22780683/217171343-d079549f-c1e7-4f1a-b392-78d253efb602.png) Then `##.` simply tells the adblocker to look for any `class=` values. For example `page-responsive`. As a result, `##.page-responsive` would hide that part of the page.

I am allowed to send an issue if there is another syntax I’m  trying to understand right?

**Comment by DandelionSprout** [comment]
On paper, experimenting around with uBlock Origin's element picker (Icon below; other adblockers' pickers are less versatile) and the F12 element tree should be easier and quicker than asking others; so I sadly won't allow particularly many questions about such.
![image](https://user-images.githubusercontent.com/22780683/217185621-9fa05947-2a82-4d39-a0cf-fae36e02b136.png)

**Comment by malicerainbow** [comment]
> On paper, experimenting around with uBlock Origin's element picker (Icon below; other adblockers' pickers are less versatile) and the F12 element tree should be easier and quicker than asking others; so I sadly won't allow particularly many questions about such.
> ![image](https://user-images.githubusercontent.com/22780683/217185621-9fa05947-2a82-4d39-a0cf-fae36e02b136.png)

Could you at least recommend what I should study on to better understand this?

right now I’m taking YouTube courses on html and css 

I was planing to take courses on dev tool on YouTube also

but is there something more specific to what the syntax list is exactly that I can look up of a course?

**Comment by DandelionSprout** [comment]
YouTube courses on HTML and CSS are irrelevant to adblockers, as they only teach how to create such things, not how to modify them.

I don't think there are any courses in existence on adblocker syntax, it has unfortunately traditionally been a matter of "Messing around with element pickers and how to host TXT files" with no one (except arguably me, who also made [list templates for beginners](https://github.com/DandelionSprout/adfilt/blob/master/Adblock%20list%20templates/Adblock%20list%20template%20-Beginner-.txt) long ago) seeming to thinking about making a step-by-step guide for such.

**Comment by malicerainbow** [comment]
> YouTube courses on HTML and CSS are irrelevant to adblockers, as they only teach how to create such things, not how to modify them.
> 
> I don't think there are any courses in existence on adblocker syntax, as it has unfortunately traditionally been a matter of "Messing around with element pickers and how to host TXT files" with no one (except arguably me, who also made [list templates for beginners](https://github.com/DandelionSprout/adfilt/blob/master/Adblock%20list%20templates/Adblock%20list%20template%20-Beginner-.txt) long ago) seeming to think about making a step-by-step guide for such.

So the only way for me to learn the list you provided is by just messing around with the block element option of any adblocker and seeing what shows up in the custom rules, after you select something? 

Would doing courses on everything there is about dev tool elements help? 

I mean I just don’t understand I’m trying to be the person to learn this instead of depending on tech support but how can I learn if there’s material to go to teach me the syntax symbols you listed?

**Comment by iam-py-test** [comment]
> Would doing courses on everything there is about dev tool elements help?

Imre (DandelionSprout) might disagree (and he is far more knowledgeable than me), but I personally would say probably yes. Sadly, all of the adblocker references I'm aware of require at least a basic understanding of HTML/CSS. developer.mozilla.org is a good reference and has some guides on HTML/CSS, although all are about creating websites and not reverse engineering them.
The developer tools are really helpful, and even experienced filterlist maintainers probably still use them. Sadly, they also aren't the easiest to learn. I don't even think iOS Safari has devtools though, so if you are only using iOS, it is understandably harder (I started programming using only iOS, so I guess it's possible).
Sorry I can't be more helpful.

**Comment by DandelionSprout** [comment]
Sure I'm a big fan of fairies, but let me be very straightforward here:

*w h a t t h e f u c k*

Posting art portfolios in fullsize, that are just *barely* better than typical deviantART stuff, is not a recipe to get anywhere in the world of adblocking regardless of intent. I am closing this thread, and ceasing all further contact with you (malicerainbow), because there is 0% chance that anything good could come out of this if this thread continued.

**Comment by krystian3w** [comment]
https://adguard.com/kb/general/ad-filtering/create-own-filters/#cosmetic-rule

https://help.adblockplus.org/hc/en-us/articles/360062733293-How-to-write-filters#content-filters
