### ISSUE TITLE
For DandelionSprout

### ISSUE THREAD

**Issue by ghost** [DandelionSprout/adfilt#775]
.

**Comment by Faemacabre** [comment]
All i was trying to do was be nice and friendly im sorry if it didnt come off that way but i dont get social skills i dont get social cues, i dont get social norms, i dont understand how people are supposed to socialize with others who are not autistic i am learning this right now as an adult. I have to literally take classes on something you people just knew, of how to act, how to behave, how to interact with others, i dont have that luxury i have to learn it take classes on social skills
