### ISSUE TITLE
ITavisen.no er ødelagt

### ISSUE THREAD

**Issue by kristofferR** [DandelionSprout/adfilt#778]
## Beskriv problemet under denne linjen så detaljert og utdypende som mulig (inkl. nettlenker hvis det er noen):
Mesteparten av innholdet på forsiden av ITAvisen.no blir skjult med dette filteret aktivert. Kun artiklene på toppen og bunnen av siden vises, resten skjules.

https://itavisen.no/

## Hvilken reklameblokkerer og versjon brukte du da du testet dette?

- [x] uBlock Origin
- [ ] AdGuard (Betalt skrivebordsversjon)
- [ ] AdGuard (Nettleserutvidelse)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (Utvidelsen)

## Hvilke filterlister brukte du? Å ikke fortelle dette, vil føre til at saken blir midlertidig lukket frem til dette blir fortalt.

NOR, DNK, ISL: Dandelion Sprouts nordiske filtre

## Hvilke(n) nettleser(e) og versjon(er) brukte du?

Firefox 110

**Comment by DandelionSprout** [comment]
Takk for tipset. Selv om jeg allerede hadde blitt advart om det for 2 dager siden (https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-1425346184), skjønte ikke alvoret på det tidspunktet, og slet også med trøtthet som ikke ville gi slipp. Jeg skal ta en titt på saken ASAP i løpet av 15min nå.

**Comment by kristofferR** [comment]
Tusen takk! Vet ikke hvor mye takk du mottar, men er iallefall mange som setter pris på jobben du gjør selv om de ikke er bevisste på det. Sendte deg $10.

**Comment by DandelionSprout** [comment]
Takker og bukker. Det er ikke akkurat store penger donasjonsmessig i å gjøre disse tingene, men setter pris på at et anslag på flere hundre tusen benytter listen min i hverdagen.
