### ISSUE TITLE
False Positive: grainger.com

### ISSUE THREAD

**Issue by WMT-IT** [DandelionSprout/adfilt#780]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Grainger.com is a website used for ordering industrial supplies, used by factories and other industrial sites.

||grainger.com^$all,~inline-script,~inline-font

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

Adguard Home  v0.107.23

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Anti-Malware List

### Which browser(s) did you use when testing this?

Firefox, Chromium for Linux (Manifest V2), Microsoft Edge (Manifest V2)

### Browser version(s)

Librewolf, Edge Browser, Iridium Browser

### OS version(s)

Windows 10, Arch Linux

**Comment by DandelionSprout** [comment]
While I fully believe you, it's a mystery to me why `grainger.com` would be hosted on an IP (`64.132.201.92`) where ≥95% of the other domains are used in E-mail scams and malware. I'll try to get it whitelisted within 3 hours or so.
