### ISSUE TITLE
strims.top

### ISSUE THREAD

**Issue by BlazDT** [DandelionSprout/adfilt#787]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Site does not open on iOS due to this rule:

`||top^$document,domain=~caitlin.top|~corriente.top|~gdtot.top|~nicenature.top|~reminder.top|~magocoro.top|~castlevania.top|~suiten.top|~shucks.top|~1stream.top|~ambr.top|~techblog.top|~changlam10.top|~changlam11.top|~pdcdn1.top|~mastodon.top|~pressplay.top|~chillx.top`

### Which adblocker(s) did you use when testing this?

(Other)

### Adblocker version(s)

AdGuard for iOS 4.4.5

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Annoyances List

### Which browser(s) did you use when testing this?

(Other)

### Browser version(s)

Safari

### Which OS(s) did you use when testing this?

(Other)

### OS version(s)

iOS 16

**Comment by DandelionSprout** [comment]
I'm normally somewhat hostile to football stream sites, and I presume the site will get taken down within a month anyway, but I presume I've got little choice than to whitelist it when the request is made by an AdGuard Team member. Give me 15min.
