### ISSUE TITLE
Legitimate URL Shortener breaks Aliexpress homepage and product pages

### ISSUE THREAD

**Issue by butterbutts** [DandelionSprout/adfilt#789]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

aliexpress.com redirects to aliexpress.us for certain pages, including the home page and some product pages. These .us pages fail to load with "The page isn't redirecting properly.". The pages get stuck on "https://login.aliexpress.us/sync_cookie_write.htm?acs_random_token=" and then some page tracking data.

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Firefox

### Which OS(s) did you use when testing this?

Windows 11

**Comment by Nojuuu** [comment]
Try 
```adblock
@@||login.aliexpress.us^$removeparam=_ga
```

**Comment by butterbutts** [comment]
It looks like that works.

**Comment by iam-py-test** [comment]
Fixed in https://github.com/DandelionSprout/adfilt/commit/24dea8f2b90f4329d4239092db58bf3bf996d994 (accidentally deleted the 9 so flagged the wrong issue). @butterbutts can you remove @Nojuuu's rule, update Legit URL, and retest? Thanks
Thank you @Nojuuu for saving me the time of investigating.

**Comment by butterbutts** [comment]
I removed the rule and updated, it's working.
