### ISSUE TITLE
linkedin.com breakage

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [DandelionSprout/adfilt#795]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

“Start a post” button on your own Linkedin profile page leads to a blank overlay with your annoyances filter list.

### Add screenshots below if needed

![Screenshot 2023-02-28 at 13-59-38 Dimitris Kalaboukas LinkedIn](https://user-images.githubusercontent.com/101707608/221873172-a1670639-9abc-4de2-aa60-148dce151a3f.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.47.2

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

All default uBO filters plus your annoyances filter list.

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

110.0

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

22H2

**Comment by iam-py-test** [comment]
Can you open [the uBlock Origin logger](https://github.com/gorhill/uBlock/wiki/The-logger), reproduce the issue, and post back with [the logger export](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog)?

**Comment by iam-py-test** [comment]
Don't worry, that contained the log I needed. However, I don't see anything going on that could cause the issue, which is odd.
I have created a test LinkedIn account and am looking into the problem

**Comment by iam-py-test** [comment]
Found the issue and fixed it (it was caused by a very broad entry for blocking social media share icons/buttons). Thank you for reporting this.

**Comment by DimitrisKalaboukas** [comment]
@iam-py-test Well done!!!

**Comment by DandelionSprout** [comment]
I've slowly begun to realise that I could indeed add whitelistings for a fair few of the entries in the "Anti-'Social share' list" section, though it's hard to tell which ones and for which sites.
