### ISSUE TITLE
[Question] I am confused with some lists.

### ISSUE THREAD

**Issue by AdishSagarawat** [DandelionSprout/adfilt#797]
Are the following lists already included in Annoyances List?
____________________________________________________________
Empty Padding Remover                                                    |
I Don't Want To Download Your Browser                            |
Imgur: Pure Imagery Experience                                         |
Website Stretcher                                                               |
Website Stretcher Vertical                                                   |
YouTube: Even More Pure Video Experience                       |
Anti-Elsagate List                                                               |
Ad Removal List for Unusual Ads                                        |
stayingonbrowser                                                               |
Browse websites without logging in                                    |
Dandelion Sprout's Anti-Malware List                                 |
ExtremelyCondensedList                                                     |
____________________________________________________________

**Comment by iam-py-test** [comment]
> Empty Padding Remover |
>  I Don't Want To Download Your Browser |
>  Website Stretcher |
>  Ad Removal List for Unusual Ads |
>  stayingonbrowser |
>  Browse websites without logging in |
>  Dandelion Sprout's Anti-Malware List |

These are all included. Not sure about the rest.

**Comment by DandelionSprout** [comment]
Whenever anyone is in doubt, one can doublecheck https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList and see if the filename shows up in an `!#include` line.
