### ISSUE TITLE
suggestion for the website stretcher

### ISSUE THREAD

**Issue by elypter** [DandelionSprout/adfilt#8]
for very wide monitors it might become cumbersome to read text that is stretched over the whole screen. this doesn't mean you have to limit the width though. there are handy css attributes that automatically spread text over multiple collumns

https://www.w3schools.com/cssref/css3_pr_column-width.asp

this particular one creates collumns as soon as there is enough space to fit multiple collumns of a minimum width.

**Comment by DandelionSprout** [comment]
Having only now been able to really experiment with it, my initial results with it were poor... until I through some googling came across (what was to me) a miraculous thing called _viewpoints_, which are width and height values that are percentages of the actual monitor size.

So now that I was able to make various width values a whole lot better to end-users' monitors, I was able to get some use for _column-width_ as well at last. https://github.com/DandelionSprout/adfilt/commit/527a38aef162840530a814f178702db8ab629eda#diff-1e929a6aae0cc2b10261fd5e0f502aec

Now that I've learned about _column-width_ in action and have included it in my list (even if only for one purpose thus far), I'll consider this issue report to have been a success and will therefore close it.
