### ISSUE TITLE
 break Github layout

### ISSUE THREAD

**Issue by neoOpus** [DandelionSprout/adfilt#803]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Some of the pages are showing overlapping parts and some other don't get all elements distribute properly at 1920x1080 

### Add screenshots below if needed

![image](https://user-images.githubusercontent.com/1388336/225321283-09510bc5-80aa-428c-879d-37f5601983a5.png)
![image](https://user-images.githubusercontent.com/1388336/225321570-d3dfb97c-cc85-4fd2-983f-78719031be97.png)
![image](https://user-images.githubusercontent.com/1388336/225321733-a4dacb49-c3df-4f51-930d-adb3a2983f45.png)
![image](https://user-images.githubusercontent.com/1388336/225321875-ce5537a4-7620-4718-878e-4a1855e345d4.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.47.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Website Stretcher

### Which browser(s) did you use when testing this?

Microsoft Edge (Manifest V2)

### Browser version(s)

111.0.1661.41 (Official build) (64-bit) 

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

Device name	LAPTOP-KMGOSEKL
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	64.0 GB (63.8 GB usable)
Device ID	1F63C1F6-6323-4167-A848-D1B2169C9A28
Product ID	00331-10000-00001-AA330
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by DandelionSprout** [comment]
Screenshot 1 and 2 have been known problems for me, though it seems like it'd take more than a brush stroke for me to fix. Nevertheless I'll look into it this morning.

**Comment by neoOpus** [comment]
Yeah no rush, just wanted to report them :)

**Comment by rellyrell7898** [comment]
No

**Comment by DandelionSprout** [comment]
As I simply can't seem to reproduce screenshots 3 and 4 under any circumstances, and 1 and 2 having hopefully been fixed for a while, I'll declare this case resolved. Comments will remain open.
