### ISSUE TITLE
Add Gootloader malware command and control servers

### ISSUE THREAD

**Issue by realugbun** [DandelionSprout/adfilt#808]
Goot loader infects machines and is the first step in a ransomware attack.

A full writeup on goot loader listing the servers can be found here.

https://www.mandiant.com/resources/blog/tracking-evolution-gootloader-operations

Note I maintain a personal hosts list which I import into Pihole. I have added these entries to my personal list and verified they are blocked. I have not tested with any other ad blocking software.

```
➜  ~ dig kepw.org

; <<>> DiG 9.10.6 <<>> kepw.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 677
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kepw.org.			IN	A

;; ANSWER SECTION:
kepw.org.		2	IN	A	0.0.0.0

;; Query time: 8 msec
;; SERVER: 192.168.0.100#53(192.168.0.100)
;; WHEN: Sat Mar 18 14:50:26 EDT 2023
;; MSG SIZE  rcvd: 42
```

## Which entry/entries are you submitting?
```
## Goot loader command and control
0.0.0.0 jonathanbartz.com
0.0.0.0 jp.imonitorsoft.com
0.0.0.0 junk-bros.com
0.0.0.0 kakiosk.adsparkdev.com
0.0.0.0 kepw.org
0.0.0.0 kristinee.com
0.0.0.0 lakeside-fishandchips.com

## Cobalt Strike Beacon Backdoor
0.0.0.0 108.61.242.65
0.0.0.0 108.61.242.65
0.0.0.0 146.70.78.43
0.0.0.0 146.70.78.43
0.0.0.0 87.120.254.39
0.0.0.0 87.120.254.39
0.0.0.0 45.150.108.213
0.0.0.0 45.150.108.213
0.0.0.0 92.204.160.240
0.0.0.0 92.204.160.240
```

## Which of my lists are you submitting it to?
Malware

## Which adblocker(s) and version did you use when writing and testing the entries?

- [ ] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):

**Comment by DandelionSprout** [comment]
The linked-to blog article doesn't seem to explain why exactly `jp.imonitorsoft.com` or `lakeside-fishandchips.com` are directly connected to Goot, unfortunately. Googling those domains does not seem to bring up anything that establishes such a connection.

**Comment by realugbun** [comment]
These domains are extracted from the malware as command and control servers as indicated in the network indicators section.

**Comment by DandelionSprout** [comment]
Okay, I think I understand a bit more of the article now. I'll look into running the `GootLoaderAutoJsDecode.py` file tomorrow if I remember to do so.

**Comment by iam-py-test** [comment]
> `lakeside-fishandchips.com`

Seems to be used by https://www.virustotal.com/gui/file/efcc5e2ac2fcad4b92d843b59c70fb28ac207bf4b6add230dcd83df3328a7ee4/detection (https://app.any.run/tasks/3b5bff9b-708d-45c7-a971-c25f75ef36c7/), and a few other samples (https://app.any.run/tasks/402d89af-d76e-4666-9b6b-7ea17a4b3fb9/, https://app.any.run/tasks/9bc3e0f0-6266-4ba6-a79e-a7f6d55f2254/)
