### ISSUE TITLE
Add tts.monster to .monster exclusion list

### ISSUE THREAD

**Issue by holysnipz** [DandelionSprout/adfilt#809]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

[tts.monster](https://tts.monster/) is a third party service that offering an AI powered Custom TTS alert for livestreamers.

### Add screenshots below if needed

![image](https://user-images.githubusercontent.com/9103583/226188705-d92c19cd-d398-42c0-b072-90828741c05d.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

[Anti-Malware List](https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt)

but i don't know if there are more lists that have `.monster` domain block as well

### Which browser(s) did you use when testing this?

Firefox

**Comment by DandelionSprout** [comment]
The site looks pretty legitimate to me too. I'll whitelist it within 25min.
