### ISSUE TITLE
WesternStandard Membership Nag

### ISSUE THREAD

**Issue by ArtexJay** [DandelionSprout/adfilt#811]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Open any article from WesternStandard and via it's scripts will block scrolling, and display a screen prompting you to either become a paying member or sign up for free to view the article.
Blocking all scripts stops the nag from appearing but messes up the website's look.

### Add screenshots below if needed

![Screenshot 2023-03-19 220154](https://user-images.githubusercontent.com/32932497/226231022-18ab93fd-ae72-4b8e-803d-e2f391501a8f.png)

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop version)

### Adblocker version(s)

v7.12

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Browse Websites Without Logging In (normal)

### Which browser(s) did you use when testing this?

Microsoft Edge (Manifest V2)

### Browser version(s)

Edge Stable

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

22H2

**Comment by DandelionSprout** [comment]
It took me a while to reproduce it, but I think I've found a fix now: `/tncms/api/access.js|$script,domain=westernstandard.com`. I'll add it pretty soon now.
