### ISSUE TITLE
Links for shared Bing answer is broken

### ISSUE THREAD

**Issue by nhan000** [DandelionSprout/adfilt#826]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

In Bing Chat, when I want to share a link using this button:

![image](https://user-images.githubusercontent.com/85216095/230743319-9ed60160-0c94-4af6-bf7e-b94464507bbf.png)

I got this link: https://sl.bing.net/foWkJhKYjUO, which I then paste into another browser and it's supposed to turn into this link https://www.bing.com/search?q=What+is+the+new+Bing%3F&showconv=1&filters=wholepagesharingscenario%3A%22Conversation%22&shareId=88b12b5a-6ef0-4f74-8ee5-693874d808b2&shtc=0&form=EX0050&shid=060eb2b3-a359-4aaa-8418-5551755da9fc&shtp=GetUrl&shtk=Q2hlY2sgb3V0IHRoaXMgQmluZyBhbnN3ZXI%3D&shdk=SGVyZSdzIGFuIGFuc3dlciBJIGdvdCB1c2luZyB0aGUgbmV3IEJpbmcsIHRoZSB3b3JsZOKAmXMgZmlyc3QgQUktcG93ZXJlZCBhbnN3ZXIgZW5naW5lLiBDbGljayB0byBzZWUgdGhlIGZ1bGwgYW5zd2VyIGFuZCB0cnkgaXQgeW91cnNlbGYu&shhk=AndpqVdcqsRkX6zLKjZy7zZ3NNS4NLqrVhr2Xm1Yl0g%3D&shth=OBFB.107AF8B2FB79BD01FFDCABA4D756224A

which would show this content: 
![image](https://user-images.githubusercontent.com/85216095/230743350-976f1385-c98d-453f-8f68-fb562abacdd2.png)

However, using the current list, the shortened link expanded into 
https://www.bing.com/search?q=What+is+the+new+Bing%3F&showconv=1&filters=wholepagesharingscenario%3A%22Conversation%22

and it just showed up as a blank page. 

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.48.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Legitimate URL Shortener (https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt)

### Which browser(s) did you use when testing this?

Microsoft Edge (Manifest V2)

### Browser version(s)

Version 112.0.1722.34 (Official build) (64-bit)

### OS version(s)

22H2

**Comment by DandelionSprout** [comment]
The report looks good enough to me. I've identified the problem as being caused by `||bing.com^$removeparam=/^sh[a-np-z0-9]/` removing the `shareId` parameter, so I guess I'll whitelist that parameter for the time being. Thanks for the headsup.
