### ISSUE TITLE
tumblr.com###glass-container:has(button[aria-label]) breaks Reblog Post dialogue

### ISSUE THREAD

**Issue by naturalobject** [DandelionSprout/adfilt#827]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

The dialog appears for about half a second before disappearing, then i'm stuck on the reblog post url and can't scroll.

Temporary solution is to disable cosmetic filtering, but I need to keep it enabled for a site like Tumblr . This issue just started happening to me today, before keeping cosmetic filtering enabled worked fine

I can't even whitelist it, `tumblr.com#@##glass-container:has(.xXvvU)` and `tumblr.com#@#.xXvvU:upward(#glass-container)` both don't work

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.47.2

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt

### Which browser(s) did you use when testing this?

Firefox

**Comment by iam-py-test** [comment]
> I can't even whitelist it, tumblr.com#@##glass-container:has(.xXvvU) and tumblr.com#@#.xXvvU:upward(#glass-container) both don't work

The allowlist rule must exactly match the problematic rule. Can you try:
```adblock
tumblr.com###glass-container:has(button[aria-label])
```

**Comment by naturalobject** [comment]
OK it seemed to work while I was logged in, so I've logged out now and browsed a bit just to make sure I don't get dialogs asking me to log in.

Didn't know this about the whitelist, because I rarely use them. THX ❕

**Comment by iam-py-test** [comment]
This still needs to be fixed (also, the rule I posted had a typo, it has been corrected)

**Comment by iam-py-test** [comment]
You may have to wait a few minutes for the update to be available. Then, please remove any custom filters you created for this, and update the list.

**Comment by DandelionSprout** [comment]
To the extent I remember yesterday (Monday), I was doing research for another list and was suddenly shown an uncloseable login prompt somehow, so I thought *"Oh no… They've changed the site again so that `tumblr.com#?##glass-container:has(use[href*=logo-tumblr])` doesn't work. I need to come up with something real quick."*

But it turns out that not only did that `use` entry work again this morning, but AdGuard Popups Filter seems to have done a better job at removing that overlay recently than I have.
