### ISSUE TITLE
Remove parameters on baidu.com

### ISSUE THREAD

**Issue by Sonic5435325** [DandelionSprout/adfilt#831]
## Which entry/entries are you submitting?
`||baidu.com^$removeparam=fenlei`
`||baidu.com^$removeparam=ie`
`||baidu.com^$removeparam=rsv_bp`
`||baidu.com^$removeparam=rsv_btype`
`||baidu.com^$removeparam=rsv_dl`
`||baidu.com^$removeparam=rsv_enter`
`||baidu.com^$removeparam=rsv_idx`
`||baidu.com^$removeparam=rsv_pq`
`||baidu.com^$removeparam=rsv_sug1`
`||baidu.com^$removeparam=rsv_sug2`
`||baidu.com^$removeparam=rsv_sug3`
`||baidu.com^$removeparam=rsv_sug4`

## Which things do they block, hide, or unbreak?
They remove parameters from baidu.com
When searching on baidu.com, the URL usually looks something like this: `https://www.baidu.com/s?ie=utf-8&ch&bar&wd=testing&rn&fenlei=256&rqlang=en`, sometimes with even more parameters, which is why there's a lot of `$removeparam` rules.

## Which of my lists are you submitting it to?
Actually Legitimate URL Shortener Tool

## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):
uBlock Origin v1.48.9b1

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
Actually Legitimate URL Shortener Tool, AdGuard URL Tracking Protection

## (Optional) Which browser(s) and version did you use?
Firefox 112.0

**Comment by iam-py-test** [comment]
Can you try this rule and see if it breaks anything/removes the parameters needed:
```adblock
||baidu.com^$removeparam=/^rsv_/
```
If it works, then we can reduce most of those filters into one.

**Comment by Sonic5435325** [comment]
Seems to work just fine for me.

**Comment by Sonic5435325** [comment]
There seems to also be the parameter bsst, which seems to show up when clicking images sometimes. I removed it from the URL and it doesn't seem to cause any problems. Maybe that can be added as well. 
https://www.baidu.com/s?rtt=1&bsst=1&word=testing

**Comment by iam-py-test** [comment]
Ok, remove any custom rules for this and try these:
```adblock
||baidu.com^$removeparam=fenlei
||baidu.com^$removeparam=ie
||baidu.com^$removeparam=/^rsv_/
||baidu.com^$removeparam=pn
||baidu.com^$removeparam=rn
```
Not 100% sure about `t` so not adding it.

**Comment by Sonic5435325** [comment]
Works pretty well for me, though there are the parameters `bsst` and `p_tk` when I search manually on the site. I think those could be the only major ones left.

**Comment by iam-py-test** [comment]
Sorry I missed those. Original comment updated; can you see if those rules work?

**Comment by Sonic5435325** [comment]
They work fine

https://b2b.baidu.com/shop?name=%E5%8C%97%E4%BA%AC%E7%99%BE%E5%BA%A6%E7%BD%91%E8%AE%AF%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8&xzhid=35724055&fid=84017152%2C1681422863378&pi=b2b.s.ziying_link...7063833596849128&tpath=index
also `xzhid`, `fid`, and `pi`. I think that's it after those.

**Comment by iam-py-test** [comment]
Ok, updated. If those work and there aren't any more, I will add them.
Thank you!

**Comment by Sonic5435325** [comment]
You're welcome. :)

**Comment by Sonic5435325** [comment]
You also forgot category, miniId, jid, and prod_type

**Comment by iam-py-test** [comment]
Oh, sorry. Added. I'm multitasking, maybe not the greatest idea on my part.

**Comment by Sonic5435325** [comment]
Also cf, and miniId

**Comment by Sonic5435325** [comment]
So far, I haven't been able to find any more than all of the ones I listed

**Comment by Sonic5435325** [comment]
https://b2b.baidu.com/s?q=%E5%8C%85%E5%AD%90%E6%9C%BA&from_page=index&from_index=2&from_rec=fromPM
||baidu.com^$document,removeparam=/^from_/

**Comment by Sonic5435325** [comment]
Alright, so this is what I have so far:
`||baidu.com^$removeparam=fenlei`
`||baidu.com^$removeparam=ie`
`||baidu.com^$document,removeparam=/^rsv_/`
`||baidu.com^$document,removeparam=pn`
`||baidu.com^$document,removeparam=rn`
`||baidu.com^$removeparam=bsst`
`||baidu.com^$removeparam=p_tk`
`||baidu.com^$document,removeparam=ps`
`||baidu.com^$document,removeparam=nc`
`||baidu.com^$document,removeparam=xzhid`
`||baidu.com^$document,removeparam=fid`
`||baidu.com^$document,removeparam=pi`
`||baidu.com^$document,removeparam=iid`
`||baidu.com^$document,removeparam=query`
`||baidu.com^$document,removeparam=lattr`
`||baidu.com^$document,removeparam=from`
`||baidu.com^$document,removeparam=category`
`||baidu.com^$document,removeparam=jid`
`||baidu.com^$document,removeparam=prod_type`
`||baidu.com^$document,removeparam=cf`
`||baidu.com^$document,removeparam=miniId`
`||baidu.com^$document,removeparam=/^from_/`

Seems like that should be it.

**Comment by iam-py-test** [comment]
Wow, you found a lot of new parameters.
I _think_ all of those are listed, other than `from`.
I will work on testing them (just to be sure there isn't anything broken) and will add them.
Thank you!

**Comment by Sonic5435325** [comment]
Honestly, Baidu is full of them. I didn't expect to find as much either, but it's a bit of a rabbithole thing. Hahahaha. Anyways, you're welcome! I'm happy to help.

**Comment by Sonic5435325** [comment]
Also, I imagine you can change the bottom one to just `||baidu.com^$document,removeparam=/^from/` and see if that removes both the from and from_ parameters, though I'm not sure if that specific filter will have any problems.

**Comment by iam-py-test** [comment]
Ok, added. Can you remove the custom rules and test with an updated version of Legit URL (you might need to wait a few minutes for it to be available)
Thank you!

**Comment by kaedeair** [comment]
@iam-py-test 
`||baidu.com^$document,removeparam=pn` will destroy the function of page turn on `tieba.baidu.com`(eg. https://tieba.baidu.com/p/8413681325).

**Comment by iam-py-test** [comment]
Filter removed, thanks

**Comment by shz42** [comment]
@iam-py-test The `ie` parameter seems to be for the character encoding. With `||baidu.com^$removeparam=ie`you get wrong results for certain characters. (Compare https://www.baidu.com/baidu?wd=😎 and https://www.baidu.com/baidu?ie=utf-8&wd=😎)

**Comment by iam-py-test** [comment]
Fixed, thanks
