### ISSUE TITLE
Legitimate URL shortener breaks downloading files from Facebook

### ISSUE THREAD

**Issue by dexeonify** [DandelionSprout/adfilt#832]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

When I try to download a file posted in a private group, instead of downloading the file, I was redirected to the _permalink_ of the post. At first, I thought it's a Facebook issue, then I thought it's a Firefox issue. Two weeks later, I've finally narrowed it down to a filter issue. Apparently, Legitimate URL Shortener has removed one of the important parameters in the download URL, triggering Facebook's redirect to the permalink of the post.

Long story short, when I clicked on the post to download the file, I get this URL:
> https://www.facebook.com/download/1233479003946558/hello.pdf?av=1097981836&eav=AfZhhb__8IaTgj31zf1ShtOnBL_OkA2Jqc-S1NCL9vC-fkiSVFhvx4k-3YEx85faRI8&paipv=0&hash=Acpb2X6JnZNJMWB9wJ4&__cft__[0]=AZUUijMXq2z7PbdhIF1nWu_RTZRsiamnRyEWD_fV_N-r4PXvDbLvalnYeDZEQrZltcPVUkwQHaCv-5M_g1zwRbj3e8WmjMrYCpd_cU7bPaLsDZzjfEyzxVJLM1w0qSBZJQyHTeyxbMJvu9IiTDY9NRelB0ORRLkLuZMdXun9U7FU-yfb6FyXXagOw6fY4cPrk6s8w2--nB-txO0cnQJHgEWS&__tn__=H-R

**Note:** I've modified the _filename_ of the PDF in the URL so that others can't download the file. For some reason, Facebook allows you to download a file from a private group even if you're logged out.

Using the process of elimination, the parameter that Legitimate URL shortener has erroneously removed is `eav`, which is in line 1794.
https://github.com/DandelionSprout/adfilt/blob/bf21e4b1f9a86d58a7e59b638bda84499a210736/LegitimateURLShortener.txt#L1794

To verify, I am able to download the file with the following URL:
> https://www.facebook.com/download/1233479003946558/hello.pdf?av=1097981836&eav=AfaNKJRFvPXS8S72EFfj0QtCF6E9O7DdJnsuYMIY5SHNz9Fj84gZYpkqAEXKfheQlTk&hash=AcrC2GMxj03ABItKIM8

Here, you can see `av`, `eav` and `hash` are the least amount of parameters needed to get the download URL working. `paipv`, `__cft__[0]` and `__tn__` can be removed without affecting the URL. Though it's up to you whether those need to be removed or not.

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.48.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

[Legitimate URL Shortener](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt)

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

114.0a1

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

Version 22H2 (OS Build 22621.1555)

**Comment by DandelionSprout** [comment]
Thanks to the very detailed report, fixing it was pretty easy. Thanks. 👍 

As for `paipv`, `__cft__[0]`, and `__tn__`, they should nominally be removed by existing entries already.
