### ISSUE TITLE
Parameter on Google when searching on Firefox

### ISSUE THREAD

**Issue by Sonic5435325** [DandelionSprout/adfilt#834]
## Which entry/entries are you submitting?
`||google.$removeparam=client`

## Which things do they block, hide, or unbreak?
A parameter on Google. When searching on Firefox, the parameter `client` will be added to the URL. This is to stop the parameter from showing up.

## Which of my lists are you submitting it to?
Actually Legitimate URL Shortener Tool
## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
Actually Legitimate URL Shortener Tool

## (Optional) Which browser(s) and version did you use?
Firefox 112.0
uBlock Origin v1.48.9rc0

**Comment by iam-py-test** [comment]
This supposedly breaks search-term suggestions

**Comment by Nojuuu** [comment]
@iam-py-test 
Does it work if you remove from doc only?

**Comment by iam-py-test** [comment]
Looking into it.

**Comment by iam-py-test** [comment]
Seems to work. Thanks @Nojuuu for mentioning that.
Can someone test to see if the latest update correctly removes the parameter & doesn't break anything.

**Comment by Nojuuu** [comment]
Not sure because for some reason i'm getting `sclient` instead when I try to search something, but that seems to be fine to remove from doc also.

`https://www.google.com/search?q=test&sclient=gws-wiz-serp`

**Comment by iam-py-test** [comment]
Added, thanks

**Comment by Nojuuu** [comment]
Looks like you need to have it as default search engine for `client` param :

`https://www.google.com/search?client=firefox-b-d&q=test`
