### ISSUE TITLE
LegitimateURLShortener breaks bing search

### ISSUE THREAD

**Issue by jinjinjijiao** [DandelionSprout/adfilt#836]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

when i search something on bing,the problem happens.The website has been refreshed agained and agained.
URL: https://www.bing.com/search?q=test

### Add a screenshot of the extension's logger

![image](https://user-images.githubusercontent.com/46884440/232664331-4a228150-2784-4a65-8673-5e3e1b106af2.png)

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop version)

### Adblocker version(s)

7.12

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Legitimate URL Shortener,easylist and so on.
switch the Legitimate URL Shortener off,the problem fixed.

### Which browser(s) did you use when testing this?

Microsoft Edge (Manifest V2)

### Browser version(s)

 112.0.1722.48

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

22H2

**Comment by iam-py-test** [comment]
I was not able to reproduce using uBlock Origin in Edge and Firefox, so maybe this is an AdGuard for Windows-exclusive problem.
As you are using AdGuard, you will probably have to wait a few hours before you get the fix (I don't remember how long), but once it is available, please see if it fixes the problem.

**Comment by jinjinjijiao** [comment]
It works.Thanks!
