### ISSUE TITLE
[Blocked] opensubtitles.org

### ISSUE THREAD

**Issue by nightznero** [DandelionSprout/adfilt#837]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Opensubtitles is the most knows source for titles,wondering why it's blocked in this list?
Cause of that urls like `dl.opensubtitles.org` and `rest.opensubtitles.org` cannot work properly and download titles to movies

### Add screenshots below if needed

![Screenshot_20230418_082245_AdGuard](https://user-images.githubusercontent.com/61750641/232689511-1c372acd-72e0-47d3-8f5d-44315ccf569c.jpg)

### Which adblocker(s) did you use when testing this?

(Other)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Only this list blocks it

### Which browser(s) did you use when testing this?

(Other)

**Comment by DandelionSprout** [comment]
It appears to be the result of [AdGuard French Filter](https://filters.adtidy.org/extension/ublock/filters/16.txt) having `||opensubtitles.org^$subdocument,~third-party`, in part as the site seems to have lots of popup and ad scripts on it.

I can whitelist the site so you can at least visit it, at least. Give me a couple hours.
