### ISSUE TITLE
prescouter.com annoyance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [DandelionSprout/adfilt#838]
## URL:
https://www.prescouter.com/2014/04/malware-infection-rate-for-android-devices-measured-by-researchers/

## Which entry/entries are you submitting?
prescouter.com##.sgpb-popup-dialog-main-div-wrapper

## Which things do they block, hide, or unbreak?
Newsletter registration prompt
![224472833-0fdc67a5-cabc-4da3-9561-d596bf14ffb0](https://user-images.githubusercontent.com/101707608/233087510-b2cd8c60-1bae-49c3-9d1c-8d7b47e88aad.png)

## Which of my lists are you submitting it to?
Annoyances

## Which adblocker(s) and version did you use when writing and testing the entries?

- [✓] uBlock Origin

Adblocker version(s): 1.49.0

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
All filters offered by uBlock Origin

## (Optional) Which browser(s) and version did you use?
Mozilla Firefox 112.0.1

**Comment by DandelionSprout** [comment]
Sorry for noticing this report a bit late. None of my lists generally cover newsletter stuff for various legacy reasons; you can test out [AdGuard Popups Filter](https://filters.adtidy.org/extension/ublock/filters/19.txt) (which is also included in AdGuard Annoyances) and see if that list fixes it.
