### ISSUE TITLE
Actually Legitimate URL Shortener breaks Substack email only login

### ISSUE THREAD

**Issue by Elaborendum** [DandelionSprout/adfilt#839]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

I don't have a substack account, so when I try to unsubscribe from a substack newsletter, I only have the option to do it from a link in my email inbox. When opening this link, it takes me to another substack URL with a "token" parameter, which gets erased by the filterlist and prevents me from accessing the "account". However, I'm not sure if this is also the case with an actual account, as my current "account" is just the result of subscribing to a newsletter.

### Add a screenshot of the extension's logger

![imagen](https://user-images.githubusercontent.com/71190696/233543393-3a5bd9d2-2fc9-41b7-befe-6077250ade82.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.48.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![imagen](https://user-images.githubusercontent.com/71190696/233543610-cb188f7d-e491-4e45-bd68-b0d989c63898.png)

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

112.0.1

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

21H2

**Comment by iam-py-test** [comment]
Thank you for reporting this. Please update your filterlists and retest.
