### ISSUE TITLE
Browse Websites Without Logging In uBOExtension blocks Tumblr login popup

### ISSUE THREAD

**Issue by bbhtt** [DandelionSprout/adfilt#845]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

1. Open https://www.tumblr.com/
2. Click green login button on top right
3. Nothing happens
4.  It's supposed to open this popup

### Add screenshots below if needed

![Screenshot from 2023-04-28 06-52-45](https://user-images.githubusercontent.com/62639087/235032377-3b00bbf9-0f6d-4ee5-b3b9-36f04454c889.png)

### Add a screenshot of the extension's logger

![image](https://user-images.githubusercontent.com/62639087/235032533-c66b485b-6591-434d-b252-cea0a959addf.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.49.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

All standard uBO filters+Actually Legitimate URL Shortener Tool, Dandelion Sprout's Anti-Malware List, Staying On The Phone Browser, Browse websites without logging in

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

114.0a1 (2023-04-22)

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Arch Linux

**Comment by bbhtt** [comment]
These two are at fault

```
tumblr.com###glass-container:has(use[href$=_google-logo])
tumblr.com###glass-container:has(use[href*=logo-tumblr])
```

Adding an exception to them makes the popup work

```
tumblr.com#@##glass-container:has(use[href$=_google-logo])
tumblr.com#@##glass-container:has(use[href*=logo-tumblr])
```

**Comment by iam-py-test** [comment]
Thanks
