### ISSUE TITLE
Some of the newspapers from Tribune Publishing should be added to the GDPR evading list

### ISSUE THREAD

**Issue by signed-log** [DandelionSprout/adfilt#847]
## Which entry/entries are you submitting?

A blockage of :

- `nydailynews.com`
- `dailypress.com`
- `pilotonline.com`

I don't know if it's possible, but their block message is common and located at `https://www.tribpub.com/gdpr/<site-url>`, a block of that (not the whole site) should be warranted

## Which things do they block, hide, or unbreak?

All

## Which of my lists are you submitting it to?

- GDPR 451 List of Mostly American Websites Who Hate Europe and Privacy Rights

**Comment by DandelionSprout** [comment]
I seem to be able to access those 3 sites from Norway with no VPN, somehow.
