### ISSUE TITLE
Removing clickId breaks Discover cash back enrollment page

### ISSUE THREAD

**Issue by mahtd** [DandelionSprout/adfilt#870]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Once a quarter Discover sends an email to enroll in the upcoming cash back program. Removing the `clickId` param from the URL breaks the AJAX call to do the enrollment

### Add screenshots below if needed

<img width="1066" alt="image" src="https://github.com/DandelionSprout/adfilt/assets/6687627/25a6b9b5-6a95-4afc-86da-7f6a40439dbb">
<img width="306" alt="image" src="https://github.com/DandelionSprout/adfilt/assets/6687627/f2bb4c0d-b1b1-4489-a0b4-919d723a4a40">

### Add a screenshot of the extension's logger

<img width="1334" alt="image" src="https://github.com/DandelionSprout/adfilt/assets/6687627/5a4bf595-9a91-4375-96f0-bafa7caf3ef1">

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.49.2

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

AnnoyancesList: https://github.com/DandelionSprout/adfilt/raw/master/AnnoyancesList

### Which browser(s) did you use when testing this?

(Other)

### Browser version(s)

Arc Version 0.106.1 (39259)
Chromium Engine Version 114.0.5735.45

### Which OS(s) did you use when testing this?

macOS

### OS version(s)

macOS 13.4 (22F66)

**Comment by iam-py-test** [comment]
Please update your filterlists and retest.
Also, the information you shared was very helpful in fixing this 👍 
Thank you.
