### ISSUE TITLE
Community Notes for Pure Reading Experience or De-Politificator

### ISSUE THREAD

**Issue by pixiekat** [DandelionSprout/adfilt#873]
## Which entry/entries are you submitting?

Adding `twitter.com##div[data-testid="birdwatch-pivot"]` will hide the community notes box, which is pretty much used for right wing propaganda and trolling under Elon's Twitter. 

## Which things do they block, hide, or unbreak?

This snippet will hide the "Readers added context they thought people might want to know", which has been politicised for far right causes under that guy. 

## Which of my lists are you submitting it to? 
*I'm not sure which one it would better fit under but one of them, I thin fits*
- Twitter: Pure Reading Experience
- Twitter De-Politificator

## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s): uBlock Origin 1.49.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![image](https://github.com/DandelionSprout/adfilt/assets/32232155/cbc9e675-245c-4100-a8f0-94af28643ebf)

## (Optional) Which browser(s) and version did you use?

Chrome Version 113.0.5672.127 (Official Build) (64-bit)

**Comment by DandelionSprout** [comment]
Sounds perfectly believable that Twitter would manage to abuse such a feature for that kind of stuff. I've added the entry in `08June2023v2-Alpha` of `TwitterPureReadingExperience.txt` now.
