### ISSUE TITLE
forbes.com

### ISSUE THREAD

**Issue by Sonic5435325** [DandelionSprout/adfilt#874]
## Which entry/entries are you submitting?

When visiting `forbes.com`, the parameter `sh` shows up
Here's a filter I think could work:
`||forbes.com^$removeparam=sh`

## Which things do they block, hide, or unbreak?

The filter will get rid of a parameter on a site

## Which of my lists are you submitting it to?
Actually Legitimate URL Shortener

## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin (v1.49.3rc16)
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Actually Legitimate URL Shortener
AdGuard URL Tracking Protection

## (Optional) Which browser(s) and version did you use?

Firefox 114.0

**Comment by Nojuuu** [comment]
Already in both lists:

https://github.com/DandelionSprout/adfilt/blob/4d3165ad4fa9d11df10b7d158af6554f689729a4/LegitimateURLShortener.txt#L2590

https://github.com/AdguardTeam/AdguardFilters/blob/dbba61ae67773c64e74022805e54d87fee251abf/TrackParamFilter/sections/specific.txt#L121-L122

**Comment by iam-py-test** [comment]
This looks like it might be another case of history.replaceState adding parameters without reloading the page.
I can reproduce; sh is removed, but comes back

**Comment by iam-py-test** [comment]
I don't remember accepting cookies, but I will check.

**Comment by Nojuuu** [comment]
In EU I need to accept cookies for it

> `forbes.com##+js(set,history.replaceState,noopFunc)` 

Does not seem to break videos

Example: `https://www.forbes.com/video/6328506763112/aoc-threatens-musk-for-promoting-her-twitter-impersonator/`

but probably should be made  more specific if possible.

**Comment by Nojuuu** [comment]
Does this work?

```
forbes.com##+js(set, trackingService.track, noopFunc)
```

**Comment by iam-py-test** [comment]
Seems to, and I don't see any breakage (not logged in though). Guess I gave up to early.
Thanks for the solution 🥇

**Comment by iam-py-test** [comment]
@Sonic5435325 please update your filterlists and retest to see if @Nojuuu's solution works for you

**Comment by Sonic5435325** [comment]
@iam-py-test @Nojuuu Yep, that filter works very well! Thanks.

**Comment by THEtomaso** [comment]
> https://github.com/DandelionSprout/adfilt/commit/03bd9c72018462b02724bc40bf69844c0ecc4b26

It breaks the site's login function (if you click "Sign In" in the header, the popup is blocked).
It's also broken by a couple of other filters though, because the cookie consent needs to be accepted first.

### Problem filters:
* **Actually Legitimate URL Shortener Tool**
`forbes.com##+js(set, trackingService.track, noopFunc)`

* **AdGuard Tracking Protection filter** _(@Yuki2718)_
`||global.ketchcdn.com^
`
* **EasyList - Cookie Notices** _(@Khrin)_
`forbes.com##.bottom__OvpYA.root__XMKIj`

### Possible fix:
```
forbes.com#@#.bottom__OvpYA.root__XMKIj
forbes.com#@#+js(set, trackingService.track, noopFunc)
@@||global.ketchcdn.com^$domain=forbes.com
```

**Comment by iam-py-test** [comment]
Thank you for reporting this. I have fixed it in https://github.com/DandelionSprout/adfilt/commit/5cb9654bf21b015c848191ec00dcd480a195e949.

**Comment by Yuki2718** [comment]
I can't reproduce, not seeing `global.ketchcdn.com` request even with European IPs. @AdamWr can you check?

**Comment by AdamWr** [comment]
Fixed - https://github.com/AdguardTeam/AdguardFilters/commit/6541c55af361b1f324cada5b9fc91b6f93afee82

**Comment by Yuki2718** [comment]
Finally reproduced

**Comment by iam-py-test** [comment]
Thanks @Yuki2718 @AdamWr
