### ISSUE TITLE
Change @@|| to @@| in Anti-malware lists

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [DandelionSprout/adfilt#877]
Reason: some block list may block abc.google.ga but when you allow @@||google.ga it will allow all google.ca links. Instead do @@|google.ga. That will be safer. But I'm just using that as an example. Do that for all the TLDs that are blocked so that way the actual dangerous domains will still be blocked.

**Comment by DandelionSprout** [comment]
I'm currently thinking about how to rewrite those entries anyway, since uBlock Origin added a better framework for annoyances lists in 1.50.0 that make me tempted to get more of my lists included there, but they've been strangely hostile to `||top^` in particular.

**Comment by KnightmareVIIVIIXC** [comment]
I'm using Adguard DNS. I just noticed this in their block list.

**Comment by KnightmareVIIVIIXC** [comment]
I don't know how you make your lists but can you make a command to change @@|| to @@|
Ask chatgpt.

**Comment by KnightmareVIIVIIXC** [comment]
Worse case scenario, you copy paste your list into notepad++ and replace @@|| to @@| and that'll be that

**Comment by DandelionSprout** [comment]
This kind of stuff should be pretty easy for me to handle with Sublime Text and with the scripts I use.

**Comment by DandelionSprout** [comment]
Having thought about this for some days, I don't think there's much security benefits from using single `|`'s.

If we presume the use of, for example, `@@|google.gq^`, then I'd most likely have to add additional whitelistings for `www.google.gq`, `mail.google.gq`, `maps.google.gq`, and dozens more. If anything, I'd assume that all subdomains of domains that I do approve for whitelisting, can be considered to be safely under the control on the main domain's owner (In this case Google).

At most, I could evaluate the use of `|` in case-by-case, and would only be kinda feasible if any whitelisted domains turn out to have hacked subdomains of the `g37d5a.domain.top` variety that often show up in Google search results.

**Comment by DandelionSprout** [comment]
Update: I'm hoping for https://github.com/AdguardTeam/HostlistCompiler/pull/50 to get merged, which should *hopefully* allow me to revert back to the intended `~google.ga|~example.ga` format that is used in the highest-profile list versions.

**Comment by KnightmareVIIVIIXC** [comment]
I think $denyallow should be "weaker" meaning if you block the tld .org and you $denyallow example.org, but abc.example.org is blocked, then abc.example.org will be blocked and 123.example.org will be allowed unless added to a block list.

**Comment by krystian3w** [comment]
Also this can generate confusion with ABP (EasyList) syntax:

`||due-punto.bara^` - block all

`@@|http://due-punto.bara^` (unlock only http without `www.`) and still blocked `https`, `http://www.`.

**Comment by DandelionSprout** [comment]
I'm *still* waiting for https://github.com/AdguardTeam/HostlistCompiler/pull/50 to get processed. This is becoming an absolute embarrassment for AdGuard Home (The software), sorry to say.
