### ISSUE TITLE
Issue with Opera GX homepage search bar

### ISSUE THREAD

**Issue by rakantoh** [DandelionSprout/adfilt#879]
If i have the "Legitimate URL Shortener" filter enabled in adguard for windows, in opera GX when i try to search in the search bar of the opera homepage, always got an error: "This page doesn't work, ERR_TOO_MANY_REDIRECTS", i must disable the filter to recover the search bar functionality. this is only in opera gx and adguard for windows, with adguard browser extension and this filter the search bar works fine.

**Comment by iam-py-test** [comment]
Can you post a screenshot?
I am currently on a work trip so don't have a machine to investigate with.

**Comment by DandelionSprout** [comment]
I could've tested it, but am reluctant to download Opera GX since the Opera company is PRC-owned.

**Comment by rakantoh** [comment]
> Can you post a screenshot? Also, what URL do you get redirected to if Legit url is disabled? I am currently on a trip so don't have a machine to investigate with, but I will investigate later this week when I have a test system Thanks.

![imagen_2023-06-20_153236019](https://github.com/DandelionSprout/adfilt/assets/59809634/5fa3af8d-1884-4ce7-b751-258d6d43b859)

in search bar or in url bar, in both cases if i try to search anything with legitimate url shortener enabled in adguard for windows, the search fails

![imagen_2023-06-20_153438104](https://github.com/DandelionSprout/adfilt/assets/59809634/ba5f6f4e-4ec8-4ef5-8a4c-512ddf033b62)

**Comment by rakantoh** [comment]
> I could've tested it, but am reluctant this afternoon to download Opera GX since the Opera company is PRC-owned.

i dont understand, what you mean with "PRC-owned"?

**Comment by DandelionSprout** [comment]
PRC is a term for China (to make it more distinct from Taiwan), with Opera Software apparently being owned by "Beijing Kunlun".

Judging from the screenshots, it seems to be more of a problem with Google than with Opera, so I'll look into it soon.

**Comment by iam-py-test** [comment]
It might take a few hours for this fix to be available for you due to how AdGuard works, but please update your filterlists (AdGuard UI -> circle with two arrows) and retest
@rakantoh

**Comment by rakantoh** [comment]
> It might take a few hours for this fix to be available for you due to how AdGuard works, but please update your filterlists (AdGuard UI -> circle with two arrows) and retest. I think I have found the problematic filter @rakantoh Thanks

no, still the same, all filters updated

**Comment by iam-py-test** [comment]
Update your filterlists again & retest. As I said, it takes a while for the update to be available for AdGuard users as AdGuard mirrors their lists. However, the update is available as the synced the mirror 46 minutes ago.

**Comment by DandelionSprout** [comment]
Testing it now, I am so confident that iam-py-test's fix must've worked (since AdGuard's logger doesn't even show Legitimate URL Shortener as being applied for such searches anymore), that I'll consider the case to be resolved.
