### ISSUE TITLE
Issue with 'Browse Websites Without Logging In' in Pinterest

### ISSUE THREAD

**Issue by Darkmaster006** [DandelionSprout/adfilt#885]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

This specific issue happens in Pinterest, only in the mobile version.
Website: https://ar.pinterest.com/
Example: https://ar.pinterest.com/pin/727612883569239572/ and https://ar.pinterest.com/pin/307511480822464062#imgViewer
Basicallty, when you click the three-dots button (either in "img viewer" mode or in "normal" mode) because you want to download a picture, the "pop-up" window that would appear (it's not a pop-up, but like a "layered" window, you'll see in the examples) does not appear, even though the site does darkens as if it would have appeared. This is, of course, because the element is blocked by the list. The list works perfectly in blocking other annoying windows like this, but this one's actually useful. Furthermore, I am actually logged in, too.

### Add a screenshot of the extension's logger

Normal image, having opened nothing: 
![photo_4976860107077954522_y](https://github.com/DandelionSprout/adfilt/assets/21136515/6fff59d9-633d-4e97-838c-05b72465e84a)
Normal image, having opened nothing, image viewer:
![photo_4976860107077954523_y](https://github.com/DandelionSprout/adfilt/assets/21136515/78247a46-a253-4315-a2ed-a0a868a8fd78)
Image after opening in normal mode, without the list:
![photo_4976860107077954519_y](https://github.com/DandelionSprout/adfilt/assets/21136515/142fc55b-3b11-4b6c-a459-7aca0d2f5bae)
Image after opening in normal mode, with the list:
![photo_4976860107077954518_y](https://github.com/DandelionSprout/adfilt/assets/21136515/820d7310-62c2-4f85-b27c-603493849399)
Viewer mode:
![photo_4976860107077954520_y](https://github.com/DandelionSprout/adfilt/assets/21136515/482c9937-ad62-48a2-ac83-be0927c2156b)
Viewer mode, with list:
![photo_4976860107077954521_y](https://github.com/DandelionSprout/adfilt/assets/21136515/7441c2ba-ba0e-4aaf-8134-4c0b7a5f0bc1)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.50.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Browse Websites Without Logging In

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

For Android. 114.2.0 (Build #2015957435)

### Which OS(s) did you use when testing this?

Android

### OS version(s)

Galaxy A33 5G. Android 13, One UI 5.1.

**Comment by iam-py-test** [comment]
Caused by https://github.com/DandelionSprout/adfilt/blob/f4c9538d385960ffe3695617283321757802d3af/BrowseWebsitesWithoutLoggingIn.txt#L95C1-L95C65

**Comment by DandelionSprout** [comment]
Since the entry in question is probably fairly old by now, I can probably remove it and see what happens.
