### ISSUE TITLE
flattr link invalid

### ISSUE THREAD

**Issue by alpeni** [DandelionSprout/adfilt#886]
Great fan of your work

The flattr link in the right side below "Sponsor this project" is not working.

**Comment by DandelionSprout** [comment]
It's been *years* since I gave up Flattr after some complicated revamp of their site, but I'll see how easy it'd be to resume it again.

**Comment by DandelionSprout** [comment]
Okay, so it turns out they removed all support for creators to use Flattr last month, instead turned it into an extended arm of Acceptable Ads or something similar. I'll make sure to remove my links to Flattr now.
