### ISSUE TITLE
Rule blocks the Starlink router

### ISSUE THREAD

**Issue by DavidCWGA** [DandelionSprout/adfilt#889]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

This rule:

    /^[a-z]{11,15}$/

Blocks "starlinkrouter", which is how the Starlink app looks up the router.

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

v0.107.33

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Game Console Adblock List
at:
https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt

### Which browser(s) did you use when testing this?

It's about a phone/TV app

### Browser version(s)

Starlink app 2023.22.0

### Which OS(s) did you use when testing this?

(Other)

### OS version(s)

iOS 16.5.1

**Comment by iam-py-test** [comment]
I don't see that rule in "Dandelion Sprout's Game Console Adblock List"?

**Comment by DandelionSprout** [comment]
I think it's in https://github.com/Perflyst/PiHoleBlocklist/blob/master/SmartTV-AGH.txt, a list that gradually got abandoned after other lists increasingly began covering TV tracking domains.

**Comment by DandelionSprout** [comment]
Moved to https://github.com/Perflyst/PiHoleBlocklist/issues/145.
