### ISSUE TITLE
Microsoft Edge (yet again!)

### ISSUE THREAD

**Issue by yokoffing** [DandelionSprout/adfilt#89]
## Which things do they block, hide, or unbreak?

Sample URL: https://www.msn.com/en-us/news/world/brazils-cult-of-hydroxychloroquine/ar-BB17kQlA

![edge](https://user-images.githubusercontent.com/11689349/88975656-9414d580-d288-11ea-8f50-29692b8e558f.jpg)

## Which of my lists are you submitting it to?
 I don't wanna download your browser

## Which adblocker(s) and version did you use when writing and testing the entries?
- [x] Nano Adblocker
- [ ] Nano Defender
- [ ] uBlock Origin
- [ ] uBlock Origin Plus
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdGuard Home
- [ ] Blokada

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to write this will result in instant report closing.

![filters1](https://user-images.githubusercontent.com/11689349/88976062-611f1180-d289-11ea-9cad-82d0a1dac9a0.jpg)

![filters2](https://user-images.githubusercontent.com/11689349/88976069-63816b80-d289-11ea-9fb2-56dbdb26b7bd.jpg)

**Comment by DandelionSprout** [comment]
I can confirm that I can reproduce the banner, and I thank you for telling me about it.

I'll play slightly safe on this one and go for `msn.com##.articlebody > div[style="width:100%;border:1px solid #CCC;padding:10px;"]`
