### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by Sonic5435325** [DandelionSprout/adfilt#893]
## Which entry/entries are you submitting?

`||google.*$removeparam=client`

## Which things do they block, hide, or unbreak?

To reproduce: Go on Firefox with Google as your main browser.
It removes the parameter that gets added for Firefox users.

## Which of my lists are you submitting it to?
Actually Legitimate URL Shortener

## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Actually Legitimate URL Shortener, AdGuard URL Tracking Protection

## (Optional) Which browser(s) and version did you use?

Firefox 115.0.2

**Comment by iam-py-test** [comment]
That rule is commented out and I don't see any obvious explanation.
A few requests:
- What is broken?
- Can you click the uBlock Origin icon on the broken page, click the chat icon, click on "Troubleshooting information", and share that here?
- Can you also share the contents of the logger? ([wiki](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog), [video](https://youtu.be/TE82LSw3A8A))
Thanks.

**Comment by Nojuuu** [comment]
I think he's suggesting to add that filter.

Wasn't the issue only with Opera GX? So maybe `!#if env_firefox` could work?

**Comment by Sonic5435325** [comment]
@iam-py-test 
1. There is no breakage. Like @Nojuuu, it's simply a filter suggestion.
This is what I mean (On Firefox with Google as a default browser):
![Screenshot from 2023-07-18 19-42-20](https://github.com/DandelionSprout/adfilt/assets/89158249/2a2c835c-ae42-461c-b865-ee5c451bd1c3)

**Comment by iam-py-test** [comment]
I'm an idiot 🤦‍♀️ . Somehow I didn't notice "Which entry/entries are you submitting?" or the big green "Submission" tag.
@Nojuuu Good idea, I have tried that
Thank you both.
