### ISSUE TITLE
frontpage.fok.nl

### ISSUE THREAD

**Issue by Sonic5435325** [DandelionSprout/adfilt#895]
## Which entry/entries are you submitting?

`fok.nl##.r89-desktop-billboard-atf`

## Which things do they block, hide, or unbreak?

An ad billboard.
![Screenshot from 2023-07-21 14-05-45](https://github.com/DandelionSprout/adfilt/assets/89158249/379b80a9-2103-4bc3-9f4c-ab5ad23977d4)

## Which of my lists are you submitting it to?
Dandelion Sprouts nordiske filtre

## Which adblocker(s) and version did you use when writing and testing the entries?

- [X] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprouts nordiske filtre

## (Optional) Which browser(s) and version did you use?

Firefox 115.0.2

**Comment by DandelionSprout** [comment]
Uhm… I'm 100% sure that's a Dutch site. Contact https://github.com/EasyDutch-uBO/EasyDutch about it instead.

**Comment by Sonic5435325** [comment]
Sorry, I can get mixed up with languages sometimes. Thanks, I'll report it to them.
