### ISSUE TITLE
It's a Document Object Model

### ISSUE THREAD

**Issue by JustJinxed** [DandelionSprout/adfilt#899]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

"I replaced DOM tree with F12 filetree, because I 100% genuinely felt that it was easy to think DOM was short for "dominatrix", and also because many people may not even know how to open said tree in web browsers."

Not trying to hate on this, but please don't do this. If they're smart enough to get into the window that literally says DOM in some browsers, you can just as easily say, "F12 to open the DOM (Document Object Model) window / Inspect tool"

Calling it a "filetree" is just introducing more unnecessary and incorrect jargon. 

### Add screenshots below if needed

https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md

### Add a screenshot of the extension's logger

x

### Which adblocker(s) did you use when testing this?

(Other)

### Adblocker version(s)

x

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

x

### Which browser(s) did you use when testing this?

(Other)

### Browser version(s)

x

### Which OS(s) did you use when testing this?

(Other)

### OS version(s)

x

**Comment by DandelionSprout** [comment]
Well, considering the acronym's meaning was complete news to me, I can indeed implement this new information sometime this week. 😅
