### ISSUE TITLE
Breaking QPay event page sometimes 

### ISSUE THREAD

**Issue by sith-on-mars** [DandelionSprout/adfilt#903]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Sometimes the opening a QPay page would get redirected back to the QPay homepage. Turning off the filter fixed the issue.

For example this page: https://clubs.getqpay.com/?eid=20003

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Firefox

### Which OS(s) did you use when testing this?

Linux

**Comment by iam-py-test** [comment]
I have excluded QPay from the problematic rule.
Please update your filterlists in a few minutes and retest.
Thank you.

**Comment by sith-on-mars** [comment]
Thanks for the quick fix. However, I found that QPay link that contain redirection didn't work when using this filter.

For example, opening https://shutupandwrite20sepw-event.getqpay.com/ normally will be redirected to https://clubs.qpayhub.com/?eid=20483. However, if the filter is on, the redirection will fail and we'll be bounced back to the QPay homepage.

**Comment by iam-py-test** [comment]
Ok, thanks for reporting that. I have excluded that domain as well: https://github.com/DandelionSprout/adfilt/commit/dd5043785f00d296bcbdf476e239d6b94d6328e5
I am questioning if the eid rule should be applied to all websites. ClearURLs only removes eid on Facebook, and AdGuard does not touch it.
