### ISSUE TITLE
tkqlhce.com is not malware, should not be blocked by Dandelion Sprout's Anti-Malware List

### ISSUE THREAD

**Issue by Alex9001** [DandelionSprout/adfilt#904]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

tkqlhce.com is an affiliate referral redirector used by sites like slickdeals.net (example, [links in this thread]( https://slickdeals.net/f/16865834-16-9-oz-febreze-fabric-refresher-or-8-8-oz-air-freshener-various-1-61-2-pk-8-8-oz-air-freshener-april-fresh-2-69-more-free-store-pickup-at-walgreens-10-minimum-order) )

it is not a malware distribution domain, and thus should not be blocked within the context of an anti-malware list. there are certainly other lists which should block it, such as tracker blocking lists, but not an anti-malware list

it is currently being blocked by Dandelion Sprout's Anti-Malware List

### Add screenshots below if needed

![image](https://github.com/DandelionSprout/adfilt/assets/2770710/b0dc2069-b728-4324-bb2a-d66395aac038)

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

adguard home v0.107.36

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Anti-Malware List

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

all browsers

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

not relevant

**Comment by iam-py-test** [comment]
Seems to have been added because it was used to redirect from a scam website to a McAfee affiliate page: https://github.com/DandelionSprout/adfilt/issues/287
I'm guessing there was one bad affiliate link (`https://www.tkqlhce.com/click-100401187-14437943?sid=df41d215fe9342a5a52fd569fa1b5a8c19660&pid=57311`), though interestingly, that link is still online & redirects to a McAfee affiliate page despite the original issue being from October of 2021.

**Comment by DandelionSprout** [comment]
I will doublecheck this weekend how it's being used by SlickDeals, but otherwise I at the time of writing agree with iam-py-test.

**Comment by DandelionSprout** [comment]
Strange observations I've made:
1) Somehow, if a prompt shows up on SlickDeals to ask if you are an EU citizen and you answer yes, the site does not redirect its links through `tkqlhce`.
2) Presuming iam-py-test's result/example URL is unchanged, I see a possible narrow-down pattern I can change the entry, even if I am certainly confident about the reliability or safety of doing so.
