### ISSUE TITLE
Twitter filtering rules for who to follow are ineffective

### ISSUE THREAD

**Issue by z0xyz** [DandelionSprout/adfilt#908]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

The Twitter [who to follow](https://github.com/DandelionSprout/adfilt/blob/725705fad82651ababbb652ab5da31a773d6bea3/TwitterPureReadingExperience.txt#L10) is ineffective as of now.

I've tried to fiddle with it, using
```
! Twitter
twitter.com##div:last-of-type span:has-text(/^Who to follow/):upward(6) +div
twitter.com##div:last-of-type span:has-text(/^Who to follow/):upward(6) +div+div
twitter.com##div:last-of-type span:has-text(/^Who to follow/):upward(6) +div+div+div
twitter.com##div:last-of-type span:has-text(/^Who to follow/):upward(6) +div+div+div+div
```
But I think it's a bit repetitive and verbose

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.51.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Twitter

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Browser version(s)

Version 116.0.5845.96 (Official Build) (64-bit)

### OS version(s)

Elementary OS 7

**Comment by DandelionSprout** [comment]
At this point, I admit to be unsure how to solve it:
* Entries involving `:has-text(/^Who to follow/)` would only work if Twitter's language is set to English.
* "Who to follow" is no longer available in guest view.
* I'd rather run a marathon than to make a Twitter account again in my life.
* Supposedly the domain change from `twitter.com` to `x.com` has taken place sometime this weekend.

I've been tempted to mark large parts of "Twitter: Pure Reading Experience" as deprecated, but I had to walk back on an earlier deprecation of other Twitter lists of mine after access to singular tweets as guests had been restored.

Overall, it could take some time before a fix is randomly come up with one day.

**Comment by DandelionSprout** [comment]
I did (rather reluctantly) add `x.com` to that list a week now; goodness knows if that made things any better or not.

**Comment by DandelionSprout** [comment]
Thinking about it for a week or so, I've decided to stop all further work on "Twitter: Pure Reading Experience" (besides rare automated mass syntax updates), since Musk is by now effectively proven to be a white supremacist and a traitor to the modern West.

The list itself will remain existing on the repo for the foreseeable future, but will not be part of Dandelion Sprout's Annoyances List or other compilation lists.

**Comment by z0xyz** [comment]
> I've decided to stop all further work on "Twitter: Pure Reading Experience" 

I'll stick to the aforementioned method then.
