### ISSUE TITLE
Norsk filter til Vivaldi Android 

### ISSUE THREAD

**Issue by jbcribz** [DandelionSprout/adfilt#909]
Hei,

Setter veldig stor pris på jobben du gjør. Bruker filtrene dine i min Adguard Home bla. Lurer på om det finnes noe spesifikt filter jeg kan bruke i Vivaldi for Android? Vh Joakim

**Comment by DandelionSprout** [comment]
Takk for spørsmålet. Jeg har kun for øyeblikket kjennskap til Vivaldis adblocker for PC; men det hadde vært rart hvis de ikke brukte samme blokkeringsmotor på PC og på Android.

Du kan forsøke med https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP.txt. Hvis det mot formodning ikke skulle fungere som ønsket, kan jeg ta en nærmere titt på saken denne helgen.

**Comment by jbcribz** [comment]
Takk. Virker som den funker perfekt.

**Comment by DandelionSprout** [comment]
Strålende å høre.
