### ISSUE TITLE
The Texan Sub/Login Popup

### ISSUE THREAD

**Issue by ArtexJay** [DandelionSprout/adfilt#911]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Similar popup as found in the Western Standard that has already been resolved. After 2-3 articles being opened, it will start blocking the article and produce the pop-up. I'm not sure if it's possible to avoid the popup while still getting to the article. If it isn't possible however, close this issue.

https://thetexan.news/

### Add screenshots below if needed

![image](https://github.com/DandelionSprout/adfilt/assets/32932497/01f5c3f0-698c-4c49-88da-59ed46d2ff36)

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop version)

### Adblocker version(s)

v7.14

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Browse Websites Without Logging In (normal)

### Which browser(s) did you use when testing this?

Microsoft Edge (Manifest V2)

### Browser version(s)

Stable

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

22H2

**Comment by DandelionSprout** [comment]
It seems the site is affected by (more or less) self-imposed GDPR EEC bans; so while I do have access to a VPN, I'll put this on the backlog until my COVID gets cured.

In the meantime, if it's a matter of haste, you can contact https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters about the site, who I think would also be willing to remove that prompt.

**Comment by DandelionSprout** [comment]
Okay, so it seems that that list's `/shared-content/art/tncms/api/access.js$script,1p` does work pretty well for me, from what it seems. I fear the AdGuard Team would raise eyebrows if I added that entry to a list that forms part of Dandelion Sprout's Annoyances List, but at least you/we know what the available options are now.
