### ISSUE TITLE
google report form is broken with Actually Legitimate URL Shortener 

### ISSUE THREAD

**Issue by e075e** [DandelionSprout/adfilt#912]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

1. open [https://support.google.com/legal](https://support.google.com/legal)
2. create a ticket (blue button)
3. answer the questions (eg: Gmail, no, policy non legal, Malicious intent, Report an abusive Gmail account)
4. a circle starts rotating endlessly

Deactivating "Actually Legitimate URL Shortener" list will show a form to submit the abuse report

### Add screenshots below if needed

**with Actually Legitimate URL Shortener**

![Screenshot 2023-09-09 at 20-21-33 Report content on Google - Legal Help](https://github.com/DandelionSprout/adfilt/assets/15078341/8868629b-a6e4-4ae2-906d-2e6b1a137efd)

**without Actually Legitimate URL Shortener**
![Screenshot from 2023-09-09 20-22-50](https://github.com/DandelionSprout/adfilt/assets/15078341/fac399df-b3f5-4b2e-9f9b-ace775ba8b58)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Actually Legitimate URL Shortener

### Which browser(s) did you use when testing this?

Firefox

### Which OS(s) did you use when testing this?

Linux

**Comment by iam-py-test** [comment]
I think I have found the cause and fixed it. Please wait a few minutes, then update your filterlists and report back.
Thanks for reporting this.
