### ISSUE TITLE
vipre.com breakage

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [DandelionSprout/adfilt#914]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Breakage of main article body

### Add screenshots below if needed

![Screenshot 2023-09-12 at 12-45-29 The Future of Machine Learning   AI in Cybersecurity](https://github.com/DandelionSprout/adfilt/assets/101707608/4e38ac30-74c0-44d7-9ce8-ff651ffd7a0e)

### Add a screenshot of the extension's logger

https://www.dropbox.com/scl/fi/0pffddidf3mvu0w8e4e4k/uBlock.zip?rlkey=jm0e0lqr6ydlscos5zq20aedc&dl=1

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.51.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

All filters offered by uBO + your annoyances list

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

117.0.1

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

22H2

**Comment by DimitrisKalaboukas** [comment]
My omission: article URL:

https://vipre.com/blog/future-of-machine-learning-and-ai-cybersecurity/

**Comment by DandelionSprout** [comment]
I did find it slightly odd that the OP lacked a link, but I found `https://vipre.com/blog/fighting-advanced-threats-machine-learning/` and thankfully found a list fix pretty quickly.
