### ISSUE TITLE
Browse Instagram without logging in

### ISSUE THREAD

**Issue by llebout** [DandelionSprout/adfilt#920]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hello!

I tried using your list Browse sites without logging in but it seemed unable to block the Instagram login prompts that appear after scrolling. E.g. https://www.instagram.com/p/CxlEkAYMeuH/ then scroll down until prompt appears.

I already have all annoyance lists included by default in Ublock Origin enabled and I use Firefox on Android right now, even though IIRC this also happens to me on desktop.

I have searched far and wide for a list specially about browsing without logging in and yours was the only one I found. I am guessing other list policies and priorities arent quite about this topic since even with everything enabled I get those kinds of popups on many websites incl. Facebook, Twitter, Instagram etc.

I tried looking into it myself but not very experienced with writing filters. I see that the element ids etc seem randomized on the login popup everytime..

If anyone can help..

Thanks!

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

All default Ublock Origin, + all list labeled annoyances, easylist+adguard ads and mobile ads + all tracking (minus block outsider into lan), Pete's DNS list, adguard français + ru adlist

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

117.1.0

### Which OS(s) did you use when testing this?

Android

### OS version(s)

Android 13

**Comment by DandelionSprout** [comment]
Instagram is a rather heavy mess to handle, since they use a Facebook-like method to show a hard login prompt after approx. 7 page visits. I'll see if my rather worsening health can look into it later this week.

**Comment by Nojuuu** [comment]
Does this work?
```adblock
instagram.com##[style^="position: fixed;"][style$="pointer-events: none; contain: strict; z-index: -9999;"] + [style^="--fds-black: #000000;"]
```

**Comment by llebout** [comment]
@DandelionSprout @Nojuuu 

I tried your filter and it still showed prompts after scrolling a bit to show more content (on e.g. https://www.instagram.com/pepsi/ ) - I used Firefox Android 118.1.0

Your health is most important, I am not in very good condition either. Wish you the best and have rest.

After opening this issue I noticed that after browsing for a little while refreshing the page to get another go without a login prompt until scrolling shows it again and I started getting errors from the Instagram frontend as if I got rate limited or blocked and I could not get any content more than I was given on first page load by scrolling. Though on Instagram web the only way you can discover post links is by scrolling through stuff so it kinda just locks you out of most content.

It made me question whether bypassing this prompt was worth it since Instagram still seems to rate limit/block pretty quickly if you don't log in anyway.

**Comment by Nojuuu** [comment]
```adblock
instagram.com##div:matches-css(background-color: rgba(0, 0, 0, 0.65)):upward(1)
instagram.com##div:matches-css(background-color: rgba(0, 0, 0, 0.65))
```

Should be more consistent but it will flash quickly

**Comment by DandelionSprout** [comment]
I'm unsure if I've asked about this before or not, but was a consensus ever agreed on for a fix for this thread/OP? 😅

**Comment by DandelionSprout** [comment]
I'll assume 'no' then, unfortunately.

**Comment by llebout** [comment]
Hello, sorry I have gotten no notification of your message, well the problem is that the Instagram API rate limits you if you bypass the prompt, so it's pointless to try and bypass it.
