### ISSUE TITLE
Wikia/fandom filters

### ISSUE THREAD

**Issue by NotaInutilis** [DandelionSprout/adfilt#921]
## Which entry/entries are you submitting?

Stuff that makes fandom/wikia a little more tolerable. Mainly tested on the genshin wiki.

! Left bar
fandom.com,wikia.org##.global-navigation
! Footer "more fandoms"
fandom.com,wikia.org##.page-footer__trfc-147
! Footer self ad for fandom, all its sites, apps etc
fandom.com,wikia.org##.global-footer__content
! Mobile list of articles at the bottom, with sometimes links to other fandom wikis
fandom.com,wikia.org##.recirculation-prefooter
! Mobile top bar with links to fandom. removed only the left side because the right side has search and login. There might be a better solution for this one, but it's my first time doing cosmetic filters so it's good enough for me.
fandom.com,wikia.org##.mobile-global-navigation__left
! Mobile "ad" for fanhub in the top bar dropdown login menu
fandom.com,wikia.org##.global-navigation__fanhub-wrapper
! Mobile top bar fandom logo/link
fandom.com,wikia.org##.mobile-global-navigation__logomark
! Mobile "Others like you also viewed"
fandom.com,wikia.org##.render-wiki-recommendations
! Mobile "how do you feel about this article" survey box. This one might actually belong in an ad filter, not sure if it's fandom-only.
fandom.com,wikia.org##.openweb-slot

## Which things do they block, hide, or unbreak?
Fandom self advertisement, recommendations, weird surveys (that only appear on my smartphone, had to learn how to use usb debug to find that piece of trash)

## Which of my lists are you submitting it to?
Fandom (formerly Wikia): Pure Browsing Experience
(it's a twitter/x half joke, because the wikia brand is actually dead and buried)

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s): 1.52.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
Wikia: Pure Browsing Experience, a very good list, love it.

## (Optional) Which browser(s) and version did you use?
Firefox windows and android, 117.0.1

**Comment by DandelionSprout** [comment]
Testing the suggested entries (albeit on the somewhat less cluttered Sims Wiki), it's pretty limited to which extent I can remove navigation bars, footers, and headers. However, I have decided to add these three entries:
```
! I felt like sparing the odd top 3 list part of the recirculation
fandom.com##.recirculation-prefooter__recommendations
! Implementing "Mobile "ad" for fanhub in the top bar dropdown login menu" verbatim
fandom.com##.global-navigation__fanhub-wrapper
! Futhead seems to have been down for months, and I hate Ultimate Team anyway
fandom.com##.global-footer a[href*=futhead]
```

**Comment by NotaInutilis** [comment]
Testing the Sims Wiki as an unlogged user, I've found another annoying notification box on saying "Don't like the ads? Then create an account! [...]" on the bottom on the screen, mobile only.

```
# Mobile: log in to remove ads
fandom.com,wikia.org##.notifications-box
```

However, I'm not quite sure to understand why you've only implementing 3 of these suggestions. Are they not working properly? Or do you feel like they're removing important functionality? Should I try to tweak them a bit or add more evidence like screenshots? As I said, it's my first time making this kind of filters so I'd like to know what makes a good rule that should be added or not.

**Comment by NotaInutilis** [comment]
I'm also using this issue thread to report a very minor issue with the Wikia list. There's a redundant entry:
```
wikia.org,fandom.com##.mcf-mosaic
wikia.org,fandom.com###mixed-content-footer
```

`mcf-mosaic` is part of `mixed-content-footer`, only the `mixed-content-footer` should be needed.

![Capture d'écran 2023-09-29 144327](https://github.com/DandelionSprout/adfilt/assets/9675966/eb572d45-a67a-4a79-9df3-bdc10156efdd)

**Comment by DandelionSprout** [comment]
There simply wasn't all of them I could block on moral grounds. For instance, I couldn't apply `##.global-footer__content` because that would've made it harder for users to find stuff like customer support.

**Comment by NotaInutilis** [comment]
Thanks for explaining, I understand your goal now.

I've tweaked some rules so they don't disrupt normal use and important links. For others, I've just updated the descriptions and added screenshots to be clearer as I believe they're not breaking anything important. I've tested a couple of wikis and the main Fandom site so they should work properly. Otherwise, tell me if there's anything broken and I'll do my best to fix it!

1. Edited the "Futhead out of Footer" rule. I understand you've modified the footer filter because it broke a lot of important links so here's another, more precise version.
```
! Removes Fandom self-promotion from all wiki's global footer, leaves important links such as ToS, privacy and help.
! Does not apply to the main Fandom site as its footer uses different classes names.
fandom.com##.global-footer__header
fandom.com##.global-footer__section-fandom-overview.global-footer__section
fandom.com##.global-footer__section-social-links.global-footer__section
fandom.com##.global-footer__section-advertise.global-footer__section
fandom.com##.global-footer__section-fandom-apps.global-footer__section
fandom.com##.global-footer__section-fandom-stores.global-footer__section
```
![1 off](https://github.com/DandelionSprout/adfilt/assets/9675966/424d72e3-b5bf-4807-bbb0-5d79538dd6a6)
![1 on](https://github.com/DandelionSprout/adfilt/assets/9675966/fc079fd4-e4c4-4176-8e2e-da8e35766bb4)

2. New rule for a login nag notification (seen on the Sims and Lego wikis).
```
! Removes notification nagging user to log in in order to remove ads.
fandom.com##.notifications-box
```
![2](https://github.com/DandelionSprout/adfilt/assets/9675966/2efa23f9-9124-4c4a-9806-644a037e26a5)

3. Same rules, better description + screenshot for "Others like you also viewed".
```
! Removes "Others like you also viewed" article recommendation carousel (mobile only).
fandom.com##.render-wiki-recommendations
```
![3](https://github.com/DandelionSprout/adfilt/assets/9675966/dcffa138-822e-4ca6-bfae-8c2ea8715886)


4. Same rules, better description + screenshot for "More Fandoms".
```
! Removes promotion of other Fandom wikis via the "More Fandoms" recirculation footer.
fandom.com##.page-footer__trfc-147
```
![4](https://github.com/DandelionSprout/adfilt/assets/9675966/387d7683-0eac-407f-8a90-337ae18265c5)


5. Updated rules for the "How Do You Feel About This Article?" survey box. The previous rule was actually broken and didn't hide it properly. I can't figure what makes it appear, but I hate it and want it gone. I've seen it appear on the normal and mobile version of the site but only when accessed through Firefox Android. It didn't show up when testing the mobile site on desktop, even with mobile dev tools.
```
! Removes inconsistantly appearing "How Do You Feel About This Article?" survey box.
! Appears only on a mobile device (Android Firefox), not on every wiki nor page, not on every load, and not always at the same spot.
! OpenWeb Pools & Reactions, only used to drive engagement and ad revenue, also contains a div titled openweb-ad-unit https://www.openweb.com/blog/reactions-get-a-pulse-on-your-community-with-interactive-polls
fandom.com##.open-web-wrapper
fandom.com##.openweb-slot
```
![5 a](https://github.com/DandelionSprout/adfilt/assets/9675966/6db38ac6-61b5-44f1-9f91-1757ff491e84)
![5](https://github.com/DandelionSprout/adfilt/assets/9675966/880ae27a-7536-498d-a959-dba519bae8a8)

6. Same rules, better description + screenshot for the first mobile toolbar. It keeps access to all important functions: search and login. I've included an alternative rule which keeps the logo.
```
! Removes Fandom self-promotion links from the first top bar (mobile only).
fandom.com##.mobile-global-navigation__left
! Alternative rule which keeps the logo.
fandom.com##.mobile-global-navigation__links
```
![6 off](https://github.com/DandelionSprout/adfilt/assets/9675966/138fe7d9-ab81-4015-9875-174e6f7bc9d9)
![6 on](https://github.com/DandelionSprout/adfilt/assets/9675966/1b6d39ea-0039-4bbf-b0af-bc76f7df29aa)

7. Same rules, better description + screenshot for the second mobile toolbar. For this one, an alternative might be to only remove the link.
```
! Removes Fandom logo and link from the second top bar (mobile only).
fandom.com##.mobile-global-navigation__logomark
```
![7 off](https://github.com/DandelionSprout/adfilt/assets/9675966/fa12537e-3c4d-4324-bff6-df7002157dd9)
![7 on](https://github.com/DandelionSprout/adfilt/assets/9675966/72f53bcb-bc6a-45b3-bf44-0f93f56771b1)

8. Modified rule for the desktop left navigation bar. I believe it can be completely removed, as important functions (search and login) are already present on the top bar menu. I've put an exception for the main Fandom site, as it actually serves a purpose here. An alternative ruleset just cleans the bar from recirculation links and the Fandom logo (again just removing the link from the logo is another option).
```
! Removes the left lateral bar with Fandom self-promotional links, except on the main Fandom site.
! Important features from this bar (search and login) are already present in the wiki's top bar menu.
fandom.com,~www.fandom.com##.global-navigation
! Alternative rule to clean the bar of Fandom self-promotion and recirculation links.
fandom.com,~www.fandom.com##.global-navigation__links
fandom.com,~www.fandom.com##.global-navigation__logo
```
![8](https://github.com/DandelionSprout/adfilt/assets/9675966/825f1a03-1062-409f-a557-ef712e69365e)
![8b](https://github.com/DandelionSprout/adfilt/assets/9675966/e612470d-8c72-4dde-b3ff-312fd62e0d36)

9. I was thinking that you were right about leaving the top 3 list on the recirculation footer, but it is actually super annoying! It loads only when arriving at the bottom of the page, and thus shifts everything downwards when you are, for example, trying to take screenshots of the footer! We definitely need more indie wikis.

10. I'd also like to add some more optimization suggestions for the nitpicky stuff.
- remove the `wikia.org,fandom.com##.mcf-mosaic` rule, which is redundant with the `wikia.org,fandom.com###mixed-content-footer` one
- remove all `wikia.org` from rules, maybe? The filters would be a little bit easier to read.
- add a search engine masking rule for "Extraordinarily bad or fraudulent Wikias" in the style of https://github.com/quenhus/uBlock-Origin-dev-filter
- `wikia.net` still exists, as one weirdly empty Fandom page. It would be overkill to add it to the filters but I wanted to share that information.

**Comment by DandelionSprout** [comment]
I'll be AFK for 3½ days due to a job conference and shopping, but you raise detailed enough points that I'll reopen the thread until I can look into it on Thursday or Friday.

**Comment by NotaInutilis** [comment]
Absolutely no hurry here, all the rules are in my own filter list and *it works for me*®. Enjoy your trip (even if it's work related)!

**Comment by DandelionSprout** [comment]
2, 3, 4, 5, and 12 seem like splendid ideas and will be implemented within mere minutes from now. 11 is supposed to apply on *non*-mobile devices. The rest I need consideration time on.

**Comment by NotaInutilis** [comment]
The rule you've written for 4 does not work, the box still appears.
I've tinkered a bit with it and the shortest working alternative I found is `fandom.com##[class^=page-footer__]`

In every wiki I've encountered it, that box is *always* `page-footer__trfc-147`. The last part seems to be hardcoded so a "generic" filter might not be needed (for now).

**Comment by NotaInutilis** [comment]
13. Adding a new entry here instead of editing and risking it to be forgotten. I encountered another inconsistently appearing Fandom Trivial quizzes promotion on mobile. This one appeared only once, so I'm not sure if its class changes. I would guess it doesn't, same as the other `trfc-147`. It might need a bit more investigation by somebody who desperately wants to know more about the Hulk.

`fandom.com##.trfc161`

![Screenshot_20231015-061220_Trebuchet](https://github.com/DandelionSprout/adfilt/assets/9675966/383cc80e-f05f-44df-ac30-1693c820f9a5)

**Comment by DandelionSprout** [comment]
It dawned on me after 2 months where I've been pretty sleepy, that I should ask which of the above things that still show up on your end? Especially given the colossal size of the screenshots, though I remembered only *now* that me as repo admin can place the edits into open/close tabs to save vertical space.

**Comment by NotaInutilis** [comment]
Oh man, your hibernation schedule is so messed up. You should go see a forest bear druid or something.

I don't remember which rules you've taken care of, but I've pruned them from my personal filterlist when you added them to the list. None of the rules you've added showed issues other than the ones I've already reported. Here's what's remaining on my end:

<details>
<summary>Unimplemented wikia filter rules</summary>

```
! Wikia/Fandom
! https://github.com/DandelionSprout/adfilt/issues/921

! Removes the left lateral bar with Fandom self-promotional links, except on the main Fandom site.
! Important features from this bar (search and login) are already present in the wiki's top bar menu.
fandom.com,~www.fandom.com##.global-navigation

! Alternative rule clean the bar of self-promotion and recirculation links.
! fandom.com,~www.fandom.com##.global-navigation__links
! fandom.com,~www.fandom.com##.global-navigation__logo

! Removes Fandom self-promotion links from the first top bar (mobile only).
fandom.com##.mobile-global-navigation__left

! Alternative rule which keeps the logo.
! fandom.com##.mobile-global-navigation__links

! Removes Fandom logo and link from the second top bar (mobile only).
fandom.com##.mobile-global-navigation__logomark

! Removes Fandom self-promotion from wiki's global footer, leaves important links such as ToS, privacy and help.
! Does not apply to the main Fandom site as its footer uses different classes names.
fandom.com##.global-footer__header
fandom.com##.global-footer__section-fandom-overview.global-footer__section
fandom.com##.global-footer__section-social-links.global-footer__section
fandom.com##.global-footer__section-advertise.global-footer__section
fandom.com##.global-footer__section-fandom-apps.global-footer__section
fandom.com##.global-footer__section-fandom-stores.global-footer__section
```
</details>

Indeed, that collapsible stuff is neat! Had no idea it was there and could reduce these awful mobile screenshots.

**Comment by DandelionSprout** [comment]
Doing a quick status update:
* `fandom.com##.mobile-global-navigation__logomark` only appears to apply if the screen width is ≤767px.
* `fandom.com##.mobile-global-navigation__links` only appears to apply if the screen width is ≥768px.
As such it's a close call which one (or both) I'll add, but I'll add at least one at some point.

Among footer self-promotions, `##.global-footer__section-advertise` seems like fair game and can be added within 5min of me posting this comment. `##.global-footer__section-fandom-(apps/stores)` I can add to "Staying on the Phone Browser", but are unlikely to be directly added to Trash Removal.

`fandom.com##.global-footer__section-fandom-overview` is (sadly?) DSQ because it has a link to the up-and-coming Steam competitor store "Fanatical". In contrast to huge parts of the internet, I approve of pretty much any store that can challenge Steam's near-monopoly on PC games.

• *"You should go see a forest bear druid or something."*
It's been a very sleepy autumn for sure. Mid-late October and most of December got especially wild.

**Comment by NotaInutilis** [comment]
>     * `fandom.com##.mobile-global-navigation__logomark` only appears to apply if the screen width is ≤767px.
>     * `fandom.com##.mobile-global-navigation__links` only appears to apply if the screen width is ≥768px.

I believe I see both of those on my 1080px width phone. Either fandom's confusing or I'm confused.

> `fandom.com##.global-footer__section-fandom-overview` is (sadly?) DSQ because it has a link to the up-and-coming Steam competitor store "Fanatical". In contrast to huge parts of the internet, I approve of pretty much any store that can challenge Steam's near-monopoly on PC games.

Fanatical's been here for a while though (and I had no idea they'd been bought). Unless they're releasing their own platform soon and I've missed the news, they're mostly selling steam keys which isn't real competition. In this case, the price of removing valve's cut is to fund fandom. I get your choice but man, I *hate* fandom.

**Comment by DandelionSprout** [comment]
I had to think for surprisingly long about Fanatical, and yes, it turned out it wasn't a real challenger. However, I would call it fair to myself if I discouraged Fanatical but not the very similar store concepts Humble Store and Gamesplanet.

I'll give the navigation bars a true final test tonight, after which point I presume this thread has finally been fully fixed.

**Comment by NotaInutilis** [comment]
You might have thought a bit too much about Fanatical! I guess it's mostly our goals that differ a bit. My aim is a "Fandom without Fandom" experience, a "plain" wiki which just happens to be hosted on this platform. I'm really glad I can build on your list to make that happen on my browser.

Good job! I'm still wondering about one thing: is there any reason you're not blocking the left bar? Or at least some of its links? It was actually this very part of the site that motivated me to look into all that filter stuff and contribute so I'm kinda surprised it didn't make the cut. Anyway, it's still on my own filter list so my life is still better overall.
