### ISSUE TITLE
Empty Padding Remover on barter.vg

### ISSUE THREAD

**Issue by NotaInutilis** [DandelionSprout/adfilt#923]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Top menu get squished under the top search bar on `https://barter.vg/`

### Add screenshots below if needed

![Screenshot 2023-10-02 at 13-27-23 Barter vg Trade Game Bundle Leftovers for Wishlist Games](https://github.com/DandelionSprout/adfilt/assets/9675966/9a5df3bc-9dea-4f16-853b-5a314a8f50cf)

### Add a screenshot of the extension's logger

![Capture d'écran 2023-10-02 132856](https://github.com/DandelionSprout/adfilt/assets/9675966/e54daad2-9028-40b1-96a7-61980d60ab1d)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Empty Padding Remover

### Which browser(s) did you use when testing this?

Firefox

**Comment by DandelionSprout** [comment]
Seeing as triggering the squish requires logging into that site with Steam (I have a Steam account, but don't really feel like logging into Barter with it), I'll simply whitelist `barter.vg` from that entry.

**Comment by NotaInutilis** [comment]
Thanks! II logged in and did some testing. If that's useful, here's the culprit:
`*##p:has-text(/^\xA0$/):not(:has-text(/\S/)):not(:has(img))`

**Comment by DandelionSprout** [comment]
(Reopening this so I can remember to move the whitelisting to the correct entry later today.)
