### ISSUE TITLE
Question about entries in the Tabloid remover list

### ISSUE THREAD

**Issue by NotaInutilis** [DandelionSprout/adfilt#925]
I've been contributing to rimu's [No-QAnon](https://github.com/rimu/no-qanon) list for a month with a lot of very, very bad content and a basic implementation of categorization ([as you've asked for last year](https://github.com/rimu/no-qanon/pull/41)!).

I've looked at your anti tabloid/alt-right list for more sources and got a question about `pcgamingwiki.com` inclusion. What's the reason for this decision? Some other sites in that category have a pretty well documented history but I wasn't able to find anything on my own about this one.

**Comment by DandelionSprout** [comment]
I was squeezed out very dishonourably from that site, after Jigen123 began spreading extremely sexist and racist conspiracy theories on their Discord servers (Things like how he thought Sony and Capcom were conspiring with Western diversity departments to make all women in games ugly on purpose), and that the admins blatantly sided with him and permabanned several people who took issue to Jigen's comments with no advance notice.

I'm never touching those piece of shit fuckers ever again.

**Comment by NotaInutilis** [comment]
Welp, that explains why I couldn't find any info. I never looked at the community side of the site and of course, when it's on discord, it can't be found by search engines.

Anyway, thanks for the answer.
