### ISSUE TITLE
AdGuard Home List

### ISSUE THREAD

**Issue by nightznero** [DandelionSprout/adfilt#926]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Helloz Dandelion, would You be able to get whitelist `banner1.` and `banner2.` for undress.app site?
Or if You dont want to,at least provide advice how i could do myself cuz i was trying a lot Rules prefix but none doesnt work
`@@||undress.app/playground_assets/banner[1-2].webp$domain=undress.app`
`@@||undress.app/playground_assets/banner[1.-2.]webp$domain=undress.app`
`@@||undress.app/playground_assets/[banner1-banner2]webp$domain=undress.app`
Ik i can use wild card `*` but its only need to unblock 1-2banner to work site properly.
Best Regards, NIGHTZNERO.

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop version)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

AdGuard Home List

### Which browser(s) did you use when testing this?

Brave Browser

### Browser version(s)

Newest Brave,ff

**Comment by DandelionSprout** [comment]
Presuming it's about `/banner1.` and `/banner2.`, I'll look into it within 60 hours. I've had a very bad week, but am *very* slowly recovering.

**Comment by nightznero** [comment]
> Presuming it's about `/banner1.` and `/banner2.` in AdGuard Home Compilation List, I'll look into it within 60 hours. I've had a very bad week, but am _very_ slowly recovering.

Thanks!
Well,that's doesn't important as our health. Hopefully everything goes back to normal in near future.
Best Regards and stay Safe, NIGHTZNERO

**Comment by DandelionSprout** [comment]
Okay, so before I go through the relatively long process (Sometimes up to 15min-ish) of generating a list update with Python, I figured I should just chip in with a tip regarding AdGuard's paid versions, as the list should only be used in "DNS blocking" mode and not in regular filtering mode. I should probably add an option to the issue form about that. 😅 

Sure using it in DNS Blocking mode would actually make it *harder* to whitelist `undress.app`, but still.

**Comment by nightznero** [comment]
> Okay, so before I go through the relatively long process (Sometimes up to 15min-ish) of generating a list update with Python, I figured I should just chip in with a tip regarding AdGuard's paid versions, as the list should only be used in "DNS blocking" mode and not in regular filtering mode. I should probably add an option to the issue form about that. 😅
> 
> As far as AdGuard has explained DNS blocking mode, `/banner1.` would only block stuff like `https://banner1.sus.party/` in DNS Blocking mode, not stuff like `https://sus.party/img/banner1.png`.

Well,maybe ma fault cuz I was using ur Home List in normal blockong section 😅 Cause of custom rules in list thats looks like cosmetic rules ex. `/banner1.` `-ad` so didnt used it in way that should probably made for 😅 ill switch it right away to DNS section rather than holding it on AdBlock section in ADG
