### ISSUE TITLE
I wish to help Issue with the lists

### ISSUE THREAD

**Issue by DomOBU** [DandelionSprout/adfilt#927]
This issue report form is intended for people who wish to contribute to help me write my lists beyond what I am able to do on my own, including people who have no real experience with GitHub.

#### Please only select any of these tools if you are a frequent or regular user of them. For ABP/AdBlock, it's also necessary to know how to look into and resolve list problems.

- [ ] Adblock Plus or AdBlock
- [ ] Internet Explorer 11 - Tracking Protection List
- [ ] System-wide hosts file (Many possible interfaces and tools)
- [ ] Network-wide hosts file tools (Pi-hole, AdGuard Home, or Diversion)
- [ ] Android faux-VPN hosts file tools (Blokada or DNS66)
- [ ] Little Snitch
- [ ] dnsmasq
- [ ] Privoxy
- [ ] Unbound
- [ ] ISC BIND 9
- [ ] Pfsense / PfBlockerNG
- [ ] AdGuard for Samsung/Kiwi Android browsers
- [ ] Brave Shield

#### These can be selected regardless of your tools, as long as you can write entries for them and can see if they break anything of note.

- [ ] Marked in its version date as *Beta*
- [ ] Marked in its version date as *Alpha*

## Writing entries for:

- [ ] Internet Explorer 11 - Tracking Protection List
- [ ] Little Snitch
- [ ] Danish and/or Icelandic fake webstore scams
- [ ] Danish geo-locked video sites (e.g. `tv3sport.dk`, among others)
- [ ] Norwegian and Danish far-right newssite-esque blogs

## Performing lobbyism in order for:

- [ ] Adblock Plus to [support wildcard asterisks in element rule domains](https://issues.adblockplus.org/ticket/6773)

## Translating section notes and text files to:

- [ ] Danish (incl. grammar-checking my 80% competent Danish writing skills)
- [ ] Icelandic
- [ ] Faroese
- [ ] Northern Sami
- [ ] Southern Sami

## Things that concern the adblock community at large

- [ ] Lobbying for Chrome Extensions and/or Firefox Add-Ons to delist very-low-quality adblocker forks that don't have their disclaimers or distribution licences straight
- [ ] Figuring out how many of my and other listmakers' lists that can be accessed from internet-censoring trigger-happy countries (e.g. Saudi Arabia, Iran, PR-China)
- [ ] Lobbying for Pale Moon to support WebExtensions

**Comment by DandelionSprout** [comment]
I unfortunately can't take you particularly seriously when you didn't fill out any textboxes or check any boxes *at all*.
