### ISSUE TITLE
Issue with the file

### ISSUE THREAD

**Issue by DomOBU** [DandelionSprout/adfilt#928]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Please have a look at the screenshots.

### Add screenshots below if needed

![1 Capture](https://github.com/DandelionSprout/adfilt/assets/95876663/1d9aa094-5085-42b6-8473-fe08398a7346)
![2 Capture](https://github.com/DandelionSprout/adfilt/assets/95876663/d8728182-ac15-4ddd-92ff-62ef6a4a9134)

### Add a screenshot of the extension's logger

Have the look at the screenshots

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.52.2

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

The UBlock lists

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

118.0.2

### OS version(s)

Windows 10 last update

**Comment by iam-py-test** [comment]
That filter is designed for AdGuard for Windows, hence why uBo rejects it.
However, it's disabled in uBo anyway (`!#if adguard` means that filter is only active in AdGuard).
Thanks.

**Comment by iam-py-test** [comment]
What antivirus/antimalware do you use?
Thanks

**Comment by DandelionSprout** [comment]
• *"Infected web page detected"*
What in the absolute flying fuck is Bitdefender doing??!

**Comment by iam-py-test** [comment]
I am reporting a false positive to them

**Comment by iam-py-test** [comment]
@DomOBU are you on Windows?
If so, please open Command Prompt (search for `cmd.exe` in the Windows search) and type/paste `curl -vvv https://raw.githubusercontent.com`, and see if this triggers an alert?
Thanks

**Comment by iam-py-test** [comment]
Odd.
Thanks anyway. Let's see what BitDefender says.

**Comment by iam-py-test** [comment]
I guess it's just legitimate URL. Weird, though.
Thanks

**Comment by DandelionSprout** [comment]
Any updates on the plans to get the page whitelisted in Bitdefender?

**Comment by iam-py-test** [comment]
Nothing but crickets.

**Comment by DandelionSprout** [comment]
Can you test if https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt works any better?

**Comment by iam-py-test** [comment]
FYI, G-Data uses BitDefender + their own engine. So, 3/89. ESTSecurity seems prone to false positives, and frankly I have never heard of it before.
Appealing to Fortinet as they are a pretty big corporate vendor.

**Comment by DandelionSprout** [comment]
I did several major updates on the file in the past 40min, which seems the most likely cause.

**Comment by iam-py-test** [comment]
Wouldn't it have been better to "defang" the urls rather than outright remove them (replace . with [.], https with hxxpx, etc)? IMO removing the examples makes it harder to figure out why rules exist.

**Comment by DandelionSprout** [comment]
>Wouldn't it have been better to "defang" the urls rather than outright remove them (replace . with [.], https with hxxpx, etc)? IMO removing the examples makes it harder to figure out why rules exist.

Hmm, great point, actually.

>For the moment the new link has not yet triggered a BD alert.

Good to hear.

**Comment by iam-py-test** [comment]
> For the moment the new link has not yet triggered a BD alert.

I suspect that is just because it's a lesser-known mirror they forgot to blocklist, but what do I know.

**Comment by iam-py-test** [comment]
Fortinet has fixed the false positive. Still no word from BitDefender

**Comment by DandelionSprout** [comment]
ESTsecurity seem to be the only remaining false positive, and I really don't want to install [a desktop program](https://en.estsecurity.com/support/report) solely to report a false positive (especially when they don't seem to have URL text box in the report form either).

So I declare this situation to be *de facto* fixed.
