### ISSUE TITLE
Remove app banner for Doctolib

### ISSUE THREAD

**Issue by NotaInutilis** [DandelionSprout/adfilt#930]
## Which entry/entries are you submitting?

`doctolib.fr##.css-y28f86.MuiModal-root.dl-drawer-container.MuiDrawer-modal.MuiDrawer-root`
## Which things do they block, hide, or unbreak?

Doctolib's full page app banner. uBO gave me this long stuff automatically and well, it works. The `css-y` number does not seem to change.

![Capture d'écran 2023-10-17 115453](https://github.com/DandelionSprout/adfilt/assets/9675966/40aef7b6-db65-4f2d-99ea-a86fb12eeb13)

![Screenshot_20231017-115533_Trebuchet](https://github.com/DandelionSprout/adfilt/assets/9675966/a5cf9ec8-3245-44a4-a404-b0f19d303737)

## Which of my lists are you submitting it to?
Stay on the phone brower
## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s): latest

## (Optional) Which browser(s) and version did you use?

Firefox android latest

**Comment by NotaInutilis** [comment]
Bonus answer: oh yeah, no problem. The wikia ones were so weird, popping up at random and disapearing at reload that i didn't even think about providing a url.

So here's the url here: `https://www.doctolib.fr/account/appointments`

**Comment by DandelionSprout** [comment]
While the notif's text seems a bit different on my end than yours, `doctolib.fr##.MuiModal-root` seems to work for me too, so I'll add it.
![image](https://github.com/DandelionSprout/adfilt/assets/22780683/e9f4d742-e34e-4300-9b41-fc6db8e1ca3b)

**Comment by NotaInutilis** [comment]
Seems like it's working! I've tried make that banner appear on Chrome desktop with the mobile dev tools too, but it only shows the top "downoad our app" banner, never the full screen blocking one. The internet is weird (derogatory).

**Comment by NotaInutilis** [comment]
Well, it's actually NOT WORKING. When trying to get a medical appointment (we are forced to use this dreadful site now), I noticed that other parts of the site use these Muimodals to display actually useful info.

Example URL (any doctor page actually, picked a random one) https://www.doctolib.fr/cabinet-de-kinesitherapie/paris/centre-kinesitherapie-sport-et-sante

When clicking on "Voir plus" it, should display stuff like address, opening times, etc. by using a div with `MuiDrawer-root MuiDrawer-modal dl-drawer-container MuiModal-root css-y28f86` as class.

I don't know how to get better targeting then. Can it only hide something that displays "application" somewhere? Or a link to google play/appstore?

**Comment by NotaInutilis** [comment]
Through some testing, I answered my question and found 3 rules that work! Thanks again for the "syntax that's actually readable" document, it's quite helpful.

```
doctolib.fr##.MuiModal-root:has-text(application)
doctolib.fr##.MuiModal-root:has(.dl-button-label)
doctolib.fr##.MuiModal-root:has([href*="google"])

```
I'm not sure which method you prefer to use in that blocklist.
