### ISSUE TITLE
Can't switch YouTube channels when using Legitimate URL Shortener

### ISSUE THREAD

**Issue by Starmapo** [DandelionSprout/adfilt#931]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

While using an account with a brand channel, I'm unable to switch from it to the main (personal) channel while using the Legitimate URL Shortener filter. When it's disabled, I am able to switch that account.

After some testing, I found out that line 3482 is causing it:

```txt
$doc,removeparam=feature,domain=reddit.app.link|youtube.com|youtu.be
```

When I remove the YouTube domains from this line, switching accounts works again.

I can provide a video if needed.

### Add a screenshot of the extension's logger

![image](https://github.com/DandelionSprout/adfilt/assets/85134252/f9fee160-8d28-49f2-9615-48c79c483104)

(Some parts are blacked out because I'm not sure if it's sensitive info)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.52.2

I also have Enhanced Tracking Protection from Firefox using the Strict setting.

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

uBlock filters (all of them)
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe's Ad and tracking server list
Actually Legitimate URL Shortener

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

118.0.2 (64-bit)

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

Pro, version 22H2
64-bit operating system, x64-based processor

**Comment by iam-py-test** [comment]
Thank you for reporting this. I have fixed it in https://github.com/DandelionSprout/adfilt/commit/b22207348a51db3625f2ab3f1b2d62368143db90.
Please wait a few minutes, then update your filterlists and retest.
You kind-of did my job for me
