### ISSUE TITLE
Staying on browser for Doctolib: fixing the filter

### ISSUE THREAD

**Issue by NotaInutilis** [DandelionSprout/adfilt#937]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Seems like [my message on the previously closed issue](https://github.com/DandelionSprout/adfilt/issues/930#issuecomment-1773724847) flew under the radar so I'm opening a new one to fix the consequences of my non-rigorous testing.

When trying to get a medical appointment (we are forced to use this dreadful site now), I noticed that other parts of the site use these Muimodals to display actually useful info. They were not showing up. REGRETS HAPPENED.

Example URL (any doctor page actually, picked a random one) https://www.doctolib.fr/cabinet-de-kinesitherapie/paris/centre-kinesitherapie-sport-et-sante

When clicking on "Voir plus" it, should display stuff like address, opening times, etc. by using a div with `MuiDrawer-root MuiDrawer-modal dl-drawer-container MuiModal-root css-y28f86` as class.

I've done some experimentation and found out these two filters actually work and don't break the site. I'm not sure which approach (keyword or URL) you prefer to use in these filters though.

```
doctolib.fr##.MuiModal-root:has-text(application)
doctolib.fr##.MuiModal-root:has([href*="play.google"])

```

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Staying on browser

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

**Comment by DandelionSprout** [comment]
>REGRETS HAPPENED.

My deepest condolences. I've had 2 not very good weeks of my own so far, leading to not being able to do meaningful adblock work again until yesterday night, but I'll replace the entry with those entries now.

**Comment by NotaInutilis** [comment]
Thanks! And take good care of yourself.

These two filters work on their own, you don't need to add both. I've put them both because I don't know which method is recommended for these lists. Anyway this website is terrible so maybe both is better.
