### ISSUE TITLE
Scrolling issues on vink.aftenposten.no

### ISSUE THREAD

**Issue by mikke89** [DandelionSprout/adfilt#938]
Having trouble scrolling on vink.aftenposten.no, using Firefox (affects both mobile and desktop). It acts as if there is a hidden scroll region that needs to be scrolled first, then you need a second scroll action to scroll the actual page.

I tracked it down to what I believe is this rule:
https://github.com/DandelionSprout/adfilt/blob/e807dce88eae38a851313f6142f2ef1ee8b6e6ac/NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt#L46

**Comment by DandelionSprout** [comment]
I'm having some problems replicating it on Firefox and Chrome (These kinds of scrolling problems most commonly occur from anti-'cookie prompt' lists, rarely from anti-ad lists), but the UI looks so different from the regular Aftenposten pages that I'll whitelist `vink` anyway. Give me 3min.

**Comment by mikke89** [comment]
Thanks for the quick response, this indeed fixed it for me!

For future reference: To replicate, it seems one has to click into an article while being logged in. On desktop it is most easily recognized when using autoscroll (holding middle mouse button while moving the mouse up or down).
