### ISSUE TITLE
Mastodon blocklist false positives?

### ISSUE THREAD

**Issue by NotaInutilis** [DandelionSprout/adfilt#939]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

I was doing some mastodon moderation and noticed that two popular French instances are in the Tabloid Remover Mastodon blocklist: `framapiaf.org` and `mamot.fr`. Both are managed by well known FOSS (Framasoft) and internet freedom (La Quadrature du Net) groups so I'm guessing they're false positives. I've also got a lot of friends using them so I'm **hoping** it's a false positive and you're not going to reveal some awful stuff I had never heard of before.

### Which adblocker(s) did you use when testing this?

(Other)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

TabloidRemover-MastodonCategoryForImports.csv

### Which browser(s) did you use when testing this?

(Other)

**Comment by DandelionSprout** [comment]
I likely wouldn't have been able to find the toots that worried me from 2 years ago before I discontinued work on that import list, but I did a scrollthrough for `mamot.fr`, and found 4 posts from 4 users that at the very least concerned me:
```
https://mamot.fr/@charlyalexvdp/111331906326575367
https://mamot.fr/@Titichristian2/111331844941397874
https://mamot.fr/@chantalebelle_2/111331433378616433
https://mamot.fr/@lutzray/111287268123009702
```
Sure they only made up 5~7% of the instance's internal toots, but it didn't take much back then to end up on that list.

I'll see when I get some spare time to look into Framapiaf.

**Comment by NotaInutilis** [comment]
Okay, I get why you'd be worried by such toots. They need a bit of context and French knowledge to be understood. I'm not sure you want to know more about France (there are a lot of reasons to not want that) but I'll still explain those a bit.

The first one is genuinely weird, creepy and unhinged, but not in the way you'd first think. It's not some "free speech as in bigotry". It's something else but I'm not entirely sure what. This account seems to be a hardcore fan of Guillaume Meurice, a radio comedian for France Inter, who participates in a show that was demoted from daily to weekly because it was too left leaning and critical of the current government. This toot seems to defend Meurice, because he made a joke about Netanyahou and *current world events* that got him in trouble. Smells like a worrying parasocial relationship.

Regarding toot number 2, I believe it's political satire aimed at the far right. You know the terrible person on left because of *current world events*. The terrible person in the middle is Gérald Darmanin, our current minister of the interior, known for monarchism, sexual harrassment, liking Napoléon's antisemitism, [deporting people to Russia](https://www.lemonde.fr/en/france/article/2023/10/31/french-interior-minister-dusts-off-plan-to-deport-dangerous-chechens_6215796_7.html), and police violence. The terrible person on the left is Éric Zemmour, a far-right media personality/politician. He's basically our local Trump: they tried to do the same thing as in the USA in the last presidential elections, but it did not work (it still harmed the public debate). He's Jewish and has some nazi acquaintances. The blast ball launcher is here because the government (Darmanin) authorized cops to fire it at 3 meters instead of 10, which is very worrying because police has already mutilated and killed using those. The card is an enrollment paper for the president's political party. Then you get the Halloween theming. Although it features two Jewish personalities, I don't see any antisemitic trope or dog-whistle that I know of in that image. The rest of the account first raised some questions of confusionnism (mixing both far right and far left to drive to the far right), especially with the iconography being used but it was actually all far left. It looks like a weird facebook page but ultimately does not rise any red flag.

Toots 3 and 4 attack Biden, but aren't pro-Trump. They're both in English so I don't really have to explain them, but they're more of an attack on American imperialism, especially number 4 (which is actually French Canadian). In general, French people don't like American politicians, even if they are from the less terrible party. Both timelines are left-leaning, with no red flag.

Regarding Framapiaf, I know of at least a couple of accounts on it that I'd consider as "canaries", and would be really vocal if anything bad happened on that instance. They've also got good preemptive moderation, as when a known harasser (Acermendax) registered on another instance, they immediately blocked him.

Overall, I understand your concerns and hope that I've shed some light on these. Still, as you said, you've discontinued work on this list 2 years ago so yeah, maybe it's not worth it to take more hours to delve into the French-speaking corners of the internet.

**Comment by DandelionSprout** [comment]
I presume you're free to apply `@@||mamot.fr^` and `@@||framapiaf.com^` in your personal filters, since you seem very confident that these sites are fair and good to use. You didn't fill out most boxes in the form, so I have to guess that you're using a standard adblocker that can use whitelisting, as opposed to e.g. DNS servers or tools that require Hosts files.

I speak virtually no French (Occasionally checking out TiVi5Monde on weekend mornings and understands pretty much nothing), so these history lessons were actually very good and useful for me.

**Comment by NotaInutilis** [comment]
I'm actually building a blocklist for the instance I'm moderating by aggregating a few lists of bad mastodon and peertube instances, including yours. My solution has been commenting out those before the script does its magic (a sed and a cat). I actually didn't know it was possible to feed a csv file to an adblocker.

Yeah I'm pretty confident these instances are good, but "Just trust me bro" isn't quite the best argument. :P Glad you've found this explaination useful!

**Comment by DandelionSprout** [comment]
To the best of my knowledge, at least uBlock Origin, AdGuard, and AdGuard Home treat CSV files as raw text files, the same way they'd treat .txt or files with no suffix extensions. This has certainly been convenient at times.

I've even got .txt files disguised as .mp3 files to work in uBO.

**Comment by NotaInutilis** [comment]
I have now obtained knowledge about how to use that dodgy 4kbps mp3 I downloaded 20 years ago and I'm not quite sure how to feel about that.
