### ISSUE TITLE
Why block all .cf domains?

### ISSUE THREAD

**Issue by Asakushen** [DandelionSprout/adfilt#943]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Based on the following rules, all .cf domains are blocked. In fact, many students will choose that free domain name to build their personal blogs. Of course there are a lot of harmful websites because of its free nature, but it is undeniable that there are still a lot of cs majors who choose this free domain name in order to complete their assignments. (At least many of my classmates have created useful websites with this domain, which I can't access now, unfortunately.) I hope the author can remove this rule, I appreciate it.
||cf^$document,domain=~google.cf|~rths.cf|~acap.cf

### Add a screenshot of the extension's logger

||cf^$document,domain=~google.cf|~rths.cf|~acap.cf

### Which adblocker(s) did you use when testing this?

AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Annoyances 

### Which browser(s) did you use when testing this?

Microsoft Edge (Manifest V2)

### Browser version(s)

118.0.2088.76 

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

23H2

**Comment by DandelionSprout** [comment]
There was a period around 2018-20 where .cf were frequently used in malware redirection trains, but virtually all of them later moved on to ones like .xyz or .com.

I'll think more about it throughout today.

**Comment by Asakushen** [comment]
Due to the fact that Google has become more strict in recent years about the inclusion of free domain names such as cf, ml, etc., it is actually very difficult to search for harmful websites under such domain names as cf, ml through Google search. We can't cut the feet to fit the shoes, to give up the end, because of a small loss.
Thank you very much for your reply, of course the above is just my own personal opinion.

**Comment by DandelionSprout** [comment]
For at least today until I have pondered on this, you can hopefully add `||cf^$document,domain=~google.cf|~rths.cf|~acap.cf,badfilter` to "User rules" in AdGuard's settings; or alternately simply `@@||cf^`

**Comment by Asakushen** [comment]
Ok, again thank you very much for your answer. Thanks to your team for the excellent rule. I will add this rule to access my classmate's website. Once again, have a great life and good luck with your development!

**Comment by iam-py-test** [comment]
Re: abuse of .cf
There seem to be 4 .cf domains in my personal blocklist, [3 in the Phishing URL Blocklist](https://gitlab.com/malware-filter/phishing-filter), and zero in URLHaus and DurableNapkin's scam blocklist. 0.07% of the 853129 domains in *HaGeZi's Threat Intelligence Feeds* are .cf domains.
Also, there is 415 .cf domain in the top 1 million most popular domains.
Not that spouting raw statistics helps make anything clearer.

**Comment by hagezi** [comment]
![grafik](https://github.com/DandelionSprout/adfilt/assets/104343908/5d4ef880-5b70-483c-a31b-0c07d99899a0)

https://www.spamhaus.org/statistics/tlds/
