### ISSUE TITLE
Untrustworthy VPN review website owned by ExpressVPN

### ISSUE THREAD

**Issue by TotalImportance8529** [DandelionSprout/adfilt#944]
## Which entry/entries are you submitting?

Websites : 
`https://www.vpnmentor.com/bestvpns/windows/`
`https://www.wizcase.com/vpn-reviews/`

## Which things do they block, hide, or unbreak?

This article explained everything, these two website are owned by ExpressVPN, the rating are changed to promote their own products.
`https://restoreprivacy.com/vpn-review-websites-owned-by-vpns/`

## Which of my lists are you submitting it to?
💊 Dandelion Sprout's Anti-Malware List or any suitable filterlists for fake review websites like these two.
## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s): 1.52.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

uBlock filters
- uBlock filters – Ads
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Quick fixes
- uBlock filters – Unbreak

EasyList

AdGuard URL Tracking Protection

Block Outsider Intrusion into LAN

EasyPrivacy

Online Malicious URL Blocklist

Phishing URL Blocklist

EasyList – Annoyances
- EasyList – Chat Widgets
- EasyList – Newsletter Notices
- EasyList – Notifications
- EasyList – Other Annoyances
- EasyList – Social Widgets
- EasyList/uBO – Cookie Notices
  - EasyList – Cookie Notices
  - uBlock filters – Cookie Notices

uBlock filters – Annoyances

💊 Dandelion Sprout's Anti-Malware List

EasyList China

## (Optional) Which browser(s) and version did you use?

Kiwi Browser 116.0.5845.240

**Comment by iam-py-test** [comment]
Off topic, but be aware Kiwi Browser is not supported by uBlock Origin, and generally is rarely updated & buggy.
Thanks

**Comment by DandelionSprout** [comment]
I have limited experience with Kiwi Browser myself, but it's quite possibly the only non-Russian web browser for Android that supports Chromium extensions, so I permit the use of it.

Though this sounds 100.0% like something ExpressVPN would do, the situation with those sites is complicated, and it could easily take me a day or two to research. Starting with a quick peek on `VPNmentor`, almost every image is broken, and the bottom bar says "Copyright Year". Googling 2 random team member names, Ernest Sheptalo seems to be a real person, while Georgii Chanturidze seem more likely than not to be an invented person.

**Comment by iam-py-test** [comment]
> we've partnered with Kape Technologies PLC, which owns popular products like ExpressVPN, CyberGhost, ZenMate, Private Internet Access, and Intego
> We rank vendors based on rigorous testing and research, but also take into account [...] our commercial agreements with providers.

Sketchy.

**Comment by TotalImportance8529** [comment]
athese two websites didn't mention their relationship with ExpressVPN, this is very dishonest.

You can see PCMag notify their reader about their relationship with IPVanish every time they mention it.
https://www.pcmag.com/reviews/ipvanish-vpn
https://www.pcmag.com/reviews/ivpn

They didn't every recommend it in their best vpn list
https://www.pcmag.com/picks/the-best-vpn-services
https://www.pcmag.com/picks/the-best-free-vpns

This is very different to what Wizcase and vpnMentor did. They only reveal it on a small "Ownership" section, which need to be clicked to see the message.

**Comment by TotalImportance8529** [comment]
> Off topic, but be aware Kiwi Browser is not supported by uBlock Origin, and generally is rarely updated & buggy. Thanks

I use Firefox beta now, Kiwi whilelisted some websites like zoom and Bing , this makes adblocker can't block tracker on these websites :  https://github.com/easylist/easylist/issues/17756 
https://www.reddit.com/r/uBlockOrigin/comments/ppygw1/comment/hd7f42r/
https://www.reddit.com/r/kiwibrowser/comments/tem2wl/comment/i198sip/
