### ISSUE TITLE
Question regarding scope of list: IDN Homograph Attack Protection - Complete Blockage

### ISSUE THREAD

**Issue by BillyJoeJimBob** [DandelionSprout/adfilt#953]
I've used the filter in your _IDN - Complete Blockage_ list `/.*?xn--.*/` in UBO and it successfully blocks IDNs.  I've also tried the following filter: `||xn--$doc,frame` that I saw mentioned by https://nitter.net/gorhill/status/1422914791077732352#m that also blocks IDNs.    My question is whether these filters are complementary and can be used together or overlapping in scope and I should I just pick one.  It appears that yours is broader in scope, but I don't really know.  IDNs are not used in my language or region so blocking all by default is probably best.  

Thank you kindly.

see: 

https://github.com/DandelionSprout/adfilt/blob/cb8a56b43f7e9c079ee7277d988d9376ca239788/Special%20security%20lists/IDNHomographProtectionTotal.txt#L10

**Comment by DandelionSprout** [comment]
The entry in that tweet is actually pretty genius, and I'm surprised I didn't come up with it myself, even by 2020 standards when I made that list of mine.

His entry would be *marginally* less resource-intensive than the one I've been using in "IDN - Complete Blockage", and also produce a correct page warning. You can pick only `||xn--$doc,frame` for now, but I'll certainlly borrow inspiration from that for my list(s) this weekend.

**Comment by BillyJoeJimBob** [comment]
Thank you for your reply.  I guess `||xn--$all` would block IDNs but I'm not sure what that would break...

**Comment by DandelionSprout** [comment]
I pondered on whether a 1-in-200,000 chance could occur that it'd block something like `https://xn--sportschannel.com`, but I concluded that web browsers and IANA and whoever else who get to have say on it, would never allow double dashes in a domain name.

**Comment by DandelionSprout** [comment]
Disregard my previous comment: Of course I should've known that international letters would make the main domain `xn--` every time in the eyes of adblocker engines, for instance `elkjøp.no`.

Nevertheless, I remember from 2020 that this kind of blocking was exactly what the list's target audience wanted.

**Comment by iam-py-test** [comment]
> ||xn--*

Doesn't seem to work in uBlock Origin unless a modifier is appended.

**Comment by DandelionSprout** [comment]
It *seems* to work on http://www.xn--steinkjeridrettsrd-lub.no/next/p/17031/nyheter in uBO 1.53.0 for Chromium on my end, at least.
