### ISSUE TITLE
Staying on the phone: pathe.fr

### ISSUE THREAD

**Issue by NotaInutilis** [DandelionSprout/adfilt#958]
## Which entry/entries are you submitting?

pathe.fr##.smart-app-banner
## Which things do they block, hide, or unbreak?

Remove app banner on pathe.fr (all pages on the site)
Seems like `smart-app-banner` is already in the list, but for some reason it does not block on this site.
## Which of my lists are you submitting it to?
Staying On The Phone Browser
## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s): latest

## (Optional) Which browser(s) and version did you use?

Firefox Android, latest

**Comment by NotaInutilis** [comment]
Issue was on my end: `smart-app-banner` is a generic filter and the "ignore generic cosmetic filters" option was checked for some reason.

**Comment by iam-py-test** [comment]
> "ignore generic cosmetic filters" option was checked for some reason

It's enabled by default on mobile devices so generic cosmetic filters do not slow down low-end devices
Thanks
