### ISSUE TITLE
Schibsted Sweden - Cookie popup

### ISSUE THREAD

**Issue by AdblockReporters** [DandelionSprout/adfilt#960]
## Which entry/entries are you submitting?
Block all cmp consent management platform for swedish domains:
`.se/unified/wrapperMessagingWithoutDetection.js`

Block the gdpr bundle domain:
`cogwheel.inventory.schibsted.io`

## Which things do they block, hide, or unbreak?
https://www.godare.se/
<img width="829" alt="Screenshot 2023-11-16 at 14 11 16" src="https://github.com/DandelionSprout/adfilt/assets/138932214/e8601132-0332-4942-80c8-325df1a01e8d">

https://www.livsstil.se/
<img width="830" alt="Screenshot 2023-11-16 at 14 11 36" src="https://github.com/DandelionSprout/adfilt/assets/138932214/b82ee90f-c644-42f1-844a-9fcb3ab7ac3e">

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s):
uBlock Origin development build
1.53.5.109

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
```
uBlock Origin: 1.53.5rc9
Chromium: 119
filterset (summary):
 network: 283832
 cosmetic: 243696
 scriptlet: 46982
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 389-1, 5h.8m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2482-3, 5h.8m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RickrollLinkIdentifier.txt: 50-0, 5h.8m
  NOR-0: 3648-12, 5h.8m
  adguard-cookies: 28068-30, 5h.8m
  adguard-generic: 80191-568, 5h.8m
  adguard-mobile: 8726-45, 5h.8m
  adguard-mobile-app-banners: 4751-10, 5h.8m
  adguard-other-annoyances: 13798-11, 5h.8m
  adguard-popup-overlays: 26206-88, 5h.8m
  adguard-social: 21983-928, 5h.8m
  adguard-spyware: 69884-1222, 5h.8m
  [15 lists not shown]: [too many]
 default:
  user-filters: 22-0, never
  easylist: 75434-2017, 5h.8m
  easyprivacy: 32889-16481, 5h.8m
  plowe-0: 3725-1578, 5h.8m
  ublock-badware: 7522-336, 5h.8m
  ublock-filters: 35608-4290, 5h.8m
  ublock-privacy: 680-195, 5h.8m
  ublock-quick-fixes: 148-73, 5h.8m
  ublock-unbreak: 2151-147, 5h.8m
  urlhaus-1: 11525-0, 5h.8m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 899 ms (selfie)
 maxAssetCacheWait: 229 ms
```

## (Optional) Which browser(s) and version did you use?
Chrome 119.0.6045.159 (Official Build) (arm64)

**Comment by DandelionSprout** [comment]
You should probably ask https://github.com/lassekongo83/Frellwits-filter-lists/issues about it instead. His list is Sweden-specific **and** blocks cookie prompts.
