### ISSUE TITLE
GitHub is stretched too far

### ISSUE THREAD

**Issue by erkinalp** [DandelionSprout/adfilt#962]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

GitHub is stretched too far in the issue issue/PR view

### Add screenshots below if needed

![GitHub stretched too far in the issue/PR view](https://github.com/DandelionSprout/adfilt/assets/5833034/89bd857e-b772-4440-9c9d-b1999875255d)

### Add a screenshot of the extension's logger

![AdGuard log](https://github.com/DandelionSprout/adfilt/assets/5833034/0450090d-966e-49fb-be58-680a0aeb824c)

### Which adblocker(s) did you use when testing this?

AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari), Firefox's built-in tracking protection

### Adblocker version(s)

4.2.209

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

AdGuard: [see the configuration file attached](https://github.com/DandelionSprout/adfilt/files/13403449/20231119_125157_adg_ext_settings_4.2.209.json)
Firefox tracking protection: Standard profile

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

120 beta

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Ubuntu 22.04.3

**Comment by DandelionSprout** [comment]
I guess I can set a max width for thread comments at perhaps 1500px, and doublecheck the padding of the right bar. However, it could take a couple days-ish for me to do.

**Comment by erkinalp** [comment]
@DandelionSprout you could use a CSS rule to subtract the left and right sidebars.

**Comment by erkinalp** [comment]
![this very issue's view](https://github.com/DandelionSprout/adfilt/assets/5833034/0835a9be-4f8e-4116-8aa2-1860d4f9e941)

**Comment by DandelionSprout** [comment]
It turns out that I can't for the life of me find a way to make a consistent rightbar padding that works across all resolutions (ranging from 1366px to 2880px wide windows), and I'll have to rewrite many of the GitHub entries from scratch instead. As such, there'll be a significant delay in fixing this.

**Comment by DandelionSprout** [comment]
I had some wildass luck when writing hotfixes in a hurry tonight, as the hotfixes also managed to prevent apparent overlapping as well.

**Comment by DandelionSprout** [comment]
Seems like I have to doublecheck issue pages as well. Bloody hell.
