### ISSUE TITLE
apkmirror - AdGuard Home List 

### ISSUE THREAD

**Issue by nightznero** [DandelionSprout/adfilt#963]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

blocked rule mentioned below in screenshoots breaks the site

### Add screenshots below if needed

![Screenshot_20231120_230202_AdGuard](https://github.com/DandelionSprout/adfilt/assets/61750641/10828153-e722-42a4-bd58-dec311069b5e)
![Screenshot_20231120_230217](https://github.com/DandelionSprout/adfilt/assets/61750641/353f9ba9-021a-478c-9305-389cbd8ab9ae)

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop/Android versions - Standard filtering + DNS Blocking™™©)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

way to much,only one blocks it

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Browser version(s)

newest ddg

**Comment by DandelionSprout** [comment]
I took a look after waking up this morning of which source entries that had resulted in `||07c225f3.online^`, and found these in "uBlock Filters - Ads":
```
||07c225f3.online^$image,1p
||07c225f3.online^$image,3p,redirect=1x1.gif
||07c225f3.online^$doc,ping,font,css
*$font,css,domain=07c225f3.online
genshinlab.com,a-ha.io,cboard.net,mobilitytv.co.kr,mememedia.co.kr,newautopost.co.kr,tvreport.co.kr,tenbizt.com,jjang0u.com,joongdo.co.kr,viva100.com##+js(noeval-if, 07c225f3.online)
```
Given `||07c225f3.online^$doc,ping,font,css`, it's not exactly a surprise why my list ended up blocking that domain; but at the same time, `||07c225f3.online^$image,3p,redirect=1x1.gif` indicate they (APKmirror) is doing some hardcore AAB stuff.

I'll figure out a solution eventually.

**Comment by DandelionSprout** [comment]
So, in order for me to fix this properly, it requires me running a 5- or 6-step guide to update the list (which takes around 20min), and I've got distracted by Sims 3 gamemodding in the past 4 days. I haven't forgot this report entirely, at least.

**Comment by nightznero** [comment]
> I've got distracted by Sims 3 gamemodding in the past 4 days. I haven't forgot this report entirely, at least.

man does not live by work alone,so don't worry Dandi, and nice that u care
