### ISSUE TITLE
Add Phishing.Army list as source to blocking

### ISSUE THREAD

**Issue by ghost** [DandelionSprout/adfilt#967]
Hi!

Add https://phishing.army/download/phishing_army_blocklist_extended.txt as list of malware to automatic blocking. 

Main page:
https://phishing.army/

Description:
> Generated every 6 hours from [PhishTank](https://www.phishtank.com/), [OpenPhish](https://openphish.com/),
[Cert.pl](https://www.cert.pl/ostrzezenia_phishing/), [PhishFindR](https://github.com/mitchellkrogza/Phishing.Database), [Urlscan.io](https://urlscan.io/) and [Phishunt.io](https://phishunt.io/) reports.
Each domain is analyzed to eliminate false positives,
through the Whitelist of [Anudeep](https://github.com/anudeepND/whitelist) and the [Alexa Rank](https://www.alexa.com/topsites)

**Comment by DandelionSprout** [comment]
While the report is technically speaking valid, is there any particular reason why you wouldn't simply add PhishingArmy to Blokada as an additional list on your phone?

**Comment by DandelionSprout** [comment]
Oh, they deleted their account. Definitely a no deal, then. (Yes, I watched a lot of "Deal or No Deal" as a teen.)

**Comment by DandelionSprout** [comment]
Worth noting, as I made this edit as a result of this report: https://github.com/DandelionSprout/adfilt/commit/2ff48dbf2d250656462f9c9cbc5fcfd281f1d0d8
