### ISSUE TITLE
amazonaws.com - parameters

### ISSUE THREAD

**Issue by ghost** [DandelionSprout/adfilt#970]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

paramters

X-Amz-Algorithm=
X-Amz-Credential=
X-Amz-Date=
X-Amz-Expires=
X-Amz-Signature=
X-Amz-SignedHeaders=
actor_id=
key_id=
repo_id=

![picture29](https://github.com/DandelionSprout/adfilt/assets/151660568/3405fa30-4673-4ce2-9cd1-5bac1a1300a5)

I did not provide the original link for privacy reasons.
To reproduce it, open the e-mail sent by GitHub to your e-mail address and click on the image link.

![a-image88](https://github.com/DandelionSprout/adfilt/assets/151660568/86773f12-af74-4298-86a2-2a23e7f0c2e4)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

default uBO filters
extra: ➗ Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

**Comment by iam-py-test** [comment]
Sorry for the delay.
For some reason, I have been unable to reproduce this.
To me, those look like they provide some critical functionality (rather than tracking) but that's a guess.
Sorry
