### ISSUE TITLE
glami - parameters

### ISSUE THREAD

**Issue by ghost** [DandelionSprout/adfilt#971]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

I already reported this a long time ago but I don't know why it hasn't been added yet.
https://help.glami.info/pixel-2.0-release-all-you-need-to-know
$removeparam=gci
it doesn't cause breakage on my end.

---

and add these 4 parameters also.

pid=
c=
af_reengagement_window=
gci=

![picture28](https://github.com/DandelionSprout/adfilt/assets/151660568/c3f6d284-1190-42af-a92f-cf09994e9fd2)

---

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

default uBO filters
extra: ➗ Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

**Comment by iam-py-test** [comment]
Please wait a few minutes and update your filterlists to see if my changes work.
Thanks

**Comment by iam-py-test** [comment]
> Whatever, it does not matter.

I may not get to it right now, it does matter.
Where does it not work? Can you share a link (preferably one with the parameters)?
Thanks

P.S. Sorry for not seeing your original report(s).
