### ISSUE TITLE
AdGuard Home list... blocks all(*) css?

### ISSUE THREAD

**Issue by MicrosoftEggshell** [DandelionSprout/adfilt#974]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

There's a problematic [rule](https://github.com/DandelionSprout/adfilt/blob/46bad5c66ea176b5be378b920c7997651a0a3037/AdGuard%20Home%20Compilation%20List/AdGuardHomeCompilationList.txt#L35750) in the AdGuard Home Compilation List: `://www.*.css|`

(*)As it turns out, most of the modern web either doesn't use `www.`, uses some parameters when requesting their stylesheets, or both. At any rate, some big sites like [The World Bank](https://www.worldbank.org) still get loaded without css thanks to this - I'm not sure how or why the rule got added in the first place.

### Add screenshots below if needed

![image](https://github.com/DandelionSprout/adfilt/assets/71736138/b485e657-03c6-4755-8040-5fc600067493)

### Add a screenshot of the extension's logger

![image](https://github.com/DandelionSprout/adfilt/assets/71736138/d886947a-8fb1-48c9-b56a-7825f331163e)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.54.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

AdGuard Home Compilation List

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

librewolf 120.0.1.1

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

Windows 10 Pro N 21H2 (19044.3086)

**Comment by DandelionSprout** [comment]
I admit and take blame for that I didn't make it more clear previously, but the list in question **is not designed or intended** to be used with uBlock Origin under **any** circumstances.

**Comment by MicrosoftEggshell** [comment]
Fair enough, the list *is* clearly made for AdGuard after all, I guess that just completely slipped by me when I made the report.

Although the original `://www.*.css|$script,3p` rule does have the same workarounds I mentioned in my post which makes it an even stranger rule, but I digress.
