### ISSUE TITLE
stiffy360.artstation.com

### ISSUE THREAD

**Issue by Sonic5435325** [DandelionSprout/adfilt#978]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Page is hidden
`https://stiffy360.artstation.com/projects/rJdnEJ?album_id=447728`

### Add a screenshot of the extension's logger

uBlock Origin: 1.54.1b6
Firefox: 120
filterset (summary):
 network: 195831
 cosmetic: 210341
 scriptlet: 47684
 html: 1332
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2507-1, 20h.22m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive%20lists/Dandelion%20Sprout's%20Anti-Religion%20List.txt: 2570-0, 20h.22m
  adguard-generic: 80568-7357, 20h.22m
  adguard-mobile: 8788-112, 20h.22m
  adguard-spyware-url: 1351-200, 20h.22m
  adguard-spyware: 76717-16963, 20h.22m
  block-lan: 55-0, 20h.22m
  adguard-cookies: 28246-63, 20h.22m
  adguard-popup-overlays: 26540-801, 20h.22m
  adguard-mobile-app-banners: 4819-1070, 20h.22m
  adguard-other-annoyances: 14024-321, 20h.22m
  adguard-widgets: 2354-1, 20h.22m
  [6 lists not shown]: [too many]
 default:
  user-filters: 718-0, never
  ublock-filters: 36796-476, 20h.22m
  ublock-badware: 7559-11, 20h.22m
  ublock-privacy: 921-52, 20h.22m
  ublock-unbreak: 2204-1, 20h.22m
  ublock-quick-fixes: 299-67, 2h.52m
  easylist: 75857-829, 20h.22m
  easyprivacy: 33035-887, 20h.22m
  urlhaus-1: 9930-0, 20h.22m
  plowe-0: 3779-1, 20h.22m
filterset (user): [array of 661 redacted]
userSettings:
 advancedUserEnabled: true
 tooltipsDisabled: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 7438 ms (selfie)
 maxAssetCacheWait: 366 ms

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin v1.54.1b6

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Anti-'Religious insanity' List

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

Firefox 120.0.1

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Mint 21.2

**Comment by DandelionSprout** [comment]
I've found the broken entry; bafflingly and solely my fault, it astonishingly turned out that `:has-text(/Aries($| )/i)` also matches `Mercenaries `. I'll get it fixed within 1~3hrs.
