### ISSUE TITLE
Rickroll rule addition

### ISSUE THREAD

**Issue by erkinalp** [DandelionSprout/adfilt#979]
## Which entry/entries are you submitting?
https://www.youtube.com/watch?v=nsCIeklgp1M

## Which things do they block, hide, or unbreak?
https://www.youtube.com/watch?v=nsCIeklgp1M

## Which of my lists are you submitting it to?
RickRoll rule identifier

## Which adblocker(s) and version did you use when writing and testing the entries?
applies to all
## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
[20231205_202015_adg_ext_settings_4.2.209.json](https://github.com/DandelionSprout/adfilt/files/13614032/20231205_202015_adg_ext_settings_4.2.209.json)

## (Optional) Which browser(s) and version did you use?
Firefox, but not relevant for this issue

**Comment by DandelionSprout** [comment]
Having checked the link at last, I'm thinking "Surely it'd be cruel to a BBC official Glastonbury recording to think it'd be primarily used for rickrolling?"

Maybe it's time for me to retire my Rickroll Link Identifier list sometime soon. Who knows at this point.
