### ISSUE TITLE
www.tu.no

### ISSUE THREAD

**Issue by steinrr** [DandelionSprout/adfilt#983]
## Beskriv problemet under denne linjen så detaljert og utdypende som mulig (inkl. nettlenker hvis det er noen):
Does not seem that any of the major ads on www.tu.no is blocked.

## Legg til skjermklipp under hvis det trengs:
<img width="1507" alt="Screenshot 2023-12-31 at 11 40 42" src="https://github.com/DandelionSprout/adfilt/assets/12039073/c7810fec-8007-401d-b0e0-41b3a1eae919">
## Hvilken reklameblokkerer og versjon brukte du da du testet dette?

- [x] uBlock Origin
- [ ] AdGuard (Betalt skrivebordsversjon)
- [ ] AdGuard (Nettleserutvidelse)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (Utvidelsen)

## Hvilke filterlister brukte du? Å ikke fortelle dette, vil føre til at saken blir midlertidig lukket frem til dette blir fortalt.
<img width="659" alt="Screenshot 2023-12-31 at 11 42 01" src="https://github.com/DandelionSprout/adfilt/assets/12039073/4b5e6fd8-8a9f-4d1a-9089-2f2ff38c57fd">

## Hvilke(n) nettleser(e) og versjon(er) brukte du?
MS Edge - Version 120.0.2210.91 (Official build) (arm64)

## (Valgfritt) Hvilket OS og versjon brukte du?
- [ ] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7 SP1
- [x] macOS
- [ ] Linux
- [ ] Android

OS-versjon:
Sonoma 14.2.1

**Comment by DandelionSprout** [comment]
I think I fixed that site yesterday (Saturday), I recall? And I see the "List not recently updated" warning sign in the filterlists screenshot, so you can try clicking on *Oppdater nå* in the upper left of that menu in uBO's settings and see if that fixes it.

**Comment by steinrr** [comment]
Hmmm... that is really strange. I actually installed your list yesterday to get rid of these tu-ads, and it worked fine. But today it did not work anymore. I clicked update both on uB level and on list level (got the warning sign when I did). But now I retried to update on uB level and it works again. Strange things - but good that it works again. Thanks for your effort!
