### ISSUE TITLE
liveagent.com

### ISSUE THREAD

**Issue by CbumDino** [DandelionSprout/adfilt#984]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

The chat button functionality that their application offers doesn't work for their SE customers.
You can visit https://liveagent.se/ with the "Dandelion Sprout's Nordic Filters+EasyList" list enabled and check the console. These are being blocked:

https://liveagent.se/wp-content/plugins/convertplug/modules/assets/js/cp-module-main.js?ver=3.5.24
https://liveagent.se/wp-content/plugins/convertplug/modules/info_bar/assets/js/info_bar.min.js?ver=3.5.24

### Add screenshots below if needed

![liveagent](https://github.com/DandelionSprout/adfilt/assets/65717387/9031bd65-d0e8-47a8-8229-c88d1cd1ded1)

### Which adblocker(s) did you use when testing this?

Adblock Plus (Firefox or Manifest V2)

### Adblocker version(s)

3.21.1

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

Dandelion Sprout's Nordic Filters+EasyList

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Browser version(s)

120.0.6099.109

### Which OS(s) did you use when testing this?

macOS

### OS version(s)

MacOS Monterey 12.4

**Comment by DandelionSprout** [comment]
I've found a probable fix, but it may take up to 24 hour before it takes effect.

**Comment by CbumDino** [comment]
Hey @DandelionSprout, Thank you for your support. 
Unfortunately, the issue is still there.

https://liveagent.se/boka-demo-chatt-pa-hemsida/
`liveagent.se/scripts/track`

![liveagent2](https://github.com/DandelionSprout/adfilt/assets/65717387/9e1b97e0-dc9d-4498-90a6-f98bbcab8e34)

**Comment by DandelionSprout** [comment]
I hope I've found a fix for that too… I hope. Should take effect overnight.
