### ISSUE TITLE
Reddit loads indefinitely when using Actually Legitimate URL Shortener Tool

### ISSUE THREAD

**Issue by crisp5** [DandelionSprout/adfilt#985]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Upon opening https://reddit.com/ on Brave Android using the filter lists listed below, the site loads indefinitely. I've tracked the issue down to Actually Legitimate URL Shortener Tool, which I had added to Brave's Custom filter lists.

A very similar issue had been [reported in the Brave forums earlier in 2023](https://community.brave.com/t/unable-to-open-reddit-com-urls-in-private-tabs/503125), and fixed with [this pull request](https://github.com/brave/adblock-lists/pull/1289/commits/0f4c618a006823276f10bbfe490bcf957d86937b). Is this something that can also be applied here?

### Which adblocker(s) did you use when testing this?

Brave's built-in adblocker (a.k.a. Brave Shield)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

- **Actually Legitimate URL Shortener Tool**
- Brave filter lists used when setting Block trackers & ads (Aggressive)
- EasyList Cookie
- Fanboy's Mobile Notifications
- Bypass Paywalls Clean Filters

### Which browser(s) did you use when testing this?

Brave Browser

### Browser version(s)

1.61.109

### Which OS(s) did you use when testing this?

Android

### OS version(s)

Android 14

**Comment by DandelionSprout** [comment]
Brave Shield is an adblocker I have rather limited experience with, but I'll look into it eventually. Hoping to do it within 48 hours, could be *far* quicker, could be slightly longer.

**Comment by iam-py-test** [comment]
I have temporarily disabled `rdt` based on the Brave forums post, but I do not know if that is the cause.
In May of last year I added a warning that Brave's removeparam implementation was buggy, but the commit is vague and lacks reference to an issue or specific problem.
Thanks

**Comment by DandelionSprout** [comment]
So, testing with Windows Subsystem for Android, hoping it'd be easier to test that way than on my physical phone (Kinda turned out it wasn't; turned out I had to set Vulkan rendering to off to get pages to load), I at least see that Legitimate URL Shortener is *not* included as opt-in or opt-out in Brave Shield. So that thankfully rules out the possibly that they could've included a list that was not designed for most Brave builds' Brave Shield.

I know all too well about how Reddit would go through the often many `rdt` redirects, but would proceed to load the actual subreddit after 2sec. However, I can't seem to reproduce those redirects on Brave Android *nor* Chrome Windows tonight.

**Comment by crisp5** [comment]
OK FINALLY, my browser got into a weird state where custom filter lists were flat-out ignored, reinstalling took care of it. Can confirm that the last commit fixed the issue.

> I at least see that Legitimate URL Shortener is not included as opt-in or opt-out in Brave Shield. So that thankfully rules out the possibility that they could've included a list that was not designed for most Brave builds' Brave Shield.

Yeah, it's definitely not included by them, but a recent-ish version of Brave Android made adding custom filter lists more prominent (Settings > Brave Shields > Content Filtering as opposed to through brave://adblock), so it's possible more users start delving into the world of filter lists. If that's the case, I'll leave [this for future reference](https://community.brave.com/t/brave-shields-is-unable-to-clean-url-remove-tracking-elements-despite-adding-filters-which-work-in-ublock-origin-and-adguard/512317/2). Exceptions and regex aren't supported by removeparam yet, and some params are cleaned by the browser itself, independent of any removeparam rules.

Thanks y'all 👍 Feel free to close unless there's any additional testing you want to do
