### ISSUE TITLE
ClearURLs for uBo

### ISSUE THREAD

**Issue by Oxygen112** [DandelionSprout/adfilt#986]
Fb Photo and video not loading when **ClearURLs for uBo** is turned on Brave Shields. Kindly resolve the issue.

**Comment by iam-py-test** [comment]
I am sorry, but [support for Brave Shields is buggy at best, with some rules not properly functioning](https://github.com/DandelionSprout/adfilt/issues/985). As far as I am aware, this is a bug in Brave not ClearURLs/ClearURLs for uBo.
Thank you.

**Comment by antonok-edm** [comment]
@Oxygen112 FWIW it's likely due to https://github.com/brave/adblock-rust/issues/246 - ClearURLs makes heavy use of regex removeparams.

**Comment by iam-py-test** [comment]
Thanks @antonok-edm 
Since this is a known issue with Brave, and one which is being worked on, I think I can close this issue.
