### ISSUE TITLE
I don't want to download your browser - support for DuckDuckGo

### ISSUE THREAD

**Issue by SocietasEvanescentes** [DandelionSprout/adfilt#989]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

DuckDuckGo now advertises their browser(s) when using any other browser but DDG. 

### Add screenshots below if needed

<img width="1497" alt="Untitled" src="https://github.com/DandelionSprout/adfilt/assets/25782090/788ee618-94e4-4168-9542-97df385d8834">

### Add a screenshot of the extension's logger

I use AdGuard for Windows with this list added.

### Which adblocker(s) did you use when testing this?

AdGuard (Paid desktop/Android versions - Standard filtering + DNS Blocking™™©)

### Adblocker version(s)

Latest desktop beta

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

- Adguard Base Filter
- AdGuard Mobile Ads Filter
- Adguard Annoyances Filter
- Legitimate URL Shortener
- I don't want to download your browser

### Which browser(s) did you use when testing this?

Vivaldi

### Browser version(s)

Vivaldi Snapshot 3238.3

### OS version(s)

macOS 14.2

**Comment by DandelionSprout** [comment]
I've found a fix for it, which I will implement within a few minutes.
