### ISSUE TITLE
Lists contain bad entries such as `!#if`

### ISSUE THREAD

**Issue by ThinkChaos** [DandelionSprout/adfilt#997]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hi,

I noticed some lists contains lines like `!#if`. I'm guessing you use those for pre-processing.  
Anyways they're not valid for hosts, domains, and most likely other formats.

A couple random examples:
- https://github.com/DandelionSprout/adfilt/blob/a25ce67890b9b2d4250bb658058204dfad6f404e/Alternate%20versions%20Anti-Malware%20List/AntiMalwareDomains.txt#L5
- https://github.com/DandelionSprout/adfilt/blob/a25ce67890b9b2d4250bb658058204dfad6f404e/AntiAmazonListForTwitch.txt#L9

### Which adblocker(s) did you use when testing this?

(Other)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

`AntiMalwareHosts.txt`

### Which browser(s) did you use when testing this?

(Other)

**Comment by iam-py-test** [comment]
>  Anyways they're not valid for hosts, domains, and most likely other formats.

[`!#if` is valid syntax in uBlock Origin and AdGuard](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#pre-parsing-directives), and is treated as a comment in AdBlock/ABP. PiHole _should_ treat them as comments, though it may not, as it handles "adblock" syntax filterlists different from every other mainstream content blocker.
That said, they are not valid in HOSTs/domains style files.
Thanks

**Comment by DandelionSprout** [comment]
I've been on a run lately, where I've tried to ensure that most of my lists (**except** those that are included as opt-out or opt-in in adblockers, before anyone asks) would be forcibly non-working in uBO Minus or AdGuard MV3; and uBO have traditionally been able to handle both Hosts and raw domain files very easily.

So I admit I'm unsure how to handle this.

**Comment by DandelionSprout** [comment]
Okay, so it turns out that there's several dozen similar `!#if` tags in the first of those files, making me wonder how on earth I even managed to do such a mistake in my conversion scripts in the first place.

This gives me a faint clue on how to fix this, but the implementation of that fix(es) won't be a stroll in the park, sadly.

**Comment by ThinkChaos** [comment]
> I've been on a run lately, where I've tried to ensure that most of my lists (except those that are included as opt-out or opt-in in adblockers, before anyone asks) would be forcibly non-working in uBO Minus or AdGuard MV3; and uBO have traditionally been able to handle both Hosts and raw domain files very easily.

FWIW I'm using the list with [blocky](https://github.com/0xERR0R/blocky), and we've intentionally avoided implementing adblocking list directives since they're mostly irrelevant/unusable for DNS blockers.

I appreciate the goal of breaking extensions from bad actors, but I think having working hosts/domains is more important. Anyways I'd guess those extensions are less likely to use these list formats.

**Comment by ThinkChaos** [comment]
Thanks!
